### ISSUE TITLE
Docker安装

### ISSUE THREAD

**Issue by koalang** [zfile-dev/zfile#1]
Docker安装
播放音乐文件显示“系统异常, 请联系管理员”
还有站点名貌似不起作用。改了还是显示首页

**Comment by zhaojun1998** [comment]
播放音乐，你存储策略用的时什么。

站点名称是有点问题，这个后面会修复

**Comment by koalang** [comment]
> 播放音乐，你存储策略用的时什么。
> 
> 站点名称是有点问题，这个后面会修复

本地储存

**Comment by zhaojun1998** [comment]
可能是文件目录的权限问题，方便提供下错误日志吗。

**Comment by koalang** [comment]
> 可能是文件目录的权限问题，方便提供下错误日志吗。

尴尬了 好像部署的时候没开日志，等下重新部署试试，有没有TG，换个地方联系...

**Comment by zhaojun1998** [comment]
https://t.me/zhaojun1998

**Comment by wei** [comment]
您好 请问有官方 Docker 版本吗？或者能否分享一下 Dockerfile 和/或 docker-compose.yml ？感谢！🙏

**Comment by koalang** [comment]
> 您好 请问有官方 Docker 版本吗？或者能否分享一下 Dockerfile 和/或 docker-compose.yml ？感谢！

`FROM mbdiallo/jdk-alpine
RUN wget https://github.com/zhaojun1998/zfile/releases/download/0.2/zfile-0.2.jar
VOLUME /zfile
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","./zfile-0.2.jar"]`
