### ISSUE TITLE
Onedrive for business无法使用

### ISSUE THREAD

**Issue by xyk92615us** [zfile-dev/zfile#10]
使用Onedrive for business，获取token和设置没都没问题，但是访问网页后提示设置有问题。
如果使用个人版同样的操作就没问题，网页正常访问、文件数据均无问题。
能否增加Onedrive for business支持？

**Comment by zhaojun1998** [comment]
@xyk92615 我测试是没问题的，可以提供更详细的日志信息。
如当前程序版本，操作步骤等。

**Comment by xyk92615us** [comment]
> @xyk92615 我测试是没问题的，可以提供更详细的日志信息。
> 如当前程序版本，操作步骤等。

试了下，全局管理员的就行，普通用户不可以，我试试看看是不是组织里默认关闭了一些权限，试了后来答复下。

**Comment by zhaojun1998** [comment]
@xyk92615 好的，如果试出来，还麻烦说下如何设置的。我添加到文档，方便其他人也注意。

**Comment by zhaojun1998** [comment]
因无反馈，暂时先关闭问题了，有需要再打开。
