### ISSUE TITLE
前后端分离无法添加和编辑驱动器

### ISSUE THREAD

**Issue by D3CODING** [zfile-dev/zfile#101]
因为源站带宽有限，所以将静态文件放到对象存储做前后端分离部署。

在使用2.4版本进行前后端分离部署，系统为CentOS7.3，添加驱动器时能够跳出页面，但是填好信息之后点击提交，显示了一个提交中的圈圈后快速消失，然后还是填写信息页面。

在尝试直接访问源站时，提交后应该显示绿色的成功，然后填写信息的框消失，添加成功。

**Comment by D3CODING** [comment]
另外提出一个小建议希望考虑，在填写Sk或者操作员密码后，如果验证成功可用，再次点击编辑的时候建议显示成为“留空则不修改”而不是直接显示明文的密钥。

**Comment by zhaojun1998** [comment]
@lichenzero 未复现出此问题，请描述下，在添加什么存储策略时，出现的提示。一般出现圈圈后，停留在填写信息页面，是有会红色的错误提示的。

这里明文与否，好像意义不大，因为管理员就你一个人用。
