### ISSUE TITLE
feat: 对GoogleDrive的目录支持

### ISSUE THREAD

**Issue by superxxl** [zfile-dev/zfile#104]
## 概述
希望能增加GoogleDrive的目录支持

## 动机
希望这个项目可以实现一站式，认识的很多人都使用GoogleDrive做为存储，容量大，而目GitHub开源项目中对于GoogleDrive的目录索引并没有过多的关注，希望能增加这个功能

GoogleDrive的API
https://developers.google.com/drive/api/v3/about-sdk

**Comment by Jandaes** [comment]
这个你可以用rclone 把google drive挂载到本地、然后在通过zfile指定就行了！我就是这样操作， 还可以挂载google team drive
