### ISSUE TITLE
feat: 建议链接全部变成16进制

### ISSUE THREAD

**Issue by mi229ller** [zfile-dev/zfile#105]

**Comment by zhaojun1998** [comment]
请详细描述下你的需求，及使用场景。

**Comment by mi229ller** [comment]
使用onedrive上传视频，然后zfile获取链接，添加到苹果cms使用，苹果cms的不支持链接中带有汉字，将这种链接https://zfile.jun6.net/directlink/1/视频/%E5%B8%A6%E5%AD%97%E5%B9%95%E7%9A%84%E8%A7%86%E9%A2%91.mp4直接转换为https://zfile.jun6.net/directlink/1/%E8%A7%86%E9%A2%91/%25E5%25B8%25A6%25E5%25AD%2597%25E5%25B9%2595%25E7%259A%2584%25E8%25A7%2586%25E9%25A2%2591.mp4这种格式。

**Comment by zhaojun1998** [comment]
明白，现在没有对全部 URL 进行编码，下个版本将修改。

**Comment by zhaojun1998** [comment]
已修改，发布至 2.6 版。
