### ISSUE TITLE
软路由上，用docker安装的zfile，本地存储无效。

### ISSUE THREAD

**Issue by jy3344511** [zfile-dev/zfile#109]
onedrive挂载不了，用本地存储的功能，路径：/mnt/sda1，显示有效，打开首页后，全部空白，FTP能正常显示，但是FTP打开视频，会提示下载，挂载本地存储主要是想用zfile的播放器在线播放视频。另外，试过不同版本的zfile，挂载本地存储后，打开首页，都是啥没有。

**Comment by zhaojun1998** [comment]
docker 本地路径，挂载的时 docker 容器中的文件地址吧，你需要做个映射

**Comment by jy3344511** [comment]
> docker 本地路径，挂载的时 docker 容器中的文件地址吧，你需要做个映射

-v /mnt/sda1:/root/zfile/data \
在创建容器的时候，做了，啥没有啊，是哪里不对吗？


![image](https://user-images.githubusercontent.com/49992475/81482497-0ff31900-926a-11ea-9b51-cb88eb202aaa.png)
