### ISSUE TITLE
请问ftp应该怎样设置

### ISSUE THREAD

**Issue by sknpy** [zfile-dev/zfile#117]
是因为我ftp路径中有中文吗，我关联ftp后什么文件都读取不到
填写错误的帐号密码好像会显示配置错了，填写正确了，读取的是一片空白
顺带一提，ftp的加速域名是什么呀！！！

**Comment by zhaojun1998** [comment]
@sknpy 这个一个 BUG，会对 FTP 修复。

**Comment by zhaojun1998** [comment]
@sknpy  已在 2.8 版本修复
