### ISSUE TITLE
希望能增加webdav的功能 

### ISSUE THREAD

**Issue by youlikesoilove** [zfile-dev/zfile#118]
## 概述

希望能支持webdav协议，以解决某些视频无法在线播放的问题。

## 动机

某些视频格式在线播放器不支持，Nplayer和Potplayer可以弥补，配合Nplayer和Potpalyer可以记录视频播放，并自动跳转上次播放位置、支持自动播放下一个、支持调整缓存大小，调整缓存时长、Nplayer同时支持视频批量下载、无级变速、等等。
## 详细解释
WebDAV 允许客户端进行下列操作
处理服务器上 WebDAV 发布目录中的资源。使用此功能，其优点例如:
1.具有正确权限的用户可以在 WebDAV目录中复制和移动文件。
2.修改与某些资源相关联的属性。例如，用户可写入并检索文件的属性信息。
3.锁定并解锁资源以便多个用户可同时读取一个文件。但每次只能有一个人修改文件。
4.搜索 WebDAV 目录中的文件的内容和属性。
在服务器上设置 WebDAV 发布目录与通过 Internet 信息服务管理单元设置虚拟目录一样简单。设置好发布目录后，具有适当权限的用户就可以向服务器发布文档，并处理目录中的文件。在设置 WebDAV 目录之前，必须首先安装 Windows XP Professional。
WebDAV 客户端
可以通过下面列表中描述的任意一种 Microsoft 产品或通过其他任意的支持行业标准 WebDAV 协议的客户端来访问 WebDAV 发布目录。
·Windows XP 通过“添加网上邻居向导”与 WebDAV 服务器连接，并显示 WebDAV 目录中的内容，如同它是本地计算机上同一文件系统的组成部分。连接完成之后，就可以拖放文件、检索和修改文件属性以及执行许多其他文件系统任务。
·Internet Explorer 5.0 与 WebDAV 目录连接，使您可以执行通过 Windows XP 所能执行的文件系统任务。
·Office 2000 通过其中包含的任意应用程序创建、发布、编辑并直接将文档保存到 WebDAV 目录中。
在 WebDAV 中搜索
一旦与 WebDAV 目录建立连接，就可以快速搜索此目录中文件的内容和属性。例如，可以搜索包含
table 一词的所有文件或所有由 Fred 编写的文件。

**Comment by TOYUBOOT** [comment]
+1
