### ISSUE TITLE
feat: 希望加入排序功能

### ISSUE THREAD

**Issue by zifeiyue** [zfile-dev/zfile#119]
希望加入排序功能，例如时间排序，大小排序

**Comment by curiosity2** [comment]
我也有同样的需求，希望能加入这个功能

**Comment by parkergrt** [comment]
同样需要，因为在一个文件夹下有大量文件的时候，按时间排序的真的是刚需，希望优先添加此功能

**Comment by zhaojun1998** [comment]
已修改

**Comment by bcaso** [comment]
希望增加按字符排序的选项。因为常用终端，所以我有很多文件都使用 16 进制前缀。

**Comment by zhaojun1998** [comment]
@bcaso 
这个暂不考虑，需求太特殊，如需求，可自行修改源码。
