### ISSUE TITLE
feat: 希望可以加上把隐藏文件(Linux下 .xxx)不可见

### ISSUE THREAD

**Issue by boomker** [zfile-dev/zfile#120]

**Comment by boomker** [comment]
我希望把类似下面这种文件不让其他人看见
<img width="238" alt="图片" src="https://user-images.githubusercontent.com/19751472/82869011-2a164200-9f60-11ea-9ceb-0e566cb93c5a.png">

**Comment by Smith-Cruise** [comment]
同理，不显示隐藏文件

**Comment by zhaojun1998** [comment]
@Smith-Cruise @boomker 已在 2.8 版本增加此功能
