### ISSUE TITLE
未创建任何驱动器时，浏览首页出现异常

### ISSUE THREAD

**Issue by GOBEYONDO** [zfile-dev/zfile#122]
## 错误日志

![image](https://user-images.githubusercontent.com/49560678/83347320-f28c0900-a356-11ea-9629-aafff484c7db.png)

## 期望行为
如果没有创建任意驱动器，应该提示您未创建驱动器

提示创建驱动器
## 当前行为
![image](https://user-images.githubusercontent.com/49560678/83347357-0afc2380-a357-11ea-88f4-3c45cd6078e4.png)

`http://localhost:8080/#/main`
在这个url  时
点击左上角'首页'时
会弹出三个‘系统异常请联系管理员’
'http://localhost:8080/api/config/undefined?path='
这个路径接收的driveId 值是undefined
希望能修正，并且能捕获到未创建任意驱动器，提示用户去创建驱动器,而不是请联系管理员

**Comment by zhaojun1998** [comment]
@GOBEYONDO  已在 2.8 版本完善系统中的错误提示。
