### ISSUE TITLE
feat: 本地存储可以增加上传功能吗?(最好能多线程和断点续传)

### ISSUE THREAD

**Issue by jzh20042003** [zfile-dev/zfile#123]
网盘没有上传功能感觉就是个文件下载站......功能不完整啊 如果能支持上传和断点续传还有网络不好的时候多线程上传或者其它高速上传的方法就好了.........

感谢大神.................

**Comment by mrjucn** [comment]
这个zfile只是个获取文件的目录程序。你们说的这些功能有点过分额。

**Comment by zhaojun1998** [comment]
上传会支持，多线程和断点续传，做不了。稳定的高速上传，请使用专业的工具进行上传，本项目初衷仅仅是列目录展示而已。
