### ISSUE TITLE
~/zfile/bin/start.sh 输入后，需要等待10-25s才可进入访问

### ISSUE THREAD

**Issue by ntgeralt** [zfile-dev/zfile#124]
当然，这不是什么BUG，只是和一般start.sh脚本相比，这个启动比较慢。一般玩家输入完后直接访问IP:8080 没反应，以为防火墙问题，结果鼓捣防火墙了。殊不知只是启动慢，不是其他的锅。

**Comment by zhaojun1998** [comment]
后续版本更新，会完善 start.sh，启动后控制台输出启动日志，而不是没有任何信息。
