### ISSUE TITLE
左上的面包屑导航点击后加载不出内容

### ISSUE THREAD

**Issue by fgprodigal** [zfile-dev/zfile#127]
docker版zfile，左上的面包屑导航点击后加载不出内容，一直转圈圈

**Comment by BusyHe** [comment]
一样，希望能解决一下

**Comment by zhaojun1998** [comment]
@fgprodigal  我需要更详细的信息，才能排查此问题，比如你提供一个地址，或 gif  等方式来让我复现这个问题。
