### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by cloudfly23** [zfile-dev/zfile#13]
我试了一下发现直接访问文件链接是空白页面，不能直接启动下,网盘没有外链功能还是挺难受的，而且有些地方还是需要直链的
程序支持多个对象存储，但是我试了一下发现只能选择一个策略，如果能通过自己设置目录来挂载多个不同的对象储存，可能会更好一点
整体设计非常不错，挺好的软件

**Comment by zhaojun1998** [comment]
@cloudfly23 
整理下你提出的建议：

1. 直接访问文件链接是空白页面，没明白什么意思。能详细描述下吗。
2. 外链功能，可以提供，列表后增加操作按钮：`查看直链`、`下载`、`预览` 等操作。
3. 后续会考虑支持同时开启多存储策略。

**Comment by cloudfly23** [comment]
就比如你的示范网站：https://zfile.jun6.net/#/main/%E9%9F%B3%E9%A2%91/%E4%BB%BB%E7%B4%A0%E6%B1%90%20-%20%E8%83%A1%E5%B9%BF%E7%94%9F.mp3
直接输入到具体到文件名的链接会
![image](https://user-images.githubusercontent.com/42934604/73737970-8a4d6200-477e-11ea-9cf0-69f38bc2291c.png)
或许可以直接跳转到下载链接会更好一点

**Comment by zhaojun1998** [comment]
@cloudfly23  ok 明白，会考虑支持。
