### ISSUE TITLE
移动端界面布局不是很好，强烈建议博主优化一下

### ISSUE THREAD

**Issue by voiin** [zfile-dev/zfile#135]

**Comment by mrjucn** [comment]
哈哈。我也觉得移动端的布局确实有点问题。看来只有自己去自定义css了。大概作者是专业后端人士，对前端不是很熟练吧。

**Comment by zhaojun1998** [comment]
@voiin @juxiaodong 是否可以给予一些建议，确实是后端开发，对前端经验差一下，尤其是移动端。
