### ISSUE TITLE
feat: 视频播放增加上一条，下一条

### ISSUE THREAD

**Issue by langshenzy** [zfile-dev/zfile#137]
希望作者大大能优化一下视频播放功能让视频播放完了能自动播放下一条视频提升系统观影体验   能让用户在播放界面任意切换上一条视频或者下一条视频

**Comment by kfcceo** [comment]
收到建议，下一版本就加上这个功能，到时候记得更新。（虽然我不是作者哈哈）

**Comment by zhaojun1998** [comment]
@kfcceo 
@langshenzy 

非常抱歉这么久才回复，最新版本已经支持此功能
