### ISSUE TITLE
本地存储有很多地方会出现bug

### ISSUE THREAD

**Issue by GillianJiao** [zfile-dev/zfile#138]
作者您好：程序使用本地存储有很多地方会出现bug
1.搭建上传password.txt，页面不显示加密；（希望大佬能出一个后台添加到方法）

2.本地上传password.txt，出现加密但是输入密码一直提示密码不对；程序使用宝塔搭建权限755；

![](https://cdn.jsdelivr.net/gh/8838/img@latest/2020/07/29/f5f01c9d7b0cf10e1a391991a7306659.png)

![](https://cdn.jsdelivr.net/gh/8838/img@latest/2020/07/29/3ad7d934816a451336a891421aa3b99d.png)

**Comment by zhaojun1998** [comment]
@GillianJiao  密码不对可能时里面有空字符，或者换行符之类的导致的。当然后面的版本会增强这些特殊情况的处理。
