### ISSUE TITLE
Zfile不支持通过<iframe>引入

### ISSUE THREAD

**Issue by bluskai** [zfile-dev/zfile#139]
## 我的环境
Windows10 Pro
JVM 版本 1.8.0_261

## 期望行为
已经按照配置好了Zfile服务，可以通过http://10.10.10.10:8080正常访问使用。
现在做了一个聚合页面，网址http://10.10.10.10:80。
在聚合页面里，通过<iframe>标签引入了Zfile服务，即<iframe src="http://10.10.10.10:8080"></iframe>

## 当前行为
聚合页面无法正常引入Zfile服务，显示如图

![1](https://user-images.githubusercontent.com/37144222/89125591-2380e980-d512-11ea-9d9c-c633abf63e1e.PNG)

![2](https://user-images.githubusercontent.com/37144222/89125594-2a0f6100-d512-11ea-95e7-09f6f2cf374a.PNG)

**Comment by zhaojun1998** [comment]
此为浏览器安全限制，和程序无关
