### ISSUE TITLE
onedrive 授权时长太短

### ISSUE THREAD

**Issue by Omoinemie** [zfile-dev/zfile#14]
Sorry, something went wrong
The access token has expired. It's valid from '2/4/2020 2:58:10 AM' and to '2/4/2020 3:58:10 AM'.

**Comment by zhaojun1998** [comment]
@Omoinemie  什么类型的 OneDrive，系统会通过定时任务自动刷新 Token 的，所以应该不会存在这个问题啊。

上面的提示信息，是哪里提示的。下载文件时？

**Comment by Omoinemie** [comment]
5T的，rclone就不会过期

**Comment by Scolism** [comment]
我的也过期了，奇怪。。就是下载文件时

**Comment by Scolism** [comment]
有没有自己手动添加定时任务的方法呢

**Comment by zhaojun1998** [comment]
@Omoinemie 国际版还是世纪互联，有没有开启缓存。

**Comment by zhaojun1998** [comment]
@CuteLouise 系统中有定时任务的，系统启动时自动刷新一次，然后每 15 分钟自动刷新一次。

**Comment by Scolism** [comment]
国际版的，缓存开了。

**Comment by Scolism** [comment]
> @CuteLouise 系统中有定时任务的，系统启动时自动刷新一次，然后每 15 分钟自动刷新一次。

系统是在crontab里设置的定时吗，我在里面没看到（哭哭哭）

**Comment by zhaojun1998** [comment]
@CuteLouise 程序中内置的，刷新后有输出日志：`tail -fn100 ~/.zfile/logs/zfile.log`

**Comment by Scolism** [comment]
> @CuteLouise 程序中内置的，刷新后有输出日志：`tail -fn100 ~/.zfile/logs/zfile.log`

[日志.txt](https://github.com/zhaojun1998/zfile/files/4156984/default.txt)
这个是日志，好像有错误，您看一下是什么原因，谢谢~

**Comment by zhaojun1998** [comment]
@CuteLouise 晚上解决，白天我还有工作。

**Comment by Scolism** [comment]
辛苦了！

**Comment by Scolism** [comment]
这个我后来重新点击了一次“”存储策略“”里的“”确认“”键，然后清理缓存，然后关闭后又重新开启缓存，就没有这个问题了，原理不清楚。

**Comment by zhaojun1998** [comment]
@Omoinemie @CuteLouise 
经查询，此问题，因为 OneDrive 官方 API 提供的下载地址，就是一小时有效，所以此问题无法解决。

出现这种情况后刷新下页面，一般就好了，会重新获取下载地址的。但对于大文件来说，如果一小时内没有下载完成，那就没办法了，我看了其他对接 onedrive 的也有这个问题，因官方限制，都没解决此问题。
