### ISSUE TITLE
feat: 天翼云盘 有机会加进去吗?

### ISSUE THREAD

**Issue by eluotao** [zfile-dev/zfile#142]
## 概述
现在天翼云盘的市场用户也不少了，很多朋友都有十几年的云盘会员账号，如果能支持天翼云盘，就完美了。毕竟下载速度比百度好多了。

**Comment by zhaojun1998** [comment]
@eluotao  不会支持，因为没有官方 API，但我知道有其他项目支持了，你可以考虑使用那些项目来搭建天翼云的环境。
