### ISSUE TITLE
目录或文件名里有井号'#'会导致路径出错/无法显示文件

### ISSUE THREAD

**Issue by PShawnKD35** [zfile-dev/zfile#164]
## 我的环境

操作系统 | Linux
系统版本 | 4.4.236-perf+
系统架构 | aarch64
程序路径 | ~/zfile/WEB-INF/classes
系统启动时间 | 1天13小时40分26秒
系统总内存 | 0 B
系统已使用内存 | NaN undefined
系统空闲内存 | 51.06 MB
JVM 可占用内存 | 1.24 GB
JVM 已占用内存 | 449.00 MB
JVM 空闲内存 | 231.11 MB
JVM 版本 | 1.8.0_272

## 当前行为

目录或文件名里有井号'#'会导致路径出错/无法显示文件

**Comment by zhaojun1998** [comment]
@PShawnKD35 P

非常抱歉这么久才回复，最新版本已经解决此问题。
