### ISSUE TITLE
用http://localhost.run代理后，文本无法预览

### ISSUE THREAD

**Issue by ibrucekong** [zfile-dev/zfile#172]
## 我的环境

```
属性 | 值
操作系统 | Windows 10
系统版本 | 10.0
系统架构 | amd64
程序路径 |  
系统启动时间 | 34分25秒
系统总内存 | 39.91 GB
系统已使用内存 | 33.10 GB
系统空闲内存 | 6.81 GB
JVM 可占用内存 | 3.54 GB
JVM 已占用内存 | 640.00 MB
JVM 空闲内存 | 390.63 MB
JVM 版本 | 1.8.0_201
```

## 错误日志

[ZFile 诊断日志 - 2021-01-14 09_29_56.zip](https://github.com/zhaojun1998/zfile/files/5811868/ZFile.-.2021-01-14.09_29_56.zip)

## 期望行为

能正常预览文本文件(txt后缀)

## 当前行为

运行jar命令：`java -jar ./zfile-release.jar --server.port=28080`
使用localhost.run代理：`ssh -R 80:localhost:28080 ssh.localhost.run`
然后访问生成的公网地址，结果发现文本(txt)无法预览，报错：
`TypeError: Cannot read property 'init' of undefined`
跟踪代码发现在如下位置报错：
```javascript
initTextDialog: function() {
    this.$refs.textDialog.init() // 这里的$refs中没有textDialog导致init报错
},
```
感谢！

**Comment by zhaojun1998** [comment]
请尝试使用最新版，如有问题可重新打开 issue
