### ISSUE TITLE
尚未初始化驱动器, 请联系管理员

### ISSUE THREAD

**Issue by SynchronizLife** [zfile-dev/zfile#173]
环境windows10，springboot运行后访问http://localhost:8080/#/main，可以登陆，但是登录进去后就报这个异常
<img width="909" alt="微信图片_20210115151408" src="https://user-images.githubusercontent.com/42559229/104693467-abffe900-5744-11eb-8787-fe292e46344c.png">

**Comment by zhaojun1998** [comment]
@SynchronizLife 

这不是报错，是需要你去后台填写你的文件存储源，不然程序不知道展示什么文件。

后台地址：http://ip:port/#/admin

**Comment by SynchronizLife** [comment]
> @SynchronizLife
> 
> 这不是报错，是需要你去后台填写你的文件存储源，不然程序不知道展示什么文件。
> 
> 后台地址：http://ip:port/#/admin



> @SynchronizLife
> 
> 这不是报错，是需要你去后台填写你的文件存储源，不然程序不知道展示什么文件。
> 
> 后台地址：http://ip:port/#/admin



> @SynchronizLife
> 
> 这不是报错，是需要你去后台填写你的文件存储源，不然程序不知道展示什么文件。
> 
> 后台地址：http://ip:port/#/admin
