### ISSUE TITLE
阿里云存储策略图片无法下载

### ISSUE THREAD

**Issue by SynchronizLife** [zfile-dev/zfile#176]
本地存储的驱动器的图片点击下载正常，阿里云驱动器中的图片点击下载只展示图片没有进行下载

**Comment by zhaojun1998** [comment]
@SynchronizLife 右键下载。

**Comment by SynchronizLife** [comment]
> @SynchronizLife 右键下载。
试了，还是只展示，没有下载

**Comment by SynchronizLife** [comment]
> @zhaojun1998 试了，还是只展示，但是本地存储驱动器中的文件的是没问题的，直接点击下载，右键下载都可以

**Comment by zhaojun1998** [comment]
@SynchronizLife 这不是 BUG，只是特性而已，而且是 OSS 本身的特性，想要直接下载请咨询 OSS 的工程师，可以使用再次右键另存为。

**Comment by SynchronizLife** [comment]
> @zhaojun1998 
好的，谢谢
