### ISSUE TITLE
feat: 建议出一个可以直接部署到计算函数的版本

### ISSUE THREAD

**Issue by waitsaber** [zfile-dev/zfile#177]
## 概述

  像在阿里云的计算函数中是可以选择运行环境，其中包括java8、java11、php、pyton，因为看了文档使用的是java的运行环境加上程序本身比较的轻量化，还可以添加各种网盘可以摆脱本地存储，所以建议出一个可以直接运行在计算函数中的版本这样就可以不用去花钱租云服务器可以白嫖了。

## 动机

  动机在于使用该程序大多数使用的是云存储策略如OneDrive、oss等无需本地存储，直接部署在计算函数中会比租用云服务器进行部署要划算，因为访问频率会比较低且完全可以不用本地流量，部署在阿里、腾讯这些计算函数中是比较经济实惠的方案。

## 详细解释

大概就像oneindex、onemanager一样可以直接部署在计算函数中，oneindex、onemanager功能都比较单一只支持OneDrive，支持多种云存储、界面简洁实用的非常少有可以直接部署到计算函数中。

**Comment by zhaojun1998** [comment]
单纯计算函数修改工作量巨大，等于完全重写，不会实现。

而使用计算函数的 java8 运行环境版，费用也是很高的。
