### ISSUE TITLE
如何重置管理後臺帳號密碼

### ISSUE THREAD

**Issue by forjustice** [zfile-dev/zfile#179]

**Comment by forjustice** [comment]
很棒的程序，感謝。
另外，後續是否會支援通過命令重置密碼呢？

**Comment by zhaojun1998** [comment]
@forjustice  配置文件中开启 zfile.debug 模式，然后访问 http(s)://ip:port/debug/resetPwd 即可将账号密码强制重置为 admin 123456   切记重置后，关闭 debug 模式，重新启动项目

**Comment by forjustice** [comment]
> @forjustice 配置文件中开启 zfile.debug 模式，然后访问 http(s)://ip:port/debug/resetPwd 即可将账号密码强制重置为 admin 123456 切记重置后，关闭 debug 模式，重新启动项目

感謝！
