### ISSUE TITLE
请问为什么header.md 上传了，但是就显示了一次，就不再显示了

### ISSUE THREAD

**Issue by smloli** [zfile-dev/zfile#18]

**Comment by smloli** [comment]
还有就是header.md能不能设置显示在底部呢

**Comment by zhaojun1998** [comment]
@smloli  因为底部是滚动加载的，所以不能放在底部。

**Comment by smloli** [comment]
> @smloli 因为底部是滚动加载的，所以不能放在底部。

谢谢，还有那个头部md为什么就偶尔显示啊，另外那个配置文件中cache:300代表多长时间啊，我想改成3小时刷新一次

**Comment by zhaojun1998** [comment]
@smloli 

头部 MD，可能与文件缓存有关，开启缓存后，你上传，程序是无法感知上传的。请在未开启缓存的状态下是否出现偶尔显示的状况。

动态切换缓存刷新时间，这个功能待定。因为涉及的东西比较多，但也应该会支持的。

**Comment by zhaojun1998** [comment]
头部 MD问题，已经修复。动态缓存后续会支持，此问题先关闭了。
