### ISSUE TITLE
feat: 可以试试对接天翼云，阿里的teambition，和蓝奏云oos

### ISSUE THREAD

**Issue by gakiyukr** [zfile-dev/zfile#180]
## 概述
可以试试对接天翼云，阿里的teambition，和蓝奏云oos

## 动机
目前来说天翼云，阿里的t--（简写）算是一个比较好用并且便宜的云盘，并且52有大佬写出类似程序，在实现上应该比从无到有发一个新程序简单。
蓝奏云oos在价格上有很大优势，算是方便了部分小站长，并且目前没见过蓝奏云（无论是oos还是网盘）有相关程序，也算是填补了这一块的市场空白。

**Comment by zhaojun1998** [comment]
@Ansetheisia 
是否对接取决于是否有官方提供的 API，未公开的官方 API 将不会支持。

**Comment by gakiyukr** [comment]
天翼云盘和teambition都是有现成的程序的，大佬可以去52看看，52的程序都能实现列出目录并且生成直链的功能。


------------------&nbsp;Original&nbsp;------------------

**Comment by zhaojun1998** [comment]
@Ansetheisia 是有程序，但不是通过官网 API 接口实现的，使用 cookie 方式或抓包等方式进行登录认证的这里不做考虑。

**Comment by gakiyukr** [comment]
你这样一解释我也明白了，也感谢大佬能抽出时间回复我。


------------------&nbsp;Original&nbsp;------------------
