### ISSUE TITLE
ftp添加后，在主页不显示ftp内容（内有截图链接）

### ISSUE THREAD

**Issue by GAted0** [zfile-dev/zfile#181]
我的ftp配置
https://ftp.bmp.ovh/imgs/2021/02/ec1389adcc7b2778.png

实际ftp根目录 
https://ftp.bmp.ovh/imgs/2021/02/3c81bedbbebcf4ce.png

配置后主页显示
https://ftp.bmp.ovh/imgs/2021/02/173a11097db86260.png

补充一下
日志显示错误代码 530 ，但程序所在主机可以通过其他程序连接该ftp，我电脑本地也可以连接

**Comment by joral1993** [comment]
这个我也遇到了把下面这行注释掉试试
//ftp.getClient().configure(new FTPClientConfig(FTPClientConfig.SYST_UNIX));

**Comment by GAted0** [comment]
> 这个我也遇到了把下面这行注释掉试试
> //ftp.getClient().configure(new FTPClientConfig(FTPClientConfig.SYST_UNIX));

谢谢大佬了，但我现在已经把文件全部上传到od里然后挂载了 QWQ

**Comment by zhaojun1998** [comment]
下版本修复

**Comment by zhaojun1998** [comment]
@joral1993 
@GAted0 
已修复 FTP 功能，见 3.1 版本
