### ISSUE TITLE
feat: 支持隐藏或者不列出某些目录与驱动器

### ISSUE THREAD

**Issue by zjzdy** [zfile-dev/zfile#182]
## 概述
能否支持隐藏或者说不列出某些目录与驱动器，但通过文件url能正常访问与下载里面的文件。
开启后对应的目录或者驱动器显示为空，亦或者不显示。

## 动机
希望能使用zfile提供的功能做直链，但又不想列出目录，避免被爬全部文件。

**Comment by zhaojun1998** [comment]
@zjzdy 支持文件夹密码，可以给文件夹加访问密码，不会影响下载功能。

**Comment by zjzdy** [comment]
这也是一个解决办法，不过我这文件夹层数与文件夹数并不小，逐一添加也是有点费劲，如果能支持在后台直接配置正则/前后缀匹配来设置密码/隐藏就好了

**Comment by zhaojun1998** [comment]
@zjzdy  支持的呀，后台支持通过通配符来隐藏目录或文件的
