### ISSUE TITLE
feat: 能否在后台驱动器列表给每个驱动器添加仅管理员可见备注

### ISSUE THREAD

**Issue by ghost** [zfile-dev/zfile#183]
## 概述

有时候一个策略挂载挂了许多个账号和驱动器，但驱动器名称是按照每个驱动器内文件类型命名，后台想找到对应账号有点麻烦
希望在后台驱动器列表可以给每个驱动器添加  一排仅管理员可见的文字备注信息  功能

为什么不直接给盘符添加备注？
有些不想在前端页面显示

## 动机
这样即使再添加许多驱动器，后在后台仍然一眼就能知道对应账户

**Comment by zhaojun1998** [comment]
非常抱歉这么久才恢复，最新版本已经支持此功能
