### ISSUE TITLE
管理员后台隐藏驱动器后前台仍能通过驱动器id访问相关驱动器  驱动器权限问题

### ISSUE THREAD

**Issue by tvnn** [zfile-dev/zfile#184]
## 我的环境
CentOS Linux 7.9.2009 (Core)

## 错误日志
暂无

## 期望行为
管理员后台通过隐藏驱动器阻止用户在前端访问相关驱动器、下载相关文件

## 当前行为
我通过后台隐藏驱动器后，仍能够通过驱动器id访问相关驱动器，相关驱动器内文件的预览、下载并没有受到阻止

**Comment by zhaojun1998** [comment]
只能做到隐藏，无法完全禁止
