### ISSUE TITLE
设置文件夹密码显示IO错误

### ISSUE THREAD

**Issue by Kissycat** [zfile-dev/zfile#187]
## 我的环境
Openwrt R21 Docker 
k5.4 nginx反代
硬盘根目录映射到/root/zfile/data,驱动器目录写到/root/zfile，写到/root/zfile/data也是一样
密码写在硬盘根目录，也就是/root/zfile/data中
## 错误日志

I/O error on GET request for "https://我.的.域名/file/234/password.txt": 我.的.域名; nested exception is java.net.UnknownHostException: 我.的.域名

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://我.的.域名/file/234/password.txt": 我.的.域名; nested exception is java.net.UnknownHostException: 我.的.域名

## 期望行为

Emmm,我希望能直接给添加的驱动器指定访问密码？

还有这个flv格式的视频加载得超级快，很舒服，但是这个mp4和mkv格式的视频就要黑屏大约15秒才能出画面...

还有部分mkv10分钟也是黑屏的，隔壁h5ai倒是能播放但没有声音，估计是这部分视频格式太水了

## 当前行为

点了哪里？，就是点击加密的文件夹就会这样啊

![image](https://user-images.githubusercontent.com/20614068/107874537-46467e80-6ef5-11eb-9611-bd7d2a91f8e9.png)

嗯，其实我觉得当前用着已经很nice了....

**Comment by zhaojun1998** [comment]
@CDLLY 
你手动访问报错信息中的地址，看看是否可以访问：  `https://你的域名/file/234/password.txt`，错误原因就是服务器尝试去读取这个地址的文件，获取文件内容中的密码，然后读取失败导致的。

 `https://你的域名` 这部分是在站点信息中配置的，如不对，请自行修改。

视频播放速度和程序无关，和网络原因，文件大小，文件格式等都有关系
至于有的视频播放黑屏，或者没声音，是因为格式原因，浏览器直接可以解码的视频格式和音频格式均有限制，这个是浏览器协议规定的，我程序控制不了。

**Comment by Kissycat** [comment]
@zhaojun1998 
Emm,可以手动访问，密码被直接下载下来了，里面就我的一串密码，大写开头，有数字，总共9位...
wc，这岂不是意味着只要挨个访问驱动器号...

站点信息应该没有问题。

关于视频，我的意思是：这个flv文件，哪怕视频有5GB大小，也可以光速点播,但是mp4和mkv文件虽然也可以正常播放，但是要黑屏等15秒，这一点那个h5ai刚好相反，那东西mp4,mkv秒点，flv却时灵不灵，不好使...

**Comment by zhaojun1998** [comment]
@CDLLY
那密码不应该提示错误的，除非你的机器访问不到密码文件这个地址，你用你的服务器，wget 那个地址呢。
而且**密码文件的名称是可以修改**的，这样别人就无法下载你的密码文件了。

还有就是视频这些问题，和程序没有什么关系，都是浏览器来解码和播放的，至于加载速度可能是网络和解码速度有关，也可能和视频的码率有关。

**Comment by Kissycat** [comment]
@zhaojun1998 
试了下，物理主机能wget到文件，zfile的docker容器不行，是zfile主程序和password文件不在一个物理硬盘的问题？还是物理主机上nginx反代的原因？但是为什么页面上都可以访问到password文件，反而主程序却不行，应该也不是前后端的问题啊，算了，业余人员选择放弃思考...🤣

还有那个视频，算了，反正慢点也能用...
（但是用h5ai开相同mp4,mkv文件真的是秒开啊，而且在zfile里打开其他文件也都是秒开的😣）

**Comment by zhaojun1998** [comment]
@CDLLY 那容器内 wget 的错误信息是什么呢，看看原因。

**Comment by zhaojun1998** [comment]
@CDLLY 你是引用了 docker 宿主机的路径么，这是怎么一个关系

**Comment by Kissycat** [comment]
@zhaojun1998 
Emmm，大概就是用docker run 的-v参数把宿主机挂载在/mnt下的硬盘映射到zfile docker容器的uploads/data目录，然后zfile主程序被我映射到另一个磁盘。

zfile的docker容器的相关端口被我映射到宿主机的指定其他端口，然后用Nginx反代了这个端口到443端口，以实现https访问...

**Comment by Kissycat** [comment]
@zhaojun1998 
wget的错误信息就是无法访问嘛，通过域名解析出了我的IP地址:443，然后显示无法访问，正在重试。
我用的是ipv6地址，这应该不影响吧，毕竟它都解析出来了...

**Comment by Kissycat** [comment]
@zhaojun1998 
得，问题解决了，我发现docker容器好像访问不了ipv6地址...
简直了🤯

**Comment by Kissycat** [comment]
@zhaojun1998 
最后，非常感谢帮忙排查到了这个问题所在，但我仍对通过域名访问的方式访问配置文件以验证密码的方法表示怀疑，咱真的不能本地访问吗😣

噢，对了，还有一个问题，似乎所有的开关类选项类的控件，好像对触摸的支持都不太好，PC端触摸很难点到，手机端根本点不了😂

**Comment by zhaojun1998** [comment]
@CDLLY 本地访问可以，但对于其他存储类型呢，毕竟只有本地存储可以访问本地的，其他都要走网络请求。

**Comment by Kissycat** [comment]
@zhaojun1998 
噢，对哦，这还有面向云端存储来着，我不用云储给忘了🤪

Emmm，我现在似乎没有什么问题了，需要把这个issue关闭吗？

**Comment by zhaojun1998** [comment]
触屏问题和移动端问题，暂时没计划进行优化。没什么时间，我可以先加到开发计划中。
