### ISSUE TITLE
response返回的content-type均为application/octet-stream

### ISSUE THREAD

**Issue by shouziws** [zfile-dev/zfile#189]
response返回
Accept-Ranges: bytes
Cache-Control: max-age=43200
Cache-Control: no-cache
Connection: keep-alive
Content-Disposition: form-data; name="attachment"; filename="bbb.jpg"
Content-Length: 153811
Content-Type: application/octet-stream
我如果有一张图片想让其它网站引用，可是用直链链接好像不会展示

**Comment by zhaojun1998** [comment]
下版本会修改

**Comment by zhaojun1998** [comment]
3.2 版本已解决此问题
