### ISSUE TITLE
用阿里云的OSS 权限策略是私有的话 如果是自定义域名 在文件列表访问的时候就无法访问 验签失败，如果用默认的bucket域名访问就没有问题，请问一下和这关怎么处理 谢谢

### ISSUE THREAD

**Issue by Zhaoxixiangchu** [zfile-dev/zfile#191]
用阿里云的OSS 权限策略是私有的话 如果是自定义域名 在文件列表访问的时候就无法访问 验签失败，如果用默认的bucket域名访问就没有问题，请问一下和这关怎么处理 谢谢

**Comment by zhaojun1998** [comment]
@Zhaoxixiangchu  麻烦给更详细的信息。报错信息是什么，在 zfile 添加的配置是怎么填写的，自定义域名绑定截图看一下。
