### ISSUE TITLE
看图模式缩略图

### ISSUE THREAD

**Issue by xinxin8816** [zfile-dev/zfile#193]
目前的看图模式提供原图，这点对大尺寸图片、小屏幕和低带宽环境不友好。

OneDrive 和 SharePoint 官方提供缩略图 API：https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_list_thumbnails

如果能调用该 API 获取缩略图就完美了。

**Comment by Herts** [comment]
为什么Close了？

**Comment by zhaojun1998** [comment]
因为 3.0 版本更新了看图模式。
至于你说的缩略图，是什么。



---原始邮件---
发件人: "Herts ***@***.***&gt;
发送时间: 2021年5月17日(周一) 晚上10:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 看图模式缩略图 (#193)




 
为什么Close了？

**Comment by Herts** [comment]
缩略图就是指Graph提供的缩略图接口，可以在列出文件时返回压缩过的图片：[缩略图API](https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/api/driveitem_list_thumbnails?view=odsp-graph-online)

> Getting thumbnails while listing DriveItems
If you are retrieving a list of DriveItem resources to display, you can use the $expand query string parameter to also include the thumbnails for those resources. This enables your app to retrieve thumbnails and items in a single request, instead of issuing many requests.
`GET /me/drive/items/{item-id}/children?$expand=thumbnails`

我测试过，这样调用也可以：
``https://graph.microsoft.com/v1.0/users/{userId|userPrincipalName}/drive/root:/(path):/children?$expand=thumbnails``

项目里的代码在这里：
```java
    @Override
    public List<FileItemDTO> fileList(String path) {
...
            }else if (ZFileConstant.PATH_SEPARATOR.equalsIgnoreCase(fullPath) || "".equalsIgnoreCase(fullPath)) {
                requestUrl = DRIVER_ROOT_URL;
            } else {
                requestUrl = DRIVER_ITEMS_URL;
            }
...
```

**Comment by Herts** [comment]
> 因为 3.0 版本更新了看图模式。 至于你说的缩略图，是什么。
> […](#)
> ---原始邮件--- 发件人: "Herts ***@***.***&gt; 发送时间: 2021年5月17日(周一) 晚上10:24 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [zhaojun1998/zfile] 看图模式缩略图 (#193) 为什么Close了？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

现在的看图模式生成的是download的那个链接。

我现在的使用需求是放点照片，能给朋友在线看的。发现图片多了，原图加载慢，而且非常卡顿了。

**Comment by Tlntin** [comment]
支持楼主，看图模式很卡。
临时解决办法：通过nginx来实现图片压缩和缓存。但是问题就是会导致无法下载原图。
解决办法，通过观察reffer，当reffer为空的时候，进入原图下载模式。
以下方法适用于本地储存。

我的nginx配置参考：
```text
server {
    listen 8188;
    server_name localhost;
    location ~ /pd/(.*\.(gif|jpg|png|jpeg))$ {
        # 重新设置图片的大小
        alias /data/pan/download/$1;
        image_filter resize 720 720;
        image_filter_buffer 100M;
    }
}


server {
    listen 8189;
    server_name localhost;
    location ~ /pd/(.*\.(gif|jpg|png|jpeg))$ {
        # 直接看原图
        alias /data/pan/download/$1;
    }
}


server
{
    listen 80;
    listen 443 ssl http2;
    server_name xxxxxx;
    index index.php index.html index.htm default.php default.htm default.html;
    #HTTP_TO_HTTPS_START
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    
    client_max_body_size 100m;
    location / {
        client_max_body_size 100m;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:6834/;
    }
    
    # 拦击图片
    location /pd/images/ {
      client_max_body_size 100m;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_cache_key $uri;
      proxy_cache_valid 200 302 240h;
      proxy_cache_valid 404 1m;
      # 压缩后进入缓存，缓存有效期10天。
      # 客户端不开缓存，方便下载图片（实测作用不大，还是保留缓存吧）
      # proxy_cache my_zone;
      # add_header Cache-Control no-cache;
      # add_header Pragma no-cache;
      # add_header Expires 0;
      set $is_matched 0;
      if ($http_referer ~* "xxxxxx"){
          proxy_pass http://127.0.0.1:8188;
          set $is_matched 1;
      }
      # 否则，不进行压缩，直接放原图
      if ($is_matched = 0) {
        proxy_pass http://127.0.0.1:8189;
      }
      valid_referers xxxxxx;
      # 对于没有reffer的情况，则不进行缓存。
      proxy_cache_bypass $invalid_referer;
      proxy_no_cache $invalid_referer;
      
      if ($invalid_referer) {
          proxy_pass http://127.0.0.1:8189;
      }
      
    }
}
```

**Comment by zhaojun1998** [comment]
@Tlntin 

这也是一个好办法，而且后续版本会更新，针对特定的存储类型，支持缩略图的话，会优先读取缩略图，用户自己在配置存储源时根据自己的服务器配置和带宽情况自己决定是否开启。
