### ISSUE TITLE
搜索不管用！

### ISSUE THREAD

**Issue by iceloX** [zfile-dev/zfile#20]
在搜索框中搜索不管用！

**Comment by zhaojun1998** [comment]
@iceloX 怎么个不管用，搜索不到数据嘛，还是提示错误，还是什么情况。

**Comment by iceloX** [comment]
我收不到数据啊！

**Comment by zhaojun1998** [comment]
@iceloX  是否可提供更详细的信息。或者给个演示站。

**Comment by iceloX** [comment]
http://yun.icelo.club/
这个，使用OneDrive网盘存储！

**Comment by zhaojun1998** [comment]
@iceloX 因为没缓存完毕，所以缓存功能无法使用。你这是部署的最新的程序吗。

**Comment by iceloX** [comment]
是的，前天部署的，因为之前使用的是oneindex,那个视频还看不了，这个还有一个问题，有时候会遇到刷新令牌过期的问题！最后希望解决/#/的问题！

**Comment by zhaojun1998** [comment]
@iceloX  
1. 搜索问题：你关闭缓存后，重新开启缓存试下。
2. 刷新令牌过期是指什么，具体在操作什么的时候提示的，目前系统是有自动刷新令牌的。且根据微软的文档看来说访问令牌是有时效性的，但刷新令牌没有时效性。还希望你可以提供更多信息，以协助解决这个问题。
3. 伪静态功能已经有人提出，会尝试解决的。#23
