### ISSUE TITLE
腾讯云cos添加报错

### ISSUE THREAD

**Issue by lovezm** [zfile-dev/zfile#200]
初始化异常, 错误信息为: The specified bucket does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: NjA2MDBiZmJfNTBjODJhMDlfMjhhZjRfMzkzOTU3; S3 Extended Request ID: null)

照着文档截图的内容复制的 应该是没错的 就是报不存在

**Comment by zhaojun1998** [comment]
@lovezm 
参考文档中的示例：[点击进入](http://docs.zhaojun.im/zfile/#/example?id=%e8%85%be%e8%ae%af%e4%ba%91)

**Comment by lovezm** [comment]
对啊 就是按照这个填写的

**Comment by zhaojun1998** [comment]
@lovezm 截图你的腾讯云信息，和你填写的信息，注意截图密钥打码

**Comment by lovezm** [comment]
公有私有我都设置了试了一下 是一样的结果  具体不太清楚是哪里错了 还望指点一下



***@***.***
 
发件人： 赵俊
发送时间： 2021-03-30 18:34
收件人： zhaojun1998/zfile
抄送： WangMuDu; Mention
主题： Re: [zhaojun1998/zfile] 腾讯云cos添加报错 (#200)
@lovezm 截图你的腾讯云信息，和你填写的信息，注意截图密钥打码

**Comment by lovezm** [comment]
![image](https://user-images.githubusercontent.com/10624938/113076685-2eeff600-9202-11eb-9409-7d241c59c7e8.png)
![image](https://user-images.githubusercontent.com/10624938/113076714-3d3e1200-9202-11eb-93fa-a99508251599.png)

**Comment by zhaojun1998** [comment]
@lovezm 你确定你这个密钥和这个对象存储是同一个账号中的？或者你的密钥有访问对象存储权限么。

**Comment by lovezm** [comment]
是同一账号的 我是用QQ登录的 应该不会错吧

**Comment by lovezm** [comment]
权限方面 创建密钥的时候么有看到有设置相关的啊 应该都有的吧

**Comment by zhaojun1998** [comment]
你确认下密码，或者重新复制下密钥，如果还不行，新创建一个存储桶试试

**Comment by lovezm** [comment]
好了 就是那个存储桶的问题好像  新建了一个就可以了 应该是以前创建的  区域不一样吧
