### ISSUE TITLE
feat: 增加阿里云盘支持

### ISSUE THREAD

**Issue by qingshanking** [zfile-dev/zfile#203]
## 概述

尊敬的开发者，您好，感谢您开源这个项目，目前阿里云盘热度挺火，建议增加阿里云盘的支持。目前github上已经有支持这个功能的，但是有些单一，希望可以集成一下。

https://github.com/Xhofe/alist

## 动机

目前阿里云盘热度比较高，下载速度快。

## 详细解释

目前网上开源的阿里云盘，都是基于api进行调取即可，下载文件速度快。

**Comment by zhaojun1998** [comment]
@qingshanking  如官方不正式开发 API，本项目不会支持，自抓取 API 有封号风险。
