### ISSUE TITLE
 S3通用协议不支持Oracle Cloud对象存储的Amazon S3 Compatibility API

### ISSUE THREAD

**Issue by judiw** [zfile-dev/zfile#206]
## 期望行为

添加Oracle Cloud对象存储作为驱动器

## 当前行为

Oracle Cloud在使用S3协议请求的EndPoint为：mynamespace.compat.objectstorage.us-phoenix-1.oraclecloud.com
且需要指定region或留空。
![image](https://user-images.githubusercontent.com/38564340/113569819-b5169d00-9645-11eb-9243-a4a1174b31d2.png)
但程序中取region值的方法为region = endPoint.split("\\.")[1]; 即将“compat”作为了region，导致请求错误。
![image](https://user-images.githubusercontent.com/38564340/113569736-8c8ea300-9645-11eb-8a3f-71b8b90ea4a0.png)
请求在配置页面增加region配置字段，以解决这种情况

**Comment by zhaojun1998** [comment]
3.2 版本已解决此问题
