### ISSUE TITLE
求助一下大佬，如何在网页中增添一个浏览量记录器

### ISSUE THREAD

**Issue by LengMingxuan** [zfile-dev/zfile#207]
你好！感谢你愿意考虑希望 ZFile 增加“浏览量记录器”新功能。

  谢谢！

## 动机

我公开了我用你的项目搭建的资源分享网站
## 详细解释

可以记录这个网页被多少人浏览过

**Comment by zhaojun1998** [comment]
@LengMingxuan 本程序不会加次功能，可使用百度统计来实现。[点击进入](https://tongji.baidu.com/web/welcome/login)
