### ISSUE TITLE
非首页路径下刷新页面会返回首页

### ISSUE THREAD

**Issue by Tasle** [zfile-dev/zfile#209]
已更新到最新版，
系统 Debian 10

问题：
1. 非首页路径下页面刷新会返回首页
2. 未启用的驱动器可以用驱动id访问后用按钮下载
     比如挂载了驱动器1 id:1 ，可以用 XXXXX/#/1/main 访问后用右侧的下载按钮下载

**Comment by zhaojun1998** [comment]
已知问题，下版本都会修复

**Comment by zhaojun1998** [comment]
@Tasle  已修复，见 3.1 版本
