### ISSUE TITLE
加密文件夹输入一次密码，其他人都可以直接访问，不再需要输入密码了，只有从后台再次刷新这个文件夹缓存，才需要再次输入密码

### ISSUE THREAD

**Issue by smloli** [zfile-dev/zfile#21]
是我设置有问题，还是本来就是这样呀

**Comment by zhaojun1998** [comment]
@smloli 

加密文件夹输入一次密码后，会在浏览器缓存这个密码，下次就不用输入了，当你切换浏览器或者清空浏览器缓存后，还是需要再次输入密码的。

还是通用的问题，你动态添加的 password.txt 文件，程序无法感知，需要手动刷新缓存，或者自动刷新缓存后，方可生效。

**Comment by zhaojun1998** [comment]
经测试这是个 BUG，已经修复。
