### ISSUE TITLE
feat: 希望能增加隐藏直链的功能

### ISSUE THREAD

**Issue by DMC-cmd997** [zfile-dev/zfile#211]
希望可以增加隐藏直链的功能。只单独显示短链接用于下载就可以了。

**Comment by zhaojun1998** [comment]
下版本考虑添加

**Comment by a2313153** [comment]
> 希望可以增加隐藏直链的功能。只单独显示短链接用于下载就可以了。

非常赞同，希望增加隐藏直连和批量下载，每次都要自己改下js太麻烦了

**Comment by zhaojun1998** [comment]
@a2313153  @DMC-cmd997 已支持，见 3.1 版本
