### ISSUE TITLE
按照文档描述反代后访问提示ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Tokiichika** [zfile-dev/zfile#215]
按照文档描述反代后访问提示ERR_TOO_MANY_REDIRECTS
纯小白，望dalao赐教

**Comment by zhaojun1998** [comment]
截图反代设置，最好给个预览地址。

**Comment by Tokiichika** [comment]
![image](https://user-images.githubusercontent.com/82693134/115554627-4130f180-a2e1-11eb-8ba1-bebfcd4127c9.png)
就是这样设置的，之前不行，现在它自己又好了 ，预览地址是www.chinodisk.top,现在的问题就是我宝塔那边开了SSL之后访问还是会提示这个：
![image](https://user-images.githubusercontent.com/82693134/115554830-789f9e00-a2e1-11eb-9eea-b71578d9f5bf.png)
去百度查了一下基本上都解决不了，是因为我套了cloudflare（开了绕过缓存）的原因吗，还是需要配置下nginx改ssl的端口？

**Comment by zhaojun1998** [comment]
我没套过 CF，你可以自己试验下到底是哪里的问题，因反代问题和本项目无关，故关闭该 issue，有项目问题再重新开启 issue。
