### ISSUE TITLE
feat: readme.md文档显示的建议

### ISSUE THREAD

**Issue by luolovehk** [zfile-dev/zfile#216]
readme.md建议考虑一下，
不要放在一个框架里面固定位置，需要再次拖动滚动条查看，
直接加载主页面下拉查看就可以了。
或者把这个框架再做长一点，太多文字的看起来有点困难。

**Comment by zhaojun1998** [comment]
可以考虑下，这样的话，其实文件也没必要固定到中间，都应该自动向下平铺。

**Comment by zhaojun1998** [comment]
@luolovehk 

非常抱歉这么久才回复，最新版本已经支持此功能。
