### ISSUE TITLE
添加FTP时，错误

### ISSUE THREAD

**Issue by zhiyuan2016** [zfile-dev/zfile#218]
添加FTP驱动器时，FTP账号正常，但加载出错
windows10系统
错误代码:
could not execute statement; SQL [n/a]; nested exception is org.hibernate.PessimisticLockException: could not execute statement
![IMG_20210426_135334](https://user-images.githubusercontent.com/35165744/116035105-02ab8600-a697-11eb-9d6b-4ea3fc4f8591.jpg)

**Comment by zhaojun1998** [comment]
FTP 有 BUG，下版本会修复

**Comment by zhaojun1998** [comment]
@zhiyuan2016  已修复 FTP 功能，见 3.1 版本
