### ISSUE TITLE
feat: 功能建议，

### ISSUE THREAD

**Issue by luolovehk** [zfile-dev/zfile#220]
我通过这个程序主要是浏览图片和视频比较多，是否考虑添加打开图片观看的时候支持点击或者滑动下一张，视频播放支持下一条或者列表完毕整个文件夹的功能。谢谢

**Comment by zhaojun1998** [comment]
下版本会支持的

**Comment by zhaojun1998** [comment]
@luolovehk 

非常抱歉这么久才回复，最新版本已经支持此功能。
