### ISSUE TITLE
关于搜索功能

### ISSUE THREAD

**Issue by geekmakersun** [zfile-dev/zfile#221]
我开启了缓存 ，前台未显示搜索功能，

**Comment by a2313153** [comment]
由于安全问题好像取消了，但还是希望恢复让站长自己选择是否开启，个人认为利大于弊

**Comment by jtyoui** [comment]
可以搜索本地也好

**Comment by tb-bear** [comment]
同感，本地文件支持检索名称即可

**Comment by zhaojun1998** [comment]
@a2313153 
@GeekMakerSun 
@jtyoui 


非常抱歉这么久才回复，最新版本已经重新支持此功能。
