### ISSUE TITLE
刷新页面的时候有办法不回到首页吗

### ISSUE THREAD

**Issue by fopiko** [zfile-dev/zfile#224]
每次在文件夹里面刷新都会回到首页，是我设置上的问题吗？还是程序就是这样的

**Comment by zhaojun1998** [comment]
这是个 BUG，下次更新会修复

**Comment by fopiko** [comment]
有时候返回上一页文件名会错乱，名字是显示另外的文件，点进去又是别的文件，这个bug要再开一个issue还是在这里反馈就行？

**Comment by zhaojun1998** [comment]
已修复 FTP 功能，见 3.1 版本，其他 bug 新开一个 issue 吧。
