### ISSUE TITLE
项目为什么不用Graph的SDK?

### ISSUE THREAD

**Issue by Herts** [zfile-dev/zfile#226]
请问：
[https://mvnrepository.com/artifact/com.microsoft.graph/microsoft-graph](https://mvnrepository.com/artifact/com.microsoft.graph/microsoft-graph)
[https://mvnrepository.com/artifact/com.azure/azure-identity](https://mvnrepository.com/artifact/com.azure/azure-identity)
是Microsoft开发的Graph和azure身份认证的SDK，请问下为什么项目里不用啊？

**Comment by zhaojun1998** [comment]
因为不好用，他那是为安卓设计的 sdk



---原始邮件---
发件人: "Herts ***@***.***&gt;
发送时间: 2021年5月18日(周二) 凌晨0:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 项目为什么不用Graph的SDK? (#226)




 
请问：
 https://mvnrepository.com/artifact/com.microsoft.graph/microsoft-graph
 https://mvnrepository.com/artifact/com.azure/azure-identity
 是Microsoft开发的Graph和azure身份认证的SDK，请问下为什么项目里不用啊？
