### ISSUE TITLE
您好，请问脚本可以在同一个服务器上面运行多个吗？

### ISSUE THREAD

**Issue by DMC-cmd997** [zfile-dev/zfile#227]
请问脚本可以在同一个服务器上面运行多个吗？
我想在一个服务器上面运行多个，每个都绑定不同的域名。
试了下，好像第一个运行了以后，运行第二个好像也还是第一个运行的数据。

**Comment by zhaojun1998** [comment]
启动脚本前，修改配置文件中的启动端口，数据库文件，日志文件，临时文件路径即可同时启动多个



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月21日(周五) 晚上10:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 您好，请问脚本可以在同一个服务器上面运行多个吗？ (#227)




 
请问脚本可以在同一个服务器上面运行多个吗？
 我想在一个服务器上面运行多个，每个都绑定不同的域名。
 试了下，好像第一个运行了以后，运行第二个好像也还是第一个运行的数据。

**Comment by DMC-cmd997** [comment]
感觉您的答复，我还有一个疑问，就是关于防盗链的。我把zflie里面的资源作为视频床调用，然后在宝塔面板中设置了防盗链，许可域名也设置了我自己的域名，但是发现无法调用，这个防盗链功能能写到脚本里面吗？

**Comment by zhaojun1998** [comment]
@DMC-cmd997 无法调用是怎么无法调用，什么现象，有什么错误信息，打开浏览器控制台 F12 看看

**Comment by DMC-cmd997** [comment]
不好意思，我看了下，已经没问题了。宝塔面板里面给反代理的配置文件写上防盗链规则就可以了。
