### ISSUE TITLE
FTP“暂无数据”

### ISSUE THREAD

**Issue by Song-Xin233** [zfile-dev/zfile#229]
最新的构建版本  
添加FTP协议的映射后在主页访问显示“暂无数据”  
但是FTP里面是有东西的23333

![image](https://user-images.githubusercontent.com/64391901/120054846-0c912200-c065-11eb-938c-a7b87e2974e0.png)

**Comment by star2k** [comment]
docker 3.1也一并更新一下吧。

**Comment by zhaojun1998** [comment]
@Song-Xin233 @star2k 已修复 FTP 功能，见 3.1 版本，docker 版也更新了 3.1
