### ISSUE TITLE
可否添加伪静态功能呢

### ISSUE THREAD

**Issue by noisky** [zfile-dev/zfile#23]
vue地址中的/#/不是很友好，可否添加伪静态功能将其隐藏掉呢

**Comment by zhaojun1998** [comment]
会考虑实现，在不影响原先功能的前提下。

**Comment by noisky** [comment]
主要是作为永久链接使用，而且现在程序好像没有外链功能，直接访问文件绝对路径什么都不显示，
如: 
https://dl.ffis.me/#/main/Chrome/Tampermonkey_4.6.0.crx
直接访问是无法下载的
只有点击下载后才能复制到微软的下载链接，然而那个显然不适合做外链用，所以伪静态功能还是很有用的，
https://dl.ffis.me/Chrome/Tampermonkey_4.6.0.crx
既可以作为永久地址 也可以作为外链
有了伪静态了 也可以添加右键复制链接的功能了
只是一个建议
不错的程序支持一下~

**Comment by zhaojun1998** [comment]
明白你的意思了。微软的那个下载链接是有时效性的，不能用于永久链接。

但伪静态这功能，不太好实现，怕会影响 vue 的路由功能，但我可以提供永久地址。如：

对于 `/Chrome/Tampermonkey_4.6.0.crx` 来说，我提供如下地址，用于访问永久链接：

```
https://dl.ffis.me/link/Chrome/Tampermonkey_4.6.0.crx
```

即，需要加一个 `link` 前缀。

**Comment by noisky** [comment]
外链功能可以加 伪静态这个不是刚需

**Comment by zhaojun1998** [comment]
ok，明天更新个版本，右键增加复制永久链接功能。

**Comment by zhaojun1998** [comment]
已更新版本。
