### ISSUE TITLE
希望会增加隐藏驱动器的功能。

### ISSUE THREAD

**Issue by DMC-cmd997** [zfile-dev/zfile#230]
3.0版本那个是否启用，实际就是隐藏吧。希望能把这个功能放到新版本里面。
3.1版本里面就变成实实在在的关闭驱动器了。

主要我做视频图床用，把驱动器禁用了以后，链接也解析不了。希望可以有隐藏驱动器的功能。隐藏完还可以解析链接。

**Comment by zhaojun1998** [comment]
这个可以自行使用文件夹密码功能来限制其他人访问驱动器，不额外增加太多相似的功能了，过于臃肿了。
