### ISSUE TITLE
能提供 ARM 支持么? 或 Dockerfile

### ISSUE THREAD

**Issue by stilleshan** [zfile-dev/zfile#233]
早前看到 Dockerfile 中的 FROM  zhaojun1998/alpine-java 的基础镜像.
能提供ARM版支持么? 或者 dockerfile 文件自己来构建?

**Comment by stilleshan** [comment]
已经自己解决!

**Comment by wanggq654321** [comment]
能发下你的dockerfile 吗 ？

**Comment by stilleshan** [comment]
https://github.com/stilleshan/dockerfiles/blob/main/zfile/Dockerfile
