### ISSUE TITLE
建议增加管理员界面上传功能

### ISSUE THREAD

**Issue by jiazhi1** [zfile-dev/zfile#237]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by zhaojun1998** [comment]
有这个计划，但不确认发布时间

**Comment by zhaojun1998** [comment]
@jiazhi1 

非常抱歉这么久才回复，最新版本已经支持文件上传功能，且可控制游客是否可用。
