### ISSUE TITLE
下载项目时失败

### ISSUE THREAD

**Issue by sirewang** [zfile-dev/zfile#238]
<img width="511" alt="image_249" src="https://user-images.githubusercontent.com/62597175/123099145-7df5a200-d464-11eb-86c2-c9dce1aa8f45.png">
您好，在安装项目的时候命令框显示没有安全证书无法安装，请问一下这是什么情况？

**Comment by zhaojun1998** [comment]
@1170761233  已修复，重试下

**Comment by sirewang** [comment]
> @1170761233 已修复，重试下

好了，恢复了，感谢老哥
