### ISSUE TITLE
建议增加首页可选账号密码登陆功能

### ISSUE THREAD

**Issue by Tennyson75** [zfile-dev/zfile#241]
我搭建zfile是做个人私人网盘，不做公共网盘，别人通过我的直链知道我的域名，一输入域名就可以看见我的网盘文件列表就很不爽，虽然可以通过在根目录下放置一个密码文件，但就是不想别人知道这个域名就是一个网盘。希望怎加可选首页需要账户密码登陆功能。我尝试通过宝塔面板进行访问限制，结果分享的直链也访问限制了。或者可以让首页显示401，不会跳转到网盘目录页面。感谢大佬

**Comment by zhaojun1998** [comment]
@Tennyson75 此功能不会支持，可自行使用 nginx 指定目录，排除掉直链地址来设置访问权限。
