### ISSUE TITLE
feat：加密功能问题，不需要密码就能够访问加密文件夹下的子文件夹

### ISSUE THREAD

**Issue by ycdxsb** [zfile-dev/zfile#242]
## 概述
虽然目前zfile能够对单个文件夹加密，但是我发现zfile并没有对该文件夹下的所有子文件夹进行加密，攻击者可以暴力的去枚举子文件夹的路径，对这些没有加密的子文件夹进行访问

比如我在网盘根目录下通过password.txt对它进行了加密，其实隐含的意思是说，我要访问这个网盘，就得输入密码，但我访问网盘中某个没有password.txt文件的文件夹时，并不需要我输入密码，这其实是违背了我的想法的。

## 动机
我在自己设置网盘密码的时候发现了这个问题，当我在根目录下设置了password.txt时，我可以在不输入密码直接访问根目录下其他的文件夹，这其实是一个安全隐患

## 详细解释
无

**Comment by zhaojun1998** [comment]
@ycdxsb 

可如果父目录有密码，别人压根不可能知道目录名称都有什么，所以也不存在直接访问子文件夹的情况。

如果你想全局设置密码，可以使用 nginx 增加 Basic HTTP authentication

不考虑这个问题还有一个原因就是性能原因，如访问 /1/2/3/4/5 那么访问的性能就比访问 / 慢五倍。或者你可以给每个文件夹都加上 password.txt 文件，这样会更灵活。毕竟不是每个人都认为应该限制其子文件夹
