### ISSUE TITLE
请问S3协议支持密码和readme吗？

### ISSUE THREAD

**Issue by stevennight** [zfile-dev/zfile#243]
请问S3协议支持密码和readme吗？这边添加了文件了，但是两个都没有效果。
请问可以给些思路帮忙看看吗，不知道怎么排查了。谢谢。

**Comment by zhaojun1998** [comment]
支持的

1. 请先尝试其他类型的文件是否可正常下载。
2. 检查是否是公开空间，不是的话，记得在 zfile 勾选私有空间
3. 如果上面两个都没问题，请提供诊断日志，可在管理员页面点击下载

**Comment by stevennight** [comment]
> 支持的
> 
> 1. 请先尝试其他类型的文件是否可正常下载。
> 2. 检查是否是公开空间，不是的话，记得在 zfile 勾选私有空间
> 3. 如果上面两个都没问题，请提供诊断日志，可在管理员页面点击下载

是不是哪里有缓存，今天就好了。 但是我没有开驱动器里面的缓存。
