### ISSUE TITLE
nginx反代后404. 通过ip访问正常

### ISSUE THREAD

**Issue by skyrim663** [zfile-dev/zfile#245]
nginx设置：
	     location /path {
	     proxy_pass http://127.0.0.1:XXXX;
	     proxy_http_version 1.1;

	    }

**Comment by skyrim663** [comment]
zfile配置文件仅修改了端口

**Comment by zhaojun1998** [comment]
1. 反代是你配置问题，和zfile无关。
2. 不支持域名后增加额外路径的方式
