### ISSUE TITLE
feat: 希望增加密码访问文件夹日志记录

### ISSUE THREAD

**Issue by alimalls** [zfile-dev/zfile#246]
老大有没考虑增加一下文件夹密码访问记录功能，我想方便记录都有谁用密码访问过文件夹，什么时候，从哪个IP访问的。这样我可以方便知道我的密码有没涉密，文件夹有没被人访问过。只记录正确访问的，错误的可以不记录。

**Comment by zhaojun1998** [comment]
这个不会加，非公共需求
