### ISSUE TITLE
sharepoint世纪互联是否支持根目录

### ISSUE THREAD

**Issue by rain10154** [zfile-dev/zfile#249]
我自己搭建了一套，使用的sharepoint世纪互联，但是由于我的文档都放在根目录下，目前显示不出来

**Comment by zhaojun1998** [comment]
没明白你的意思，什么根目录。

目前显示不出来是什么意思，是在后台添加不成功，还是说添加成功了，但现实的不是根目录，还是什么意思。

**Comment by rain10154** [comment]
不好意思，回复慢了，是这样的，就是sharepoint世纪互联在选择的时候必须是sites或者是teams下面的，但是我的文件不在这两个下面，在其他软件，比如raidrive做选择的时候直接选择root目录就行了，没有跟任何sites或者是teams关联

**Comment by zhaojun1998** [comment]
你说的是 onedrive 下的文件么，目前来看 sharepoint 是只有 sites 和 teams 的。

**Comment by rain10154** [comment]
不是onedrive呢，就是sharepoint

**Comment by rain10154** [comment]
![1629188565(1)](https://user-images.githubusercontent.com/5436350/129690831-c4ecd035-12d9-47be-bbf7-c28eb2110559.png)
举个例子，比如说raidrive只需要root就好了

**Comment by rain10154** [comment]
![1629188749(1)](https://user-images.githubusercontent.com/5436350/129691269-d4a56148-4938-4402-a360-e878b0a5b430.png)
看了一下配置，完整的是这样的

**Comment by zhaojun1998** [comment]
你登录世纪互联后台，进去 sharepoint 这个目录，然后看 url 参数是什么，比如我的 sharepoint 中文件夹名为： zfile，我的 URL 就是：https://sust365.sharepoint.cn/sites/zfile

**Comment by rain10154** [comment]
https://*.sharepoint.cn/Shared%20Documents/Forms/AllItems.aspx?viewid=835a9fb8%2Dafae%2D4f7e%2Da644%2D8ba586674848&id=%2FShared%20Documents%2Fbook难道是中间的Shared%20Documents

**Comment by zhaojun1998** [comment]
你这是分享链接？

别人或者你分享的文件夹？

**Comment by rain10154** [comment]
这个是我查看时候的链接啊，里面的一个文件夹是book，自己看的，你的意思是需要分享出去的链接是吗

**Comment by zhaojun1998** [comment]
你是这个域的超级管理员么，这种路径是怎么创建的，我这里发现只能创建网站才能存文件，你这是存储到哪里的

**Comment by rain10154** [comment]
对，我自己的号，这些文件在设置-网站内容-文档里面

**Comment by zhaojun1998** [comment]
目前不支持存储在这个路径的文件

**Comment by rain10154** [comment]
有计划支持不，或者这个好改吗，最近正好有时间

**Comment by zhaojun1998** [comment]
可以添加到计划，但最近没时间

**Comment by zhaojun1998** [comment]
@rain10154 

非常抱歉这么久才回复，最新版本已经支持选择 SharePoint 子网站和子目录功能
