### ISSUE TITLE
提个建议|能不能把“右侧信息框”的内容居中，贴在右边看起来好难受...

### ISSUE THREAD

**Issue by IO0288** [zfile-dev/zfile#25]
![image](https://user-images.githubusercontent.com/48312963/74083743-8b460280-4aa2-11ea-8094-30e727536cd1.png)
另外，如果可以的话，能不能加一个能验证身份的上传功能。

**Comment by zhaojun1998** [comment]
@IAbu0288
1. 没明白，如何居中，能详细说下吗，你指的是 “pan” 那个字吗。
2. 验证身份的上传功能会增加的。

**Comment by IO0288** [comment]
是文件夹那个图片和下面的二维码，它们是贴在右侧屏幕边缘的。

**Comment by zhaojun1998** [comment]
@IAbu0288  那你的意思是放在哪里比较好。

**Comment by IO0288** [comment]
@zhaojun1998 emm就是稍微往左边移动一点点，在“右侧信息框”中图片居中。别贴在屏幕边缘就行。
![Snipaste_2020-02-09_16-01-32.png](https://image-iabu.oss-accelerate.aliyuncs.com/2020/02/09/11cfed765cec6.png)

**Comment by zhaojun1998** [comment]
已更新版本
