### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by ST-0nirii** [zfile-dev/zfile#250]
新版本的txt预览蛮好用的，右侧的预览sublime的很像很喜欢，
但是不支持ctrl+F搜索，文档内也无法ctrl+F，希望能被搜索到/允许文档内开启搜索吧~

**Comment by zhaojun1998** [comment]
后续版本会完善编辑器，增加搜索，高亮，等功能

**Comment by zhaojun1998** [comment]
@ST-0nirii S
非常抱歉这么久才回复，最新版本已经支持此功能。
