### ISSUE TITLE
反馈个播放flv视频的问题

### ISSUE THREAD

**Issue by xiaocainiao2020** [zfile-dev/zfile#258]
用b站录播姬标准模式录制的flv视频，在zfile上点击播放后，拖动进度条然后就卡住了，一直转圈圈不能继续播放。生成直链放到potplayer是可以正常播放正常拖动的。

**Comment by zhaojun1998** [comment]
后续会尝试解决此问题

**Comment by zhaojun1998** [comment]
@xiaocainiao2020 

非常抱歉这么久才回复，最新版本已经支持调用本地播放器来解决视频播放格式和卡顿问题。
