### ISSUE TITLE
MinIO 添加异常， Error Code: AuthorizationHeaderMalformed

### ISSUE THREAD

**Issue by stevennight** [zfile-dev/zfile#259]
日志：
```
Resolved [im.zhaojun.zfile.exception.InitializeDriveException: 初始化异常, 错误信息为: . (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: 169A780A6427A6A0; S3 Extended Request ID: 1867056a-27f0-414e-9214-fc74770bf39a)]
```

个人觉得，很有可能是因为“Region"的问题，因为我用php-aws组件调的时候，Region不对就报错了，也是报AuthorizationHeaderMalformed，不知道和这个有没有关系。但是在zfile后台无论选择通用协议还是MinIO都没有办法添加一个Region，区域的设置。
麻烦大佬看一下哈~

![捕获.PNG](https://i.loli.net/2021/08/12/fiGLeg3MEhAwOYK.png)
如图MinIO Console，好像还不能留空。

**Comment by zhaojun1998** [comment]
后续会修复此 BUG

**Comment by zhaojun1998** [comment]
3.2 版本已解决此问题
