### ISSUE TITLE
txt不显示内容？

### ISSUE THREAD

**Issue by dudt** [zfile-dev/zfile#260]
打开txt文档只有一个1内容。是什么原因呀

**Comment by zhaojun1998** [comment]
请详细描述你的问题。

你用的存储引擎。
txt 文档预期应该是什么内容。
下载文件都查看文件内容是否正常。
是否所有文件都显示为 `1`
如果是本地存储，你的站点地址设置的是否正确。

**Comment by zhaojun1998** [comment]
长期未回复，暂时关闭此问题，有问题再打开。
