### ISSUE TITLE
点击文件跳转提示404

### ISSUE THREAD

**Issue by lcnwys** [zfile-dev/zfile#261]
点击文件跳转提示 “很抱歉，您要访问的文件/页面不存在！”，点击下载也一样，但是点击后面的生成直链的链接却可以访问，这是哪里配置不对么，在线等大佬回复

**Comment by zhaojun1998** [comment]
是否是本地存储

如果是本地存储，请检测站点域名设置是否正确。
如果不是本地存储，请提供使用的存储类型，什么情况下文件会出现这种情况。最好提供预览站点

**Comment by lcnwys** [comment]
onedrive 存储方式，站点 zfile.lcnwys.com

**Comment by zhaojun1998** [comment]
你 onedrive 填写反代域名了？写的是：`https://zfile.lcnwys.co`，而且你这写的也不对，这个域名是有要求的，需要配置，详见文档。

**Comment by lcnwys** [comment]
原来这个反代说的不是我理解的那个反代，感谢大佬把反代域名清空就可以了

**Comment by zhaojun1998** [comment]
这个反代地址，反代的是 onedrive 的下载地址
