### ISSUE TITLE
无法加载文件列表

### ISSUE THREAD

**Issue by threo9** [zfile-dev/zfile#262]
Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection

我的Zfile项目运行于CentOS 7的服务器上，在我打开该站点时无法加载文件显示此错误，若有需要我可以提供日志文件，谢谢！

**Comment by threo9** [comment]
重启程序可以暂时解决此问题。

**Comment by zhaojun1998** [comment]
请检查是否有其他程序会扫描并占用数据库文件（如云盾，安全狗等程序），数据库文件默认在 /root/.zfile/db 文件夹下

**Comment by threo9** [comment]
@zhaojun1998 谢谢，已排查出是重启项目没有权限操作数据库导致的问题
