### ISSUE TITLE
腾讯云提示Jackson 远程代码执行漏洞

### ISSUE THREAD

**Issue by lcnwys** [zfile-dev/zfile#263]
今天收到服务器安全提醒提示说jackson-databind-2.9.7.jar 存在安全隐患，项目是否需要这个包，是否可以直接删掉这个包，还是说我去 marven下载新版本的包替换就可以呢，我搜索jackson-data 开头的文件有好几个同样是2.9.7版本的是否都需要升级
![image](https://user-images.githubusercontent.com/40192017/129822388-393703cc-0c4e-4f85-9b65-2d984bfc4eac.jpeg)

![image](https://user-images.githubusercontent.com/40192017/129822408-7942a442-9f48-4c74-b494-911c51bb0877.jpeg)

**Comment by zhaojun1998** [comment]
后续版本会修复此问题，也可手动升级这些包放到 lib 目录下

**Comment by zhaojun1998** [comment]
3.2 版本已解决此问题
