### ISSUE TITLE
怎么用宝塔docker管理器去部署呢

### ISSUE THREAD

**Issue by vlssu** [zfile-dev/zfile#264]
没办法正常运行，运行指令那边是需要添加什么指令吗
![image](https://user-images.githubusercontent.com/43847794/130310178-82554db1-0166-48a4-942e-46dddbce0ab6.png)

**Comment by zhaojun1998** [comment]
现在你这样设置，部署有什么问题，报错还是什么。如果报错，报错信息是什么。如何体现的

**Comment by vlssu** [comment]
防火墙和安全组全都开放了3010但都是无法访问的
![image](https://user-images.githubusercontent.com/43847794/130914428-150a4bd4-35b6-423c-b215-5b405699634e.png)
![image](https://user-images.githubusercontent.com/43847794/130914102-10d4df9b-43f8-48b5-945f-837a5431b283.png)
![image](https://user-images.githubusercontent.com/43847794/130914789-b647df8b-56fe-4978-a839-e67a8aa4e5ad.png)

**Comment by zhaojun1998** [comment]
看看日志路径 /root/zfile/logs 你映射到宿主机的日志

**Comment by vlssu** [comment]
并没有成功映射
![image](https://user-images.githubusercontent.com/43847794/130950235-ff65f596-cda3-405d-888c-e6c6fad191c5.png)

**Comment by zhaojun1998** [comment]
你现在到底是不是用 docker 部署的呀，如果是，怎么这里还有 war 文件，还有META-INF 等文件

**Comment by vlssu** [comment]
使用docker部署的，但是因为用不了我就先用linux的启动方式去启动他了

docker的一开始我尝试很多次他都没有启动成功

**Comment by zhaojun1998** [comment]
可能你映射的端口已经被占用了，或者使用纯命令的 docker 试试，宝塔的那个我没用过。

使用 docker 映射后，如果访问不了，请提供 docker 映射后的日志信息，如果 docker 路径映射都不好使，这个你就应该先去找宝塔官方解决这个插件的问题了。

目前你没有提供日志信息，我无法排查问题。

**Comment by vlssu** [comment]
好的
