### ISSUE TITLE
feat: 增加对onedrive病毒程序下载支持

### ISSUE THREAD

**Issue by dreamncn** [zfile-dev/zfile#267]
## 概述

onedrive病毒程序下载支持

## 动机

使得包含病毒程序代码的文档可以正常下载。

## 详细解释

我是一个安全研究人员，会经常性地上传一些病毒程序、以及包含病毒程序代码的文档或者疑似病毒程序（onedrive误报），但是他们在下载的时候，却出现了问题，onedrive的网站上可以下载，只是下载之前会弹出警告。希望zfile也可以像onedrive一样弹出警告并允许下载。

如果你需要测试，我可以提供相关病毒程序，它只有两行代码，不过不会造成什么大的危害。

**Comment by zhaojun1998** [comment]
这个不受我程序控制，微软提供的下载 api，默认就不支持下载这种类型的文件。没有额外的选项可以下载。
