### ISSUE TITLE
这个项目不支持arm设备吗

### ISSUE THREAD

**Issue by wangx2** [zfile-dev/zfile#268]
docker命令倒是简单，我进去一看他显示amd64,这个是不是不支持arm设备呀？

安装也没报错，但是就是无法访问。

**Comment by DingChang90** [comment]
支持的， N1正常安装了，很好用。

**Comment by zhaojun1998** [comment]
@wangx2  那可能是你防火墙或者其他问题，这个支持 arm 是没问题的。

**Comment by zhaojun1998** [comment]
长期未回复，暂时关闭此问题，有问题再打开。
