### ISSUE TITLE
header.md 在x5内核下可以正常下拉浏览文件夹，谷歌内核就不行了，会卡住，下拉不了

### ISSUE THREAD

**Issue by smloli** [zfile-dev/zfile#27]
![截屏_20200208_210459](https://user-images.githubusercontent.com/55375920/74085753-6019de00-4ab7-11ea-958a-b5ab6d2f0205.jpg)其实这个问题之前版本就有了，只不过那时header.md显示一次再刷新就不会显示了，所以可以正常浏览

**Comment by zhaojun1998** [comment]
已更新版本

**Comment by smloli** [comment]
已更新版本，但是还是会卡住，我的网站www.iles.fun
