### ISSUE TITLE
更宽的 README 显示区域

### ISSUE THREAD

**Issue by cxplay** [zfile-dev/zfile#276]
现有的  README 展示区域过于狭小, 对于内容较多的说明展示非常不便: <https://doc.bugimg.com/2/main/Android/Redmi%20Note%207%20Pro/DotOS>

![image](https://user-images.githubusercontent.com/62034099/133941889-84c69735-3b66-4019-83f2-c3e6f8702545.png)

建议部分参考 Cloudreve 的 README 做法: <https://filel.ink/s/OpHV?path=%2FAndroid%2FRedmi%20Note%207%20Pro%2FDotOS>

现有的卡片 README 页面很棒建议保留, 对于显示区域可紧贴文件列表最后一个文件显示, 然后就能有比现在区域更长的显示区域.

但是对于文件列表超过屏幕显示区域的可能要限定一个最长显示长度.

**Comment by zhaojun1998** [comment]
@cxplay 

非常抱歉这么久才回复，最新版本已经修改为宽度支持全屏和中间显示
