### ISSUE TITLE
feat:  添加下载整个文件夹的按钮

### ISSUE THREAD

**Issue by huochai67** [zfile-dev/zfile#278]
你好！感谢你愿意考虑希望 ZFile 增加某个新功能。请花一点点时间尽量详细地回答以下基础问题。
  谢谢！

## 概述
  添加下载整个文件夹的按钮

## 动机
  需要下载整个文件夹的时候需要进入文件夹一个个点下载，非常的麻烦

## 详细解释
  对了，后台可以加个选项，固定下载文件时content type为application/octet-stream，现在下载音乐文件的时候会被浏览器理解为要在线播放

**Comment by zhaojun1998** [comment]
本地存储可以这样控制，但第三方存储的响应头无法控制。

且打包下载功能不会支持，大多第三方存储都不支持此功能，本地存储的话，对服务器资源占用会很高，作为公开网盘，此功能风险较高。
