### ISSUE TITLE
您好，是否有办法去除路径中的/1/main

### ISSUE THREAD

**Issue by HCARX** [zfile-dev/zfile#279]
挂载一个盘的时候是否可以不显示/1/
或者是否可以通过伪静态之类的操作去掉/1/main呢

**Comment by zhaojun1998** [comment]
不清楚伪静态是否可隐藏 /1/main，你可自行尝试，或者自己修改前端 vue 的路由源码。

**Comment by zhaojun1998** [comment]
@HCARX H

非常抱歉这么久才恢复，最新版本已经解决此问题。去掉了 main，其中前面的 1 也支持自定义
