### ISSUE TITLE
安装总是失败

### ISSUE THREAD

**Issue by xiaocainiao2020** [zfile-dev/zfile#281]
看文档写着不再支持安装到二级目录了，但是下面路径说明又感觉是装在了二级目录，我按着教程，要不就是打不开主页，要不就是点击文件管理打不开，要不就是文件显示不出来，现在已经完全蒙了，到底是应该怎么样安装呢？

**Comment by zhaojun1998** [comment]
错误信息是什么，安装后现象是什么。

**Comment by zhaojun1998** [comment]
长时间无回复，先关闭问题，有反馈再打开
