### ISSUE TITLE
无法接入七牛云储存

### ISSUE THREAD

**Issue by bighamx** [zfile-dev/zfile#283]
## 我的环境
CentOS 7

## 错误日志

错误日志中无任何ERROR信息 仅有DEBUG INFO

## 期望行为

填写正确的七牛云 AK SK等配置 能正常使用

## 当前行为

填写正确的AK SK等配置 但是提交时报错  
初始化异常, 错误信息为: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: dn4AAAASMyj0BqcW; S3 Extended Request ID: null)

**Comment by zhaojun1998** [comment]
@bighamx  添加存储策略时，使用的是七牛，还是 S3 协议。

经测试使用七牛可以正常添加成功：

![image](https://user-images.githubusercontent.com/35387985/134761859-d3dfcf16-24e3-481a-9308-034624249692.png)

**Comment by zhaojun1998** [comment]
长时间无回复，先关闭问题，有反馈再打开

**Comment by bighamx** [comment]
> 长时间无回复，先关闭问题，有反馈再打开

![image](https://user-images.githubusercontent.com/10262931/135388886-dbb580b2-07b9-437f-821f-5f8236780eae.png)

**Comment by bighamx** [comment]
确实选择的是七牛云， ak sk 加速域名也确认无误， 但是报错S3相关信息

**Comment by zhaojun1998** [comment]
截图你的配置项，还有七牛云里的存储器信息，关键信息打码

**Comment by bighamx** [comment]
![image](https://user-images.githubusercontent.com/10262931/135421146-8cd9774a-11bc-4302-99ec-912e7d25dde7.png)
![image](https://user-images.githubusercontent.com/10262931/135421224-55b7c116-b68b-4cc3-ba05-3c503b9d07aa.png)

**Comment by bighamx** [comment]
![image](https://user-images.githubusercontent.com/10262931/135421509-793dd4ad-da33-497c-93c5-bd06efc933cd.png)

**Comment by zhaojun1998** [comment]
@bighamx 新创建密钥对或使用其他存储空间，绑定试试，还有检查下密钥左右两端是否复制了空格

**Comment by DingChang90** [comment]
初始化异常, 错误信息为: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: KocAAABaZId84sgW; S3 Extended Request ID: null)

七牛云，报相同错误

**Comment by zhaojun1998** [comment]
@DingChang90 

麻烦截图你七牛的信息和zfile中填写的信息，ak 和 sk 记得打码。还有版本是最新的 3.2 版本么。

zfile 文档中有相关说明，可以先看看是否和文档中配置一致 https://docs.zfile.vip/#/example?id=%e4%b8%83%e7%89%9b%e4%ba%91

**Comment by DingChang90** [comment]
> @DingChang90
> 
> 麻烦截图你七牛的信息和zfile中填写的信息，ak 和 sk 记得打码。还有版本是最新的 3.2 版本么。
> 
> zfile 文档中有相关说明，可以先看看是否和文档中配置一致 https://docs.zfile.vip/#/example?id=%e4%b8%83%e7%89%9b%e4%ba%91

![密钥](https://user-images.githubusercontent.com/71495804/148771259-cf3160a1-07c3-4414-b784-35e7d8e87af2.PNG)
![配置](https://user-images.githubusercontent.com/71495804/148771274-044fe7c3-e24b-420e-bce6-98ef9b92be90.PNG)
![域名解析  空间](https://user-images.githubusercontent.com/71495804/148771280-8aa896ba-c6ce-4c13-a787-48e272726e40.PNG)

**Comment by zhaojun1998** [comment]
@DingChang90 

刚我测试了下，没问题的，你这存储器是不是很久之前创建的，试试新创建的呢。

然后检查下所有字段左右是否有空格。


![image](https://user-images.githubusercontent.com/35387985/148772741-bdfb700f-61bb-4d8d-855f-3ce7e32f1af9.png)

![image](https://user-images.githubusercontent.com/35387985/148772828-01d42f66-a819-4013-bdf1-b12327cb6f7f.png)

**Comment by DingChang90** [comment]
> @DingChang90
> 
> 刚我测试了下，没问题的，你这存储器是不是很久之前创建的，试试新创建的呢。
> 
> 然后检查下所有字段左右是否有空格。
> 
> ![image](https://user-images.githubusercontent.com/35387985/148772741-bdfb700f-61bb-4d8d-855f-3ce7e32f1af9.png)
> 
> ![image](https://user-images.githubusercontent.com/35387985/148772828-01d42f66-a819-4013-bdf1-b12327cb6f7f.png)

谢谢，新创建的储存器确实没有问题，可以挂载了。

**Comment by zhaojun1998** [comment]
@DingChang90 

你可以点这里看看，是否可 zfile 中的一致，可能是七牛老的默认没有开启 S3 域名或者 S3 域名不一样导致的。

如果不一样，在 ZFILE 区域中，直接输入对应的值回车即可。

![image](https://user-images.githubusercontent.com/35387985/148865545-19e819b2-efa8-4190-9207-3d1af40169bb.png)


![image](https://user-images.githubusercontent.com/35387985/148865566-c5e39389-85e4-45c3-8ca3-77267409bd3c.png)
