### ISSUE TITLE
feat: 期待增加文件夹大小的查看功能

### ISSUE THREAD

**Issue by poisonbian** [zfile-dev/zfile#285]
## 概述

  期待增加文件夹大小的查看功能

## 动机

  在进行远程文件管理的时候，可能会经常需要根据文件夹的大小去查找、定位、处理和一些文件（例如进行ftp清理），但是通常只有到了对应的文件夹才能查看单个文件大小，如果可以在任一个文件夹视图中，就能看到所有的子文件夹的大小，对文件清理的帮助比较大。

**Comment by zhaojun1998** [comment]
这个要根据存储源本身是否支持来定，一般来说本地存储和 FTP  协议一般都不支持返回文件夹大小。部分对象存储或者网盘类的才可能支持。

**Comment by poisonbian** [comment]
是的，正因如此，才希望有其他的方式。之前试过的方案是自己调用ftp的协议或命令，递归进入每个文件夹去获得文件大小之后，本地运算获得文件夹的大小

**Comment by zhaojun1998** [comment]
没有其他方式，实时统计太消耗性能了
