### ISSUE TITLE
feat:强烈希望作者大大能推出文件夹下载以及分享功能，或者后台设置可选择是否开启

### ISSUE THREAD

**Issue by AllenHong007** [zfile-dev/zfile#291]

**Comment by zhaojun1998** [comment]
关于下载整个文件夹功能，已经在此 issue 中回复：#278 

文件夹分享功能后续可能会支持。

**Comment by AllenHong007** [comment]
下载文件夹可以只针对于本地存储的，并且可以让用户自己选择是否开放文件夹下载就好啦，第三方存储的不支持就可以不用考虑.
因为目前看来，这个下载文件夹的功能，对于本地存储的用户来说，需求量还是蛮大的，可以点击下载的时候打成zip包.

**Comment by zhaojun1998** [comment]
如果是公开网盘，支持压缩文件夹并返回的话，考虑到压缩时间和占用性能问题。可能打包下载要等待很久才能打包完成返回给用户下载。
且如果有人批量恶意打包，会导致服务器 CPU，内存，磁盘，网络都满载。

**Comment by AllenHong007** [comment]
我是希望在本地存储能加上这个目录打包下载已经分享，公开网盘的话如果怕被跑满的话，可以手动控制开启或关闭就行.

**Comment by zhaojun1998** [comment]
后续版本本地存储会考虑增加打包下载功能

**Comment by AllenHong007** [comment]
好的好的，谢谢大大！期待！
