### ISSUE TITLE
feat: 大佬你好，zfile十分强大，不知道是否有开放接口的计划呢，例如上传、生成直链等接口

### ISSUE THREAD

**Issue by wraptor** [zfile-dev/zfile#293]
## 概述
不知道是否有开放接口的计划呢，例如上传、生成直链等接口

## 动机

这样的话可以把这个对象储存来使用，让我自己的系统可以不必对接阿里oss或七牛云，只对接zfile，而zfile能同时接入阿里oss和七牛甚至onedrive，做得更加灵活且强大

**Comment by zhaojun1998** [comment]
目前没有上传功能，后续版本会完善功能和文档

**Comment by Ero-Cat** [comment]
> 目前没有上传功能，后续版本会完善功能和文档

期待 也非常希望有OneDrive的上传和生成链接的接口，方便对其他服务二次开发。

**Comment by zhaojun1998** [comment]
有的，正在开发4.0版本。发布后会有完善的文档和 api，大概一两个月之后才能开发完成并发布。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月4日(周五) 凌晨0:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] feat: 大佬你好，zfile十分强大，不知道是否有开放接口的计划呢，例如上传、生成直链等接口 (Issue #293)




  
目前没有上传功能，后续版本会完善功能和文档
  
期待 也非常希望有OneDrive的上传和生成链接的接口，方便对其他服务二次开发。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Nicolasking007** [comment]
没下文了吗

**Comment by zhaojun1998** [comment]
@Nicolasking007 

访问你 zfile 地址的   http://ip:port/doc.html   即可访问接口文档。但是不保证发布新版本后对旧版本的兼容。

**Comment by Nicolasking007** [comment]
> @Nicolasking007
> 
> 访问你 zfile 地址的 http://ip:port/doc.html 即可访问接口文档。但是不保证发布新版本后对旧版本的兼容。

谢谢
