### ISSUE TITLE
如何使用SSL？

### ISSUE THREAD

**Issue by LxnChan** [zfile-dev/zfile#298]
在直接访问（ip:port）的前提下如何使用ssl？

**Comment by zhaojun1998** [comment]
不推荐在程序上直接绑定 https，可以使用 nginx 反向代理添加 SSL

**Comment by LxnChan** [comment]
好的谢谢了，我先研究一下

> 不推荐在程序上直接绑定 https，可以使用 nginx 反向代理添加 SSL

**Comment by zhaojun1998** [comment]
长时间未回复，暂时关闭 issue，有问题请在打开。
