### ISSUE TITLE
请问如何绑定域名

### ISSUE THREAD

**Issue by Buysoso** [zfile-dev/zfile#3]
我想绑定http域名，默认配置在管理地址填了绑定域名，我解析到IP，页面要空白页面。
请问如何绑定域名？

**Comment by zhaojun1998** [comment]
程序并没有限制 IP 访问还是域名访问，你现在用 IP 可以访问么

**Comment by Buysoso** [comment]
可能DNS解析问题，现在要正常了。
请问如何让 访问  a.com  会自动跳转到 a.com/#/main  ？
或者打开a。com  就可以显示网盘内容。

**Comment by zhaojun1998** [comment]
现在就是这样的，直接访问域名，就可以了，如果你那有问题，请清理缓存后再试

**Comment by Buysoso** [comment]
清除了缓存，直接访问打不开。
 提示： 该网页无法正常运行。

**Comment by zhaojun1998** [comment]
你是反向代理的？

**Comment by Buysoso** [comment]
centos安装好项目，我在后台设置域名绑定。
直接A解析，没有反向代理。
需要填:8080/#/main
？是不是需要配置文件修改端口为80？

**Comment by zhaojun1998** [comment]
是的，或者域名反代 8080 端口

**Comment by Buysoso** [comment]
好的。谢谢，我尝试一下。

**Comment by zhaojun1998** [comment]
由于暂时没有回复，先关闭了，如果有问题，请再重新打开问题
