### ISSUE TITLE
能否增加在线更新功能...

### ISSUE THREAD

**Issue by noisky** [zfile-dev/zfile#30]
好吧我承认我实在是太懒了，一行一行的敲代码更新实在是太麻烦了
能否在打开后台的时候检查更新，有更新通知用户并且可以点击一键更新...
或者增加一键更新的脚本 `update.sh` 也行...哈哈
毕竟懒才是程序员的第一生产力嘛~

**Comment by zhaojun1998** [comment]
脚本会考虑支持，至于网页在线点击升级，因语言限制，不可能实现。

**Comment by noisky** [comment]
脚本也行，不过要注意用户自定义的配置文件，配合cron使用也是可以满足需求的
我记得原生的 `h5ai` 左边还有一个目录树，在打开多级目录的时候，进行不同目录的跳转挺方便的，是否考虑加上呢，可作为可选功能，在后台根据需要开启即可

**Comment by zhaojun1998** [comment]
计划在，不会再支持。保留现有更新模式
