### ISSUE TITLE
关于上传功能支持的讨论

### ISSUE THREAD

**Issue by zhaojun1998** [zfile-dev/zfile#303]
鉴于很多人提问，在此统一讨论。

到目前 3.2 版本为止，是不支持上传功能的，原因如下：

1. 定位问题
ZFile 设计初衷就是简洁的**文件列目录展示**程序，而不是像 [Cloudreve](https://github.com/cloudreve/Cloudreve) 之类的云盘，所以未考虑上传功能。

    *私以为，如果你有一个需求，应该去找适合的产品，而不是让一个产品成为百宝箱，没有银弹，没有一个产品能满足所有需要。*

2. 时间成本问题
因目前为止支持数达 14 个存储源类型，且以后会更多的情况，对所有存储源开发上传功能，是一项巨大的工作量，我只能在下班时间，工作日，节假日进行开发，故支持此功能需要付出的时间成本太高。

不过还是迫于太多人提此功能，所以后续会逐步支持上传功能，初期可能会有较多的问题，望大家理解。

**Comment by design-1996** [comment]
可以，大佬牛逼，有空的话可以搞搞。他们可能是想要全功能型网盘。你可以把现有的aria2+rclone+网盘 这种离线现在功能一起给他们整合进去。这样离线下载有了，上传功能也有了哈。

**Comment by XingHehy** [comment]
先把本地上传功能弄上就行，一个一个来

**Comment by sswangifly** [comment]
支持开发上传功能，另外，客户端是否考虑支持或者支持nextcloud api？

**Comment by zhaojun1998** [comment]
不会开发客户端。也不会对接 nextcloud。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月21日(周日) 上午8:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 关于上传功能支持的讨论 (Issue #303)




 
支持开发上传功能，另外，客户端是否考虑支持或者支持nextcloud api？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghost** [comment]
@zhaojun1998 其实本地的就好了。上传、下载、搜索，对于家用足以。至于云上的存储类型个人觉得还不如网盘会员开一个。

**Comment by yaoxinghuo** [comment]
希望有个本地上传+1

**Comment by ZhangShanFeng1114** [comment]
本地上传+1

**Comment by wodepig** [comment]
本地上传+1

**Comment by KevinYouu** [comment]
本地上传+1

**Comment by Castleeee** [comment]
本地上传+1，至少能上传个图，不然当图床的话每次扔到onedrive都要手动去admin刷新一次，打开三个tab。
可以弄得简单点，密码让用户写死在配置文件里，上传要输入密码。

**Comment by miaoweiwei** [comment]
本地上传+1 ，感觉上传的功能还是比较有必要的，其实我还期望有一个离线下载的功能:smile:，这样就可以作为一个家庭版的nas使用了

**Comment by Castleeee** [comment]
> 本地上传+1 ，感觉上传的功能还是比较有必要的，其实我还期望有一个离线下载的功能😄，这样就可以作为一个家庭版的nas使用了
那还不如直接用cloudreve

**Comment by miaoweiwei** [comment]
你好，你的邮件我已收到。苗卫伟

**Comment by gongjing666** [comment]
不求其他上传，OneDrive世纪互联没有上传功能是真难用，每次还要到单独的网站上传

**Comment by ghost** [comment]
大家散了吧  显然作者没时间

**Comment by zhaojun1998** [comment]
@saodis @gongjing666 

六月底会发布 4.0 版本，上传，下载，删除，重命名等文件操作都会有的。

**Comment by ChoviWu** [comment]
> 鉴于很多人提问，在此统一讨论。
> 
> 到目前 3.2 版本为止，是不支持上传功能的，原因如下：
> 
> 1. 定位问题
>    ZFile 设计初衷就是简洁的**文件列目录展示**程序，而不是像 [Cloudreve](https://github.com/cloudreve/Cloudreve) 之类的云盘，所以未考虑上传功能。
>    _私以为，如果你有一个需求，应该去找适合的产品，而不是让一个产品成为百宝箱，没有银弹，没有一个产品能满足所有需要。_
> 2. 时间成本问题
>    因目前为止支持数达 14 个存储源类型，且以后会更多的情况，对所有存储源开发上传功能，是一项巨大的工作量，我只能在下班时间，工作日，节假日进行开发，故支持此功能需要付出的时间成本太高。
> 
> 不过还是迫于太多人提此功能，所以后续会逐步支持上传功能，初期可能会有较多的问题，望大家理解。

关于这个功能，后续有没有考虑让大家一起参与开发？ 你分配feature，大家领任务

**Comment by ghost** [comment]
> @saodis @gongjing666
> 
> 六月底会发布 4.0 版本，上传，下载，删除，重命名等文件操作都会有的。

七月了😂一直用 h5ai，没敢换过来...

**Comment by zhaojun1998** [comment]
@saodis 

已经在公测了，可参考进行功能预览 https://preview.zfile.vip/zfile-test

大约一周内测试完毕后，发布到 github

**Comment by ghost** [comment]
@zhaojun1998 咋上传嘞？能访问的人都可以上传么，不应该是管理能上传么？
![image](https://user-images.githubusercontent.com/51149477/177262041-33d645b9-fcbd-4a67-89e8-1d7be5a729ed.png)

**Comment by zhaojun1998** [comment]
@saodis 

后台可关闭操作功能

**Comment by zhaojun1998** [comment]
4.0 版本已发布，支持了上传功能
