### ISSUE TITLE
分享链接编码问题

### ISSUE THREAD

**Issue by RogerHuOut** [zfile-dev/zfile#304]
中文的文件名或文件夹，长链中是否可以未中文，不展示为编码后的字符，否则分享链接不太好看

**Comment by zhaojun1998** [comment]
不使用编码的话，很多程序和网站会不识别，好看的话，可以使用短链。

![image](https://user-images.githubusercontent.com/35387985/142098713-0048a885-219d-4512-801d-980dd6df7d08.png)

**Comment by zhaojun1998** [comment]
暂时关闭，有问题可再反馈
