### ISSUE TITLE
feat: 作者有考虑添加账号权限功能吗

### ISSUE THREAD

**Issue by ccquan** [zfile-dev/zfile#305]
## 动机
虽然有文件夹密码，但如果是多个人用的话好像不太适合这个

**Comment by zhaojun1998** [comment]
不考虑，本项目定位不适合多人同时使用，你的使用场景适合 [cloudreve](https://cloudreve.org/)

**Comment by zhaojun1998** [comment]
暂时关闭，有问题可再反馈
