### ISSUE TITLE
FTP存储策略

### ISSUE THREAD

**Issue by HoratioShaw** [zfile-dev/zfile#307]
你好，之前反馈了FTP无法正常显示到现在都还没有解决，想向您再次反馈一下
Zfile搭建环境：Debian 10，版本：docker-3.2（使用镜像：stilleshan/zfile,zhaojun1998/zfile均无法显示）
FTP搭建环境：Debian 10，FTP程序：使用宝塔部署 Pure-Ftpd 1.0.49
我在我的相同系统环境的5个服务区测试，均无法正常显示FTP文件，但我在本地连接FTP是正常的，查看Zfile诊断日志也并未发现有关于FTP的报错

**Comment by zhaojun1998** [comment]
@HoratioShaw 
已解决，并发布 3.2.2 版本
