### ISSUE TITLE
feat: 关于新增footer后台可配置的功能

### ISSUE THREAD

**Issue by DeaneChen** [zfile-dev/zfile#309]
## 概述

在管理员后台新增像“公告内容”那样支持html文本的footer配置栏。

## 动机

因为习惯，会喜欢在页面的最下面增加footer，包含备案号、All Rights Reserved、Powered By等信息，并加入超链、加粗、加灰等Style。我尝试在主页中新增footer但发现并没有显示，不知道是不是被js代码产生的页面内容覆盖。

万分感谢

**Comment by zhaojun1998** [comment]
@DeaneChen 

非常抱歉这么久才回复， ZFile 4.x 已经支持底部文本设置
