### ISSUE TITLE
已更新，但是header还是会卡住，下拉不了

### ISSUE THREAD

**Issue by smloli** [zfile-dev/zfile#31]

**Comment by zhaojun1998** [comment]
@smloli  可否给出预览地址

**Comment by smloli** [comment]
www.iles.fun

**Comment by smloli** [comment]
手机端显示不正常

**Comment by zhaojun1998** [comment]
@smloli  已更新版本。优化了这个功能，把 header.md 去掉了，改为了 readme.md，显示在底部，上方增加了网站公告功能。

**Comment by smloli** [comment]
嗯嗯，已经更新了，现在就是加密文件夹输入密码后，搜索不到文件，后台已经开启搜索包含加密文件，没加密的文件夹倒是搜得到

**Comment by smloli** [comment]
@zhaojun1998  我关闭那个搜索包含加密文件，就可以搜索到加密文件夹的内容了，但是此时加密文件夹还没有输入密码，请问能不能实现没输入密码就搜索不了加密文件夹的内容，输入了才可以搜索的内容
