### ISSUE TITLE
m3u8文件预览失败，生成的短链和直链都无法访问

### ISSUE THREAD

**Issue by tianfeng98** [zfile-dev/zfile#312]
## 我的环境

- ZFile Admin v3.2.0
- win10
- docker部署，局域网环境

## 错误日志

无

## 期望行为

正常预览或链接访问

## 当前行为

链接：http://tangtianfeng.cn:8008/directlink/1/videos/%E5%8E%A8%E8%89%BA/%E5%85%BB%E9%94%85/output.m3u8
![image](https://user-images.githubusercontent.com/37977609/145721674-cf60f41b-ed4e-4f5b-a586-48cf60df1a84.png)

**Comment by zhaojun1998** [comment]
1. 是否所有文件都无法下载
2. 使用的存储类型是什么
3. 局域网环境，那么 zfile 站点是否写的是 zfile 内网地址，是否站点设置，还有你访问的都是内网。
4. 如果是局域网通过家庭带宽动态公网 IP 访问的话，可能存在本地回环的问题，即无法在局域网内，使用公网 IP 访问公网 IP 对应的局域网内访问自身。
