### ISSUE TITLE
关于最近dlog4j2重大BUG

### ISSUE THREAD

**Issue by LFMcxixif** [zfile-dev/zfile#313]
请问在软件中这个BUG有没有修复呢？

**Comment by zhaojun1998** [comment]
之前在交流群里发过通告，github 因无法给用户发通知，故未发相关提示。

据悉，最新公开的 log4j 高危漏洞 https://www.safedog.cn/news.html?id=2052
经排查，zfile 3.2 及之前版本所使用版本包含此内容，请各位修改 bin/start.sh 中第 15 行增加此部分 " -Dlog4j2.formatMsgNoLookups=true “，如图所示：

https://cdn.jun6.net/uPic/2021/12/10/9EmS0J.jpg

后续发布版本将会更新为修复后的版本，谢谢。

**Comment by LFMcxixif** [comment]
> 之前在交流群里发过通告，github 因无法给用户发通知，故未发相关提示。
> 
> 据悉，最新公开的 log4j 高危漏洞 https://www.safedog.cn/news.html?id=2052 经排查，zfile 3.2 及之前版本所使用版本包含此内容，请各位修改 bin/start.sh 中第 15 行增加此部分 " -Dlog4j2.formatMsgNoLookups=true “，如图所示：
> 
> https://cdn.jun6.net/uPic/2021/12/10/9EmS0J.jpg
> 
> 后续发布版本将会更新为修复后的版本，谢谢。

我是windows用户，下面是我的启动参数，如何修改？
`java -Dfile.encoding=utf-8 -jar -Dserver.port=8444 .\zfile-3.2.jar`

**Comment by zhaojun1998** [comment]
```bash
java -Dfile.encoding=utf-8 -Dlog4j2.formatMsgNoLookups=true -jar -Dserver.port=8444 .\zfile-3.2.jar
```

**Comment by LFMcxixif** [comment]
> ```shell
> java -Dfile.encoding=utf-8 -Dlog4j2.formatMsgNoLookups=true -jar -Dserver.port=8444 .\zfile-3.2.jar
> ```

非常感谢
