### ISSUE TITLE
群晖Docker部署zfile，无法修改配置文件

### ISSUE THREAD

**Issue by Onloker** [zfile-dev/zfile#314]

**Comment by Onloker** [comment]
将/root/.zfile挂载到了群晖的文件夹下，但是还是没有application.yml，没办法修改相关配置

**Comment by Onloker** [comment]
在终端新增 /bin/sh打开终端，然后用vi编辑application.yml

**Comment by i-iooi-i** [comment]
> 在终端新增 /bin/sh打开终端，然后用vi编辑application.yml

同在群辉部署，但是在Docker里面映射不出来任何文件夹，哭了。

**Comment by zhaojun1998** [comment]
可以通过群辉的命令行进入容器内执行命令修改。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月3日(周四) 晚上11:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 群晖Docker部署zfile，无法修改配置文件 (Issue #314)




  
在终端新增 /bin/sh打开终端，然后用vi编辑application.yml
  
同在群辉部署，但是在Docker里面映射不出来任何文件夹，哭了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Onloker** [comment]
> > 在终端新增 /bin/sh打开终端，然后用vi编辑application.yml
> 
> 同在群辉部署，但是在Docker里面映射不出来任何文件夹，哭了。

只需要映射你存储文件夹就好了，其他的不需要映射

**Comment by i-iooi-i** [comment]
谢谢大佬，我在群晖里把文件存储目录 /file 映射出来了，就暂时不改配置了，反正可以用，谢啦。🌞

**Comment by i-iooi-i** [comment]
嗯嗯 起初我映射的是/zfile ，结果是错的。晚上在B站看了个教程，映射 /file 目录就出来了，感谢。

**Comment by moeik** [comment]
Docker部署文件映射目录是哪个? 本地存储 @zhaojun1998

**Comment by zhaojun1998** [comment]
@moeik 
你需要先把你准备用于 zfile 的目录，创建容器时，就映射进 docker 容器内。如果以 docker 容器运行，zfile 就只能读取容器内的文件。

如，你想在 docker 容器中使用宿主机 /root/zfile-files 目录，需要进行如下配置(主要是第三行)：

```bash
docker run -d --name=zfile --restart=always \
    -p 8080:8080 \
    -v /root/zfile-files:/root/zfile-files \
    -v /root/zfile/db:/root/.zfile/db \
    -v /root/zfile/logs:/root/.zfile/logs \
    zhaojun1998/zfile
```
