### ISSUE TITLE
通过在/etc/hosts设置域名来访问内网服务无法显示

### ISSUE THREAD

**Issue by UntaggedRui** [zfile-dev/zfile#316]
## 我的环境

使用docker运行，命令为` docker run -d --name=zfile --restart=always  -p 8060:8080 -v /home/rui/fileshare/zfile/db:/root/.zfile/db  -v /home/rui/fileshare/zfile/logs:/root/.zfile/logs  -v /home/rui/targz:/data           zhaojun1998/zfile`
已经通过nginx设置域名反向代理到8060端口，通过ip+端口访问正常。
因为是内网ip，想通过域名访问，已经在/etc/hosts里面设置域名到ip的映射。
## 错误日志

通过ip+端口访问正常。通过域名访问时无法加载首页，查看控制台发现如下错误。
因为我的域名是自己设置的所以公网dns无法知道。
![image](https://user-images.githubusercontent.com/28807947/147550784-8d12a072-dda8-4bba-b4eb-a0047ccbd040.png)

## 期望行为
这个请求是干什么的？可以去掉吗？我希望能通过自己在/etc/hosts设置的域名访问。

**Comment by zhaojun1998** [comment]
@UntaggedRui 
我程序中没有发这个请求，请检测是否是浏览器插件发送的，比如使用 Chrome 无痕模式，禁用所有插件后，再查看所有网络请求。

如果要在内网通过域名访问的话，需要在客户端，服务端均设置 hosts 文件，不能只设置一个。
且对于非 80 端口的程序，你即使 hosts 配置了域名，域名访问也要加端口的，如 192.168.1.131:8080 ，hosts 映射 192.168.1.131 example.com，访问时要使用 example.com:8080

**Comment by UntaggedRui** [comment]
> 

感谢回复，问题已经解决。
在确认zifle没有问题后，我又检查了一下，是我自己的问题，我的hosts配置有问题。
