### ISSUE TITLE
3.1.0版本存在目录穿越漏洞

### ISSUE THREAD

**Issue by sievr** [zfile-dev/zfile#318]
在3.1.0版本中，可以通过在/main后面衔接../进行目录穿越，导致可以看见整个服务器所有文件，但不能查看文件内容，仅能查看目录

**Comment by zhaojun1998** [comment]
@sievr 
刚测试了下，在 3.2 版本 history 模式中，此问题不存在，后续版本在 hash 模式下，也会修复此问题
