### ISSUE TITLE
能否新增页脚Readme.md功能？

### ISSUE THREAD

**Issue by wjy20030407** [zfile-dev/zfile#32]
之前的版本好像有过footer.md功能，但是好像无效？后来不知道为什么移除了，能否添加回来呢？

**Comment by zhaojun1998** [comment]
@wjy20030407  已更新版本。优化了这个功能，把 header.md 去掉了，改为了 readme.md，显示在底部，上方增加了网站公告功能。

**Comment by wjy20030407** [comment]
我觉得还可以改善一下，readme.md常驻底部可能会影响用户的内容浏览体验
![](https://i.loli.net/2020/02/15/meu7GLgMYrVRDdC.jpg)

**Comment by D3CODING** [comment]
我觉得常驻倒是没关系，不过如果目录下没有readme.md，能不能自动隐藏而不是显示一个白框框。

**Comment by zhaojun1998** [comment]
@wjy20030407  @lichenzero 
下个版本优化下，即使开启了文档区，但此目录没有文档，就取消常驻。

**Comment by Dragon1573** [comment]
@zhaojun1998 
&emsp;&emsp;我的网页因为通过了备案而必须在页面底部悬挂网站备案信息，这个是只需要在首页挂备案信息还是所有页面都要挂？如果所有页面都要挂，那么每一个文件夹都要放这么一个 `readme.md` ，效率会不会太低了？

&emsp;&emsp;我尝试去修改 `index.html` ，但界面布局还是不尽人意。所以能否考虑在文档区之外再增加一个全局页脚？我们可以在这里写站长信息、备案信息什么的。
