### ISSUE TITLE
软链接问题

### ISSUE THREAD

**Issue by xiaoyaohanyue** [zfile-dev/zfile#320]
## 当前行为

我用软链接关联了一个文件夹，然后源文件夹可以正常 访问，软链接的目标文件夹无法访问
![image](https://user-images.githubusercontent.com/44468010/149858271-de275a43-9f93-4f5b-a267-ab1903436258.png)
然后我用nginx搭建了文件服务器可以正常打开
![image](https://user-images.githubusercontent.com/44468010/149858354-b286c210-67a9-4586-ab49-4a08add5f8a2.png)

**Comment by tianfeng98** [comment]
同问，搭建镜像服务器的时候，软链接超省空间。希望能解决这个bug

**Comment by zhaojun1998** [comment]
@LinktoDream 

我会尝试解决此问题的，周末会对问题进行反馈。感谢。

**Comment by tianfeng98** [comment]
@zhaojun1998 感谢作者！软连接不好搞的话，我也可以用硬链接，也能达到效果。

**Comment by zhaojun1998** [comment]
@LinktoDream 
@xiaoyaohanyue 

经测试，软连接文件和文件夹都没有问题，可以正常展示并可下载。测试环境为 Centos 7，部署 ZFile 方式为直接在宿主机部署，非 Docker 内运行。

可以提供下你们的软连接命令，及运行环境，还有操作系统吗。

**Comment by tianfeng98** [comment]
@zhaojun1998 我这里是Centos7 docker内运行，ln -s命令，软连接文件夹。
<img width="490" alt="截屏2022-05-30 19 51 03" src="https://user-images.githubusercontent.com/37977609/170986650-56708b64-ff50-423a-b976-79d62d86370e.png">
这个v16.0.1就是软连接

**Comment by xiaoyaohanyue** [comment]
@zhaojun1998 我的和 @LinktoDream 的操作一样的

**Comment by zhaojun1998** [comment]
就是 exec 进 docker 容器内，创建软连接，zfile 读取有问题， 硬链接，没问题，是吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月31日(周二) 下午5:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 软链接问题 (Issue #320)




 
@zhaojun1998 我的和 @LinktoDream 的操作一样的

**Comment by xiaoyaohanyue** [comment]
但是这样有个问题，如果我需要软链接的文件不在容器映射的目录内就无法通过exec这种方式来添加软链接了，所以还是希望可以直接在系统内直接使用ln -s来软链接而不是在容器内这种方式

**Comment by jinglekang** [comment]
@zhaojun1998 我也遇到了此问题，我是在宿主机创建的软连接，然后挂载到docker内，在系统内就变成文件无法访问了。

> ln -s /xxx/folder_a /xxx/folder_b

![image](https://user-images.githubusercontent.com/17934343/192799242-29a5dfcf-97c5-4dad-8587-eaab1fa1e636.png)

**Comment by zhaojun1998** [comment]
@xiaoyaohanyue @tianfeng98 


这应该并不是 ZFile 的问题，而是 docker 容器映射的问题。

如有实际文件目录 `/data/upload`，软连接 `/www/wwwroot/zfile/upload` 指向 `/data/upload`。

在 docker 配置映射时，如果只映射 `/www/wwwroot/zfile/upload` 是不行的，因为软连接指向的是宿主机的 `/data/upload` 路径，可你并没有将其映射到 docker 容器内，所以 docker 认为软连接是无效的。

应该把 `/www/wwwroot/zfile/upload` 和 `/data/upload` 都映射到容器内。也就是说要保证软连接本身和软连接后的路径都需要映射到 docker 容器中。

**Comment by zhaojun1998** [comment]
@xiaoyaohanyue 
@tianfeng98 

参考：https://stackoverflow.com/questions/38485607/mount-host-directory-with-a-symbolic-link-inside-in-docker-container

**Comment by ECS-tasy** [comment]
> @LinktoDream @xiaoyaohanyue
> 
> 经测试，软连接文件和文件夹都没有问题，可以正常展示并可下载。测试环境为 Centos 7，部署 ZFile 方式为直接在宿主机部署，非 Docker 内运行。
> 
> 可以提供下你们的软连接命令，及运行环境，还有操作系统吗。

大佬你好，我在考虑搭建NAS，但是NAS好像没有相同文件秒传的功能，只有用插件去重。Zfile能不能实现秒传？这个功能感觉还蛮有市场的，我搜的时候看到蛮多在问的，比如照片去重，还有像这里有人搭建镜像服务器可以节省空间

**Comment by zhaojun1998** [comment]
@ECS-tasy 
做不了，建议看看其他有秒传的软件。ZFile 只实时读取文件信息，不会存储文件特征，信息。
