### ISSUE TITLE
关于使用mysql后数据无法写入

### ISSUE THREAD

**Issue by Jakob-Boy** [zfile-dev/zfile#325]
## 当前行为
你好，主要问题为手动修改jar包内application.yml内的数据库配置，使用mysql，已经注释h2并取消注释mysql，具体内容我下面贴出来，因为我不会java所以不懂源码一些问题，只能描述所观察到的麻烦谅解谢谢。使用mysql版本为5.7，数据库初始化全部清空，安装zfile后mysql中多了4张表（所以我认为数据库应该是正常连接上的），访问ip:8080跳转/install，输入信息提示初始化成功，自动刷新后又回到/install页面，循环。查看数据库中依旧是4张表，貌似数据表内没有数据，貌似无法写入数据？或者是我使用方式不对，麻烦作者查看一下谢谢。

`# h2 内存数据库 配置`
    `#driver-class-name: org.h2.Driver`
    `#url: jdbc:h2:${zfile.db.path}`
    `#username: zfile`
    `#password: 123456`

`# MySQL 配置`
      `driver-class-name: com.mysql.jdbc.Driver`
      `url: jdbc:mysql://ip:3306/数据库名称?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false`
      `username: 数据库用户名`
      `password: 数据库密码`

## 我的环境
docker镜像openjdk:slim-buster内运行文档中的jar包

## 期望行为
可以使用mysql进行数据库持久化

**Comment by zhaojun1998** [comment]
目前 MySQL 版本是有 BUG 的，现在正在开发 ZFIle 大版本更新， V4.0，发布后会修复及完善对 MySQL 的支持

**Comment by Jakob-Boy** [comment]
好的谢谢
