### ISSUE TITLE
README 文本体积超过在线预览限制导致整个目录无法打开

### ISSUE THREAD

**Issue by cxplay** [zfile-dev/zfile#328]
README 文本如果体积超过了设定的限制, 在提示无法打开之后会一直处于加载状态, 目录文件无法列出.

![image](https://user-images.githubusercontent.com/62034099/152764822-ec3b711c-6307-4934-a97e-cb13134409b2.png)

> 演示地址: <https://doc.bugimg.com/5/main/Font/超级字体整合包%20XZ%20-%20VCB-Studio>

**Comment by zhaojun1998** [comment]
收到。下版本会优化，即使超出发现也应不影响
文件列表显示。


不过允许预览的文件大小，可在配置文件中调整。或者适当减少其大小。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月7日(周一) 下午5:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] README 文本体积超过在线预览限制导致整个目录无法打开 (Issue #328)




 
README 文本如果体积超过了设定的限制, 在提示无法打开之后会一直处于加载状态, 目录文件无法列出.
 

  
演示地址: https://doc.bugimg.com/5/main/Font/超级字体整合包%20XZ%20-%20VCB-Studio
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhaojun1998** [comment]
@cxplay 

最新版本已经改为读取后台设置的 markdown，而不是读取 readme.md.
