### ISSUE TITLE
无法访问（包括又拍云和世纪联华）

### ISSUE THREAD

**Issue by vlssu** [zfile-dev/zfile#329]
## 我的环境
并没有找到，并且我是用的是docker

## 错误日志
[ZFile 诊断日志 - 2022-02-19 18_00_03.zip](https://github.com/zhaojun1998/zfile/files/8101897/ZFile.-.2022-02-19.18_00_03.zip)

## 期望行为
又拍云正常添加并访问

## 当前行为
无法访问
初始化异常, 错误信息为: v0.api.upyun.com
![image](https://user-images.githubusercontent.com/43847794/154796191-26da96c5-aa87-481f-b59a-fa30dd91a326.png)

**Comment by zhaojun1998** [comment]
这个是虚拟机里 dns 的问题，可创建 docker 容器时指定 dns 地址解决
