### ISSUE TITLE
本地储存的txt文件点会跳转到一个简易的预览页不提示下载

### ISSUE THREAD

**Issue by LemonSpell** [zfile-dev/zfile#331]

**Comment by LemonSpell** [comment]
您好我有个小问题。本地储存的txt文件点下载会跳转到一个简易的预览页，怎么不提示下载框呢？

**Comment by zhaojun1998** [comment]
@q246 
本地存储现在是没全部走的浏览器默认行为，下版本针对本地存储会区分支持下载和预览功能。

但其他存储类型的下载/预览行为控制无法实现。

**Comment by LemonSpell** [comment]
还有个两个小问题就是可以开启守护进程吗？另外可以对页面进行美化吗。怎么美化呢？

**Comment by zhaojun1998** [comment]
@q246 

守护线程自行百度查询吧，或者用 docker 部署，开启自动启动
美化可以使用自定义 css 进行

**Comment by LemonSpell** [comment]
好的 感谢

**Comment by LemonSpell** [comment]
建议添加123云盘



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月6日(周日) 中午11:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 本地储存的txt文件点会跳转到一个简易的预览页不提示下载 (Issue #331)




 
@q246
 
守护线程自行百度查询吧，或者用 docker 部署，开启自动启动
 美化可以使用自定义 css 进行
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhaojun1998** [comment]
123云盘官方未提供 api，无法支持
