### ISSUE TITLE
安全问题

### ISSUE THREAD

**Issue by lyuly** [zfile-dev/zfile#332]
安装zfile后，打开首页，默认会请求首页的文件数据和站点数据，其中得到的数据里有username（也即后台登录名），这会不会导致别人暴力枚举你后台密码，可否将这个username变量不作返回？
![](https://i.bmp.ovh/imgs/2022/03/d18fb800f5f2c202.png)

**Comment by zhaojun1998** [comment]
可以，下版本会取消这个字段返回。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月9日(周三) 晚上6:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 安全问题 (Issue #332)




 
安装zfile后，打开首页，默认会请求首页的文件数据和站点数据，其中得到的数据里有username（也即后台登录名），这会不会导致别人暴力枚举你后台密码，可否将这个username变量不作返回？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lyuly** [comment]
好的👌🏻

**Comment by zhaojun1998** [comment]
@lyuly 

非常抱歉这么久才回复，最新版本已经修复了此问题

**Comment by lyuly** [comment]
灰常感谢
