### ISSUE TITLE
zfile播放mkv视频时快进功能失效

### ISSUE THREAD

**Issue by Hreint** [zfile-dev/zfile#333]
作者您好，

我在使用zfile自带的视频播放器观看mkv格式的视频时会遇到快进功能失效的问题，就是点进度条或者拖动进度条会让视频直接重头开始播放。

zfile版本3.2.1

您可以在此页面里的视频测试一下：https://files.pepper.blue/2/main/ESO/Daily

**Comment by zhaojun1998** [comment]
浏览器对视频解码能力有限，请在播放器中右键，调用本地播放器，如 potplay 播放，这些播放器会调用本地解码，比浏览器支持的视频格式多。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月13日(周日) 凌晨4:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] zfile播放mkv视频时快进功能失效 (Issue #333)




 
作者您好，
 
我在使用zfile自带的视频播放器观看mkv格式的视频时会遇到快进功能失效的问题，就是点进度条或者拖动进度条会让视频直接重头开始播放。
 
zfile版本3.2.1
 
您可以在此页面里的视频测试一下：https://files.pepper.blue/1/main/ESO/Daily
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
