### ISSUE TITLE
希望可以新增个可以填写统计代码的功能

### ISSUE THREAD

**Issue by waitsaber** [zfile-dev/zfile#337]
## 概述
后台管理中添加一个文本框，用于输入第三方的统计代码，统计代码建议放置在 </head> 标签前。

## 动机
添加统计代码后可以看到网站的被访问情况，访问量等。

**Comment by waitsaber** [comment]
放置在 /head 标签前。

**Comment by zhaojun1998** [comment]
现在可以写在自定义 js 中。

**Comment by waitsaber** [comment]
我是使用docker部署的更新到最新的3.2.2后在 自定义js中填写了统计代码好像不太行，我使用的是 51.la 的统计代码，通过F12查看51.la的 js-sdk-pro.min.js 没有被加载出来。

**Comment by zhaojun1998** [comment]
@waitsaber 

可以贴一下脚本么，屏蔽下敏感信息

**Comment by waitsaber** [comment]
> 
统计代码如下：
“<script charset="UTF-8" id="LA_COLLECT" src="//sdk.51.la/js-sdk-pro.min.js"></script>”
“<script>LA.init({id: "JeEtZnulJwHL7xHj",ck: "JeEtZnulJwHL7xHj"})</script>”

**Comment by zhaojun1998** [comment]
改成这段就可以了，因为 ZFILE 这个自定义 js 框，输入的是 JS 脚本，而不是 html 标签， 你发的 <script> 标签是 html 的一部分。

```javascript
function loadScript(src, callback) {
 var script = document.createElement('script'),
  head = document.getElementsByTagName('head')[0];
 script.type = 'text/javascript';
 script.charset = 'UTF-8';
 script.src = src;
 if (script.addEventListener) {
  script.addEventListener('load', function () {
   callback();
  }, false);
 } else if (script.attachEvent) {
  script.attachEvent('onreadystatechange', function () {
   var target = window.event.srcElement;
   if (target.readyState == 'loaded') {
    callback();
   }
  });
 }
 head.appendChild(script);
}



loadScript('//sdk.51.la/js-sdk-pro.min.js',function(){
    LA.init({id: "JeEtZnulJwHL7xHj",ck: "JeEtZnulJwHL7xHj"})
});
```

**Comment by waitsaber** [comment]
原来如此，我使用51.la提供的js统计代码填进去会导致整个页面是空白的连公告栏都不显示，但是能够加载成功统计网站也能正常获取数据。代码如下：
document.write("<script>!function(p){\"use strict\";!function(t){var s=window,e=document,i=p,c=\"\".concat(\"https:\"===e.location.protocol?\"https://\":\"http://\",\"sdk.51.la/js-sdk-pro.min.js\"),n=e.createElement(\"script\"),r=e.getElementsByTagName(\"script\")[0];n.type=\"text/javascript\",n.setAttribute(\"charset\",\"UTF-8\"),n.async=!0,n.src=c,n.id=\"LA_COLLECT\",i.d=n;var o=function(){s.LA.ids.push(i)};s.LA?s.LA.ids&&o():(s.LA=p,s.LA.ids=[],o()),r.parentNode.insertBefore(n,r)}()}({id:\"JeEtZnulJwHL7xHj\",ck:\"JeEtZnulJwHL7xHj\"});</script>")

**Comment by zhaojun1998** [comment]
因为这个脚本是加载后才执行的，所以不能用 `document.write`，你按照我上面的方式参考进行修改吧。

**Comment by waitsaber** [comment]
使用你修改的确实可以加载并识别，后续的版本能否对html标签的统计代码进行兼容，大多数统计网站都比较推荐使用HTML标签，毕竟一两行代码就能搞定。

**Comment by zhaojun1998** [comment]
如果要实现动态 html，那页面就不能是纯静态 HTML 了。技术上无法实现。或者可以直接修改 index.html，在这个文件里直接改。
