### ISSUE TITLE
当播放mkv视频失败时,第一次点下载会null

### ISSUE THREAD

**Issue by balh55y** [zfile-dev/zfile#338]
![image](https://user-images.githubusercontent.com/85926883/161179996-2b69d409-9048-4063-adf3-2eb0d6549d7a.png)
![image](https://user-images.githubusercontent.com/85926883/161180033-805f54cf-3cf2-474a-9d18-e91fd833ffe8.png)
![image](https://user-images.githubusercontent.com/85926883/161180046-c2093caf-b8bd-456d-9e79-0f349474906d.png)
第二次点下载会正常下载

**Comment by zhaojun1998** [comment]
存储源类型是什么，是否可以贴下两次分别的 URL 地址。可隐去 ip 和端口部分。

**Comment by balh55y** [comment]
又拍
/directlink/1/%E8%B7%AF%E4%BA%BA%E5%A5%B3%E4%B8%BB%E7%9A%84%E5%85%BB%E6%88%90%E6%96%B9%E6%B3%95%E2%99%AD%E3%80%8C%E6%97%A0%E4%BF%AE%E3%80%8D/%5BKamigami&Mabors%5D%20Saenai%20Heroine%20no%20Sodatekata%20Flat%20-%2001%20%5B1080p%20x265%20Ma10p%20AAC%5D.mkv
↑是null的
http://image-tuchuang-v1.test.upcdn.net/%E7%95%AA%E5%89%A7/%E8%B7%AF%E4%BA%BA%E5%A5%B3%E4%B8%BB%E7%9A%84%E5%85%BB%E6%88%90%E6%96%B9%E6%B3%95%E2%99%AD%E3%80%8C%E6%97%A0%E4%BF%AE%E3%80%8D/[Kamigami&Mabors]%20Saenai%20Heroine%20no%20Sodatekata%20Flat%20-%2001%20[1080p%20x265%20Ma10p%20AAC].mkv
第二次就是又拍的链接了

**Comment by balh55y** [comment]
而且我想通过播放器播放的时候也是第一个链接,导致本地播放器也放不了
![image](https://user-images.githubusercontent.com/85926883/161185669-2543390b-a38d-4647-9b28-1859c26e07ac.png)

**Comment by zhaojun1998** [comment]
因未复现成功，可以私发 zfile 地址到我邮箱吗，以便进一步排查问题。  

873019219@qq.com

**Comment by zhaojun1998** [comment]
@balh55y 

已修复并发布 3.2.2  版本
