### ISSUE TITLE
java 13 好像不能运行

### ISSUE THREAD

**Issue by Omoinemie** [zfile-dev/zfile#34]
我有其他程序需要用高版本，但是好像你的程序在运行之后就没有反应了，也进不去网页。
环境：apache 反向代理+jdk 13.0.2

**Comment by zhaojun1998** [comment]
@Omoinemie  请使用 JDK8 版本，JDK 13 兼容性有问题。

**Comment by Omoinemie** [comment]
宝塔面板里面有个Java项目管理器，里面的tomcat是独立的，你知道怎么使用

**Comment by Omoinemie** [comment]
这是运行日志，看一下什么问题
[zfile.log](https://github.com/zhaojun1998/zfile/files/4184349/zfile.log)

**Comment by zhaojun1998** [comment]
@Omoinemie  测试过，编译版本是 JDK8，且依赖项在 JDK8 才可使用，故不支持高版本的 JDK。此问题就先关闭了。
