### ISSUE TITLE
feat: 在挂载OneDrive盘的时候支持自定义应用ID，应用机密

### ISSUE THREAD

**Issue by haoduck** [zfile-dev/zfile#340]
![QQ截图20220404034700](https://user-images.githubusercontent.com/56804964/161445555-cd7c38ca-3d26-4d24-862a-fa533a809c95.png)

## 概述

建议可以在挂载一个OneDrive的时候自定义应用ID，应用机密等。

如上图所示，这是隔壁Sharelist的挂载页面，我觉得它是非常好的。

## 动机

目前虽然可以修改application.yml文件来实现，但美中不足。假设有2个或以上的OneDrive盘的时候，它们只能用application.yml里设置的同一个应用，而不能各自用各自的。

**Comment by zhaojun1998** [comment]
下版本会考虑此建议，谢谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月4日(周一) 凌晨3:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] feat: 在挂载OneDrive盘的时候支持自定义应用ID，应用机密 (Issue #340)




 

 
概述
 
如上图所示，建议可以在挂载一个OneDrive的时候自定义应用ID，应用机密等。
 
动机
 
目前虽然可以修改application.yml文件来实现，但美中不足。假设有2个或以上的OneDrive盘的时候，它们只能用application.yml里设置的同一个应用，而不能各自用各自的。
 
详细解释

**Comment by zhaojun1998** [comment]
@haoduck 

以增加此功能
