### ISSUE TITLE
能否支持对MOV视频格式的支持

### ISSUE THREAD

**Issue by xuebiya** [zfile-dev/zfile#344]
你好 能否支持对MOV视频格式的支持

**Comment by zhaojun1998** [comment]
@xuebiya 

在线播放视频是浏览器进行解码播放，目前所有浏览器仅支持封装格式为 h264，也就是我们常说的 mp4 格式的编码，所以不能也无法额外支持视频格式的在线播放，因为这个是浏览器的行为。

**Comment by xuebiya** [comment]
那能否像alist一样视频下方增加一个调用vlc等播放器的按钮
https://github.com/Xhofe/alist

**Comment by zhaojun1998** [comment]
下个版本会添加

**Comment by xuebiya** [comment]
好的 谢谢

**Comment by zhaojun1998** [comment]
@xuebiya 
新发布 4.0 已增加此功能
