### ISSUE TITLE
mysql初始化创建short_link表的问题

### ISSUE THREAD

**Issue by makexiao113** [zfile-dev/zfile#345]
## 我的环境
在使用mysql作为数据源初始化数据库时会报错导致short_link表创建失败

## 当前行为

原因是key在mysql中是关键词，导致无法正常创建short_link表
在ShortLinkConfig.java中的key属性前加@Column(name = "k") 可解决此问题

**Comment by makexiao113** [comment]
发生问题的是master版本，在dev版本此问题已解决

**Comment by zhaojun1998** [comment]
最新版本已解决此问题。
