### ISSUE TITLE
能够考虑增加对H.265编码格式视频的在线播放支持？

### ISSUE THREAD

**Issue by noisky** [zfile-dev/zfile#35]
H.265编码的视频体积更小，更适合在线播放，但是现在的播放器只支持h.264，h.265编码无法显示画面，只有声音，能否考虑增加对H.265的支持？

**Comment by zhaojun1998** [comment]
@noisky 
这是浏览器限制，并不是我不支持，目前浏览器均不支持 H.265 解码，请详细参考浏览器对 HEVC 视频的支持范围 https://caniuse.com/#search=hevc

**Comment by noisky** [comment]
了解了~ 非常感谢
