### ISSUE TITLE
OneDrive硬盘挂载报错

### ISSUE THREAD

**Issue by jixishi** [zfile-dev/zfile#352]
## 我的环境
![image](https://user-images.githubusercontent.com/57534147/164957196-76fc667c-9ee2-4de9-8ab5-ae657f2566ea.png)

## 错误日志
[ZFile 诊断日志 - 2022-04-24 12-51-50.zip](https://github.com/zhaojun1998/zfile/files/8549048/ZFile.-.2022-04-24.12-51-50.zip)

**Comment by jixishi** [comment]
初始化异常, 错误信息为: I/O error on GET request for "https://graph.microsoft.com/v1.0/me/drive/root/children": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by zhaojun1998** [comment]
@jixishi 
您这个是通过 docker 运行的还是直接宿主机运行的，如果是宿主机，jdk 的版本号是多少。

**Comment by jixishi** [comment]
运行环境是本机 

jdk1.8 是![Screenshot_20220612-222933.jpg](https://user-images.githubusercontent.com/57534147/173238065-ea35fd7c-d85e-4316-ac71-8a30599e7ded.jpg)

**Comment by zhaojun1998** [comment]
报什么错啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月12日(周日) 晚上10:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] OneDrive硬盘挂载报错 (Issue #352)




 
运行环境是本机
 
jdk1.8 是

**Comment by jixishi** [comment]
报错就是前面那个io错误啥啥啥的，我是在32位arm上跑的不知道是否与这个有关

**Comment by zhaojun1998** [comment]
我看错误信息，是 jdk 的问题，可尝试重新安装，最好是使用 `xxx.tar.gz` 安装包，解压并配置环境变量来安装 jdk。

可参考。https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ
