### ISSUE TITLE
端口号如何变更？在哪里面配置？

### ISSUE THREAD

**Issue by megvil** [zfile-dev/zfile#354]
8080端口被jenkins占用了。请问一下，这个在哪里修改端口呢？

**Comment by zhaojun1998** [comment]
https://docs.zfile.vip/#/config?id=%e5%90%af%e5%8a%a8%e7%ab%af%e5%8f%a3

**Comment by megvil** [comment]
@zhaojun1998 看到这个了，但是没看明白，在哪个文件里面修改。/root/zfile  里面有 bin WEB-INF  META-INF

**Comment by zhaojun1998** [comment]
https://docs.zfile.vip/#/question?id=modify_port

在这个路径下：
```java
/zfile/WEB-INF/classes/application.yml
```

**Comment by megvil** [comment]
搞定了，非常感谢
