### ISSUE TITLE
能否用本项目做论文上的研究

### ISSUE THREAD

**Issue by A-Rivi** [zfile-dev/zfile#356]
开发团队，你们好。首先非常感谢你们的辛苦付出。
我想问，我能否使用本项目的前端部分代码搭建自己的云盘系统，仅仅用作个人研究，毕业论文上会用到本项目前端部分代码，
不会有任何商用。

**Comment by zhaojun1998** [comment]
可以的，没问题

**Comment by A-Rivi** [comment]
非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月29日(星期五) 上午10:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhaojun1998/zfile] 能否用本项目做论文上的研究 (Issue #356)





 
可以的，没问题
