### ISSUE TITLE
Windows平台使用Docker Desktop部署的zfile

### ISSUE THREAD

**Issue by byddgithubzh** [zfile-dev/zfile#357]
## 我的环境
windows通过docker desktop部署

## 错误日志
除了读取不到文件，其他都是正常的。

## 期望行为
能够读取到文件。

## 当前行为
读取不到本地文件。

事情大概是这样的，我用Docker Desktop在windows平台部署了最新的zfile，自定义了:3535为端口，zfile可以正常登录，应该也做了文件链接，我安装的代码如下（docker run -dit -v D:/Docker/root/zfile/db:/root/zfile/db -v D:/Docker/root/zfile/logs:/root/zfile/logs -p 3535:8080 --name zfile --hostname zfile -e TZ=Asia/Shanghai --restart unless-stopped zhaojun1998/zfile:latest），参照网上找的青龙的Docker Desktop部署的例子自己改的。青龙成功的登上了也能正常使用、读取本地文件。zfile也能成功的登录，以及进行一些设置，但是无法正常的读取到文件，甚至使用everything文件按搜索工具也不能搜到网页上的文件。
zfile的截图
![image](https://user-images.githubusercontent.com/78755339/167187312-b5a5d176-da63-4eb5-9698-661b774e0e15.png)
驱动器添加设置
![image](https://user-images.githubusercontent.com/78755339/167188005-1c1636bc-f740-4780-81dc-72cc9f2e04c8.png)
Docker Desktop界面
![image](https://user-images.githubusercontent.com/78755339/167188287-3c2d60b9-b088-4c16-ba7c-88d1595e0017.png)

我不知道这是软件bug，还是我什么地方设置错了，请帮忙解决。

**Comment by zhaojun1998** [comment]
因为你的 zfile 是运行在 docker 容器里的，所以他读取的是 docker 容器内的 /root 目录下的文件。你在宿主机上肯定搜索不到。


如果想在 docker 容器内访问宿主机的文件夹，并映射出去。需要在创建 docker 容器时，就用 -v 命令将宿主机的指定目录映射到 docker 容器内。


如 -v d:/video:/data/video
在 zfile 中配置 /data/video 目录，就能访问到宿主机的 d:/video 目录。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月7日(周六) 凌晨1:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] Windows平台使用Docker Desktop部署的zfile (Issue #357)




 
我的环境
 
错误日志
 
期望行为
 
当前行为
 
事情大概是这样的，我用Docker Desktop在windows平台部署了最新的zfile，自定义了:3535为端口，zfile可以正常登录，应该也做了文件链接，我安装的代码如下（docker run -dit -v D:/Docker/root/zfile/db:/root/zfile/db -v D:/Docker/root/zfile/logs:/root/zfile/logs -p 3535:8080 --name zfile --hostname zfile -e TZ=Asia/Shanghai --restart unless-stopped zhaojun1998/zfile:latest），参照网上找的青龙的Docker Desktop部署的例子自己改的。青龙成功的登上了也能正常使用、读取本地文件。zfile也能成功的登录，以及进行一些设置，但是无法正常的读取到文件，甚至使用everything文件按搜索工具也不能搜到网页上的文件。
 zfile的截图
 
 驱动器添加设置
 
 Docker Desktop界面
 
 
我不知道这是软件bug，还是我什么地方设置错了，请帮忙解决。

**Comment by byddgithubzh** [comment]
> 因为你的 zfile 是运行在 docker 容器里的，所以他读取的是 docker 容器内的 /root 目录下的文件。你在宿主机上肯定搜索不到。 如果想在 docker 容器内访问宿主机的文件夹，并映射出去。需要在创建 docker 容器时，就用 -v 命令将宿主机的指定目录映射到 docker 容器内。 如 -v d:/video:/data/video 在 zfile 中配置 /data/video 目录，就能访问到宿主机的 d:/video 目录。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月7日(周六) 凌晨1:53 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [zhaojun1998/zfile] Windows平台使用Docker Desktop部署的zfile (Issue #357) 我的环境 错误日志 期望行为 当前行为 事情大概是这样的，我用Docker Desktop在windows平台部署了最新的zfile，自定义了:3535为端口，zfile可以正常登录，应该也做了文件链接，我安装的代码如下（docker run -dit -v D:/Docker/root/zfile/db:/root/zfile/db -v D:/Docker/root/zfile/logs:/root/zfile/logs -p 3535:8080 --name zfile --hostname zfile -e TZ=Asia/Shanghai --restart unless-stopped zhaojun1998/zfile:latest），参照网上找的青龙的Docker Desktop部署的例子自己改的。青龙成功的登上了也能正常使用、读取本地文件。zfile也能成功的登录，以及进行一些设置，但是无法正常的读取到文件，甚至使用everything文件按搜索工具也不能搜到网页上的文件。 zfile的截图 驱动器添加设置 Docker Desktop界面 我不知道这是软件bug，还是我什么地方设置错了，请帮忙解决。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感谢，这个问题已经解决，现在可以读取到文件了。

我遇到了新的问题，我使用钉钉的免费内网穿透功能来实现远程访问电脑上的Zfile
![image](https://user-images.githubusercontent.com/78755339/167252696-1ed29121-74ea-42fa-be04-6eb8483b98c3.png)
起初远程访问时不能加载文件（网页预览列表是正常的），我简单的分析了下，是钉钉的内网穿透没把链接传递完整，传递出来的是http://localhost:端口/文件（手动补齐链接是可以使用的）。发现这一问题后我在zfile的管理面板-基本设置-站点域名，修改为钉钉内网穿透的完整域名就可以解决部分，如视频、txt文件等，但还是有文件不能正常传递链接。

请问这个问题怎么解决？

**Comment by byddgithubzh** [comment]
> 因为你的 zfile 是运行在 docker 容器里的，所以他读取的是 docker 容器内的 /root 目录下的文件。你在宿主机上肯定搜索不到。
> 
> 
> 如果想在 docker 容器内访问宿主机的文件夹，并映射出去。需要在创建 docker 容器时，就用 -v 命令将宿主机的指定目录映射到 docker 容器内。
> 
> 
> 如 -v d:/video:/data/video
> 在 zfile 中配置 /data/video 目录，就能访问到宿主机的 d:/video 目录。
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2022年5月7日(周六) 凌晨1:53
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.***&gt;;
> 主题: [zhaojun1998/zfile] Windows平台使用Docker Desktop部署的zfile (Issue #357)
> 
> 
> 
> 
>  
> 我的环境
>  
> 错误日志
>  
> 期望行为
>  
> 当前行为
>  
> 事情大概是这样的，我用Docker Desktop在windows平台部署了最新的zfile，自定义了:3535为端口，zfile可以正常登录，应该也做了文件链接，我安装的代码如下（docker run -dit -v D:/Docker/root/zfile/db:/root/zfile/db -v D:/Docker/root/zfile/logs:/root/zfile/logs -p 3535:8080 --name zfile --hostname zfile -e TZ=Asia/Shanghai --restart unless-stopped zhaojun1998/zfile:latest），参照网上找的青龙的Docker Desktop部署的例子自己改的。青龙成功的登上了也能正常使用、读取本地文件。zfile也能成功的登录，以及进行一些设置，但是无法正常的读取到文件，甚至使用everything文件按搜索工具也不能搜到网页上的文件。
>  zfile的截图
>  
>  驱动器添加设置
>  
>  Docker Desktop界面
>  
>  
> 我不知道这是软件bug，还是我什么地方设置错了，请帮忙解决。
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

已解决
