### ISSUE TITLE
docker运行 OneDrive驱动器 抛异常

### ISSUE THREAD

**Issue by ouyanglong721** [zfile-dev/zfile#358]
## 我的环境 
Docker运行  3.2.0版本   使用H2数据库 

## 错误日志
![image](https://user-images.githubusercontent.com/52189456/167249195-9977bb92-e9a3-45a9-b1fb-3f8eb9fa3a7b.png)

[ZFile 诊断日志 - 2022-05-07 17-39-31.zip](https://github.com/zhaojun1998/zfile/files/8644856/ZFile.-.2022-05-07.17-39-31.zip)

不知道是不是网络的问题，部署在服务器上，使用过程，文件刷新也很卡顿，卡顿之后就死了，驱动的任何操作都做不了

**Comment by zhaojun1998** [comment]
服务器地域是哪里的，出现卡顿的情况多吗。还有图片上的报错，是点击什么出现的。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月7日(周六) 下午5:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] docker运行 OneDrive驱动器 抛异常 (Issue #358)




 
我的环境
 
Docker运行  3.2.0版本   使用H2数据库
 
错误日志
 

 
ZFile 诊断日志 - 2022-05-07 17-39-31.zip
 
不知道是不是网络的问题，部署在服务器上，使用过程，文件刷新也很卡顿，卡顿之后就死了，驱动的任何操作都做不了
 
期望行为
 
当前行为

**Comment by ouyanglong721** [comment]
> 服务器地域是哪里的，出现卡顿的情况多吗。还有图片上的报错，是点击什么出现的。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月7日(周六) 下午5:56 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [zhaojun1998/zfile] docker运行 OneDrive驱动器 抛异常 (Issue #358) 我的环境 Docker运行 3.2.0版本 使用H2数据库 错误日志 ZFile 诊断日志 - 2022-05-07 17-39-31.zip 不知道是不是网络的问题，部署在服务器上，使用过程，文件刷新也很卡顿，卡顿之后就死了，驱动的任何操作都做不了 期望行为 当前行为 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

腾讯云轻量，广州，异常在编辑驱动器，删除驱动器时出现

**Comment by zhaojun1998** [comment]
我看你这个版本是之前的了。之前有遇到过么，是最近才出现的，还是一直都是这样。


点击编辑或删除报错，是每次点击都报错么。


现在的3.2.0版本当时是全新安装，还是通过旧版本的 db 文件升级的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月7日(周六) 晚上6:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] docker运行 OneDrive驱动器 抛异常 (Issue #358)




  
服务器地域是哪里的，出现卡顿的情况多吗。还有图片上的报错，是点击什么出现的。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年5月7日(周六) 下午5:56 收件人: @.&gt;; 抄送: @.&gt;; 主题: [zhaojun1998/zfile] docker运行 OneDrive驱动器 抛异常 (Issue #358) 我的环境 Docker运行 3.2.0版本 使用H2数据库 错误日志 ZFile 诊断日志 - 2022-05-07 17-39-31.zip 不知道是不是网络的问题，部署在服务器上，使用过程，文件刷新也很卡顿，卡顿之后就死了，驱动的任何操作都做不了 期望行为 当前行为 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
腾讯云轻量，广州，异常在编辑驱动器，删除驱动器时出现

**Comment by ouyanglong721** [comment]
目前我使用的是最新版本的Docker安装的，全新安装的。现在每次点击编辑和删除都报错，已经挂掉了

**Comment by zhaojun1998** [comment]
删掉 db 文件。重新初始化一次试试呢，可能 docker 异常关闭导致 db 文件损坏了，4.0 会使用更稳定的 mysql 来尽量避免这种问题。


方便的话，可以给一份 db 文件发到我邮箱 ***@***.*** 以便排查问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月7日(周六) 晚上6:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] docker运行 OneDrive驱动器 抛异常 (Issue #358)




 
目前我使用的是最新版本的Docker安装的，全新安装的。现在每次点击编辑和删除都报错，已经挂掉了

**Comment by ouyanglong721** [comment]
邮箱被*号了，我发现每次在设置完驱动器，比如修改配置后，就会比较卡，甚至抛异常。刚刚把场景又复现了，添加完文件后，刷新文件首页，然后再去修改配置，会导致出现刚刚的异常。

**Comment by zhaojun1998** [comment]
873019219&nbsp; &nbsp; &nbsp;是QQ的邮箱



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月7日(周六) 晚上6:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] docker运行 OneDrive驱动器 抛异常 (Issue #358)




 
邮箱被*号了，我发现每次在设置完驱动器，比如修改配置后，就会比较卡，甚至抛异常。刚刚把场景又复现了，添加完文件后，刷新文件首页，然后再去修改配置，会导致出现刚刚的异常。

**Comment by ouyanglong721** [comment]
邮件已发送，请查收。

**Comment by zhaojun1998** [comment]
收到，谢谢，一天内给答复。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月7日(周六) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] docker运行 OneDrive驱动器 抛异常 (Issue #358)




 
邮件已发送，请查收。

**Comment by ouyanglong721** [comment]
貌似现在又变的很流畅了，不知道为啥，可以考虑在一些API上加上超时时间限制。

**Comment by zhaojun1998** [comment]
经测试，你这个数据库文件是没问题的，文件列表刷新时正常的，后台点击编辑也能打开。

我看你是 3.2.0，最新版本是 3.2.4，你用的那个版本已经是去年 9 月份的版本了。但你说你是最新安装的，可能你用的不是 zfile 官方的 docker 镜像，最新版是：https://hub.docker.com/r/zhaojun1998/zfile

**Comment by ouyanglong721** [comment]
用最新镜像测试了，好像也抛这个异常，感觉像是网络阻塞导致事务出问题了。

**Comment by zhaojun1998** [comment]
什么是好像抛出了异常。


更新最新的 3.2.4 之后，还是列表加载不出来，或者列表加载慢。&nbsp; 并且后台点击编辑和删除报错么。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月8日(周日) 凌晨0:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] docker运行 OneDrive驱动器 抛异常 (Issue #358)




 
用最新镜像测试了，好像也抛这个异常，感觉像是网络阻塞导致事务出问题了。

**Comment by ouyanglong721** [comment]
是的，更新后还是有同样的问题，不知道什么时候更新4.0版本

**Comment by zhaojun1998** [comment]
@ouyanglong721 
目前来看不是版本问题，是腾讯云轻量，广州 到微软服务器网络问题。

之前用的时候有遇到过这个问题么，是最近出现的，还是一直有这个问题。（同样在轻量广州机器下）

**Comment by ouyanglong721** [comment]
最近开始使用zfile的，但是我用cloudreve部署的另一个服务，另一个OneDrive子账号   好像就没这个问题0.0

**Comment by zhaojun1998** [comment]
用同一个 onedrive 账号试试

**Comment by ouyanglong721** [comment]
好的 下午有时间试试

**Comment by zhaojun1998** [comment]
还有 cloudreve 不是用 docker 部署的话， zfile 也别用 docker 试试，也可能是 docker 容器内 dns 问题导致的

**Comment by ouyanglong721** [comment]
都是用docker部署的

**Comment by ouyanglong721** [comment]
不知道是不是cloudreve和zfile调用的不是同一套接口？

**Comment by zhaojun1998** [comment]
@ouyanglong721 接口肯定是同一套，只要你的 onedrive 账号都是同类型的，接口就肯定是一样的。

onedrive 分为世纪互联，国际版，SharePoint 等版本，请确认你在 cloudreve 上用的账号和 zfile 中用的账号是同一版本的。以便排查到底是网络问题，还是其他问题。

**Comment by ouyanglong721** [comment]
版本肯定是相同的哦，但是貌似cloudreve使用的都是异步请求。

赵俊 ***@***.***> 于2022年5月9日周一 10:58写道：

**Comment by ouyanglong721** [comment]
@zhaojun1998   最大可能应该还是网络问题，现在部署在Oracle的大版机器上，貌似就没问题出现了。
