### ISSUE TITLE
监听主机IP地址修改

### ISSUE THREAD

**Issue by HappyLife-page** [zfile-dev/zfile#359]
请问如何修改监听的IP地址呢，默认为公网IP不可以修改为localhost吗？

**Comment by zhaojun1998** [comment]
@HappyLife-page 

可以啊，默认都监听了，只要端口正确，用什么机器的哪个 IP 都可以访问的。

**Comment by mzhboy** [comment]
配置文件有 
`server.port=8080` 
改为 

```
server.port=8080
server.address=127.0.0.1
```
