### ISSUE TITLE
[咨询]有办法支持多个存储策略吗？

### ISSUE THREAD

**Issue by greenhat616** [zfile-dev/zfile#36]
有这么一个需求：
* 系统 v1 时文件使用了域名 v1.cdn.xxxx.domain（比如说后端 UPYUN）
* 系统 v2 时，文件使用了域名： v2.cdn.xxx.domain（比如说后端腾讯云）
* ...etc
然后，我们想开放这些文件供使用者查看，换句话说，我们希望用户能查看 v1.cdn.xx v2.cdn.xx 特定目录列出的合集。
类似的组合：
> UPYUN 配置1，配置2...

请问，目前我们的系统支持吗？如果不支持的话，架构上有预留嘛？

**Comment by zhaojun1998** [comment]
目前架构上不支持，且没有用户和授权的概念。

你可以在同一台机器，部署两套程序，然后映射不同域名，也是可以的。

后续会开发同时支持多存储策略的功能，但不会支持多用户及授权功能。

**Comment by greenhat616** [comment]
好的，等待你的好消息哦。
P.S：我的意思也不是要多用户啦，上面的意思就是多储存策略的功能。

**Comment by zhaojun1998** [comment]
@greenhat616 新版本 （2.3）已支持多存储策略
