### ISSUE TITLE
无法添加 Cloudflare R2 对象存储

### ISSUE THREAD

**Issue by Hreint** [zfile-dev/zfile#360]
## 我的环境

ZFile v3.2.5

## 错误日志

![Inked2022-05-19_204138_LI](https://user-images.githubusercontent.com/64591583/169389878-736898e8-da00-455f-82db-30b2f68eee54.jpg)

## 期望行为

Cloudflare R2 采用 S3 兼容的 API，根据官方文档应该是可以作为 S3 存储添加的才对。

https://developers.cloudflare.com/r2/examples/rclone/

## 当前行为

无法添加 Cloudflare R2 存储。

**Comment by zhaojun1998** [comment]
https://developers.cloudflare.com/r2/platform/s3-compatibility/api/

根据官网文档，地域要填写 auto

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/35387985/169433681-bef8d40c-ea59-4948-a7b3-efdc0b7582b7.png">

**Comment by Hreint** [comment]
> https://developers.cloudflare.com/r2/platform/s3-compatibility/api/
> 
> 根据官网文档，地域要填写 auto
> 
> <img alt="image" width="1283" src="https://user-images.githubusercontent.com/35387985/169433681-bef8d40c-ea59-4948-a7b3-efdc0b7582b7.png">

确实如此，添加 auto 了之后就可以了！十分感谢！

**Comment by zhaojun1998** [comment]
@Hreint 
可以提供下 `Worker` 访问 `B2` 资源的函数吗，我自己没测试出来，可以的话，我补充到文档中。

**Comment by Hreint** [comment]
> @Hreint 可以提供下 `Worker` 访问 `B2` 资源的函数吗，我自己没测试出来，可以的话，我补充到文档中。

啥意思？是 cloudflare worker 反代 B2 存储的函数吗？

**Comment by zhaojun1998** [comment]
是的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月21日(周六) 晚上9:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 无法添加 Cloudflare R2 对象存储 (Issue #360)




  
@Hreint 可以提供下 Worker 访问 B2 资源的函数吗，我自己没测试出来，可以的话，我补充到文档中。
  
啥意思？是 cloudflare worker 反代 B2 存储的函数吗？

**Comment by Hreint** [comment]
> 是的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月21日(周六) 晚上9:04 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [zhaojun1998/zfile] 无法添加 Cloudflare R2 对象存储 (Issue #360) @Hreint 可以提供下 Worker 访问 B2 资源的函数吗，我自己没测试出来，可以的话，我补充到文档中。 啥意思？是 cloudflare worker 反代 B2 存储的函数吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我用的就是文档里面反代 OneDrive 的那个函数，在这个页面的方法二：https://docs.zfile.vip/#/advanced?id=onedrive-cf，把网址替换成 B2 的网址就可以了。

**Comment by imChaLi** [comment]
因为Cloudflare R2 目前不开放公网访问
所以添加到ZFile之后 也无法查看或者下载文件 提示Unauthorized

想问下这个有办法解决么
谢谢啦

**Comment by zhaojun1998** [comment]
@ichali 

新建一个 `worker`

1. 去 `worker` 设置 -> 变量 -> R2 存储桶绑定, 变量名称填写 PUBLIC，值选你的 R2 存储桶。
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/35387985/172523794-f4ddd4cf-80ec-4f98-84d5-0151846feecf.png">

2. worker 代码内容填写：

```javascript
var src_default = {
  async fetch(request, env) {
    const { pathname } = new URL(request.url);
    const obj = await env.PUBLIC.get(decodeURIComponent(pathname.slice(1, void 0)));
    if (obj === null)
      return new Response("Not found.", { status: 404 });
    const headers = {};
    if (obj?.httpMetadata.contentType)
      headers["content-type"] = obj?.httpMetadata.contentType;
    if (obj?.httpMetadata.contentEncoding)
      headers["content-encoding"] = obj?.httpMetadata.contentEncoding;
    if (obj?.httpMetadata.contentDisposition)
      headers["content-disposition"] = obj?.httpMetadata.contentDisposition;
    if (obj?.httpMetadata.contentLanguage)
      headers["content-language"] = obj?.httpMetadata.contentLanguage;
    if (obj?.httpMetadata.cacheControl)
      headers["cache-control"] = obj?.httpMetadata.cacheControl;
    if (obj?.httpMetadata.cacheExpiry)
      headers["expires"] = obj?.httpMetadata.cacheExpiry.toUTCString();
    return new Response(obj?.body, {
      headers
    });
  }
};
export {
  src_default as default
};
```

3. 然后访问 `worker` 生成的域名访问就可以了。如根目录有一个 `1.png`，访问 `https://worker-name.username.workers.dev/1.png` 即可

**Comment by imChaLi** [comment]
@zhaojun1998 
之前试验过用workers反代，还是提示Unauthorized
直接绑定wokers是可行的

非常感谢啦

**Comment by Hreint** [comment]
作者您好，

我最近尝试了一下最新版也就是 4.1.1 版本的 zfile，发现好像又无法添加 R2 存储了。

![2022-09-10_180028](https://user-images.githubusercontent.com/64591583/189478467-22db9151-0d91-48d5-ad6d-b6632c3e2322.png)

![2022-09-10_180044](https://user-images.githubusercontent.com/64591583/189478493-c89051ea-b18c-42ee-89c3-ded50ed7b59c.png)

存储策略选的是 S3通用协议，地域已经填了 auto，但还是提示“无效的地域名称”。
