### ISSUE TITLE
【百度网盘】网盘能力全方位开放

### ISSUE THREAD

**Issue by ifeisier** [zfile-dev/zfile#361]
![image](https://user-images.githubusercontent.com/89009057/169789085-b4208c6e-d19b-4e37-ae09-670171372773.png)

请问能接入吗？

[https://pan.baidu.com/union](https://pan.baidu.com/union)

**Comment by zhaojun1998** [comment]
@ifeisier 

可以的，目前已经测试通过了，不过百度云下载链接，有限制，必须指定 User-Agent 才能下载。换句话说就是，浏览器无法直接下载，需要通过其他插件支持。

https://pan.baidu.com/union/doc/pkuo3snyp

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/35387985/169789586-1e8439fe-5fa8-493b-977e-9ebbdfd2e8ee.png">

**Comment by ifeisier** [comment]
@zhaojun1998 

可以使用 IDM 或 Motrix，实现。

**Comment by zhaojun1998** [comment]
@ifeisier 

是的，没问题的，不过 ZFile 不会实现第三方的，或者官网文档未提供的 API。

ZFile 对接官方 API，用户自行使用工具下载，这个是没问题的。

**Comment by ifeisier** [comment]
> @ifeisier
> 
> 是的，没问题的，不过 ZFile 不会实现第三方的，或者官网文档未提供的 API。
> 
> ZFile 对接官方 API，用户自行使用工具下载，这个是没问题的。

好的

**Comment by woshihoujinxin** [comment]
请问已经实现了么，要怎么配置才能支持百度云
