### ISSUE TITLE
【应用功能】能将网络存储驱动写成插件吗？

### ISSUE THREAD

**Issue by ifeisier** [zfile-dev/zfile#362]
## 概述

可以将 OneDrive、SharePoint、又拍云、本地存储 这些以插件发布吗？

## 动机

这样我可以直接开发其它网络存储驱动的插件，而不是在源码的基础上修改并打包。

**Comment by zhaojun1998** [comment]
@ifeisier 

插件化后续会考虑，不过 ZFile 下个大版本 4.0 会进一步优化代码，减少增加存储源的代码量。软件插件化需要的工作量比较大，近期还在修改大版本，所以需要往后排了。

**Comment by ifeisier** [comment]
> @ifeisier
> 
> 插件化后续会考虑，不过 ZFile 下个大版本 4.0 会进一步优化代码，减少增加存储源的代码量。软件插件化需要的工作量比较大，近期还在修改大版本，所以需要往后排了。

期待
