### ISSUE TITLE
Docker配置下加入 password.txt 后无法工作

### ISSUE THREAD

**Issue by goldyard2021** [zfile-dev/zfile#363]
我安装了最新的版本: v3.2.5
未添加 password.txt 文件前工作正常， 在添加了 password.txt 文件后， 访问后一直无法现实密码提示框， 多次刷新后后台 JDBC 缓冲池溢出。 password.txt 编码格式测试过 UTF8 和 GBK， 都是相同问题。删除后可以恢复正常工作。 

## 我的环境
群晖下 Docker， 安装标准镜像， 全新安装。 

没找到系统监控区域

**Comment by zhaojun1998** [comment]
@goldyard2021 
加密码文件后，加载文件时提示什么错误信息，还是一直转圈。

还有就是检查下站点域名配置是否正确，即是否是内网地址。

<img width="505" alt="image" src="https://user-images.githubusercontent.com/35387985/171985941-8bab1adc-a50f-4c6d-a1f6-bace99508481.png">

**Comment by goldyard2021** [comment]
就是一直在转， 站点域名设置的是外网域名， 不是内网IP地址

**Comment by goldyard2021** [comment]
如果我把站点域名改回内网IP地址， 就可以正常显示密码提示了。

**Comment by goldyard2021** [comment]
找到原因了， 首先电信的ADSL作为服务器， Java拿到的外部DDNS域名IP无法从内网直接访问， 导致http://域名/xxx/password.txt在内网访问失败。 改为内网IP： 192.168.102.100就可以访问了。 
解决办法， 登陆到docker内部， 修改/etc/hosts文件， 直接把外网域名解析到内网IP即可。 
例如加入：
192.168.102.100 home.zfileServer.com

**Comment by zhaojun1998** [comment]
好的，解决了就 ok。
