### ISSUE TITLE
【所有网络驱动】新增挂载点功能

### ISSUE THREAD

**Issue by ifeisier** [zfile-dev/zfile#364]
我请求新增一个挂载点功能，因为我有多个 OneDrive 网盘，所以我想将这些网盘都挂在到同一个挂载点，网盘目录列出的就是这些网盘的所有文件。

例如：假设我分别有 OneDriveA、OneDriveB、OneDriveC 这三个网盘，我可以将这三个网盘，挂载到同一个挂载点。
当访问前端时，只需要访问这个挂载点，就可以访问到这三个网盘中的数据。

**Comment by zhaojun1998** [comment]
就是说如账号 A 有:

```
.
├── 1.txt
├── 2.txt
```


然后账号 B 有:

```
.
├── 3.txt
├── 4.txt
```


挂载到同一挂载点，如访问 `http://ip:port/od/` 显示:

```
.
├── 1.txt
├── 2.txt
├── 3.txt
├── 4.txt
```

是这个意思吗。


这样有一个问题啊，比如账号 A 和账号 B 指定目录有同名文件呢，显示谁的.

**Comment by zhaojun1998** [comment]
这样还会有关联问题，od api 是有请求次数限制的。这样的话，访问量大的时候，可能其中一个网盘 api 遇到阈值了，请求不到数据了。

还有个问题就是，网站也是文件请求速度会至少慢 N 倍，（N = 同时挂载的数量，这里说至少是指，如文件过多，浏览器展示也会很慢。）

**Comment by ifeisier** [comment]
@zhaojun1998 "这样有一个问题啊，比如账号 A 和账号 B 指定目录有同名文件呢，显示谁的."   合并显示啊，根据文件夹路径和名称合并显示。

请求速度问题可以用缓存解决吧，，用户可以再后台刷新缓存，，或再一小时更新一次缓存。

**Comment by zhaojun1998** [comment]
也就是同目录下可能会出现文件名称一模一样的文件。可程序里还有根据路径的直链地址。这样就匹配不上了。


缓存也有刷新问题。这个功能影响挺多的，后续会考虑实现，但优先级不会太高。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月4日(周六) 下午5:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 【所有网络驱动】新增挂载点功能 (Issue #364)




 
@zhaojun1998 "这样有一个问题啊，比如账号 A 和账号 B 指定目录有同名文件呢，显示谁的."   合并显示啊，根据文件夹路径和名称合并显示。
 
请求速度问题可以用缓存解决吧，，用户可以再后台刷新缓存，，或再一小时更新一次缓存。

**Comment by ifeisier** [comment]
@zhaojun1998 无所谓，基于你的开源协议，我可以把你程序重新开发，并发布出去。

**Comment by zhaojun1998** [comment]
可以的，不过现在正在重构，重构后代码应该会更规范一些，不急的话，可以等等。

**Comment by ifeisier** [comment]
> 可以的，不过现在正在重构，重构后代码应该会更规范一些，不急的话，可以等等。

我可以等

**Comment by zhaojun1998** [comment]
4.0 版本已发布
