### ISSUE TITLE
希望在后台登录界面添加验证码防止嗯破

### ISSUE THREAD

**Issue by LxnChan** [zfile-dev/zfile#366]
## 概述

在后台登录和需要密码验证的文件夹添加验证防止嗯破。

## 动机

一晚上后台被暴力破解上万次实在是受不了...

## 详细解释

在后台登录部分和需要密码验证的文件添加一个验证码，既可以考虑原始的图片验证码，也可以考虑诸如GeeTest、reCaptcha这种的现代化验证方案，防止暴力破解。其中GeeTest和Google reCaptcha有一套通用逻辑，服务端填写对应的密钥对即可，希望作者大大能考虑一下，谢谢。

**Comment by zhaojun1998** [comment]
@LxnChan 
好，会考虑增加图形验证码、第三方验证码，或者 2FA。

**Comment by 1405701162** [comment]
这么简单自己写不好吗？

**Comment by zhaojun1998** [comment]
@LxnChan 

新版本已经实现，约六月底发布。

![image](https://user-images.githubusercontent.com/35387985/172584947-8bb26621-b088-4b67-a06e-ef7105fb6581.png)

![image](https://user-images.githubusercontent.com/35387985/172584923-6e6bd222-38b0-4b4b-9b9b-2f90dcf87700.png)

![image](https://user-images.githubusercontent.com/35387985/172584910-b0ff4378-6241-4fe1-8fd2-e16e01e68226.png)

**Comment by LxnChan** [comment]
感谢作者大大！

**Comment by zhaojun1998** [comment]
已发布 4.0 版本
