### ISSUE TITLE
更新3.25后无application.yml文件

### ISSUE THREAD

**Issue by zranl** [zfile-dev/zfile#368]
更新3.25后无application.yml文件  无法修改一些信息

vi ~/zfile/WEB-INF/classes/application.yml 为空
Docker文件里也找不到该文件

**Comment by zhaojun1998** [comment]
@zranl 

你是 docker 安装的么，你截图你查看 docker 容器内 application.yml 文件的命令及返回结果。

**Comment by Kissycat** [comment]
> @zranl
> 
> 你是 docker 安装的么，你截图你查看 docker 容器内 application.yml 文件的命令及返回结果。

Docker的确实没了，得自己弄一份...
![image](https://user-images.githubusercontent.com/20614068/175197306-4a320320-d87b-48cb-90b3-7352ba066b82.png)
