### ISSUE TITLE
feat: 点击到不支持预览的文件时不要自动下载

### ISSUE THREAD

**Issue by pulsgarney** [zfile-dev/zfile#369]
## 概述

点击到不支持预览的文件时不要自动下载。因为文件类型特别多，除非点到“下载”按钮，点击文件名时不要老是自动就下载文件了，很是干扰。也没有个确认是否下载的流程直接就下载了很是难受。

## 动机

参考一般网盘应用，如果是不支持预览的文件，一般是点击后选中或者无动作。

**Comment by zhaojun1998** [comment]
很不错的建议。会考虑增加选项来控制这种行为。



---原始邮件---
发件人: "Puls ***@***.***&gt;
发送时间: 2022年6月10日(周五) 晚上9:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] feat: 点击到不支持预览的文件时不要自动下载 (Issue #369)




 
概述
 
点击到不支持预览的文件时不要自动下载。因为文件类型特别多，除非点到“下载”按钮，点击文件名时不要老是自动就下载文件了，很是干扰。也没有个确认是否下载的流程直接就下载了很是难受。
 
动机
 
参考一般网盘应用，如果是不支持预览的文件，一般是点击后选中或者无动作。
 
详细解释

**Comment by zhaojun1998** [comment]
@PulsGarney 

4.0 版本已修改此问题。

<img width="588" alt="image" src="https://user-images.githubusercontent.com/35387985/178384944-352e6b09-4831-4e4c-931f-4e5f9a35615f.png">
