### ISSUE TITLE
Hi，你好，我是源码弹幕的作者，看到你尝试了一下我的插件，特意来拜访一下。

### ISSUE THREAD

**Issue by SetoKaiba** [zfile-dev/zfile#37]
Hi，你好，我是源码弹幕的作者，看到你尝试了一下我的插件，特意来拜访一下。谢谢你尝试我的插件，然后，还有我发现你注册的时候邮箱填错了- -、目前插件才起步，邮箱验证这块没做，你可以从右上角名字，点Edit Profile修改。

**Comment by zhaojun1998** [comment]
@SetoKaiba  
很好的插件，可以解决阅读源码加注释的痛点，希望继续开发。

关于改邮箱，我现在修改为 `root@zhaojun.im` 提示 `email contains sensitive word: 40,`，尝试改为 `gmail` 也通过不了校验。

**Comment by SetoKaiba** [comment]
额，现在的敏感词列表有点问题，我修正一下，谢谢使用呀。
我现在加了个注册发激活邮件，避免再次出现邮箱输入错误的问题。

**Comment by SetoKaiba** [comment]
@zhaojun1998 Hi. 邮件系统和敏感词的bug修正也改掉了，你试试？之前敏感词在url解码之前做了，所以有问题，现在应该好了。
https://github.com/SetoKaiba/SourceDanmakuBugFeedback/issues
对了，如果还有什么bug或者意见可以这里留言，谢谢呀。

**Comment by zhaojun1998** [comment]
@SetoKaiba 好，谢谢，那此 issue 就先关闭了。
