### ISSUE TITLE
feat: json文件的预览（源文件预览）

### ISSUE THREAD

**Issue by inmarkd** [zfile-dev/zfile#375]
## 概述

1. 希望增加对json文件的源码预览，如同github的源码预览一般
2. 本地路径时管理后台可以增加上传文件的功能吗
## 动机

json源码预览就可以当作一个小型的后端服务，为前端提供数据接口

**Comment by zhaojun1998** [comment]
已发布 4.0 版本，支持文件上传功能， json 预览可惜支持不了。

**Comment by zhangjh** [comment]
json文件至少可以当纯文本查看

**Comment by zhaojun1998** [comment]
后台能设置文本格式后缀。你去加上 .json就行了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月26日(周二) 晚上6:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [zhaojun1998/zfile] feat: json文件的预览（源文件预览） (Issue #375)




 
json文件至少可以当纯文本查看

**Comment by zhangjh** [comment]
作者可以介绍下前后端的部署吗？我看整体是前后端分离的，但安装的war包是一体的。如果能介绍一下这方面，我可以提供一些功能开发，比如文件预览方面

**Comment by zhaojun1998** [comment]
暂时不需要了，最近会频繁更新的。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月27日(周三) 上午10:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [zhaojun1998/zfile] feat: json文件的预览（源文件预览） (Issue #375)




 
作者可以介绍下前后端的部署吗？我看整体是前后端分离的，但安装的war包是一体的。如果能介绍一下这方面，我可以提供一些功能开发，比如文件预览方面

**Comment by zhangjh** [comment]
Ok，期待早日支持上更多格式的预览功能

**Comment by yeungchie** [comment]
json无法预览，版本

> 已发布 4.0 版本，支持文件上传功能， json 预览可惜支持不了。

你好，json文件预览失败，文件可以正常生成链接并下载，版本4.1.5。

![image](https://github.com/zfile-dev/zfile/assets/30793662/bcfa36be-73b6-4486-8f3b-0dec4040c049)
