### ISSUE TITLE
docker 部署的时候如何修改端口号

### ISSUE THREAD

**Issue by anduinnn** [zfile-dev/zfile#376]
通过docker 部署,想修改程序的默认端口,但是又没有找到 application.yml这个文件,是需要下载一份,修改后放到什么地方吗,这一点不太明白.
提前感谢!

**Comment by zhaojun1998** [comment]
@anduinnn 

docker 本身不是支持映射对外的端口吗

```
docker run   -p 8096:8096  ...
```

`-p` 后面左侧的是映射到宿主机的端口，右侧的是容器内的端口

**Comment by anduinnn** [comment]
非常感谢秒回:
如果我想通过服务器的 8091端口 是这样写的嘛?
docker run -d --name=zfile --restart=always -p 8080:8091 -v /root/zfile/db:/root/.zfile/db -v /root/zfile/logs:/root/.zfile/logs zhaojun1998/zfile

**Comment by zhaojun1998** [comment]
反了，左侧是宿主机端口。右侧才是容器内端口，所以应该是：

```
docker run -d --name=zfile --restart=always -p 8091:8080 -v /root/zfile/db:/root/.zfile/db -v /root/zfile/logs:/root/.zfile/logs zhaojun1998/zfile
```
