### ISSUE TITLE
请问某种文件类型想要隐藏不显示,具体在哪里可以改动

### ISSUE THREAD

**Issue by lee29** [zfile-dev/zfile#377]
RT

**Comment by zhaojun1998** [comment]
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/35387985/177266132-b99627cd-0dbb-4daf-a6b7-5048043c46f4.png">

<img width="979" alt="image" src="https://user-images.githubusercontent.com/35387985/177266207-1ee7eade-f4ff-41c3-8445-74e530b6cbe3.png">

**Comment by lee29** [comment]
thanks
