### ISSUE TITLE
后台添加存储桶 onedrive获取令牌的地址是不是错误的？

### ISSUE THREAD

**Issue by imrelax** [zfile-dev/zfile#380]
后台添加 onedrive的存储桶的时候 获取令牌。
然后后台有个快速获取令牌的那个地址。
但是点击是会提示错误的？ 是什么原因。

**Comment by zhaojun1998** [comment]
@imrelax 
指的是这个吗，点击后报什么错，麻烦贴个图或复制错误信息

<img width="941" alt="image" src="https://user-images.githubusercontent.com/35387985/178410963-ebbe9d55-0277-4032-98fd-a84cc0b9cec6.png">

**Comment by imrelax** [comment]
是的
![cw1](https://user-images.githubusercontent.com/33931868/178411289-f6fc8e44-fa0c-434f-b348-602aee886af1.png)

**Comment by zhaojun1998** [comment]
你这不是获取令牌报错呀，是获取令牌成功，保存也成功，但首页文件显示不了。

去后台找到这个，看看上次刷新令牌的时间和是否成功，如果不成功，提供错误信息。还有请提供 onedrive 的版本，国际版还是世纪互联。

<img width="352" alt="image" src="https://user-images.githubusercontent.com/35387985/178412515-6ad04db6-b87f-48fa-8d38-ee5d180e72c6.png">

**Comment by imrelax** [comment]
国际版。
我通过https://docs.zfile.vip/#/example?id=onedrive 这里获取令牌是OK的
![55](https://user-images.githubusercontent.com/33931868/178412843-4f2c0e36-d393-4a8a-be8f-9ca5c7be51a6.png)
而且也添加成功！
![ct3](https://user-images.githubusercontent.com/33931868/178412870-3d20b0da-1eb6-4ec8-b497-e6a159232cb4.png)

**Comment by zhaojun1998** [comment]
那能提供下 onedrive 的账号类型么，或者购买渠道，如教育版，A1,A3,E3,E5 等各种版本，我来测试两个链接获取到的令牌有什么不同。

还有麻烦提供下后台的日志下载，我看日志来排查问题。可发送到我邮箱 (因 github issue 留邮箱会被 * 号，故放在下图).
<img width="145" alt="image" src="https://user-images.githubusercontent.com/35387985/178413713-ea84588f-c866-401e-a51a-02576324bafe.png">

**Comment by imrelax** [comment]
好的。 已发送！

**Comment by zhaojun1998** [comment]
@imrelax 

更新最新版后再试试，从网站获取令牌，然后保存，看看文件是否能正常展示和下载

**Comment by imrelax** [comment]
已经升级到 4.02 并没有解决。
我现在的问题只是后台这里直接获取 不到。我通过https://docs.zfile.vip/#/example?id=onedrive 这里获取令牌是OK的。而且是正常的。，可以下载。 可以获取到。 
![11111](https://user-images.githubusercontent.com/33931868/178669966-6c5159b0-e3fe-47eb-ad78-7c0316d98f98.png)

**Comment by zhaojun1998** [comment]
@imrelax 

可以提供下错误的访问令牌和刷新令牌吗，我测试下。或者提供下当时的购买驱动我去购买一个，可发我邮箱。
