### ISSUE TITLE
登录状态下文件操作框显示不正常

### ISSUE THREAD

**Issue by yaoxinghuo** [zfile-dev/zfile#382]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/69723/178490429-35ed2e64-07a9-4609-90ec-ac15453c3aa5.png">
如果文件操作框里面的按钮不能全部显示（应该要显示出删除、重命令、移动这几个）在那排能显示的按钮下面一点点地方，用鼠标划过去才能显示出来。使用的是docker环境搭建的，版本4.0.2

**Comment by zhaojun1998** [comment]
收到。明天解决。



---原始邮件---
发件人: "Terry ***@***.***&gt;
发送时间: 2022年7月12日(周二) 晚上8:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 登录状态下文件操作框显示不正常 (Issue #382)




 

 如果文件操作框里面的按钮不能全部显示（应该要显示出删除、重命令、移动这几个）在那排能显示的按钮下面一点点地方，用鼠标划过去才能显示出来。

**Comment by yaoxinghuo** [comment]
给力，已解决！
