### ISSUE TITLE
feat:  关于界面调整的一些小建议

### ISSUE THREAD

**Issue by imrelax** [zfile-dev/zfile#384]
![rz1](https://user-images.githubusercontent.com/33931868/178654566-4953f7de-985b-42bc-b790-ff5f29fc9fc2.png)
1、这个日志下载。对于我们正常网站来说真的用不着吧？ 说实话我真的不会经常性的去点击这个日志下载下来去看内容。这个对于问题分析才有用的吧。所以 我建议把它挪到其他二级菜单里面去。因为这个地方已经被我无数次的误点了。我觉得这个功能完全可以挪到二级菜单里面，对于有需求的时候去二级菜单。比如基本设置或者哪里去下载。

2、 我没看到后台哪里直接显示版本号！ 我这人喜欢追新。但是我似乎没找到哪里看版本号？是否考虑哪个位置显示下。

**Comment by zhaojun1998** [comment]
1. 为啥会误点那里呢，是想点击直链管理点错了吗？这个功能一直都是在这个位置，突然修改怕有人找不到.
2. 现在 F12 能看到，下版本会在后台 logo 处悬浮上去显示当前版本号.

**Comment by zhaojun1998** [comment]
长时间无回复，关闭 issue
