### ISSUE TITLE
手机上管理员登录后的页面没有导航条

### ISSUE THREAD

**Issue by yaoxinghuo** [zfile-dev/zfile#386]
谢谢作者开发这么好用的软件！有个小问题，手机上管理员登录后的页面，没有最上面的那个导航条(就是有logo 菜单 头像的那一条)，需要再刷新下才会出现。用的版本是docker的4.0.3
![Screenshot_20220714-084449_Chrome](https://user-images.githubusercontent.com/69723/178861455-5737116e-0f5e-45a1-84c6-85136d4e5439.jpg)

**Comment by zhaojun1998** [comment]
我刚测试了下，我这没问题，可能是您手机浏览器的问题，尝试换个浏览器呢。

然后您提供下手机型号，屏幕尺寸，浏览器名称和版本号，我找条件去看看能不能复现

**Comment by yaoxinghuo** [comment]
确实我手机问题，我试了下其他手机，没有这个问题，我的三星S10就有问题（分辨率FHD+: 2280×1080 WQHD+ / 3040×1440，Chrome、三星自带浏览器也一样的问题）用电脑版本Chrome模拟多种手机的分辨率均无法复现这个问题，很可能是个别现象，如果后面有其他用户提出这个问题，再看看吧。

**Comment by zhaojun1998** [comment]
那先关闭 issue 了
