### ISSUE TITLE
连接了OSS,预览视频的时候出现跨域错误,预览文件或图片正常预览

### ISSUE THREAD

**Issue by anduinnn** [zfile-dev/zfile#387]
使用自带的视频播放器,出现了四次重新连接,都失败后 提示加载失败
---
使用本地播放器可以播放
[错误图片](http://114.115.241.242:8091/s/xsnp7r)
---

**Comment by zhaojun1998** [comment]
不确定到底是跨域问题还是视频格式问题。

浏览器只能解码 H.264 编码的视频，或 FLV 格式的视频，如浏览器无法播放，通过下发工具类调用本地播放器可以播放，那大概率就是视频编码问题。

如果您觉得是跨域问题，请贴上跨域的错误图片，之前附的图都是打不开的

**Comment by anduinnn** [comment]
我重新编辑了一下图片
[错误图片](https://zfile-ohiyou.oss-cn-hangzhou.aliyuncs.com/shijian.png)
在没升级4.0的时候视频是可以正常在线播放的,感觉是跨域问题 请求oss的是https的,我部署的服务器是http+ip+端口的

**Comment by zhaojun1998** [comment]
如果是跨域问题，不可能 3.x 行，4.x 不行，你确定是同一个视频文件么。

还有跨域设置在阿里云控制台，您可以修改这里。

<img width="940" alt="image" src="https://user-images.githubusercontent.com/35387985/178958307-3fb983b9-6b4a-4cf3-a03b-e38bd3d9e3a8.png">

**Comment by anduinnn** [comment]
刚才配置了oss里的跨域,解决了问题

非常感谢
