### ISSUE TITLE
上传功能

### ISSUE THREAD

**Issue by summer-6121** [zfile-dev/zfile#388]
拉了最新代码，找了半天没发现哪有上传功能，本来就是要做上传的，只是选择的存储位置不一样而已，没有上传就感觉功能用不了了

**Comment by summer-6121** [comment]
好奇怪啊，刚刚刷新了好多次页面 都没有展示出来，现在突然有了

**Comment by zhaojun1998** [comment]
之前版本有点问题，你看看你是不是 4.0.4 版本，如果是，则看看这个设置，是不是没有开启匿名操作，然后换了个浏览器登陆失效了，自然就不显示了

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/35387985/179144708-a6719956-6588-4a06-bf53-1b53e00c7f42.png">

**Comment by summer-6121** [comment]
我刚看了，是4.0.3版本，没有上传我觉得是因为没有 启用文件操作，现在开了就可以上传
另外问一下，前端页面和后端分离的要怎么搞    我是通过后端启动，然后输端口号进去的
