### ISSUE TITLE
界面乱码

### ISSUE THREAD

**Issue by fcwys** [zfile-dev/zfile#39]
如图：
尝试切换编码无效
![image](https://user-images.githubusercontent.com/28641034/74581238-1580f000-4fe8-11ea-9151-8c4b3eb0535b.png)
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by zhaojun1998** [comment]
@fcwys 你是 windows 下部署的嘛

**Comment by fcwys** [comment]
是的

**Comment by zhaojun1998** [comment]
@fcwys  第一次启动是不是没加 `-Dfile.encoding=utf-8`

**Comment by fcwys** [comment]
嗯，我再看下，谢谢了
