### ISSUE TITLE
feat: 添加Office预览和编辑

### ISSUE THREAD

**Issue by gtwxxh666** [zfile-dev/zfile#391]
有时候身边没设备，只有手机。
想要编辑office文件，还要下载下来，很麻烦。
建议添加添加Office预览和编辑

**Comment by zhaojun1998** [comment]
@gtwxxh666 

有这个计划，但现在还没有比较好的方案，一般解析能力强的服务都是收费的，其他的都会有诸多问题。

**Comment by nxliubo** [comment]
大佬好！能不能自己使用搭建的开源OnlyOffice环境，通过API实现呢？用公有服务器总是不放心。

**Comment by zhaojun1998** [comment]
@nxliubo 

目前最新版是支持了对接 onlyoffice 服务来实现预览。
