### ISSUE TITLE
文件列表 长度 问题

### ISSUE THREAD

**Issue by imrelax** [zfile-dev/zfile#393]
目前的文件长度 貌似是 固定长度。 并不是根据文件数量自动 缩长缩短的。
所以我现在 发现个问题。
我在后台设置 目录文档 并在底端显示之后 就算当前文件比较少。 
依然需要滚动到最底部才会看得到这个通知。
所以 为了保证这个文档所有人都看得到 我只能选择 置顶显示。
建议修改成。当文件较少时。自动缩减页面高度。  设置文件列表最高高度。这样子文件内容较多的时候 右侧出现滚动条滚动。

**Comment by zhaojun1998** [comment]
收到，非常感谢您的反馈。一周内会修复此问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月17日(周日) 下午4:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 文件列表 长度 问题 (Issue #393)




 
目前的文件长度 貌似是 固定长度。 并不是根据文件数量自动 缩长缩短的。
 所以我现在 发现个问题。
 我在后台设置 目录文档 并在底端显示之后 就算当前文件比较少。
 依然需要滚动到最底部才会看得到这个通知。
 所以 为了保证这个文档所有人都看得到 我只能选择 置顶显示。
 建议修改成。当文件较少时。自动缩减页面高度。  设置文件列表最高高度。这样子文件内容较多的时候 右侧出现滚动条滚动。

**Comment by zhaojun1998** [comment]
@imrelax 

已发布 4.0.7 版本修复了此问题
