### ISSUE TITLE
设置了密码的路径，开启匿名文件操作，不输入密码也可以上传文件/创建文件夹，请问下是否预期？

### ISSUE THREAD

**Issue by twursc** [zfile-dev/zfile#394]
如题

**Comment by zhaojun1998** [comment]
目前是这个结果。可设置仅管理员操作即可。
后面版本也会检验上传，删除，新建文件夹所在文件夹的密码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月18日(周一) 凌晨1:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 设置了密码的路径，不输入密码也可以上传文件/创建文件夹，请问下是否预期？ (Issue #394)




 
如题

**Comment by zhaojun1998** [comment]
新版本已对文件操作进行校验文件夹密码
