### ISSUE TITLE
初始化异常, 错误信息为: 404 Not Found

### ISSUE THREAD

**Issue by sjzbim** [zfile-dev/zfile#397]
您好，今天再添加Onedrive时，出现错误，之前已经添加了3个，都没问题，错误如下：
初始化异常, 错误信息为: 404 Not Found: "{"error":{"code":"itemNotFound","message":"The resource could not be found.","innerError":{"date":"2022-07-24T00:12:06","request-id":"9f51c556-fdba-493a-849e-e4d5289b19ff","client-request-id":"9f51c556-fdba-493a-849e-e4d5289b19ff"}}}"

**Comment by zhaojun1998** [comment]
这个就是字面意思，你应该是写了基路径，但是基路径不存在。


也可能是令牌串了，复制错了，导致你以为是d账号的基路径，其实令牌还是c账号。



---原始邮件---
发件人: "Allan ***@***.***&gt;
发送时间: 2022年7月24日(周日) 上午8:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 初始化异常, 错误信息为: 404 Not Found (Issue #397)




 
您好，今天再添加Onedrive时，出现错误，之前已经添加了3个，都没问题，错误如下：
 初始化异常, 错误信息为: 404 Not Found: "{"error":{"code":"itemNotFound","message":"The resource could not be found.","innerError":{"date":"2022-07-24T00:12:06","request-id":"9f51c556-fdba-493a-849e-e4d5289b19ff","client-request-id":"9f51c556-fdba-493a-849e-e4d5289b19ff"}}}"

**Comment by sjzbim** [comment]
您好，令牌应该没错，也用无痕模式试过了；路径的问题，我再试试，谢谢您

**Comment by zhaojun1998** [comment]
所以你是写基路径了吧。你写的是什么。


或者你先不写基路径保存看看可以不。如果可以去前台看看文件，到底有没有那个文件夹。



---原始邮件---
发件人: "Allan ***@***.***&gt;
发送时间: 2022年7月24日(周日) 上午8:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 初始化异常, 错误信息为: 404 Not Found (Issue #397)




 
您好，令牌应该没错，也用无痕模式试过了；路径的问题，我再试试，谢谢您

**Comment by sjzbim** [comment]
厉害👍，确实是基路径的问题，可能网盘里没有指定文件夹…去掉基路径，解决了……谢谢您！

**Comment by zhaojun1998** [comment]
那关闭问题了。

**Comment by sjzbim** [comment]
谢谢

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
