### ISSUE TITLE
20220724今天用docker compose安装zfile,拉取的镜像为latese.为什么镜像是3.2版本的?不是4.05

### ISSUE THREAD

**Issue by vyv2000** [zfile-dev/zfile#398]
今天用docker compose安装zfile,为什么镜像是3.2版本的，前几天用arm机器安装的都是4.05版本，一直没想明白

**Comment by zhaojun1998** [comment]
Docker pull 一次后，如果不删除镜像，是不会去重新拉取的。你可以直接拉取 zhaojun1998/zfile:4.0.5&nbsp; 或&nbsp; docker rmi zhaojun1998/zfile:latest 删除后，重新拉取 latest 即可。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月24日(周日) 下午5:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 20220724今天用docker compose安装zfile,拉取的镜像为latese.为什么镜像是3.2版本的?不是4.05 (Issue #398)




 
今天用docker compose安装zfile,为什么镜像是3.2版本的，前几天用arm机器安装的都是4.05版本，一直没想明白

**Comment by vyv2000** [comment]
还是没有成功，zhaojun1998/zfile:latest明明是删了的，版本3.2，9 Month ago,怎么拉都是3.2版本，然后我这边用docker pull zhaojun1998/zfile:4.0.5&nbsp; ,结果找不到镜像，docker-compose.yml
version: '3.3'
services:
  zfile:
    image:  zhaojun1998/zfile:4.0.5&nbsp; 
    container_name: zfile
    ports:
      - '8080:8080'
    volumes:
      - './db:/root/.zfile-v4/db'      # 数据库映射到当前文件夹下的db目录
      - './logs:/root/.zfile-v4/logs'  # 日志文件映射到当前文件夹下的logs目录
      - '/root/data/zfdata:/root/.zfile-v4/data'  # 额外映射了一个data目录，等下本地存储我们就可以填/root/.zfile-v4/data目录啦
    restart: always

找不到镜像

**Comment by vyv2000** [comment]
难道是我这边dock镜像源不对？开始是阿里云的源，后来换成默认，还是不行，真是奇怪了

**Comment by vyv2000** [comment]
dock-compose  拉zhaojun1998/zfile:4.0.5&nbsp; ，或zhaojun1998/zfile:4.0.5&nbsp;  没成功

**Comment by vyv2000** [comment]
root@Ubuntu20:~/data/docker_data/zfile# docker pull zhaojun1998/zfile:4.0.5&nbsp;
[1] 3326

Command 'nbsp' not found, did you mean:

  command 'bsp' from deb glbsp (2.24-4)
  command 'bsp' from deb zdbsp (1.19+20181027+dfsg.1-2build1)

Try: apt install <deb name>

root@Ubuntu20:~/data/docker_data/zfile# Error response from daemon: manifest for zhaojun1998/zfile:4.0.5 not found: manifest unknown: manifest unknown

**Comment by zhaojun1998** [comment]
@vyv2000 

看起来是您的 docker 安装的有问题，或者镜像源的问题，阿里云之类的镜像源可能存在不同步的情况。

**Comment by zhaojun1998** [comment]
@vyv2000 

抱歉，我刚看了下，是没有推送 zhaojun1998/zfile:4.0.5 导致的，目前 zhaojun1998/zfile:latest 就是 4.0.5.

不过我刚已经重新推送了下，您再 pull 下试试。

**Comment by vyv2000** [comment]
前两天在外地。今天用另一个机器测试了一下  完全没问题 就是9天前的新版本。 但那个老版本的机器怎么拉都还是3.2版。查看了dock和docker-compose的版本都是对的，应该是镜像源的问题了。

**Comment by vyv2000** [comment]
更换了镜像源 成功拉取4.05新版
