### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by zhushiyang** [zfile-dev/zfile#399]
## 概述
会支持RABC权限管理吗？同时可以对接OpenLDAP

## 动机

网盘想开放给公司不同组的同事使用

## 详细解释

支本地用户权限分配与验证。也可以对接OpenLDAP进行用户验证

**Comment by zhaojun1998** [comment]
不会考虑，以后也永远不会支持多用户及 RBAC.

zfile 定位不是企业云盘，请使用专业的工具解决专业的事情。
