### ISSUE TITLE
Mac 10.15.2 Chrome79 特殊字符的文本文件预览有乱码

### ISSUE THREAD

**Issue by buginote** [zfile-dev/zfile#4]
Mac 10.15.2 Chrome79 特殊字符的文本文件预览有乱码
见附件图片

![Screen Shot 2020-01-04 at 00 38 27](https://user-images.githubusercontent.com/17897107/71735961-d9a42800-2e8a-11ea-99cc-7924811672f1.png)

**Comment by zhaojun1998** [comment]
@buginote 那是因为 DEMO 站的那个文件本身是 GBK 编码，程序只能解析所有 UTF-8 编码的文件内容。
