### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by fcwys** [zfile-dev/zfile#40]
1.文件下载增加验证（验证码或其他），防止恶意刷流量。
2.COS支持

**Comment by zhaojun1998** [comment]
@fcwys  
1. 第一个不会实现，想刷，总能刷的，防不住，你可以考虑加文件夹密码。
2. COS 支持，是指腾讯云 COS 么，现在是支持的。

**Comment by fcwys** [comment]
好的，谢谢！
