### ISSUE TITLE
本地存储-上传文件夹时，文件夹中的文件无法全部上传，只能上传一部分

### ISSUE THREAD

**Issue by zhushiyang** [zfile-dev/zfile#400]
bug反馈：本地储存，从浏览器上传文件夹时，文件夹中的文件貌似只能上传100多个，剩余的文件无法进行上传。是对上传的文件数有限制吗？

**Comment by zhaojun1998** [comment]
是不是上传不成功的都是超出50M的，而且你用了宝塔反向代理。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月28日(周四) 上午9:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 本地存储-上传文件夹时，文件中的文件无法全部上传，只能上传一部分 (Issue #400)




 
bug反馈：本地储存，从浏览器上传文件夹时，文件夹中的文件貌似只能上传100多个，剩余的文件无法进行上传。是对上传的文件数有限制吗？

**Comment by zhushiyang** [comment]
> 是不是上传不成功的都是超出50M的，而且你用了宝塔反向代理。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年7月28日(周四) 上午9:49 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [zhaojun1998/zfile] 本地存储-上传文件夹时，文件中的文件无法全部上传，只能上传一部分 (Issue #400) bug反馈：本地储存，从浏览器上传文件夹时，文件夹中的文件貌似只能上传100多个，剩余的文件无法进行上传。是对上传的文件数有限制吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

没有用宝塔，直接裸docker启动的。文件大小在8M左右，大概400+个文件

**Comment by zhaojun1998** [comment]
@zhushiyang 

没有限制上传数量的，您如何判断的没有上传完成和未上传完成。上传错误的有报错么

**Comment by turkeymap** [comment]
上传文件至一半，会自动停止。然后必须重新再次上传，还是会会自动停止。https://image.turkeymap.org/i/2022/07/31/a6aniv.webp

**Comment by zhaojun1998** [comment]
@turkeymap 

方便的话，麻烦向下面邮件发送下您的 zfile 地址，我去看看到底什么原因导致对

<img width="149" alt="image" src="https://user-images.githubusercontent.com/35387985/182005687-d614f3b2-89bc-4ded-9af0-70d698261383.png">

**Comment by zhushiyang** [comment]
> 
文件总共4个G，每个文件在8MB左右。以目录方式上传完成（我这里没有报错，显示的是上传成功）后，我在服务器上核对了下目录大小是800M，文件数在100+，还有很多没有上传。

**Comment by zhushiyang** [comment]
> @zhushiyang
> 
> 没有限制上传数量的，您如何判断的没有上传完成和未上传完成。上传错误的有报错么

> 
文件总共4个G，每个文件在8MB左右。以目录方式上传完成（我这里没有报错，显示的是上传成功）后，我在服务器上核对了下目录大小是800M，文件数在100+，还有很多没有上传。

**Comment by zhaojun1998** [comment]
@turkeymap 

目前看来可能是服务器性能问题。

有几个问题。
1. 本地存储是直接读取的本地硬盘，还是云硬盘，或者挂载的其他网络盘
2. 服务器配置是多少，几核心、几G 内存、带宽多大
3. 使用 HTTP2 试试，我看您网站是 HTTP3 的。

**Comment by zhaojun1998** [comment]
@zhushiyang 

可否提供 zfile 地址，我测试下。发送地址到我邮箱

![](https://user-images.githubusercontent.com/35387985/182005687-d614f3b2-89bc-4ded-9af0-70d698261383.png)

**Comment by zhaojun1998** [comment]
@turkeymap 

我知道为啥了，您用了宝塔的 nginx，他默认限制最大上传文件大小为 50M，需要修改下。

<img width="636" alt="image" src="https://user-images.githubusercontent.com/35387985/182982426-c6d11570-42e4-4a32-ba91-f7470ec181bd.png">

**Comment by zhushiyang** [comment]
> @zhushiyang
> 
> 可否提供 zfile 地址，我测试下。发送地址到我邮箱
> 
> ![](https://user-images.githubusercontent.com/35387985/182005687-d614f3b2-89bc-4ded-9af0-70d698261383.png)

公司内网搭建的，无法开放

**Comment by turkeymap** [comment]
*同一个服务器，File Browser <https://github.com/filebrowser/filebrowser> 则没有此问题。*


zhushiyang ***@***.***> 于2022年8月5日周五 06:14写道：

**Comment by zhaojun1998** [comment]
@turkeymap @zhushiyang 

更新了 4.0.9 版本，试试最新版本还有此问题吗

**Comment by zhushiyang** [comment]
> @turkeymap @zhushiyang
> 
> 更新了 4.0.9 版本，试试最新版本还有此问题吗

我在关注下

**Comment by turkeymap** [comment]
己经升级还是不行，也有可能是我的服务器配置问题。我会自我检查下。

zhushiyang ***@***.***> 于2022年8月12日周五 05:42写道：

**Comment by zhaojun1998** [comment]
@turkeymap 

上传页没有错误信息么，最新版本加入了上传错误信息提示的。
