### ISSUE TITLE
网站搬迁的问题

### ISSUE THREAD

**Issue by imrelax** [zfile-dev/zfile#401]
我停止了网站。然后将整个网站打包。搬迁到新的网站之后解压 再运行。网站数据全部没有了？

网站数据库存放在什么位置 要怎么搬迁？

**Comment by zhaojun1998** [comment]
Linux 的话 V4 版本数据库文件在 /root/.zfile/db 目录下。是一个隐藏文件夹。


如果是其他操作系统或ZFile版本。您说下操作系统或ZFile版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月28日(周四) 晚上7:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 网站搬迁的问题 (Issue #401)




 
我停止了网站。然后将整个网站打包。搬迁到新的网站之后解压 再运行。网站数据全部没有了？
 
网站数据库存放在什么位置 要怎么搬迁？

**Comment by imrelax** [comment]
找到了。搞定。
但是这个 设定不太方便。
建议: 要么后台直接导入导出一个数据库功能？
或者，干脆数据库就存放在目录里面 停止之后打包 解压 运行 完事！！方便

然后  是不是因为我用的是直接打包迁移。不是用的安装。现在访问会有这个错误？
![cuow](https://user-images.githubusercontent.com/33931868/181493068-7468a48a-4f4e-4973-ad87-e5f3c91a6a47.png)

**Comment by zhaojun1998** [comment]
历史版本一直是这样了。不好突然改。而且技术原因某些部署方式在启动前无法获取当前目录，也自然无法读取数据库了。


所以我在文档部署页开头就详细写了这个事。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月28日(周四) 晚上7:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 网站搬迁的问题 (Issue #401)




 
找到了。搞定。
 但是这个 设定不太方便。
 建议: 要么后台直接导入导出一个数据库功能？
 或者，干脆数据库就存放在目录里面 停止之后打包 解压 运行 完事！！方便
 
然后  是不是因为我用的是直接打包迁移。不是用的安装。现在访问会有这个错误？

**Comment by imrelax** [comment]
哦。。好吧！！！看后期慢慢的怎么调整下吧。因为确实这个list程序很多都是放在根目录。这个我以为也是。搞了半天发现没数据。。。。
 那把这个迁移 的问题 写到你们的 Zfile 文档里面去吧。
https://docs.zfile.vip/  我好想是没在这个 文档里面找到有关迁移的问题。也是找了好久没找到。才跑过来问的！！

https://dalao.im/archives/434.html

**Comment by zhaojun1998** [comment]
我会再完善文档的，让这个提示更显眼。


不过这个机制一时半会改不了啦，不然影响所有用户使用。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月28日(周四) 晚上7:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 网站搬迁的问题 (Issue #401)




 
哦。。好吧！！！看后期慢慢的怎么调整下吧。因为确实这个list程序很多都是放在根目录。这个我以为也是。搞了半天发现没数据。。。。
 那把这个迁移 的问题 写到你们的 Zfile 文档里面去吧。
 https://docs.zfile.vip/  我好想是没在这个 文档里面找到有关迁移的问题。也是找了好久没找到。才跑过来问的！！
