### ISSUE TITLE
列表没有更新，有什么办法强制更新？

### ISSUE THREAD

**Issue by imrelax** [zfile-dev/zfile#402]
onedrive的 。。发现没有自动更新列表。
修改新增的文件夹没出现。删除的 倒是没有了。
新增的文件夹虽然没出现。但是你输入路径访问 是可以访问的！ 有什么办法强制更新下列表？
新增文件夹超过10分钟了！

**Comment by imrelax** [comment]
而且我发现。我后面继续新增。都可以出来。就只是那个文件夹不出来。奇怪？！

**Comment by zhaojun1998** [comment]
什么存储类型，什么情况下出现的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月28日(周四) 晚上8:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [zhaojun1998/zfile] 列表没有更新，有什么办法强制更新？ (Issue #402)




 
而且我发现。我后面继续新增。都可以出来。就只是那个文件夹不出来。奇怪？！

**Comment by imrelax** [comment]
onedrive
我用的自动同步。本地修改了文件夹列表 然后自动同步上去。我到onedrive里面看了 文件目录正确 文件也在。
而且 我直接在浏览器里面输入目录也可以访问。
但是列表里面不显示。其他文件夹又都有  我新增 也会出来  就那一个不出来。文件夹名称是中文名字 没有特殊字符

**Comment by zhaojun1998** [comment]
@imrelax 

有没有可能是你给存储源配置了过滤规则，给过滤掉了，没有显示出来。

**Comment by imrelax** [comment]
事实是 并没有 ！！
我都是文件夹全部直接显示。 没有设置 任何 关于文件夹的 过滤规则。
然后昨晚上我已经发QQ邮件给你了。 你看下收下！！

**Comment by zhaojun1998** [comment]
我知道了，因为他是最后一个，被底部那个备案信息栏挡住了，导致没显示出来，这个也会这两天解决。

**Comment by imrelax** [comment]
额。。。。。 好吧！！！
