### ISSUE TITLE
切换到 画廊时 双击图片并不会有反应

### ISSUE THREAD

**Issue by imrelax** [zfile-dev/zfile#405]
4.0.6的版本
切换到画廊之后。双击图片。 图片不会有效果。 不会弹出？
这个地方我觉得应该改进下。 即便是在画廊情况下。双击图片应该要弹出！

**Comment by zhaojun1998** [comment]
@imrelax 

这个是 bug，今天会发布 4.0.7 解决此问题

**Comment by imrelax** [comment]
OK !!!! 期待！！！
