### ISSUE TITLE
feat: 弹出图片应该增加 上下按钮

### ISSUE THREAD

**Issue by imrelax** [zfile-dev/zfile#406]
4.0.6的版本，
目前 图片在弹出来之后。
这个图片 只有滚动放大缩小效果。 没有其他效果。 
建议增强。 
至少应该增加如翻页。翻页的话 应该是可以用鼠标左右两边有翻页按钮。 
然后应该支持键盘操作。 键盘可以 左右 翻页。

**Comment by zhaojun1998** [comment]
@imrelax 

目前有这个功能的，不过默认没开启，下版本会改为默认开启。

<img width="473" alt="image" src="https://user-images.githubusercontent.com/35387985/181720413-c0efcf29-9785-40b0-b5d9-90d485c841a3.png">


<img width="593" alt="image" src="https://user-images.githubusercontent.com/35387985/181720464-b906d9c7-f416-4347-8822-546fedadd4d3.png">


<img width="1481" alt="image" src="https://user-images.githubusercontent.com/35387985/181720508-d72f97e0-e62a-498d-bd06-48d071bca12c.png">

**Comment by imrelax** [comment]
默认没开启。。那就是要访客自己开启咯？ 客户如果不知道这个功能的话，那就是相当于没这个功能了。。
这个 要不考虑后台 做功能。 我全站默认开启？
因为我 站 图片比较多。  下载的人要先网上看看 确定之后再下载。所以这个功能我还是蛮需要的？

**Comment by zhaojun1998** [comment]
下版本会改为默认开启此功能

**Comment by imrelax** [comment]
OK。。期待！！！
