### ISSUE TITLE
feat:  能否考虑增加 文件夹的 缩略图功能

### ISSUE THREAD

**Issue by imrelax** [zfile-dev/zfile#407]
目前的情况是。如果文件夹里面全部是图片， 进入之后 打开画廊是可以显示图片的。
但是如果是里面包含了文件夹，是不会不会显示 缩略图的，

所以 我的建议是。能否也支持 文件夹的 缩略图显示呢？。

![cdt](https://user-images.githubusercontent.com/33931868/181719115-677df707-3d0b-4ee8-a6c1-74fe6c3e2b59.png)

**Comment by zhaojun1998** [comment]
@imrelax 

有计划支持，但不是主要功能，不确定什么时候能做完。

**Comment by imrelax** [comment]
好吧。。期待。。。。
