### ISSUE TITLE
是否有开发指导

### ISSUE THREAD

**Issue by wswm152** [zfile-dev/zfile#408]
我想修改项目源码，以验证代码是否可用
现在使用idea从github上clone了一份源码
但是不知道如何运行代码，是否有简易的教程或流程指导该如何快速复现项目为可执行程序

**Comment by zhaojun1998** [comment]
就是标准 springboot 程序，默认情况下不需要配置数据库。
默认端口为 8080，依赖jdk版本为1.8



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月29日(周五) 晚上9:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaojun1998/zfile] 是否有开发指导 (Issue #408)




 
我想修改项目源码，以验证代码是否可用
 现在使用idea从github上clone了一份源码
 但是不知道如何运行代码，是否有简易的教程或流程指导该如何快速复现项目为可执行程序

**Comment by wswm152** [comment]
你可能高估了我的水平，我连怎么编译和打包都不会

**Comment by wswm152** [comment]
好了我搞明白了（其实啥也不会）
