### ISSUE TITLE
为项目添加了ipfs支持，请对代码进行审核

### ISSUE THREAD

**Issue by wswm152** [zfile-dev/zfile#411]
已实现对ipfs的支持
代码库 https://github.com/wswm152/zfile
只经过简单测试，测试是不完备的，例如有关文件流功能测试不到位
本人对java开发较不熟悉，第一次接触maven及springboot，编码可能不规范或有错漏
功能是依照本地存储方式的来实现，可视为对相关类的重写

请在方便时对代码进行测试，并提出指导意见
我将在修复bug及测试完成后提交pr

感谢

**Comment by zhaojun1998** [comment]
@wswm152 

最近没时间处理这个，最晚周末处理.

**Comment by wswm152** [comment]
> @wswm152
> 
> 最近没时间处理这个，最晚周末处理.

好滴，不着急，我先试试ZFile的API
上传文件测不到不知道怎么回事

**Comment by wswm152** [comment]
请在前端库的 https://github.com/zfile-dev/zfile-vue/blob/590fc1629da94e45f9ecb9e9530226aa4d6690ca/src/composables/file/useFileUpload.js#L399 添加类型 'ipfs'
同时请为ipfs类添加logo，若存在其他需要添加的内容也麻烦，添加一下

我对vue不熟悉，无法重新编译部署该文件，如有可能请添加简略的教程（软件，环境依赖，步骤等）

我在本仓库中的对应文件中手动添加该类型后，大部分功能已经能通过测试
该文件我提交到fork的库中，保持github文件与我本地同步

**Comment by wswm152** [comment]
滴滴

**Comment by zhaojun1998** [comment]
@wswm152 

我了解了下 ipfs，并查看了下代码，目前来看 ipfs 的 java sdk 的支持还是不太乐观的，稳定性也不可保证，恐怕暂时无法添加 ipfs  到 zfile 中了，需要使用的话，您可以自行 fork 修改后编译使用。

**Comment by wswm152** [comment]
收到，感谢

> @wswm152
> 
> 我了解了下 ipfs，并查看了下代码，目前来看 ipfs 的 java sdk 的支持还是不太乐观的，稳定性也不可保证，恐怕暂时无法添加 ipfs 到 zfile 中了，需要使用的话，您可以自行 fork 修改后编译使用。
收到，感谢
