### ISSUE TITLE
全局搜索功能

### ISSUE THREAD

**Issue by wangwujie007** [zfile-dev/zfile#412]
无全局搜索功能

**Comment by zhaojun1998** [comment]
全局搜索功能为捐赠版所有


详见 https://www.zfile.vip/pricing



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月3日(周三) 下午3:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 全局搜索功能 (Issue #412)




 
无全局搜索功能
