### ISSUE TITLE
feat: 是否可以让URL不是/1/main而是自定义

### ISSUE THREAD

**Issue by haoduck** [zfile-dev/zfile#413]
## 概述

程序默认的URL是/1/main，多个盘是是/2/main。。。。
能否将这个变为可自定义设置的值呢？

例如：
我可以将其设置为
/music/*
/video/*
而不是默认的
/1/main/*
/2/main/*

**Comment by zhaojun1998** [comment]
@haoduck 

4.x 版本是有这个功能的，可以为存储源设置别名，以替代默认的数字 id

**Comment by haoduck** [comment]
> @haoduck
> 
> 4.x 版本是有这个功能的，可以为存储源设置别名，以替代默认的数字 id

好的，我更新看看，谢谢您
