### ISSUE TITLE
画廊模式在oppo安卓webview框架中图片比例不对,[图片列数]=1才正常,列数数字越大,图片比例越长.ios的没有测试..

### ISSUE THREAD

**Issue by lee29** [zfile-dev/zfile#415]
默认只有设置 [图片列数]=1才正常

![Screenshot_2022-08-05-18-09-46-94_e39d2c7de19156b0683cd93e8735f348](https://user-images.githubusercontent.com/9483929/183056816-0f38d3f3-1380-42fa-a093-79da6e3862e3.jpg)

- 是否已搜索其他 issue，没有人提过这个问题？：no
- 当前 ZFile 版本：4.0.8
- 是否尝试最新版是否已解决此问题：
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：安卓
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：微信内置浏览器&X 浏览器&oppo浏览器 都有这个问题

**Comment by zhaojun1998** [comment]
没明白您指的框架比例是什么意思。没看出来哪里不正常。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月5日(周五) 晚上6:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 画廊模式在微信浏览器安卓框架比例不对,ios的没有测试.. (Issue #415)




 
默认只有设置 [图片列数]=1才正常
 

  
是否已搜索其他 issue，没有人提过这个问题？：no 

当前 ZFile 版本：4.0.8 

是否尝试最新版是否已解决此问题： 

是否尝试重启 ZFile，且问题依旧存在？：是 

是否已尝试清空浏览器缓存，且问题依旧存在？：是 

操作系统（如 Windows、Mac、iOS、安卓）：安卓 

浏览器（如 Chrome、Firefox、Safari，X 浏览器）：X 浏览器&amp;oppo浏览器 都有这个问题

**Comment by lee29** [comment]
> 

图片比例不对,原图图片都是16:9的,[图片列数]=1才正常,列数数字越大,图片比例越长

**Comment by lee29** [comment]
> 没明白您指的框架比例是什么意思。没看出来哪里不正常。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年8月5日(周五) 晚上6:17 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [zfile-dev/zfile] 画廊模式在微信浏览器安卓框架比例不对,ios的没有测试.. (Issue #415) 默认只有设置 [图片列数]=1才正常 是否已搜索其他 issue，没有人提过这个问题？：no 当前 ZFile 版本：4.0.8 是否尝试最新版是否已解决此问题： 是否尝试重启 ZFile，且问题依旧存在？：是 是否已尝试清空浏览器缓存，且问题依旧存在？：是 操作系统（如 Windows、Mac、iOS、安卓）：安卓 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：X 浏览器&amp;oppo浏览器 都有这个问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

框架是指webview框架

**Comment by lee29** [comment]
![image](https://user-images.githubusercontent.com/9483929/183075330-a289a127-2b4c-4657-a534-80f2d0628b38.png)
不止安卓端,电脑端F12控制台模拟也是一样的结果

**Comment by zhaojun1998** [comment]
@lee29 

已验证，是一个 BUG，可以临时通过以下自定义 css 解决：

```css
.zfile-gallery-body .zfile-img-col .zfile-gallery-img {min-height:unset !important;}
```

**Comment by lee29** [comment]
> @lee29
> 
> 已验证，是一个 BUG，可以临时通过以下自定义 css 解决：
> 
> ```css
> .zfile-gallery-body .zfile-img-col .zfile-gallery-img {min-height:unset !important;}
> ```

good job!!!!!!!!
另外请问一哈,移动端和pc端能不能分别指定默认显示的[图片列数]数字

**Comment by zhaojun1998** [comment]
这个暂时没有相关选项，实在需要可以自行编译前端文件进行修改，代码位置在：

https://github.dev/zfile-dev/zfile-vue/blob/4.0.0/src/composables/header/useSetting.js#L11

**Comment by lee29** [comment]
> 这个暂时没有相关选项，实在需要可以自行编译前端文件进行修改，代码位置在：
> 
> https://github.dev/zfile-dev/zfile-vue/blob/4.0.0/src/composables/header/useSetting.js#L11

只会少点的前端,不会java   :(

**Comment by lee29** [comment]
> 这个暂时没有相关选项，实在需要可以自行编译前端文件进行修改，代码位置在：
> 
> https://github.dev/zfile-dev/zfile-vue/blob/4.0.0/src/composables/header/useSetting.js#L11

修改 WEB-INF/classes/static/zfile.config.json可以实现么
`"gallery": {
		"column": 3,        //修改这里可以实现么?
		"columnSpacing": 50,
		"gutter": 50,
		"showInfo": true,
		"showInfoMode": "hover"
	},`

**Comment by zhaojun1998** [comment]
不行，后面我尝试放到这个配置中吧

**Comment by lee29** [comment]
> 

感谢大佬解惑~~mua~（づ￣3￣）づ╭❤～

**Comment by zhaojun1998** [comment]
@lee29 

最新版本已经修复了此功能，且支持修改  `WEB-INF/classes/static/zfile.config.json` 中的 `mobileColumn`(移动端默认列数) 和 `column` (pc 端默认列数)，注意测试时要清理浏览器缓存，如果缓存中设置过，不会读取默认值。

**Comment by lee29** [comment]
> 

good job
