### ISSUE TITLE
feat: 在画廊模式下，能否支持点击大图后，可以切换上一张、下一张图片

### ISSUE THREAD

**Issue by justhy** [zfile-dev/zfile#416]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：无人提过。
- 是否已尝试使用最新版本，且仍然没有此功能？：没有该功能。
- 功能概述：在画廊模式下，能否支持点击大图后，可以切换上一张、下一张图片
- 功能动机：这样可以方便在线看漫画。
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
最新版 4.0.8 是支持这个功能的啊。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月5日(周五) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] feat: 在画廊模式下，能否支持点击大图后，可以切换上一张、下一张图片 (Issue #416)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个功能？：无人提过。 

是否已尝试使用最新版本，且仍然没有此功能？：没有该功能。 

功能概述：在画廊模式下，能否支持点击大图后，可以切换上一张、下一张图片 

功能动机：这样可以方便在线看漫画。 

详细解释（可选）：

**Comment by justhy** [comment]
感谢，好像Docker 镜像没有更新4.0.8，重新拉取 latest 镜像后依然是4.0.7

**Comment by zhaojun1998** [comment]
@justhy 

1. 你得删除本地 latest 镜像，不然标签名一样，不会自动重新拉取
2. 如果你配置了 docker 镜像源，可能是镜像源的缓存
3. 可直接拉取指定版本如 zhaojun1998/zfile:4.0.8

**Comment by justhy** [comment]
好的十分感谢!

**Comment by justhy** [comment]
![Snipaste_2022-08-06_09-53-39](https://user-images.githubusercontent.com/17880968/183229045-64dc662c-f3b8-44bd-b275-c0c07ea494eb.png)
![Snipaste_2022-08-06_09-53-52](https://user-images.githubusercontent.com/17880968/183229047-e6b24c72-7740-49d0-ab4e-131d0856fc7b.png)
目前是4.0.8版本，查看大图模式下，没有可以直接切换下一张或上一张的按钮，按方向键也没作用。

**Comment by zhaojun1998** [comment]
可能是你的浏览器缓存，之前版本默认是预览单张，后面的版本才默认支持切换上一个下一个。可以清楚浏览器缓存后再试，或者进行如图设置：

<img width="312" alt="image" src="https://user-images.githubusercontent.com/35387985/183229223-1398ccd6-413a-4cb9-972b-7d1f4929572b.png">
<img width="496" alt="image" src="https://user-images.githubusercontent.com/35387985/183229226-5ecd83ff-39f6-4e3d-938f-0d19118700ca.png">

**Comment by justhy** [comment]
感谢大佬！！
