### ISSUE TITLE
存储源别名与短链接的冲突问题

### ISSUE THREAD

**Issue by Pandaft** [zfile-dev/zfile#417]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：是
- 当前 ZFile 版本：v4.0.8
- 是否尝试最新版是否已解决此问题：否
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：All
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：All
- 做什么操作提示的错误？：浏览链接
- 期望行为（应该是什么样的结果）：正常访问
- 当前行为（当前是什么样的结果）：{"code":500,"msg":"此直链不存在或已失效.","data":null,"dataCount":null}

当存储源的别名为 `s` 时会短链接的部分功能产生冲突。

例如别名为 `s` 的存储源里有个文件夹 `folder` ，在首页中打开该存储源，能正常进入所有文件夹，但是如果此时刷新，或者在任何浏览器浏览此时的链接（`https://站点/s/folder`）都会提示 `{"code":500,"msg":"此直链不存在或已失效.","data":null,"dataCount":null}
`，只能手动在首页依次进入。即使在直链中关闭 `是否允许使用短链` ，也不能解决该问题。

虽然可能很少人会给存储源别名设置为 s ，但这也算是个潜在的问题，个人推荐的解决方案是在新建/编辑存储源的别名时检测是不是 s ，如果是就提示警告（或者禁止设置为 s）；或者在设置中可以自定义短链接的前缀。

**Comment by zhaojun1998** [comment]
收到，会添加关键词限制的.

**Comment by zhaojun1998** [comment]
@Aixzk 

4.0.9 版本已经增加若干关键字检测修复此问题。
