### ISSUE TITLE
这个错误是什么原因引起的？

### ISSUE THREAD

**Issue by imrelax** [zfile-dev/zfile#418]
![](https://user-images.githubusercontent.com/33931868/183247342-61e283b5-67de-4c46-91b3-8d50bb78ce55.png)

登录后台 提示 这个错误。是什么引起的？ 4.08

**Comment by zhaojun1998** [comment]
jdk 版本正确么，是 1.8 吗，然后是否开启了登陆图片验证码，部署方式是什么，docker 还是 war 还是 jar
