### ISSUE TITLE
收费了呀

### ISSUE THREAD

**Issue by ghost** [zfile-dev/zfile#419]
MIT 不是为所欲为嘛
![image](https://user-images.githubusercontent.com/51149477/183296810-0e102eca-04c9-46bc-b66c-b5d8e2564d5c.png)

**Comment by zhaojun1998** [comment]
开源版 MIT 协议，所以可以随便用。&nbsp;&nbsp;


捐赠版闭源，不存在开源协议。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月7日(周日) 晚上10:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 收费了呀 (Issue #419)




 
MIT 不是为所欲为嘛
