### ISSUE TITLE
下个版本能否把标签中<html lang=en>改为<html>

### ISSUE THREAD

**Issue by D3CODING** [zfile-dev/zfile#42]
如果网页头部设置成`<html lang=en>`谷歌浏览器认为是英文网站，每次打开都会问是否要翻译网页。
如果可行，能否在下个版本中改为`<html>`，这样谷歌浏览器会按照网页自动识别语言，就不会一直提示翻译了。

**Comment by zhaojun1998** [comment]
@lichenzero 好的

**Comment by D3CODING** [comment]
如果只是简体中文，其实也可以用`<html lang="zh-CN">`或者最新标准写法`<html lang="zh-Hans-CN">`

**Comment by zhaojun1998** [comment]
@lichenzero 已更新版本
