### ISSUE TITLE
feat: 建议增加首页的文档功能，增强文档功能

### ISSUE THREAD

**Issue by haoduck** [zfile-dev/zfile#421]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：是
- 是否已尝试使用最新版本，且仍然没有此功能？：是
- 功能概述：增加首页文档的设置
- 功能动机：目前首页只支持设置公告，不能设置文档，建议增加这个功能，就像存储里文档的设置那样。
- 详细解释（可选）：
还有如果可以在全局设置里设置任意一个盘的路径可能会更方便管理一点，例如我添加了两个网盘，分别命名为music和video，我在全局设置里设置文档路径为```/music/*,/music/jay```或者```/video/*,/video/国语/*,/video/英语/*```就好，而不用点进存储管理里分别设置music和video两个盘的文档。就是优先匹配存储管理里的规则，再匹配全局的规则。

**Comment by zhaojun1998** [comment]
@haoduck 

理由并不是很充分。以你的举例来说，音乐盘和视频盘，通常来说文档描述是不一样的。如果是完全通用的，那公告完全可以解决这个问题。且功能和文档都支持md语法。为什么公告不能解决你的问题呢。

**Comment by haoduck** [comment]
公告只能在页面上方，如果写了比较长的内容，会把列表挤到很下面，公告的布局看起来不适合干文档的活

赵俊 ***@***.***> 于2022年8月11日周四 21:12写道：

**Comment by zhaojun1998** [comment]
理由并不是很充分。以你的举例来说，音乐盘和视频盘，通常来说文档描述是不一样的。如果是完全通用的，那公告完全可以解决这个问题。且功能和文档都支持md语法。为什么公告不能解决你的问题呢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月9日(周二) 晚上9:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] feat: 建议增加首页的文档功能，增强文档功能 (Issue #421)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个功能？：是 

是否已尝试使用最新版本，且仍然没有此功能？：是 

功能概述：增加首页文档的设置 

功能动机：目前首页只支持设置公告，不能设置文档，建议增加这个功能，就像存储里文档的设置那样。 

详细解释（可选）：
 还有如果可以在全局设置里设置任意一个盘的路径可能会更方便管理一点，例如我添加了两个网盘，分别命名为music和video，我在全局设置里设置文档路径为/music/,/music/jay或者/video/,/video/国语/*,/video/英语/*就好，而不用点进存储管理里分别设置music和video两个盘的文档。就是优先匹配存储管理里的规则，再匹配全局的规则。
