### ISSUE TITLE
升级到4.0.9后存储源无法刷新onedrive token

### ISSUE THREAD

**Issue by justhy** [zfile-dev/zfile#422]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
升级到4.0.9后存储源无法刷新onedrive token，无法正常使用。后有截图说明。
![Snipaste_2022-08-13_23-56-07](https://user-images.githubusercontent.com/17880968/184501673-0308a7f0-3c48-4940-b285-637e87897c0b.png)

- 是否已搜索其他 issue，没有人提过这个问题？：否
- 当前 ZFile 版本：4.0.9
- 是否尝试最新版是否已解决此问题：否
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：Windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome
- 做什么操作提示的错误？：看截图
- 期望行为（应该是什么样的结果）：正常刷新token
- 当前行为（当前是什么样的结果）：无法正常使用
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：

使用的是自定义api，按照要求修改了回调地址，并且api中已经配置回调地址。点击“前往获取令牌”后 ->

![Snipaste_2022-08-13_23-57-15](https://user-images.githubusercontent.com/17880968/184501766-4be083d3-c9cf-46d0-ad26-91b371eb8f50.png)

报错提示 “AADSTS90102: 'redirect_uri' value must be a valid absolute URI.”

![Snipaste_2022-08-13_23-57-30](https://user-images.githubusercontent.com/17880968/184501812-b3e2aa84-c887-444e-b748-7d18a188238f.png)

手动复制跳转链接查看，“redirect_uri”赋值为null，手动修改null为设置的回调地址，再次访问，无法获取 "accessToken (访问令牌)" 和 “refreshToken (刷新令牌)”。

![Snipaste_2022-08-14_00-00-35](https://user-images.githubusercontent.com/17880968/184501875-5a573881-383e-4ee4-9bb8-258421762fc0.png)

**Comment by zhaojun1998** [comment]
1.用默认的api可以获取成功么。
2.自定义api回调后的页面。是你自己配置的回调地址么。
3.还有就是清空浏览器缓存后再试试。这个也会影响。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月14日(周日) 凌晨0:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 升级到4.0.9后存储源无法刷新onedrive token (Issue #422)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
 升级到4.0.9后存储源无法刷新onedrive token，无法正常使用。后有截图说明。
 
  
是否已搜索其他 issue，没有人提过这个问题？：否 

当前 ZFile 版本：4.0.9 

是否尝试最新版是否已解决此问题：否 

是否尝试重启 ZFile，且问题依旧存在？：是 

是否已尝试清空浏览器缓存，且问题依旧存在？：是 

操作系统（如 Windows、Mac、iOS、安卓）：Windows 

浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome 

做什么操作提示的错误？：看截图 

期望行为（应该是什么样的结果）：正常刷新token 

当前行为（当前是什么样的结果）：无法正常使用 

错误日志（可选）： 

复现步骤（可选）： 

您的额外信息（可选）： 
 
使用的是自定义api，按照要求修改了回调地址，并且api中已经配置回调地址。点击“前往获取令牌”后 -&gt;
 

 
报错提示 “AADSTS90102: 'redirect_uri' value must be a valid absolute URI.”
 

 
手动复制跳转链接查看，“redirect_uri”赋值为null，手动修改null为设置的回调地址，再次访问，无法获取 "accessToken (访问令牌)" 和 “refreshToken (刷新令牌)”。

**Comment by justhy** [comment]
1.用默认的api可以获取成功么。
默认API可以成功获取。

2.自定义api回调后的页面。是你自己配置的回调地址么。
对的，因为它提示  “AADSTS90102: 'redirect_uri' value must be a valid absolute URI.”

3.还有就是清空浏览器缓存后再试试。
没有效果。

**Comment by justhy** [comment]
回退到4.0.8可以正常刷新、使用。

**Comment by zhaojun1998** [comment]
哪您之前是否修改过 zfile 配置文件中的 onedrive api 信息，如果修改过，在 4.0.9 是否保持了同样的设置

**Comment by zhaojun1998** [comment]
- 4.0.8 的时候，您一直使用的是自定义 api 还是默认 api
- 是升级到 4.0.9 才更换为自定义 api 的么，如果是，更换前刷新令牌是否正常
- 检查下 api 信息是否正确，你的自定义 api 是否在其他类似的程序中验证成功过，api 有没有过期，回调地址是否有空格或者特殊字符，参考其他人的此问题相关信息。https://stackoverflow.com/questions/57789550/how-to-fix-aadsts90102-redirect-uri-value-must-be-a-valid-absolute-uri-err

**Comment by zhaojun1998** [comment]
@justhy


我今天又完整测试了下，发现是有 bug，下个版本会修复此问题。

**Comment by zhaojun1998** [comment]
@justhy 

不对，我这演示是只有 SharePoint 才有问题，您这个明显情况还不太一样。还是麻烦回答下：


- 4.0.8 的时候，您一直使用的是自定义 api 还是默认 api
- 是升级到 4.0.9 才更换为自定义 api 的么，如果是，更换前刷新令牌是否正常
- 检查下 api 信息是否正确，你的自定义 api 是否在其他类似的程序中验证成功过，api 有没有过期，回调地址是否有空格或者特殊字符，参考其他人的此问题相关信息。https://stackoverflow.com/questions/57789550/how-to-fix-aadsts90102-redirect-uri-value-must-be-a-valid-absolute-uri-err

**Comment by justhy** [comment]
@zhaojun1998 

> * 4.0.8一直都用的自定义api，挂载的是sharepoint

> * 目前回退回4.0.8可以正常刷新令牌

> * 回调地址中有特殊字符，clientSecret 含有特殊字符

**Comment by zhaojun1998** [comment]
@justhy 

都是 SharePoint 国际版吗，还是世纪互联版本

**Comment by justhy** [comment]
@zhaojun1998 

都是 SharePoint 国际版

**Comment by zhaojun1998** [comment]
您 4.0.8 自定义 api 是修改的 `application-default.properties` 里的 api 信息么。
如果是，升级到 4.0.9 是否同步修改了此配置问题。

**Comment by justhy** [comment]
没有修改文件，是直接在添加存储源的时候填写的 api 信息

**Comment by zhaojun1998** [comment]
@justhy 

方便发送下 4.0.8 中 zfile 配置截图，还有您的自定义 api 信息：clientId（api  id），clientSecret（api 密钥），redirectUri（api 回调地址）,方便具体排查信息，因为我自己新建的一个自定义 api，并没有复现此问题。

到我的邮箱（Github 不能留邮箱，看截图吧）：
<img width="169" alt="image" src="https://user-images.githubusercontent.com/35387985/184564308-37f87007-3217-41cd-9bb8-42a355526ba8.png">

**Comment by justhy** [comment]
@zhaojun1998 

已发送邮件，请查收。

**Comment by zhaojun1998** [comment]
@justhy 

感谢配合，有结果会随时反馈

**Comment by zhaojun1998** [comment]
@justhy 

我知道为啥了，因为 4.0.8 版本对自定义 api 支持不完善，即使填写了自定义 clientId 和 clietnSecret 也会使用默认的。

所以，其实 4.0.8 使用的是官网 api 获取的令牌，但存储源保存的是自定义的值。
升级到 4.0.9 之后，可以读取存储源设置的自定义 api，但这时候实际使用的令牌其实是由默认 api 获取的，但尝试刷新令牌时，使用成了您自定义 api 去获取，onedrive api 检测到两个 api 不一致，就刷新令牌失败了。


解决办法就是重新保存下存储源，写上自定义 api 和回调地址就好了，在微软的 api 设置里，也要把您 zfile 的回调地址添加进去。
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/35387985/184573137-5baedc93-b52a-4c73-b688-7d828f5b590e.png">

**Comment by justhy** [comment]
@zhaojun1998 

目前就是自定义 api 和回调地址，微软的 api 里也设置了，点击前往获取刷新令牌就会报错，应该是需要更新版本的吧

报错提示 “AADSTS90102: 'redirect_uri' value must be a valid absolute URI.”

**Comment by zhaojun1998** [comment]
@justhy 

首先需要升级到 4.0.9，然后使用自定义 api 获取令牌。

另外回调地址，您写协议头了么，如需要写为 `https://zfile.jun6.net/onedrive/callback`，而不能写成 `zfile.jun6.net/onedrive/callback`，不然就会提示 `“AADSTS90102: 'redirect_uri' value must be a valid absolute URI.”`，如果您确定写的没问题，麻烦右键复制下这个链接的地址，我看看。

<img width="958" alt="image" src="https://user-images.githubusercontent.com/35387985/184579504-72effaf3-7e0c-45d5-93f5-0e8809872f52.png">

**Comment by zhaojun1998** [comment]
@justhy 

十分抱歉，我已经确定问题了，是部分 api 密钥中包含特殊字符 `#` 导致解析异常导致的，我的好几个 api key 都没有这种特殊字符，所以我没发现这个问题，今天会发布新版本修复此问题。

**Comment by zhaojun1998** [comment]
@justhy 

已发布新版本 4.0.10，修复了此问题。

**Comment by justhy** [comment]
@zhaojun1998 

更新到4.0.10后，可以获取刷新令牌，但是是需要每个存储源都手动更新参数，我直接修改数据库无效，有方便更新源的方法吗？

**Comment by zhaojun1998** [comment]
如果都是一个od账号的话，修改数据库后重启即可。
如果不是同一个od账号，那就得一个一个重新获取了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月15日(周一) 晚上11:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 升级到4.0.9后存储源无法刷新onedrive token (Issue #422)




 
@zhaojun1998
 
更新到4.0.10后，可以获取刷新令牌，但是是需要每个存储源都手动更新参数，我直接修改数据库无效，有方便更新源的方法吗？

**Comment by justhy** [comment]
好的，感谢！
