### ISSUE TITLE
无法使用curl下载直链

### ISSUE THREAD

**Issue by Omoinemie** [zfile-dev/zfile#424]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
用curl 下载直链，不论是否开启签名，都无法下载，是个0KB的文件。
测试连接：curl http://tx.vomiku.com/zl/local/app/mipsle/npc > ~/npc

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

- 是否已搜索其他 issue，没有人提过这个问题？：
- 当前 ZFile 版本：
- 是否尝试最新版是否已解决此问题：
- 是否尝试重启 ZFile，且问题依旧存在？：
- 是否已尝试清空浏览器缓存，且问题依旧存在？：
- 操作系统（如 Windows、Mac、iOS、安卓）：
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：
- 做什么操作提示的错误？：
- 期望行为（应该是什么样的结果）：
- 当前行为（当前是什么样的结果）：
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
@Omoinemie 

这并不是 bug，而是 curl 默认不会响应重定向，需要增加 `-L` 才启用重定向才可以正常下载：

```bash
curl -L http://tx.vomiku.com/zl/local/app/mipsle/npc > ~/npc
```

**Comment by Omoinemie** [comment]
好的，谢谢
