### ISSUE TITLE
windows添加本地存储路径不识别

### ISSUE THREAD

**Issue by Omoinemie** [zfile-dev/zfile#426]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

这是绝对路径了，还是报错，也没有说明
![image](https://user-images.githubusercontent.com/31991443/184895785-c63c81bb-f5e2-49cd-abbc-be7cbf26ab81.png)

- 是否已搜索其他 issue，没有人提过这个问题？：
- 当前 ZFile 版本：
- 是否尝试最新版是否已解决此问题：
- 是否尝试重启 ZFile，且问题依旧存在？：
- 是否已尝试清空浏览器缓存，且问题依旧存在？：
- 操作系统（如 Windows、Mac、iOS、安卓）：
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：
- 做什么操作提示的错误？：
- 期望行为（应该是什么样的结果）：
- 当前行为（当前是什么样的结果）：
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
@Omoinemie 
java 版本是 1.8 么

**Comment by Omoinemie** [comment]
C:\Users\ilove>java -version
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)

**Comment by Omoinemie** [comment]
win11下不用加-Dfile.encoding=utf-8这个，不然会乱码

**Comment by zhaojun1998** [comment]
@Omoinemie 

目前 zfile 只支持到 jdk 1.8，windows 11 这个我会完善文档
