### ISSUE TITLE
首页视图

### ISSUE THREAD

**Issue by cxwya** [zfile-dev/zfile#427]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：否
- 当前 ZFile 版本：4.0.10
- 是否尝试最新版是否已解决此问题：否
- 是否尝试重启 ZFile，且问题依旧存在？：
- 是否已尝试清空浏览器缓存，且问题依旧存在？：
- 操作系统（如 Windows、Mac、iOS、安卓）：Windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome
- 做什么操作提示的错误？：
- 期望行为（应该是什么样的结果）：视图选择大时，不会出现省略号
- 当前行为（当前是什么样的结果）：视图选择大时，出现省略号
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
什么操作系统，系统有没有开缩放，开了的话是多少。屏幕尺寸和分辨率多大。浏览器有没有开缩放。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月17日(周三) 上午9:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 首页视图 (Issue #427)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个问题？：否 

当前 ZFile 版本：4.0.10 

是否尝试最新版是否已解决此问题：否 

是否尝试重启 ZFile，且问题依旧存在？： 

是否已尝试清空浏览器缓存，且问题依旧存在？： 

操作系统（如 Windows、Mac、iOS、安卓）：Windows 

浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome 

做什么操作提示的错误？： 

期望行为（应该是什么样的结果）：视图选择大时，不会出现省略号 

当前行为（当前是什么样的结果）：视图选择大时，出现省略号 

错误日志（可选）： 

复现步骤（可选）： 

您的额外信息（可选）：

**Comment by cxwya** [comment]
> 什么操作系统，系统有没有开缩放，开了的话是多少。屏幕尺寸和分辨率多大。浏览器有没有开缩放。
> [… ](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年8月17日(周三) 上午9:00 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [zfile-dev/zfile] 首页视图 (Issue #427) 为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）： 是否已搜索其他 issue，没有人提过这个问题？：否 当前 ZFile 版本：4.0.10 是否尝试最新版是否已解决此问题：否 是否尝试重启 ZFile，且问题依旧存在？： 是否已尝试清空浏览器缓存，且问题依旧存在？： 操作系统（如 Windows、Mac、iOS、安卓）：Windows 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome 做什么操作提示的错误？： 期望行为（应该是什么样的结果）：视图选择大时，不会出现省略号 当前行为（当前是什么样的结果）：视图选择大时，出现省略号 错误日志（可选）： 复现步骤（可选）： 您的额外信息（可选）： — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

系统时windows11,缩放开了125%，分辨率是1920*1080，屏幕尺寸15.6，浏览器没有开缩放，之前4.0.7版本没有省略号。

**Comment by zhaojun1998** [comment]
@Nxins 

尝试清除浏览器缓存或使用浏览器无痕模式看看是否还有问题

**Comment by cxwya** [comment]
@zhaojun1998 
应该不是这个原因，使用开发者模式，
.el-checkbox:last-of-type {
    /* margin-right: 0; */
}
把这个去掉，选择框旁边的省略号就没了

**Comment by zhaojun1998** [comment]
ok

那您先使用后台的自定义 css 功能解决吧，后续版本会测试后修复此问题。

**Comment by cxwya** [comment]
行，麻烦了
