### ISSUE TITLE
源失效后不会自动恢复

### ISSUE THREAD

**Issue by haoduck** [zfile-dev/zfile#428]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

挂载一个webdav，如果这个webdav宕机了，一段时间后又恢复了。zfile里将一直是"源错误"，没有检测是否已经恢复正常了。只有在后台点一下编辑 保存，然后才能恢复

![image](https://user-images.githubusercontent.com/56804964/185289111-6f365ab2-2bf3-4ccf-8b9c-064a4dfc63c1.png)

- 是否已搜索其他 issue，没有人提过这个问题？：是
- 当前 ZFile 版本：4.0.9
- 是否尝试最新版是否已解决此问题：
- 是否尝试重启 ZFile，且问题依旧存在？：
- 是否已尝试清空浏览器缓存，且问题依旧存在？：
- 操作系统（如 Windows、Mac、iOS、安卓）：
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：
- 做什么操作提示的错误？：
- 期望行为（应该是什么样的结果）：
- 当前行为（当前是什么样的结果）：
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
只有启动 ZFile 首次初始化失败才会这样不再刷新，这并不能算为 bug，这是为了降低系统频繁无意义的性能占用，
