### ISSUE TITLE
feat: 关于密码文件夹的失效时间问题

### ISSUE THREAD

**Issue by DeaneChen** [zfile-dev/zfile#429]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：没有
- 是否已尝试使用最新版本，且仍然没有此功能？：没有
- 功能概述：修改文件夹密码的存储失效时间
- 功能动机：设置文件夹密码用于控制访问，同时ZFile似乎存储了cookie避免重复输入提高用户体验，但该cookie似乎不会随着页面或者浏览器的关闭而失效，这将导致在公共计算机上使用时存在一定安全问题，其他人使用时可以直接访问。该情况在3.x版本并未存在。
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
@DeaneChen 

我想着时间并不是问题关键，如果想要保证安全，在公共电脑就应该清理浏览记录或使用无痕模式访问，或者可以在后台修改密码，就像你在其他人电脑上登陆其他 web 应用账号后，就算不保存密码，登陆状态也会保留，仍然是需要做一些操作才能清空记录的，无痕模式才是在公共电脑的最佳安全解决方案。

**Comment by DeaneChen** [comment]
你说的有道理，我确实一直是用清除浏览记录的方式，因为还有下载的链接等等，为了保证安全，使用者本应多做一些操作。
