### ISSUE TITLE
音频格式.ape不能播放!

### ISSUE THREAD

**Issue by fuscn** [zfile-dev/zfile#430]
最新版本
只要预览ape文件就会报错.是不支持ape么?

浏览器输出如下信息:
file.4bccb000.js:157 DOMException: Failed to load because no supported source was found.
(匿名) @ file.4bccb000.js:157
Promise.catch(异步)
value @ file.4bccb000.js:157
(匿名) @ file.4bccb000.js:157
setTimeout(异步)
(匿名) @ file.4bccb000.js:157
value @ file.4bccb000.js:13
(匿名) @ file.4bccb000.js:157
music:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.

**Comment by zhaojun1998** [comment]
@fuscn 

所有音频视频都是浏览器进行解码的，如播放不了，就是浏览器不支持此类音频的解码，一般是因为浏览器没有相关格式的解码版权导致的。

**Comment by fuscn** [comment]
Chrome系列浏览器都不行,能推荐一款浏览器不?

**Comment by fuscn** [comment]
> @fuscn
> 
> 所有音频视频都是浏览器进行解码的，如播放不了，就是浏览器不支持此类音频的解码，一般是因为浏览器没有相关格式的解码版权导致的。

Chrome系列浏览器都不行，能推荐一款浏览器不？

**Comment by zhaojun1998** [comment]
一般 Chrome 都不支持，其他浏览器也都不会支持的。
