### ISSUE TITLE
移动端浏览器打开首页空白,没有内容!

### ISSUE THREAD

**Issue by fuscn** [zfile-dev/zfile#432]
- 是否已搜索其他 issue，没有人提过这个问题？：没搜到
- 当前 ZFile 版本：4.0.10
- 是否尝试最新版是否已解决此问题：否
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：安卓
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：via,夸克
- 在微信内置浏览器是可以打开的.

和url哈希模式有关?
3.x版本正常打开.
菜鸟,望赐教!

**Comment by zhaojun1998** [comment]
via 和夸克浏使用的都是系统内置浏览器内核，微信浏览器使用的自己的内核，3.x 版本为 vue2，4.x 版本为 vue3，出现此问题为兼容性问题。为了进一步查看是否能解决此问题，还需要您提供安卓版本号，如 `Android 12`，还有手机系统的版本号，如 `MIUI 13 22.5.24`

**Comment by fuscn** [comment]
> via 和夸克浏使用的都是系统内置浏览器内核，微信浏览器使用的自己的内核，3.x 版本为 vue2，4.x 版本为 vue3，出现此问题为兼容性问题。为了进一步查看是否能解决此问题，还需要您提供安卓版本号，如 `Android 12`，还有手机系统的版本号，如 `MIUI 13 22.5.24`

安卓9,nubiaUI 7.0,

**Comment by trapan** [comment]
我也出现了这个问题，手机用的yandex，电脑360极速都出现了，正好是中午入了捐赠，服务端换了，但是配置并没有变，需要清除掉浏览器缓存。，但是有一定概率复现

**Comment by zhaojun1998** [comment]
@trapan 
@fuscn 

新版本 4.1.2 已经优化浏览器兼容性，最低支持为： `谷歌 49+`、`Firefox 51+`、`Android 7.0+` ，但不支持 IE 任何版本。可以更新后再试试。

**Comment by fuscn** [comment]
> @trapan @fuscn
> 
> 新版本 4.1.2 已经优化浏览器兼容性，最低支持为： `谷歌 49+`、`Firefox 51+`、`Android 7.0+` ，但不支持 IE 任何版本。可以更新后再试试。

感谢奉献.

**Comment by zhaojun1998** [comment]
@fuscn 
@trapan 

是否已解决，如果解决了我就关闭 issue 了
