### ISSUE TITLE
feat:  建议增加非管理员用户强制登录才能使用功能

### ISSUE THREAD

**Issue by yongxin3344520** [zfile-dev/zfile#434]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：没有
- 是否已尝试使用最新版本，且仍然没有此功能？：有匿名用户功能，但不需要登录
- 功能概述：管理员关闭匿名访问，用户需要登录才能使用
- 功能动机：管理者大多时候不希望所有人能够看见网盘内容，需要设定登录
- 详细解释（可选）：
   1.  管理员可以关闭匿名访问
   2.  管理员创建账号密码并为之分配至少一个储存源，用户登录成功后，任何操作（上传，下载，删除.....）都需要校验权限。

**Comment by zhaojun1998** [comment]
@yongxin3344520 

1. 捐赠版中可以设置仅管理员可以访问某存储源，且社区版也可以通过根目录设置密码的方式防止游客访问。
2. 暂不考虑多用户的场景，ZFile 并不打算向多用户网盘转型，多用户网盘已经有非常成熟的 Cloudreve 了。
