### ISSUE TITLE
feat: 能否增加对文本txt编辑的功能

### ISSUE THREAD

**Issue by jia2332** [zfile-dev/zfile#435]
能否增加对文本txt编辑的功能

**Comment by zhaojun1998** [comment]
@wannianxianyu 

ZFile 不考虑想向那个方向发展，目前只考虑基础的文件操作，在线协作或编辑文件的功能不打算做。

**Comment by jia2332** [comment]
@zhaojun1998 未来是否会考虑针对大文件实现分片上传呢？

**Comment by zhaojun1998** [comment]
目前 onedrive 相关是支持分片上传的。其他存储类型也在逐步实现中



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月1日(周四) 下午5:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] feat: 能否增加对文本txt编辑的功能 (Issue #435)




 
@zhaojun1998 未来是否会考虑针对大文件实现分片上传呢？
