### ISSUE TITLE
甲骨文对象存储添加失败

### ISSUE THREAD

**Issue by Aermisty** [zfile-dev/zfile#436]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：是
- 当前 ZFile 版本：4.1.1 docker compose 部署
- 是否尝试最新版是否已解决此问题：已尝试
- 是否尝试重启 ZFile，且问题依旧存在？：存在
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：macOS
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Safari / Edge
- 做什么操作提示的错误？：添加存储源
- 期望行为（应该是什么样的结果）：成功添加存储源
- 当前行为（当前是什么样的结果）：提示初始化异常、提示设置跨域失败（见后面的截图）
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：

全部开启，会提示域名风格不能为空，但是没有地方可以填写域名风格，尝试关闭开启这个按钮后就没有提示了。
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/19180725/188011707-93f54b18-6336-4bb5-a044-18c40b9eb3d6.png">

打开 CORS，提示
![Xnip2022-09-02_04-50-40](https://user-images.githubusercontent.com/19180725/188010646-1429b4ce-941f-4b15-9419-d1c330b3b24e.jpg)

关闭 CORS，提示
![Xnip2022-09-02_04-52-36](https://user-images.githubusercontent.com/19180725/188010582-05a358ed-1119-4445-8e2b-df1b692de74a.jpg)

把 Endpoint 改成 `https://compact.objectstorage.ap-singapore-1.oraclecloud.com`，提示中的链接就变成了 `https://<namespace>.compact.objectstorage.ap-singapore-1.oraclecloud.com`

**Comment by zhaojun1998** [comment]
这是一个 bug，下个版本会进行修复。

**Comment by psdzzm** [comment]
Cloudflare的R2对象存储也有这个问题

**Comment by zhaojun1998** [comment]
@leirock @psdzzm 

我本地已经测试完毕，并修复了无法添加的问题，下个版本发布后就可以正常添加了，但不幸的是 `Cloudflare R2` 和 `Oracle Object Storage` 都不支持设置 `CORS` （跨域设置），也就是说在 ZFile 上无法支持上传功能。

- `Cloudflare R2` `CORS 跨域设置` 参考文档：https://github.com/cloudflare/cloudflare-docs/issues/4455
- `Oracle Object Storage` `CORS 跨域设置` 参考文档：https://www.oracle.com/cloud/storage/object-storage/faq/

<img width="1621" alt="image" src="https://user-images.githubusercontent.com/35387985/189897951-82a2da6c-d60c-444c-9902-318bdfa75f3b.png">

**Comment by zhaojun1998** [comment]
@psdzzm  @leirock 

新版本 4.1.2 已经修复此问题。
