### ISSUE TITLE
挂载ftp存储，一级目录可列举，可新建文件夹，不可传文件。二级目录无权限

### ISSUE THREAD

**Issue by trapan** [zfile-dev/zfile#438]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：无人反馈
- 当前 ZFile 版本：4.1.1
- 是否尝试最新版是否已解决此问题：已最新
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：win7 jdk1.8 341
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：360极速
- 做什么操作提示的错误？：访问
- 期望行为（应该是什么样的结果）：挂载匿名ftp可读写
- 当前行为（当前是什么样的结果）：一级目录可列举，可新建文件夹，不能转存文件。二级目录无访问内容，不可传文件。上传文件提示错误{ "code": 500, "msg": "Change dir to [F:\\测试1\\测试1] error, maybe dir not exist!", "data": null, "dataCount": null }
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：ftp是匿名，编码gbk，用的国内常见的一键ftp，权限全开，手机，电脑直接访问正常。

**Comment by zhaojun1998** [comment]
可能是编码问题，确定 ftp 服务本身是 gbk 编码吗，请使用其他 ftp 工具测试功能是否正常，还有请提供 ftp 搭建程序及相关版本号，参数等信息，以便我进行测试。

**Comment by Yshelgi** [comment]
我今天中午刚刚一开始也遇到了这个问题,后来在宝塔里修改文件夹权限(改成777)重启服务,重新进入ZFile后台配置ftp数据源,现在使用正常了.目前服务器是centos,编码是utf8,ftp就是宝塔里配置的,希望对你有帮助

**Comment by zhaojun1998** [comment]
长时间未反馈问题，先关闭 ISSUE，有问题再重新打开。
