### ISSUE TITLE
feat: 建议新增图片预览 缩略图功能

### ISSUE THREAD

**Issue by ZhangShanFeng1114** [zfile-dev/zfile#440]
我发现如果一个文件夹图片太多且文件大小也太大的话 画廊模式的话 容易大部分图片显示不出来
有没有可能考虑下 加入下缩略图功能呢

**Comment by zhaojun1998** [comment]
目前绝大多数存储源都不支持缩略图功能，或者类似阿里oss那种是收费的。


如果服务器先下载并转码再转发给网页的话。首先下载到服务器动作受服务器下行速度限制。转码动作受服务器cpu速度限制，转发到网页加载受服务器上行速度限制。


所以无法支持，或者说即使支持了速度也不一定比原来快。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月8日(周四) 晚上11:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] feat: 建议新增图片预览 缩略图功能 (Issue #440)




 
我发现如果一个文件夹图片太多且文件大小也太大的话 画廊模式的话 容易大部分图片显示不出来
 有没有可能考虑下 加入下缩略图功能呢

**Comment by vvnocode** [comment]
建议增加图片缩略图功能：
1. 有的图片很大，家庭宽带上行不足以支撑图片下载所需速度。
2. 可以配置是否开启，如果机器性能强大，体验会好很多。
3. 可以配置浏览图片大小限制，图片超过指定大小就进行转码。
4. 可以定时任务后台转码/请求图片临时转码并存储，下次请求直接返回转码后的。
5. 可以转码成webp格式图片，应该能参考webp-sh/webp_server_go项目。
6. 是否可以接受有人提交转码相关的代码？

**Comment by zhaojun1998** [comment]
接受此功能的代码贡献



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月13日(周三) 晚上10:16
收件人: ***@***.***&gt;;
抄送: "zhao ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [zfile-dev/zfile] feat: 建议新增图片预览 缩略图功能 (Issue #440)




 
建议增加图片缩略图功能：
  
有的图片很大，家庭宽带上行不足以支撑图片下载所需速度。
 
可以配置是否开启，如果机器性能强大，体验会好很多。
 
可以配置浏览图片大小限制，图片超过指定大小就进行转码。
 
可以定时任务后台转码/请求图片临时转码并存储，下次请求直接返回转码后的。
 
可以转码成webp格式图片，应该能参考webp-sh/webp_server_go项目。
 
是否可以接受有人提交转码相关的代码？
