### ISSUE TITLE
启动

### ISSUE THREAD

**Issue by GithubGey** [zfile-dev/zfile#441]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：
- 当前 ZFile 版本：
- 是否尝试最新版是否已解决此问题：
- 是否尝试重启 ZFile，且问题依旧存在？：
- 是否已尝试清空浏览器缓存，且问题依旧存在？：
- 操作系统（如 Windows、Mac、iOS、安卓）：
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：
- 做什么操作提示的错误？：
- 期望行为（应该是什么样的结果）：
- 当前行为（当前是什么样的结果）：
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
无效 issue，未提供任何信息
