### ISSUE TITLE
4.1.1 版本无法添加 Cloudflare R2 存储

### ISSUE THREAD

**Issue by Hreint** [zfile-dev/zfile#443]
- 是否已搜索其他 issue，没有人提过这个问题？：是
- 当前 ZFile 版本：4.1.1
- 是否尝试最新版是否已解决此问题：否
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：Windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome
- 做什么操作提示的错误？：

尝试了一下最新版也就是 4.1.1 版本的 zfile，发现好像又无法添加 R2 存储了。

- 期望行为（应该是什么样的结果）：成功添加 R2 存储
- 当前行为（当前是什么样的结果）：

存储策略选的是 S3通用协议，地域已经填了 auto，但还是提示“无效的地域名称”
![image](https://user-images.githubusercontent.com/64591583/189706404-1ee7d2e2-be8f-4db4-9e0f-4dec8a5f80c0.png)
![image](https://user-images.githubusercontent.com/64591583/189706429-237abc44-76a2-47a7-99d2-cd13ca271f84.png)

**Comment by zhaojun1998** [comment]
@Hreint 

我本地已经测试完毕，并修复了无法添加的问题，下个版本发布后就可以正常添加了，但不幸的是 `Cloudflare R2` 不支持设置 `CORS` （跨域设置），也就是说在 ZFile 上无法支持上传功能。

- `Cloudflare R2` `CORS 跨域设置` 参考文档：https://github.com/cloudflare/cloudflare-docs/issues/4455

**Comment by Hreint** [comment]
感谢修复！不支持上传这倒没啥，我一直都用 Cyberduck 来上传，感觉更方便一些。

**Comment by Hreint** [comment]
> @Hreint
> 
> 我本地已经测试完毕，并修复了无法添加的问题，下个版本发布后就可以正常添加了，但不幸的是 `Cloudflare R2` 不支持设置 `CORS` （跨域设置），也就是说在 ZFile 上无法支持上传功能。
> 
> * `Cloudflare R2` `CORS 跨域设置` 参考文档：[Coverage of presigned URLs/presigned POST requests cloudflare/cloudflare-docs#4455](https://github.com/cloudflare/cloudflare-docs/issues/4455)

最近 R2 已经升级正式版了，我测试了一下，R2 可以开启 CORS 也可以正常上传。

**Comment by zhaojun1998** [comment]
@Hreint 

按说明 R2 最近更新支持了此功能
