### ISSUE TITLE
无法添加 Google Drive 存储

### ISSUE THREAD

**Issue by Hreint** [zfile-dev/zfile#444]
- 是否已搜索其他 issue，没有人提过这个问题？：否
- 当前 ZFile 版本：4.1.1
- 是否尝试最新版是否已解决此问题：否
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：Windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome
- 做什么操作提示的错误？：添加 Google Drive 存储
- 期望行为（应该是什么样的结果）：添加 Google Drive 存储成功
- 当前行为（当前是什么样的结果）：
 成功获取 Google Drive 令牌并已经填写了所有必填项，但点击添加时出现错误 “Access key cannot be null”
![2022-09-13_224904](https://user-images.githubusercontent.com/64591583/189934256-a3aa5c74-870a-4d0e-bf9c-57f8d81eb43c.png)

我在怀疑是否与该问题有关：zfile 中访问令牌与刷新令牌中包含的 _ 符号均无法正常显示，如图：
![2022-09-13_224527](https://user-images.githubusercontent.com/64591583/189934784-a5593276-f7ab-4969-b6fb-7a4b951a11b1.png)
上图是我获取到的 Google Drive 令牌

![2022-09-13_224621](https://user-images.githubusercontent.com/64591583/189934933-26bbe19b-c4b3-4de7-b395-7dfc9f6f5fdc.png)
填写到 zfile 里面就变成空格了，没有显示 _ 符号，第一张图也可看出该为 _ 符号的地方变成了空格。

**Comment by zhaojun1998** [comment]
不是这个原因。是另外一个bug导致的，就是先添加a存储类型，添加失败后，因为缓存没清理导致新添加b存储类型时，检验的还是a的存储类型。


下个版本会修复，临时解决办法是重启再添加就好了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月13日(周二) 晚上10:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 无法添加 Google Drive 存储 (Issue #444)




  
是否已搜索其他 issue，没有人提过这个问题？：否 

当前 ZFile 版本：4.1.1 

是否尝试最新版是否已解决此问题：否 

是否尝试重启 ZFile，且问题依旧存在？：是 

是否已尝试清空浏览器缓存，且问题依旧存在？：是 

操作系统（如 Windows、Mac、iOS、安卓）：Windows 

浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome 

做什么操作提示的错误？：添加 Google Drive 存储 

期望行为（应该是什么样的结果）：添加 Google Drive 存储成功 

当前行为（当前是什么样的结果）：
 成功获取 Google Drive 令牌并已经填写了所有必填项，但点击添加时出现错误 “Access key cannot be null”
  
 
我在怀疑是否与该问题有关：zfile 中访问令牌与刷新令牌中包含的 _ 符号均无法正常显示，如图：
 
 上图是我获取到的 Google Drive 令牌
 

 填写到 zfile 里面就变成空格了，没有显示 _ 符号，第一张图也可看出该为 _ 符号的地方变成了空格。

**Comment by Hreint** [comment]
明白了，感谢解答。
