### ISSUE TITLE
feat: 请问有计划开发同步阿里网盘、百度网盘和坚果云这些常用的网盘功能吗？

### ISSUE THREAD

**Issue by PankTan** [zfile-dev/zfile#445]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：否
- 是否已尝试使用最新版本，且仍然没有此功能？：是
- 功能概述：常用的网盘的文件同步到本地存储
- 功能动机：方便管理
- 详细解释（可选）：可以在zfile界面对其他网盘的文件做增删查改操作

**Comment by zhaojun1998** [comment]
1. 阿里云盘不考虑，官网未公开提供 api，现在市面上的那些都是抓包获取的接口，开发者私自对接有法律风险，使用者有封号风险。
2. 百度云盘试过，限制很多。如网页无法下载，需要设置 ua，无法通过客户端直传，只能从服务器中转上传，对服务器带宽要求很高。这两个基础功能都无法正常使用，也就没必要对接了。
3.坚果云可以使用webdav挂载到zfile

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月14日(周三) 下午4:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] feat: 请问有计划开发同步阿里网盘、百度网盘和坚果云这些常用的网盘功能吗？ (Issue #445)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个功能？：否 

是否已尝试使用最新版本，且仍然没有此功能？：是 

功能概述：常用的网盘的文件同步到本地存储 

功能动机：方便管理 

详细解释（可选）：可以在zfile界面对其他网盘的文件做增删查改操作

**Comment by reyfull** [comment]
阿里云盘官网有公开提供api了

**Comment by lisc888** [comment]
请求开发直连分享增加 密码访问

**Comment by zhaojun1998** [comment]
暂不考虑百度和阿里，限制太多。坚果云的webdav现在是支持的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月29日(周日) 下午5:05
收件人: ***@***.***&gt;;
抄送: "zhao ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [zfile-dev/zfile] feat: 请问有计划开发同步阿里网盘、百度网盘和坚果云这些常用的网盘功能吗？ (Issue #445)




 
请求开发直连分享增加 密码访问

**Comment by lisc888** [comment]
亲，您好！
    您的邮件已经收到了，请您稍作等待；我将详细审核处理。

**Comment by ashelylinluo** [comment]
夸克网盘支持吗

**Comment by lisc888** [comment]
亲，您好！
    您的邮件已经收到了，请您稍作等待；我将详细审核处理。

**Comment by ashelylinluo** [comment]
您好，你的邮件已收到，我会尽快回复您。罗琳。This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank you——Luo,Lin
