### ISSUE TITLE
无法预览3D文件，点击文件直接下载

### ISSUE THREAD

**Issue by TicklTock** [zfile-dev/zfile#446]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：未找到
- 当前 ZFile 版本：4.1.1
- 是否尝试最新版是否已解决此问题：是
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：Windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Edge
- 做什么操作提示的错误？：想要预览3D文件，直接提示是否下载
- 期望行为（应该是什么样的结果）：预览3D文件
- 当前行为（当前是什么样的结果）：显示下载3D文件
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
什么格式的 3d 文件，支持预览的 3d 文件左侧图标是一个立方体，还有你电脑是否安装了注入 IDM 之类的资源嗅探工具，还没预览的时候，就被这种工具拦截进行下载了。

**Comment by TicklTock** [comment]
> 什么格式的 3d 文件，支持预览的 3d 文件左侧图标是一个立方体，还有你电脑是否安装了注入 IDM 之类的资源嗅探工具，还没预览的时候，就被这种工具拦截进行下载了。

文件是直接从预览DEMO网站[https://demo.zfile.vip/](https://demo.zfile.vip/)里面直接下载的fbx文件然后上传到了我自己部署的网盘
应该和拦截无关，下面是图片
![image](https://user-images.githubusercontent.com/48879012/190550540-8cefc43a-0dfe-4ed0-ad5f-d97ad7e055d1.png)

**Comment by zhaojun1998** [comment]
麻烦提供一个地址以便我进行测试来复现问题

**Comment by TicklTock** [comment]
地址可能无法提供，没有服务器，只是在本地以docker-compose方式部署了zfile以及onlyoffice

**Comment by zhaojun1998** [comment]
已经复现了这个问题，目前发现是捐赠版和社区版代码不一致导致的，演示站是捐赠版，下个版本会同步这部分功能。

**Comment by TicklTock** [comment]
好的，谢谢

**Comment by zhaojun1998** [comment]
@TicklTock 

最新版 4.1.2 已修复此功能，但需要注意的是：

> 3D 文件预览功能依赖直链，所以要在后台启用 `直链管理 -> 是否允许路径直链可直接访问`，不然未生成直链的文件无法直接通过直链访问。
> 或者你确定你要预览的 3d 文件和所依赖的文件也都生成了直链也没问题。
