### ISSUE TITLE
手机端无法上传文件

### ISSUE THREAD

**Issue by Geeksun2018** [zfile-dev/zfile#448]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：否
- 当前 ZFile 版本：docker的最新镜像
- 是否尝试最新版是否已解决此问题：是
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：安卓
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：chrome
- 做什么操作提示的错误？：上传文件
- 期望行为（应该是什么样的结果）：显示上传文件的按钮
- 当前行为（当前是什么样的结果）：无显示
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：
- 
![765b535c83805f2f0d64f0acb276263](https://user-images.githubusercontent.com/42086593/190896477-af368eed-3ef5-4568-bc2f-9dfc97c80b9a.jpg)

**Comment by zhaojun1998** [comment]
请确认这两个选项的启动状态，第一个为是否**启用文件操作**，第二个是是否**允许匿名文件操作**。

目前看你截图，可能就以下几种情况：
1. 未开启 `启用文件操作`，必然无法进行上传
2. 如果未启用 `允许匿名文件操作`，那你手机上肯定没进行登录过，所以系统识别你为匿名用户，所以无法进行上传。

<img width="996" alt="image" src="https://user-images.githubusercontent.com/35387985/190898915-752f6d06-4396-49d4-8fda-14b15fbc91c9.png">

**Comment by zhaojun1998** [comment]
暂时没有回复，先关闭问题了， 有问题再打开 issue

**Comment by Geeksun2018** [comment]
> 请确认这两个选项的启动状态，第一个为是否**启用文件操作**，第二个是是否**允许匿名文件操作**。
> 
> 目前看你截图，可能就以下几种情况：
> 
> 1. 未开启 `启用文件操作`，必然无法进行上传
> 2. 如果未启用 `允许匿名文件操作`，那你手机上肯定没进行登录过，所以系统识别你为匿名用户，所以无法进行上传。
> 
> <img alt="image" width="996" src="https://user-images.githubusercontent.com/35387985/190898915-752f6d06-4396-49d4-8fda-14b15fbc91c9.png">



> 请确认这两个选项的启动状态，第一个为是否**启用文件操作**，第二个是是否**允许匿名文件操作**。
> 
> 目前看你截图，可能就以下几种情况：
> 
> 1. 未开启 `启用文件操作`，必然无法进行上传
> 2. 如果未启用 `允许匿名文件操作`，那你手机上肯定没进行登录过，所以系统识别你为匿名用户，所以无法进行上传。
> 
> <img alt="image" width="996" src="https://user-images.githubusercontent.com/35387985/190898915-752f6d06-4396-49d4-8fda-14b15fbc91c9.png">



> 请确认这两个选项的启动状态，第一个为是否**启用文件操作**，第二个是是否**允许匿名文件操作**。
> 
> 目前看你截图，可能就以下几种情况：
> 
> 1. 未开启 `启用文件操作`，必然无法进行上传
> 2. 如果未启用 `允许匿名文件操作`，那你手机上肯定没进行登录过，所以系统识别你为匿名用户，所以无法进行上传。
> 
> <img alt="image" width="996" src="https://user-images.githubusercontent.com/35387985/190898915-752f6d06-4396-49d4-8fda-14b15fbc91c9.png">

是的，我还以为代码里面限制手机端上传文件，甚至还用了手机端的电脑模式，然后还是不能上传。后面发现是自己没有登录，哭了，谢谢你了！！！
