### ISSUE TITLE
Admin/admin

### ISSUE THREAD

**Issue by byzp** [zfile-dev/zfile#449]
- 是否已搜索其他 issue，没有人提过这个问题？：好像没有
- 当前 ZFile 版本：4.1.2
- 是否尝试最新版是否已解决此问题：/
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：Windows/安卓
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：edge/Chrome
- 做什么操作提示的错误？：设置存储源别名admin会提示占用，改为Admin
- 期望行为（应该是什么样的结果）：仍然提示占用
- 当前行为（当前是什么样的结果）：访问别名为Admin的存储源时跳转到管理员登录界面
- 错误日志（可选）：/
- 复现步骤（可选）：/
- 您的额外信息（可选）：/

**Comment by zhaojun1998** [comment]
你不应该使用 admin 作为存储源名称。这占用了系统内置的路径。



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 22, 2022 21:44 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [zfile-dev/zfile] Admin/admin (Issue #449)




  
是否已搜索其他 issue，没有人提过这个问题？：好像没有 

当前 ZFile 版本：4.1.2 

是否尝试最新版是否已解决此问题：/ 

是否尝试重启 ZFile，且问题依旧存在？：是 

是否已尝试清空浏览器缓存，且问题依旧存在？：是 

操作系统（如 Windows、Mac、iOS、安卓）：Windows/安卓 

浏览器（如 Chrome、Firefox、Safari，X 浏览器）：edge/Chrome 

做什么操作提示的错误？：设置存储源别名admin会提示占用，改为Admin 

期望行为（应该是什么样的结果）：仍然提示占用 

当前行为（当前是什么样的结果）：访问别名为Admin的存储源时跳转到管理员登录界面 

错误日志（可选）：/ 

复现步骤（可选）：/ 

您的额外信息（可选）：/
