### ISSUE TITLE
用OneDrive存储策略，常常显示系统异常。

### ISSUE THREAD

**Issue by aass0810** [zfile-dev/zfile#45]
用OneDrive存储策略，进前台页面，常常显示系统异常。
到后台页面，点存储策略，在OneDrive选项里面，点下“确认”就可以正常访问了。
请问这个有办法解决吗?

**Comment by Scolism** [comment]
1.清缓存重建缓存，点确认。
2.点确认，清缓存重建缓存。       
总之，要动一下缓存，这是我以前的经验hhhh  我以前也是一直靠点“”确认“”维持生活

**Comment by zhaojun1998** [comment]
@aass0810  @CuteLouise  
我今天专门找了台服务器，使用的是 OneDrive，未复现成功此问题，关于这个问题，我需要更详细的信息，还麻烦提供下：
1. 是否开启缓存功能
2. 是否开启了搜索功能
3. 在什么操作后，出现的系统异常，是访问首页显示的吗
4. 出现频率为多久
5. 服务器操作系统及版本，内存大小

**Comment by Scolism** [comment]
> @aass0810 @CuteLouise
> 我今天专门找了台服务器，使用的是 OneDrive，未复现成功此问题，关于这个问题，我需要更详细的信息，还麻烦提供下：
> 
> 1. 是否开启缓存功能
> 2. 是否开启了搜索功能
> 3. 在什么操作后，出现的系统异常，是访问首页显示的吗
> 4. 出现频率为多久
> 5. 服务器操作系统及版本，内存大小

因为就刚安装的时候折腾过一下，后面再也没出现过了，所以我也不寻求解决啦。只是给提问者一些建议，具体信息还是等提问者来说吧~~~

**Comment by zhaojun1998** [comment]
@CuteLouise 嗯，如后面再次遇到，还希望能给予一些反馈，如提供日志文件等方式。谢谢。

**Comment by aass0810** [comment]
> @CuteLouise嗯，如后面再次遇到，还希望能给予一些反馈，如提供日志文件等方式。谢谢。

我买的是阿里云的突发性能实例规格族t5的服务器，vCPU:1，内存：2G，磁盘：40GB，基准CPU性能20%，纯粹买着自己玩练手的。
昨天重新安装了镜像，从Debian换成了centos  8.0.1905，也把存储策略从OneDrive换成了七牛对象存储，环境用的是宝塔面板7.1。
 @没有开启缓存，没有开启搜索，没有什么特定操作后会这样，反正每次突然就访问不了或者显示系统异常。访问不了的情况下会报504的错误，访问不了的情况一般在宝塔面板会显示8080端口未使用，SSH停止，启动一下就可以了。如果是什么系统异常，按下存储策略中的“确认”就行了。换成七牛后，不能访问的次数多余系统异常的次数，我每天打开的不多，大概每天至少会出现1、2次。日志附在下面了
[zfile日志.txt](https://github.com/zhaojun1998/zfile/files/4228964/zfile.txt)

**Comment by onepve** [comment]
我也是一样.....重新缓存就可以.过一会就...........附上日志
```
是否开启缓存功能   是
是否开启了搜索功能  否
在什么操作后，出现的系统异常，是访问首页显示的吗   约3小时后访问首页发现的
出现频率为多久  ...这个不知道咋测试
服务器操作系统及版本，内存大小 

centos-7.7.1908
Linux version 3.10.0-957.27.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Mon Jul 29 17:46:05 UTC 2019
1核心2GB
```
```
系统异常, 请联系管理员
```

[log.zip](https://github.com/zhaojun1998/zfile/files/4234019/log.zip)

**Comment by haibuhao** [comment]
> 用OneDrive存储策略，进前台页面，常常显示系统异常。
> 到后台页面，点存储策略，在OneDrive选项里面，点下“确认”就可以正常访问了。
> 请问这个有办法解决吗?

我也遇到了，点下确定又好了。。。

**Comment by zhaojun1998** [comment]
@aass0810 
@CuteLouise 
@wxlost 
@haibuhao 
已在 1.9 版本更新，大家更新后，看看还会不会遇到

**Comment by haibuhao** [comment]
还是会有，我的服务器配置弱 1核心 760m 运存  
[ZFile 诊断日志 - 2020-02-27 06_46_13.zip](https://github.com/zhaojun1998/zfile/files/4258573/ZFile.-.2020-02-27.06_46_13.zip)

**Comment by haibuhao** [comment]
我把缓存和搜索功能关闭了，不会出现这个问题了。

**Comment by zhaojun1998** [comment]
@haibuhao ，更新了 2.0 版本，修复了这个问题

**Comment by haibuhao** [comment]
最新版本解决了，目前不会出现这样问题，谢谢开发者。牛！
