### ISSUE TITLE
feat: 改进长视频播放卡顿的问题

### ISSUE THREAD

**Issue by xiongyicode** [zfile-dev/zfile#453]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：有但是没解决
- 是否已尝试使用最新版本，且仍然没有此功能？：无
- 功能概述：提升长视频的性能
- 功能动机：在线长视频加载慢
- 详细解释（可选）
1. 用的本地存储模式，网络带宽肯定没问题，打开长视频的时候大概要加载一分钟左右非常慢
2. 本人尝试过用Nginx做代理访问本地mp4长视频，可以做到几秒钟就开始播放

**Comment by zhaojun1998** [comment]
你提供的信息不足以证明是 ZFile 问题，请先根据以下步骤排查后回复问题，我才能进一步确定

- 长视频是多长，文件有多大，视频码率是多少？
- 搭建 ZFile 的服务器是在局域网还是公网上？
- 如果是公网上，那就受限于你公网服务器的上行带宽，那你公网服务器的上行带宽是多少？
- 如果是公网服务器，检查那是否有其他占用带宽的程序？
- 如果是局域网上，请确定是否是同一台机器，如果不是同一台，那走的网络就是网线或者 WIFI，WIFI 的话，网络不佳的情况很可能速率也不高。
- Nginx 做代理是指的代理什么，直接代理文件目录，还是代理 ZFile？
- ZFile 是直接通过端口访问的，还是通过其他的类似反向代理之后访问的？
- 打开浏览器 F12，查看视频播放是否走了 206 响应（分片播放），206 响应表示从服务器读取的某一段视频，而不是整个视频。
- 即使是 206 请求，可能读取的那一段，也超出了服务器上行带宽阈值，就会进行加载

<img width="1860" alt="image" src="https://user-images.githubusercontent.com/35387985/193157860-508a7427-beb0-4f41-b820-88333d7fd8f3.png">

**Comment by zhaojun1998** [comment]
长时间未回复，先关闭 issue 了，有回复再开启
