### ISSUE TITLE
启动Docker版ZFile报错

### ISSUE THREAD

**Issue by gradendripar** [zfile-dev/zfile#455]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：没有
- 当前 ZFile 版本：zhaojun1998/zfile:4.1.2
- 是否尝试最新版是否已解决此问题：否
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：Centos
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：
- 做什么操作提示的错误？：
执行完了这一句，查看日志后就报错了
`docker run -d --name=zfile --restart=always \
    -p 8080:8080 \
    -v /root/zfile/db:/root/.zfile-v4/db \
    -v /root/zfile/logs:/root/.zfile-v4/logs \
    zhaojun1998/zfile`
![image](https://user-images.githubusercontent.com/67825668/193855590-c856a6a1-ac9a-4576-afb5-66c078f57719.png)

**Comment by gradendripar** [comment]
然后试了下zhaojun1998/zfile:4.1.1 4.1.1版本没问题 不知道4.1.2是为什么会出现这样的问题
![image](https://user-images.githubusercontent.com/67825668/193861075-ad05575f-d497-4839-98c9-ec02ae5953ac.png)

**Comment by zhaojun1998** [comment]
我很想复现这个问题，但是一直没找到可以复现的环境，麻烦问下什么云服务的机器，什么操作系统，docker 版本，centos 版本分别是什么，以便我复现问题，谢谢。

**Comment by gradendripar** [comment]
> 我很想复现这个问题，但是一直没找到可以复现的环境，麻烦问下什么云服务的机器，什么操作系统，docker 版本，centos 版本分别是什么，以便我复现问题，谢谢。

在QQ上已经问过你这个问题了 这个issue忘了取消

**Comment by zhaojun1998** [comment]
麻烦qq上再给我说句话，我忘记当时怎么解决的了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月23日(周日) 下午2:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 启动Docker版ZFile报错 (Issue #455)




  
我很想复现这个问题，但是一直没找到可以复现的环境，麻烦问下什么云服务的机器，什么操作系统，docker 版本，centos 版本分别是什么，以便我复现问题，谢谢。
  
在QQ上已经问过你这个问题了 这个issue忘了取消

**Comment by gradendripar** [comment]
> 麻烦qq上再给我说句话，我忘记当时怎么解决的了。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年10月23日(周日) 下午2:10 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [zfile-dev/zfile] 启动Docker版ZFile报错 (Issue #455) 我很想复现这个问题，但是一直没找到可以复现的环境，麻烦问下什么云服务的机器，什么操作系统，docker 版本，centos 版本分别是什么，以便我复现问题，谢谢。 在QQ上已经问过你这个问题了 这个issue忘了取消 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

发了

**Comment by zhaojun1998** [comment]
已发布最新 docker 镜像解决。
