### ISSUE TITLE
下载大文件失败

### ISSUE THREAD

**Issue by e-chocolate** [zfile-dev/zfile#456]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：是
- 当前 ZFile 版本：4.1.2
- 是否尝试最新版是否已解决此问题：是
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：Windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome
- 做什么操作提示的错误？：文件下载
- 期望行为（应该是什么样的结果）：文件正常下载
- 当前行为（当前是什么样的结果）：下载大小为1024MB之后，立即报错“网络出现问题，无法下载”
- 错误日志（可选）：`error.log`，`warn.log`, `info.log`均无相关报错信息
- 复现步骤（可选）：
- 您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
- 什么存储类型的？如本地存储，OneDrive
- `网络出现问题，无法下载` 在哪提示的，ZFile 提示的，还是浏览器？
- `网络出现问题，无法下载` 这个错误是刚下载提示，还是大文件下载到 1G 后提示？

**Comment by Echlorine** [comment]
本地存储
Chrome浏览器提示，Zfile日志正常
刚下载一切正常，文件大于1G立即报错。

**Comment by e-chocolate** [comment]
> * 什么存储类型的？如本地存储，OneDrive
> * `网络出现问题，无法下载` 在哪提示的，ZFile 提示的，还是浏览器？
> * `网络出现问题，无法下载` 这个错误是刚下载提示，还是大文件下载到 1G 后提示？

本地存储
Chrome浏览器提示，Zfile日志正常
刚下载一切正常，文件大于1G立即报错。

**Comment by zhaojun1998** [comment]
@Echlorine 

应该是你 nginx 反向代理配置问题，你可以尝试访问 zfile 的端口，而不是反代后的端口来测试。

nginx 相关参数配置参考：

https://ms2008.github.io/2021/04/08/nginx-buffer/

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_max_temp_file_size

**Comment by e-chocolate** [comment]
> @Echlorine
> 
> 应该是你 nginx 反向代理配置问题，你可以尝试访问 zfile 的端口，而不是反代后的端口来测试。
> 
> nginx 相关参数配置参考：
> 
> https://ms2008.github.io/2021/04/08/nginx-buffer/
> 
> http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_max_temp_file_size

谢谢解答，刚刚测试了一下，确实是nginx反代的问题，笔芯！
