### ISSUE TITLE
feat: 能否添加一个ajax获取文件列表的功能？

### ISSUE THREAD

**Issue by WindowsRegedit** [zfile-dev/zfile#457]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：是
- 是否已尝试使用最新版本，且仍然没有此功能？：是
- 功能概述：添加文件使用ajax获取文件列表
- 功能动机：我有一个几千个文件的文件夹，用的是sharepoint国际版，比较慢。因为ajax刚好可以解决这个问题，所以能否添加一个这样的接口？
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
现在所有的接口调用都是 ajax 类型的异步请求啊，速度慢主要是因为与 SharePoint 之间的网络状况，还有浏览器渲染的速度。

还是说你还有其他的意思。

**Comment by WindowsRegedit** [comment]
我的意思是说可以在设置中设置一个”在文件夹里文件的数量比（）更多时，开启分页功能/其他分次序加载功能“这种类似的解决文件多的方案

**Comment by zhaojun1998** [comment]
@WindowsRegedit 

会考虑添加，但不一定能解决问题，不是所有存储类型 API 都支持分页查询的，如果存储类型不支持分页，加载 N 页，就需要消耗 N 倍的性能。而不是 1/N。

**Comment by WindowsRegedit** [comment]
我提供一种解决方案：可以使用serviceworker将已经获取到的文件列表存储下来，然后定时更新，或是手动点击刷新按钮刷新缓存。这样只有第一次查询会耗点时间。但如果该存储类型API可以分类查询，则不进行存储。

**Comment by zhaojun1998** [comment]
@WindowsRegedit 

是一个不错的建议，会加入到开发计划中
