### ISSUE TITLE
后端站点域名检测问题

### ISSUE THREAD

**Issue by fooler64** [zfile-dev/zfile#464]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：没有
- 当前 ZFile 版本：4.1.2
- 是否尝试最新版是否已解决此问题：没解决
- 是否尝试重启 ZFile，且问题依旧存在？：是的
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是的
- 操作系统（如 Windows、Mac、iOS、安卓）：windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：edge
- 做什么操作提示的错误？：将后端站点域名设置为http://[2409:8a28:62:****:****:****:****:****]:2560后显示“请输入正确的域名”
- 期望行为（应该是什么样的结果）：由于我想使用ipv6直接访问，而后端站点域名里似乎不允许带"[]"，但是想要用ipv6直接访问必须使用"[]"将ipv6地址框起来，这就导致我无法进行下载和预览以及上传，因为这样填写后端站点域名无法保存。
- 当前行为（当前是什么样的结果）：后端域名提示“请输入正确的域名”
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：
- 或许可以让用户手动取消域名检测。

**Comment by fooler64** [comment]
为了不暴露ip地址，ip后半段使用*好代替

**Comment by fooler64** [comment]
似乎没有人遇到过这个问题？

**Comment by fooler64** [comment]
<img width="1079" alt="屏幕截图 2022-11-23 130518" src="https://user-images.githubusercontent.com/106793369/203472520-78bd0c3b-1c77-4900-9992-7a7bb8356b0c.png">
这是图片。

**Comment by zhaojun1998** [comment]
这里暂不支持 ipv6 地址，临时解决办法是绑定一个域名，域名指向 ipv6 地址。

下个版本会增加这里对 ipv6 填写的支持。

**Comment by zhaojun1998** [comment]
@fooler64 

已发布新版本，支持了输入 ipv6。此 issue 关闭。
