### ISSUE TITLE
无法下载、播放包含加号的文件

### ISSUE THREAD

**Issue by PShawnKD35** [zfile-dev/zfile#47]
版本： 1.4.1
示例： https://zfile.com/file/The.Great.Buddha.+.2017.BluRay.1080p.x264C.DTS5.1-DTOne.mkv
报错： 404 FILE NOT FOUND

若播放则显示“视频加载失败”

文件名删除加号后正常： The.Great.Buddha.2017.BluRay.1080p.x264C.DTS5.1-DTOne.mkv

---------------------------------------
xxxxx@server:~$ uname -a
Linux localhost 3.18.71-Nosgoth_V7+ #1 SMP PREEMPT Sat Dec 14 13:17:47 MSK 2019 aarch64 aarch64 aarch64 GNU/Linux

**Comment by zhaojun1998** [comment]
@PShawnKD35 已更新版本
