### ISSUE TITLE
使用ARM架构机器搭建后，只要存储列表里有存储源，前端首页都会显示空白。

### ISSUE THREAD

**Issue by AMEMOES** [zfile-dev/zfile#475]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：是
- 当前 ZFile 版本：4.1.4（捐赠版）
- 是否尝试最新版是否已解决此问题：是
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：Windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome
- 做什么操作提示的错误？：使用ARM架构机器搭建后，只要存储列表里有存储源，前端首页都会显示空白。（使用域名反代）
- 期望行为（应该是什么样的结果）：显示存储。
- 当前行为（当前是什么样的结果）：前端显示空白。
- 错误日志（可选）：无
- 复现步骤（可选）：只要存储列表有存储源，就会复现。
- 您的额外信息（可选）：
- 1、使用AMD架构的机器未出现此问题，没有尝试过docker部署。
- 2、反代配置信息：
- #PROXY-START/

location /
{
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_http_version 1.1;
    # proxy_hide_header Upgrade;

    add_header X-Cache $upstream_cache_status;
    #Set Nginx Cache

    set $static_file75iY79fj 0;
    if ( $uri ~* "\.(gif|png|jpg|css|js|woff|woff2)$" )
    {
        set $static_file75iY79fj 1;
        expires 1m;
    }
    if ( $static_file75iY79fj = 0 )
    {
        add_header Cache-Control no-cache;
    }
}
#PROXY-END/

**Comment by zhaojun1998** [comment]
请提供地址，然后根据你的描述，根据我的猜测，可能是这种情况：

1. 捐赠版的校验只会在有存储源时，访问首页才会与授权服务器进行通信校验。所以有存储源，在你看来才是空白
2. 连接授权服务器有超时时间，我猜测是你 docker 容器内无法正常访问到授权服务器，可能是 dns 服务问题，也可能是容器内压根无法访问外网导致的。
3. 对于 2 所说的情况，请自行排查容器内 dns 是否正常，且是否可访问外网，可在对授权服务器进行测试可连接性： https://www.zfile.vip
4. 很可能是你 docker 配置问题，可尝试重启服务器，重启 docker，重启容器等方式来看看会不会恢复。
5. 之前有遇到过和你效果一样的，他当时是因为执行了其他的脚本，导致将系统内置的防火墙、网络等服务搞坏了，建议自行排查是否有对服务器做过相关操作，如确定完全纯净 ARM 环境，只安装了 docker 的情况，直接访问 docker 暴露的端口，即未经过任何 类似 nginx 之类的反向代理服务器的情况下，仍然有问题，那才能根据排除法确定是 zfile 本身的问题。

**Comment by zhaojun1998** [comment]
附：我自己也有 arm 架构的机器，是 oracle 的服务器，并没有这种问题，且未有其他使用捐赠版反馈 arm 无法使用的，所以可以根据排除法确定不是 arm 的问题，请按照上述的方式进行排查，对排查本身有问题，或有排查结果后，继续反馈 issue，我会持续跟进。

**Comment by AMEMOES** [comment]
目前我尝试过ping授权服务器能通，DNS解析也没有问题。
看了您的推测后结合实际，我觉得应该是系统环境或防火墙问题，因为我在安装zfile前可能对防火墙或系统环境做了错误更改。
如果有后续我会向您反馈的。

**Comment by zhaojun1998** [comment]
@AMEMOES

是否已解决，如未解决，可通过如下方式测试容器内网络：

1. 查看容器的 PID
```bash
docker inspect -f {{.State.Pid}} zfile-pro
```


2. 执行命令查看容器内：
```bash
nsenter -t <pid> -n curl https://www.zfile.vip
```

在我的环境就是：

```bash
# 通过三种方式测试网络连通性
 nsenter -t 4907 -n curl https://www.zfile.vip
 nsenter -t 4907 -n curl -I https://www.zfile.vip
 nsenter -t 4907 -n ping www.zfile.vip
```

如看不懂返回结果，可将结果复制到此 issue，我来诊断。

**Comment by AMEMOES** [comment]
已经解决，确认是系统环境问题导致的连通问题，感谢回复。
