### ISSUE TITLE
frp穿透后访问：当前无法使用此页面，未发送任何数据。

### ISSUE THREAD

**Issue by atticus-lv** [zfile-dev/zfile#477]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：无
- 当前 ZFile 版本：4.13
- 是否尝试最新版是否已解决此问题：否
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：群晖/docker
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome
- 做什么操作提示的错误？：
- 期望行为（应该是什么样的结果）：应该能够正常访问
- 当前行为（当前是什么样的结果）：当前无法使用此页面，未发送任何数据。
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：
使用腾讯轻量云，已开放端口，且其他docker服务能正常穿透
frp 配置如下，不清楚是不是出了什么问题，frp面板显示只有进数据没有出数据
```
[nas-zfile]
type = tcp
local_ip = 192.168.101.8
local_port = 8080
remote_port = 23337
```

**Comment by zhaojun1998** [comment]
只要内网能直接访问 zfile 服务的ip和端口。那就说明zfile是正常的，zfile也没有对任何形式的访问做限制。检查你frp服务和zfile服务联通性吧。还有防火墙。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月4日(周三) 上午7:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] frp穿透后访问：当前无法使用此页面，未发送任何数据。 (Issue #477)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个问题？：无
 
当前 ZFile 版本：4.13
 
是否尝试最新版是否已解决此问题：否
 
是否尝试重启 ZFile，且问题依旧存在？：是
 
是否已尝试清空浏览器缓存，且问题依旧存在？：是
 
操作系统（如 Windows、Mac、iOS、安卓）：群晖/docker
 
浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome
 
做什么操作提示的错误？：
 
期望行为（应该是什么样的结果）：应该能够正常访问
 
当前行为（当前是什么样的结果）：当前无法使用此页面，未发送任何数据。
 
错误日志（可选）：
 
复现步骤（可选）：
 
您的额外信息（可选）：
 使用腾讯轻量云，已开放端口，且其他docker服务能正常穿透
 frp 配置如下，不清楚是不是出了什么问题，frp面板显示只有进数据没有出数据
  [nas-zfile] type = tcp local_ip = 192.168.101.8 local_port = 8080 remote_port = 23337

**Comment by atticus-lv** [comment]
我再看看是咋回事

**Comment by atticus-lv** [comment]
已解决：frp容器和zfile容器重启顺序问题
