### ISSUE TITLE
feat: OneDrive如何自定义API？

### ISSUE THREAD

**Issue by hofaeair** [zfile-dev/zfile#480]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：否
- 是否已尝试使用最新版本，且仍然没有此功能？：文档里没有
- 功能概述：可以自定义api，不使用默认的 https://zfile.jun6.net/onedrive/callback
- 功能动机：遇到了 HTTP ERROR 429 ，应该是超过了api请求量限制导致的，想用自己的API，缓解一下数量
- 详细解释（可选）：官方文档里有写如何自定义 Google Drive的API，但没有写OneDrive的，我尝试自己直接创建一个应用，但授权的时候遇到了错误，所以想要问一下如何自定义API

**Comment by zhaojun1998** [comment]
请贴出错误信息



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月7日(周六) 上午9:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] feat: OneDrive如何自定义API？ (Issue #480)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个功能？：否
 
是否已尝试使用最新版本，且仍然没有此功能？：文档里没有
 
功能概述：可以自定义api，不使用默认的 https://zfile.jun6.net/onedrive/callback
 
功能动机：遇到了 HTTP ERROR 429 ，应该是超过了api请求量限制导致的，想用自己的API，缓解一下数量
 
详细解释（可选）：官方文档里有写如何自定义 Google Drive的API，但没有写OneDrive的，我尝试自己直接创建一个应用，但授权的时候遇到了错误，所以想要问一下如何自定义API

**Comment by hofaeair** [comment]
希望可以更新一下OneDrive自定义API的教程，无关错误。

**Comment by zhaojun1998** [comment]
这个百度上有很多，都是通用的，且据我了解429的阈值并不能通过更换api解决，他是账号级别的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月7日(周六) 上午9:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] feat: OneDrive如何自定义API？ (Issue #480)




 
希望可以更新一下OneDrive自定义API的教程，无关错误。

**Comment by hofaeair** [comment]
哦哦，这样啊。

**Comment by zhaojun1998** [comment]
你说了你用自定义api出错了，那得告诉我什么错误。我才能知道你哪里弄错了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月7日(周六) 上午9:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] feat: OneDrive如何自定义API？ (Issue #480)




 
希望可以更新一下OneDrive自定义API的教程，无关错误。

**Comment by hofaeair** [comment]
因为那个页面没有报错信息，只是返回失败。应该是密匙输错了。但不知道哪个值是要填的密匙什么的。

**Comment by hofaeair** [comment]
那就没事了，有空的话更新一下OD的，或者贴个其他地方的教程链接。因为密匙，ID啥的太难分清楚了。

**Comment by zhaojun1998** [comment]
@hofaeair 

https://docs.zfile.vip/advanced/onedrive-api
