### ISSUE TITLE
手机自带浏览器不能显示

### ISSUE THREAD

**Issue by woiplmm** [zfile-dev/zfile#481]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：
- 当前 ZFile 版本：4.1.3
- 是否尝试最新版是否已解决此问题：否
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：安卓
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：小米浏览器
- 做什么操作提示的错误？：手机自带浏览器不能显示，像小米手机浏览器不显示任何内容，空白一片，只在地址框里显示"zfile"，同部手机用kiwi能正常显示
- 期望行为（应该是什么样的结果）：希望能完善
- 当前行为（当前是什么样的结果）：故障依旧
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
请提供更详细的信息，如 MIUI 版本，浏览器版本，ZFile 地址。

我是测试环境为，是没有问题的：
小米 10 Pro MIUI 13 22.5.24
系统自带浏览器版本为 V17.2.97
测试 ZFile 地址为：https://demo.zfile.vip

你也可以用我的演示站 https://demo.zfile.vip 来测试是否能打开。

**Comment by woiplmm** [comment]
用演示站也试过
[image: z1.jpg]
[image: z2.jpg][image: z3.jpg]

赵俊 ***@***.***> 于2023年1月9日周一 19:59写道：

**Comment by gitbub10001** [comment]
有手机app吗

**Comment by zhaojun1998** [comment]
没有，目前也没有相关计划，目前对低版本浏览器兼容性已经做到了极致，无法再兼容了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月1日(周三) 上午10:56
收件人: ***@***.***&gt;;
抄送: "zhao ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 手机自带浏览器不能显示 (Issue #481)




 
有手机app吗

**Comment by gitbub10001** [comment]
怎么修改站点信息

**Comment by zhaojun1998** [comment]
@gitbub10001 

站点什么信息，另外不相干的请单独提交 issue，且在提交 issue 前自行搜索文档，软件所有设置，历史 issue，这种有没有 xxx 的，你没搜索到那就是没有。
