### ISSUE TITLE
上传文件夹，上传成功之后里面的目录结构混乱

### ISSUE THREAD

**Issue by mp-ui** [zfile-dev/zfile#485]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：是的
- 当前 ZFile 版本：4.1.3
- 是否尝试最新版是否已解决此问题：无
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：Windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome
- 做什么操作提示的错误？：无错误
- 期望行为（应该是什么样的结果）：上传文件夹之后目录结构应当正确
- 当前行为（当前是什么样的结果）：上传文件夹之后目录结构混乱
- 错误日志（可选）：
- 复现步骤（可选）：
存储源使用的是minio，版本为RELEASE.2021-04-22T15-44-28Z
需要上传的文件夹的目录结构如下：
├─A
│  │  1.txt
│  │  2.txt
│  │  3.txt
│  │
│  └─B
│-----│  4.txt
│-----│  5.txt
│-----│  6.txt
将文件夹A上传，上传成功之后目录结构不正确，如图所示：
![image](https://user-images.githubusercontent.com/61450971/212374833-67b97053-9800-4d5c-adca-4d1502a24bcd.png)
![image](https://user-images.githubusercontent.com/61450971/212374577-49fb6a1b-7949-4815-aa7d-a5b895f39dc4.png)
![image](https://user-images.githubusercontent.com/61450971/212374879-5af6e1b0-2428-45f3-b3bc-29cedaddb17c.png)
![image](https://user-images.githubusercontent.com/61450971/212374910-b7d73e17-1ef2-41c6-9774-3bb124108f10.png)

- 您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
感谢您的反馈，已经复现并查出了是同时上传文件数引发的 BUG，如果文件进入上传等待队列后，再唤醒，就会出现上传路径多次拼接的异常，我本地已经修改，预计会在春节期间发布新版本中解决这个问题。

**Comment by zhaojun1998** [comment]
@mp-ui 

已发布 4.1.4 版本修复了此问题
