### ISSUE TITLE
feat: 服务经Ngnix反向代理后，后台无法获取客户下载的真实ip，希望能支持

### ISSUE THREAD

**Issue by lamar8** [zfile-dev/zfile#491]
- 是否已搜索其他 issue，没有人提过这个功能？：无
- 是否已尝试使用最新版本，且仍然没有此功能？：是
- 功能概述：服务经Ngnix反向代理后，后台无法获取客户下载的真实ip，希望能支持
- 功能动机：
- 详细解释（可选）：
- 本菜鸡不懂java，大致定位到源码这个地方，但是不会编译java
- 
```
/**
 * @author zhaojun
 */
@WebFilter(urlPatterns = "/*")
public class MDCFilter implements Filter {
	
	@Override
	public void doFilter(ServletRequest request, ServletResponse response, FilterChain filterChain) throws IOException, ServletException {
		HttpServletRequest httpServletRequest = (HttpServletRequest) request;
		HttpServletResponse httpServletResponse = (HttpServletResponse) response;
		
		MDC.put(MdcConstant.TRACE_ID, IdUtil.fastUUID());

		//MDC.put(MdcConstant.IP, httpServletRequest.getHeader("X-Real-IP"));
//这里，可以根据Ngnix转发客户端真实ip的字段X-Real-IP（可伪装），再结合下面的判断真实ip，
//（我不懂java，也没装编译环境,代码不知道对不对）感谢大佬

		MDC.put(MdcConstant.IP, ServletUtil.getClientIP(httpServletRequest));

		MDC.put(MdcConstant.USER, StpUtil.isLogin() ? StpUtil.getLoginIdAsString() : "anonymous");
		
		try {
			filterChain.doFilter(httpServletRequest, httpServletResponse);
		} finally {
			MDC.clear();
		}
	}
	
}
```

**Comment by lamar8** [comment]
https://blog.51cto.com/u_116833/1707319
https://blog.csdn.net/qq_44949838/article/details/89461657
好像这两篇文章可以搞定

**Comment by zhaojun1998** [comment]
这个跟zfile没关系。不可能所有程序都单独需要给nginx适配才能用吧。
这是你nginx设置问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月30日(周一) 晚上9:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] feat: 服务经Ngnix反向代理后，后台无法获取客户下载的真实ip，希望能支持 (Issue #491)




  
是否已搜索其他 issue，没有人提过这个功能？：无
 
是否已尝试使用最新版本，且仍然没有此功能？：是
 
功能概述：服务经Ngnix反向代理后，后台无法获取客户下载的真实ip，希望能支持
 
功能动机：
 
详细解释（可选）：
 
本菜鸡不懂java，大致定位到源码这个地方，但是不会编译java
 

  /**  * @author zhaojun  */ @WebFilter(urlPatterns = "/*") public class MDCFilter implements Filter { 	 	@Override 	public void doFilter(ServletRequest request, ServletResponse response, FilterChain filterChain) throws IOException, ServletException { 		HttpServletRequest httpServletRequest = (HttpServletRequest) request; 		HttpServletResponse httpServletResponse = (HttpServletResponse) response; 		 		MDC.put(MdcConstant.TRACE_ID, IdUtil.fastUUID()); 		//MDC.put(MdcConstant.IP, httpServletRequest.getHeader("X-Real-IP")); //这里，可以根据Ngnix转发客户端真实ip的字段X-Real-IP（可伪装），再结合下面的判断真实ip， //（我不懂java，也没装编译环境,代码不知道对不对）感谢大佬 		MDC.put(MdcConstant.IP, ServletUtil.getClientIP(httpServletRequest)); 		MDC.put(MdcConstant.USER, StpUtil.isLogin() ? StpUtil.getLoginIdAsString() : "anonymous"); 		 		try { 			filterChain.doFilter(httpServletRequest, httpServletResponse); 		} finally { 			MDC.clear(); 		} 	} 	 }

**Comment by zhaojun1998** [comment]
我演示站也用了nginx反向代理，是宝塔默认反向代理，请求ip能正常获取。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月30日(周一) 晚上10:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [zfile-dev/zfile] feat: 服务经Ngnix反向代理后，后台无法获取客户下载的真实ip，希望能支持 (Issue #491)




 
https://blog.51cto.com/u_116833/1707319
 https://blog.csdn.net/qq_44949838/article/details/89461657
 好像这两篇文章可以搞定

**Comment by zhaojun1998** [comment]
长期无回复，先暂时关闭了。
