### ISSUE TITLE
feat: 存储源增加Samba服务

### ISSUE THREAD

**Issue by tianfeng98** [zfile-dev/zfile#493]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：是
- 是否已尝试使用最新版本，且仍然没有此功能？：是
- 功能概述：增加Samba服务存储源
- 功能动机：许多数据存储于Nas，可通过Samba协议进行数据交互，充分利用物理存储源。
- 详细解释（可选）：Linux系统安装smbclient命令可以很方便地操作Nas文件，集成到Java程序中应该不复杂。

**Comment by zhaojun1998** [comment]
@tianfeng98 

那欢迎您贡献代码。

**Comment by tianfeng98** [comment]
> @tianfeng98
> 
> 那欢迎您贡献代码。

直接贡献不太行，哈哈哈，我写JS的。我用Node写一个demo再回复这个issue。

**Comment by zhaojun1998** [comment]
Nas上不都支持docker么。直接docker将本地路径挂载到zfile容器中，按照本地存储添加更好一些。


Samba 还要额外中转一次。性能上。功能上都会差许多



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月5日(周日) 下午4:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] feat: 存储源增加Samba服务 (Issue #493)




  
@tianfeng98
 
那欢迎您贡献代码。
  
直接贡献不太行，哈哈哈，我写JS的。我用Node写一个demo再回复这个issue。

**Comment by zhaojun1998** [comment]
不会考虑这种方式了，有很多其他的协议可以完成同样的功能，samba 没有明显的优势。

**Comment by dreamskr** [comment]
linux没试过，但windows可以，用如下命令即可
`mklink /D G:\共享映射\共享链接1.29 \\192.168.1.29\share`

会将共享路径\\192.168.1.29\share，映射成本地一个文件夹G:\共享映射\共享链接1.29

**Comment by updsky** [comment]
强烈支持挂载smb，有些共享没办法通过本地的方式挂
