### ISSUE TITLE
当远程访问的客户机使用代理时，进度条持续加载且无法载入界面

### ISSUE THREAD

**Issue by nanaminato** [zfile-dev/zfile#494]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：没有
- 当前 ZFile 版本：
- 是否尝试最新版是否已解决此问题：
- 是否尝试重启 ZFile，且问题依旧存在？：
- 是否已尝试清空浏览器缓存，且问题依旧存在？：确实
- 操作系统（如 Windows、Mac、iOS、安卓）：windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：chrome
- 做什么操作提示的错误？：
- 期望行为（应该是什么样的结果）：
- 当前行为（当前是什么样的结果）：
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：关闭代理后，页面正常加载。页面加载成功之后，再使用代理重新加载也正常。

**Comment by zhaojun1998** [comment]
描述不清晰，请详细描述：
- 远程访问方式及所处网络
- 客户机操作系统及所处网络
- 浏览器 F12 控制台报错信息
- ZFile 日志中是否有报错信息
- 是否前后端分离了
- 代理是什么代理
- 是否确保每次测试都是新打开的无痕模式后仍然有问题。

**Comment by nanaminato** [comment]
出现问题时的： 
远程访问方式： 在客户机访问服务器
所处网络： 驻马店宽带  （网线连接路由器）
前后端未分离
代理是 shadowsocksR
-----------------------------------------------------

在开封电脑连接手机热点时工作正常，推测可能是网络运营商对某些js文件所在的服务器进行的屏蔽或者服务器无响应，导致程序无法加载完成
