### ISSUE TITLE
zfile配置cdn后无法访问

### ISSUE THREAD

**Issue by ilisuo** [zfile-dev/zfile#496]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：没有
- 当前 ZFile 版本：413
- 是否尝试最新版是否已解决此问题：未解决
- 是否尝试重启 ZFile，且问题依旧存在？：存在
- 是否已尝试清空浏览器缓存，且问题依旧存在？：存在
- 操作系统（如 Windows、Mac、iOS、安卓）：mac ios
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：chrome safari
- 做什么操作提示的错误？：无法访问
使用宝塔面板安装完成绑定了域名可以正常访问，使用腾讯cdn配置后无法打开提示发生了太多的重定向
配置如下：
宝塔面板配置file.a.com 域名并开启ssl。可以直接访问
腾讯云cdn配置file.b.com域名开启ssl，源站地址：file.a.com 回源host：file.a.com  访问file.b.com会跳转回源站file.a.com 
腾讯云cdn配置file.b.com域名开启ssl，源站地址：file.a.com 回源host：file.b.com  宝塔面板添加file.b.com域名，访问file.b.com会提示太多的重定向无法打开，
以上cdn配置使用alist，cloudreve都可以正常开启，唯独zfile无法使用。

**Comment by zhaojun1998** [comment]
@ilisuo 
首先我想说，这并不是 zfile 的问题，zfile 只负责默认暴露 8080 端口，剩下的全是你自己用其他软件或工具的额外设置。

且 zfile 本身没有也没有必要去限制 cdn 无法使用，有很多人使用各种各样的 cdn 都没有问题。

所以这是你自己设置宝塔或 cdn 的问题。

但我根据你的描述，猜测可能是你宝塔上 https 设置问题。

有以下几种可能：

1. 宝塔上 http 会自动跳转到 https，然后你 cdn 上回源的是 http 协议，所以导致  cdn(https) -> 宝塔(http) ->宝塔(https)
2. 浏览器或者 cdn 缓存（请每次测试都单独关闭所有无痕模式，然后打开一个无痕模式测试，来尽量避免本地的缓存）

我推荐你**分别**进行如下尝试：
-  关闭宝塔上的 https，然后确定 cdn 上回源协议是 http，同时宝塔上要同时添加 cdn 域名
-  不要使用宝塔的站点管理，直接让 cdn 回源 zfile 的端口，如果你没修改过，那这个端口是 8080

**Comment by zhaojun1998** [comment]
暂时关闭 issue 了，有问题再开新 issue 或重新开启此 issue
