### ISSUE TITLE
局域网下大文件传输崩溃

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [zfile-dev/zfile#499]
软件环境 树莓派4b + docker
Unable to round-trip http request to upstream: readfrom tcp 192.168.0.110:11971->192.168.0.113:8999: write tcp 192.168.0.110:11971->192.168.0.113:8999: wsasend: An existing connection was forcibly closed by the remote host.
![image](https://user-images.githubusercontent.com/27771529/219023906-4c5347e4-bce4-46c2-b3fd-25ce61ce3bc7.png)

**Comment by BrokenWingsIcarus** [comment]
运行日志
[+] Running 2/2
 ⠿ Network docker_default  Created                                                                                                                       0.1s
 ⠿ Container zfile         Created                                                                                                                      16.6s
Attaching to zfile
zfile  |  ________  ________ ___  ___       _______
zfile  | |\_____  \|\  _____\\  \|\  \     |\  ___ \
zfile  |  \|___/  /\ \  \__/\ \  \ \  \    \ \  ___
zfile  |      /  / /\ \   __\\ \  \ \  \    \ \  ___\
zfile  |     /  /_/__\ \  \_| \ \  \ \  \____\ \  _____
zfile  |    |\________\ \__\   \ \__\ \_______\ \_______\
zfile  |     \|_______|\|__|    \|__|\|_______|\|_______|
zfile  | 2023-02-15 20:21:32.285  INFO 7 --- [                                    ] [          ] [               ] [kground-preinit] o.h.validator.internal.util.Version      21     : HV000001: Hibernate Validator 6.2.3.Final
zfile  | 2023-02-15 20:21:32.519  INFO 7 --- [                                    ] [          ] [               ] [           main] im.zhaojun.zfile.ZfileApplication        55     : Starting ZfileApplication v4.1.3 using Java 1.8.0_352 on 85b94fef4605 with PID 7 (/root/app.jar started by root in /root)
zfile  | 2023-02-15 20:21:32.525  INFO 7 --- [                                    ] [          ] [               ] [           main] im.zhaojun.zfile.ZfileApplication        651    : The following 1 profile is active: "prod"
zfile  | 2023-02-15 20:21:45.182  INFO 7 --- [                                    ] [          ] [               ] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  108    : Tomcat initialized with port(s): 8999 (http)
zfile  | 2023-02-15 20:21:45.235  INFO 7 --- [                                    ] [          ] [               ] [           main] o.a.coyote.http11.Http11NioProtocol      173    : Initializing ProtocolHandler ["http-nio-8999"]
zfile  | 2023-02-15 20:21:45.241  INFO 7 --- [                                    ] [          ] [               ] [           main] o.apache.catalina.core.StandardService   173    : Starting service [Tomcat]
zfile  | 2023-02-15 20:21:45.244  INFO 7 --- [                                    ] [          ] [               ] [           main] org.apache.catalina.core.StandardEngine  173    : Starting Servlet engine: [Apache Tomcat/9.0.63]
zfile  | 2023-02-15 20:21:45.576  INFO 7 --- [                                    ] [          ] [               ] [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       173    : Initializing Spring embedded WebApplicationContext
zfile  | 2023-02-15 20:21:45.579  INFO 7 --- [                                    ] [          ] [               ] [           main] w.s.c.ServletWebServerApplicationContext 290    : Root WebApplicationContext: initialization completed in 12725 ms
zfile  | 2023-02-15 20:21:46.695  INFO 7 --- [                                    ] [          ] [               ] [           main] com.zaxxer.hikari.HikariDataSource       110    : HikariPool-1 - Starting...
zfile  | 2023-02-15 20:21:47.247  INFO 7 --- [                                    ] [          ] [               ] [           main] com.zaxxer.hikari.HikariDataSource       123    : HikariPool-1 - Start completed.
zfile  | 2023-02-15 20:21:47.700  INFO 7 --- [                                    ] [          ] [               ] [           main] o.f.c.internal.license.VersionPrinter    44     : Flyway Community Edition 7.15.0 by Redgate
zfile  | 2023-02-15 20:21:47.707  INFO 7 --- [                                    ] [          ] [               ] [           main] o.f.c.i.database.base.BaseDatabaseType   44     : Database: jdbc:sqlite:/root/.zfile-v4/db/zfile (SQLite 3.36)
zfile  | 2023-02-15 20:21:47.984  INFO 7 --- [                                    ] [          ] [               ] [           main] o.f.core.internal.command.DbValidate     44     : Successfully validated 11 migrations (execution time 00:00.149s)
zfile  | 2023-02-15 20:21:48.015  INFO 7 --- [                                    ] [          ] [               ] [           main] o.f.core.internal.command.DbMigrate      44     : Current version of schema "main": 13
zfile  | 2023-02-15 20:21:48.018  WARN 7 --- [                                    ] [          ] [               ] [           main] o.f.core.internal.command.DbMigrate      48     : outOfOrder mode is active. Migration of schema "main" may not be reproducible.
zfile  | 2023-02-15 20:21:48.022  INFO 7 --- [                                    ] [          ] [               ] [           main] o.f.core.internal.command.DbMigrate      44     : Schema "main" is up to date. No migration necessary.
zfile  |  _ _   |_  _ _|_. ___ _ |    _
zfile  | | | |\/|_)(_| | |_\  |_)||_|_\
zfile  |      /               |
zfile  |                         3.5.2
zfile  | 2023-02-15 20:22:00.783  INFO 7 --- [                                    ] [          ] [               ] [           main] i.z.z.m.s.context.StorageSourceContext   88     : 启动时初始化存储源成功, 存储源 id: [2], 存储源类型: [本地存储], 存储源名称: [本地存储2]
zfile  | 2023-02-15 20:22:00.800  INFO 7 --- [                                    ] [          ] [               ] [           main] i.z.z.m.s.context.StorageSourceContext   88     : 启动时初始化存储源成功, 存储源 id: [1], 存储源类型: [本地存储], 存储源名称: [本地存储]
zfile  | 2023-02-15 20:22:06.674  INFO 7 --- [                                    ] [          ] [               ] [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    53     : Adding welcome page: class path resource [static/index.html]
zfile  | 2023-02-15 20:22:08.700  INFO 7 --- [                                    ] [          ] [               ] [           main] o.a.coyote.http11.Http11NioProtocol      173    : Starting ProtocolHandler ["http-nio-8999"]
zfile  | 2023-02-15 20:22:08.820  INFO 7 --- [                                    ] [          ] [               ] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  220    : Tomcat started on port(s): 8999 (http) with context path ''
zfile  | 2023-02-15 20:22:09.245  INFO 7 --- [                                    ] [          ] [               ] [nio-8999-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       173    : Initializing Spring DispatcherServlet 'dispatcherServlet'
zfile  | 2023-02-15 20:22:09.250  INFO 7 --- [                                    ] [          ] [               ] [nio-8999-exec-1] o.s.web.servlet.DispatcherServlet        525    : Initializing Servlet 'dispatcherServlet'
zfile  | 2023-02-15 20:22:09.263  INFO 7 --- [                                    ] [          ] [               ] [nio-8999-exec-1] o.s.web.servlet.DispatcherServlet        547    : Completed initialization in 10 ms
zfile  | 2023-02-15 20:22:14.142  INFO 7 --- [                                    ] [          ] [               ] [           main] im.zhaojun.zfile.ZfileApplication        61     : Started ZfileApplication in 45.075 seconds (JVM running for 48.15)
zfile  | 2023-02-15 20:22:16.051  INFO 7 --- [385ad67f-854e-404c-90d6-d78126e8edae] [ anonymous] [  192.168.0.110] [nio-8999-exec-6] i.z.z.m.r.service.ReadmeConfigService    156    : 存储源 1 规则模式获取目录 /zifile/db 下文档信息
zfile  | 2023-02-15 20:22:20.076  INFO 7 --- [fd53ecb9-6ccf-494d-924f-65e2ad324bfa] [ anonymous] [  192.168.0.110] [nio-8999-exec-8] i.z.z.m.r.service.ReadmeConfigService    156    : 存储源 1 规则模式获取目录 /zifile 下文档信息
zfile  | 2023-02-15 20:22:24.120  INFO 7 --- [                                    ] [          ] [               ] [   scheduling-1] i.z.z.m.s.s.AccessTokenRefreshSchedule   31     : 开始执行需要定期刷新 AccessToken 存储源的定时任务
zfile  | 2023-02-15 20:22:24.122  INFO 7 --- [                                    ] [          ] [               ] [   scheduling-1] i.z.z.m.s.s.AccessTokenRefreshSchedule   48     : 执行需要定期刷新 AccessToken 存储源的定时任务完成
zfile  | 2023-02-15 20:22:43.905  INFO 7 --- [b63995c6-b394-40a9-a69d-51d9689c4697] [     admin] [  192.168.0.110] [nio-8999-exec-4] i.z.z.m.r.service.ReadmeConfigService    156    : 存储源 2 规则模式获取目录 / 下文档信息




zfile  | 2023-02-15 20:29:44.562 ERROR 7 --- [5d1cc0cd-39e3-41c8-8c16-07ae53b27852] [     admin] [  192.168.0.110] [nio-8999-exec-7] i.z.z.c.e.h.GlobalExceptionHandler       215    : Failed to parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.impl.IOFileUploadException: Processing of multipart/form-data request failed. java.net.SocketTimeoutException
zfile  |
zfile  | org.springframework.web.multipart.MultipartException: Failed to parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.impl.IOFileUploadException: Processing of multipart/form-data request failed. java.net.SocketTimeoutException
zfile  |        at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.handleParseFailure(StandardMultipartHttpServletRequest.java:124)
zfile  |        at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.parseRequest(StandardMultipartHttpServletRequest.java:115)
zfile  |        at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.<init>(StandardMultipartHttpServletRequest.java:88)
zfile  |        at org.springframework.web.multipart.support.StandardServletMultipartResolver.resolveMultipart(StandardServletMultipartResolver.java:122)
zfile  |        at org.springframework.web.servlet.DispatcherServlet.checkMultipart(DispatcherServlet.java:1205)
zfile  |        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
zfile  |        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
zfile  |        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
zfile  |        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
zfile  |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
zfile  |        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
zfile  |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
zfile  |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
zfile  |        at im.zhaojun.zfile.module.storage.filter.DownloadLinkFilter.doFilter(DownloadLinkFilter.java:124)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
zfile  |        at im.zhaojun.zfile.core.filter.MDCFilter.doFilter(MDCFilter.java:35)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
zfile  |        at im.zhaojun.zfile.core.filter.CorsFilter.doFilter(CorsFilter.java:38)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
zfile  |        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
zfile  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
zfile  |        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
zfile  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
zfile  |        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
zfile  |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
zfile  |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
zfile  |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
zfile  |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
zfile  |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
zfile  |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
zfile  |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
zfile  |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
zfile  |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
zfile  |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
zfile  |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
zfile  |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
zfile  |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
zfile  |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
zfile  |        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
zfile  |        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
zfile  |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
zfile  |        at java.lang.Thread.run(Thread.java:826)
zfile  | Caused by: java.io.IOException: org.apache.tomcat.util.http.fileupload.impl.IOFileUploadException: Processing of multipart/form-data request failed. java.net.SocketTimeoutException
zfile  |        at org.apache.catalina.connector.Request.parseParts(Request.java:2977)
zfile  |        at org.apache.catalina.connector.Request.parseParameters(Request.java:3263)
zfile  |        at org.apache.catalina.connector.Request.getParameter(Request.java:1141)
zfile  |        at org.apache.catalina.connector.RequestFacade.getParameter(RequestFacade.java:381)
zfile  |        at cn.dev33.satoken.servlet.model.SaRequestForServlet.getParam(SaRequestForServlet.java:48)
zfile  |        at cn.dev33.satoken.stp.StpLogic.getTokenValueNotCut(StpLogic.java:209)
zfile  |        at cn.dev33.satoken.stp.StpLogic.getTokenValue(StpLogic.java:173)
zfile  |        at cn.dev33.satoken.stp.StpLogic.getLoginIdDefaultNull(StpLogic.java:676)
zfile  |        at cn.dev33.satoken.stp.StpLogic.isLogin(StpLogic.java:589)
zfile  |        at cn.dev33.satoken.stp.StpUtil.isLogin(StpUtil.java:240)
zfile  |        at im.zhaojun.zfile.core.filter.MDCFilter.doFilter(MDCFilter.java:32)
zfile  |        ... 33 common frames omitted
zfile  | Caused by: org.apache.tomcat.util.http.fileupload.impl.IOFileUploadException: Processing of multipart/form-data request failed. java.net.SocketTimeoutException
zfile  |        at org.apache.tomcat.util.http.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:292)
zfile  |        at org.apache.catalina.connector.Request.parseParts(Request.java:2932)
zfile  |        ... 43 common frames omitted
zfile  | Caused by: org.apache.catalina.connector.ClientAbortException: java.net.SocketTimeoutException
zfile  |        at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:321)
zfile  |        at org.apache.catalina.connector.InputBuffer.checkByteBufferEof(InputBuffer.java:599)
zfile  |        at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:339)
zfile  |        at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:132)
zfile  |        at org.apache.tomcat.util.http.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:975)
zfile  |        at org.apache.tomcat.util.http.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:879)
zfile  |        at java.io.InputStream.read(InputStream.java:101)
zfile  |        at org.apache.tomcat.util.http.fileupload.util.Streams.copy(Streams.java:97)
zfile  |        at org.apache.tomcat.util.http.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:288)
zfile  |        ... 44 common frames omitted
zfile  |        Suppressed: org.apache.catalina.connector.ClientAbortException: java.net.SocketTimeoutException
zfile  |                at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:321)
zfile  |                at org.apache.catalina.connector.InputBuffer.checkByteBufferEof(InputBuffer.java:599)
zfile  |                at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:339)
zfile  |                at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:132)
zfile  |                at org.apache.tomcat.util.http.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:975)
zfile  |                at org.apache.tomcat.util.http.fileupload.MultipartStream$ItemInputStream.close(MultipartStream.java:919)
zfile  |                at org.apache.tomcat.util.http.fileupload.MultipartStream$ItemInputStream.close(MultipartStream.java:898)
zfile  |                at org.apache.tomcat.util.http.fileupload.util.Streams.copy(Streams.java:93)
zfile  |                ... 45 common frames omitted
zfile  |        Caused by: java.net.SocketTimeoutException: null
zfile  |                at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1309)
zfile  |                at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1226)
zfile  |                at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:805)
zfile  |                at org.apache.coyote.http11.Http11InputBuffer.access$400(Http11InputBuffer.java:42)
zfile  |                at org.apache.coyote.http11.Http11InputBuffer$SocketInputBuffer.doRead(Http11InputBuffer.java:1185)
zfile  |                at org.apache.coyote.http11.filters.IdentityInputFilter.doRead(IdentityInputFilter.java:101)
zfile  |                at org.apache.coyote.http11.Http11InputBuffer.doRead(Http11InputBuffer.java:249)
zfile  |                at org.apache.coyote.Request.doRead(Request.java:640)
zfile  |                at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:316)
zfile  |                ... 52 common frames omitted
zfile  | Caused by: java.net.SocketTimeoutException: null
zfile  |        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1309)
zfile  |        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1226)
zfile  |        at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:805)
zfile  |        at org.apache.coyote.http11.Http11InputBuffer.access$400(Http11InputBuffer.java:42)
zfile  |        at org.apache.coyote.http11.Http11InputBuffer$SocketInputBuffer.doRead(Http11InputBuffer.java:1185)
zfile  |        at org.apache.coyote.http11.filters.IdentityInputFilter.doRead(IdentityInputFilter.java:101)
zfile  |        at org.apache.coyote.http11.Http11InputBuffer.doRead(Http11InputBuffer.java:249)
zfile  |        at org.apache.coyote.Request.doRead(Request.java:640)
zfile  |        at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:316)
zfile  |        ... 52 common frames omitted

**Comment by zhaojun1998** [comment]
@BrokenWingsIcarus 

- 是刚上传时就报错，还是到一半，还是到最后才报错？
- 大约上传多久后才出现此报错？
- 上传时传输速度大概是多少？

**Comment by BrokenWingsIcarus** [comment]
1. 初始时速约10m/s, 后续稳定在6m/s， 出现错误后迅速上升到20~50m/s 直至以错误方式完成。
2. 上传约5分钟左右。
3. 上传到其中一部分的时候报错，初始不报错。

**Comment by BrokenWingsIcarus** [comment]
现在文件成功上传了，应该是网络波动原因导致的。但是希望本地数据源能够支持断点续传和多线程上传。
