### ISSUE TITLE
文件夹加密不生效问题

### ISSUE THREAD

**Issue by dreamskr** [zfile-dev/zfile#501]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：否
- 当前 ZFile 版本：4.1.3
- 是否尝试最新版是否已解决此问题：是
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome和360浏览器
- 做什么操作提示的错误？：
- 期望行为（应该是什么样的结果）：修改password_config的规则后，马上生效
- 当前行为（当前是什么样的结果）：使用MySQL，直接修改表password_config，添加一些文件夹密码规则，但不生效。通过后台管理页面进行设置文件夹规则，马上就生效了。
- 错误日志（可选）：
- 复现步骤（可选）：
1.在后台管理界面，设置一些规则，如下图。访问时正常弹出密码输入框。
![后台规则](https://user-images.githubusercontent.com/43511466/220096730-0c43915e-96ba-4e68-89ed-7a6dcb70129b.png)

2.直接修改password_config，增删改一些规则，如下图
![数据库表](https://user-images.githubusercontent.com/43511466/220097212-0b7c5c8c-df6c-4555-a142-2d645d65ba91.png)
新录入的规则不生效，访问时直接进入了，未弹出密码框
![前端界面](https://user-images.githubusercontent.com/43511466/220097059-a9ad5b88-2f32-48f3-a3e0-4745018b7c49.png)

3.此时，通过管理后台查看规则，界面的规则没变，跟修改数据库前的一样
![后台规则](https://user-images.githubusercontent.com/43511466/220097472-74fdbe9b-886b-417c-aa2d-e92e479ed126.png)

试过更换Chrome，360浏览器、更换电脑登录，后台界面仍如上图所示，未从数据表password_config获取最新规则。

- 您的额外信息（可选）：

因为一些业务场景需要，需要自动生成目录及文件、加密，并自动发送邮件给用户访问地址及密码。目前在第三方软件实现自动生成目录及文件、并在password_config表添加规则，但密码未生效，还请帮忙解决，谢谢

**Comment by zhaojun1998** [comment]
因为系统为了速度，做了缓存。读取一次后，未在zfile中变更。不会再次读取数据库。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月20日(周一) 晚上7:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 文件夹加密不生效问题 (Issue #501)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个问题？：否
 
当前 ZFile 版本：4.1.3
 
是否尝试最新版是否已解决此问题：是
 
是否尝试重启 ZFile，且问题依旧存在？：是
 
是否已尝试清空浏览器缓存，且问题依旧存在？：是
 
操作系统（如 Windows、Mac、iOS、安卓）：windows
 
浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome和360浏览器
 
做什么操作提示的错误？：
 
期望行为（应该是什么样的结果）：修改password_config的规则后，马上生效
 
当前行为（当前是什么样的结果）：使用MySQL，直接修改表password_config，添加一些文件夹密码规则，但不生效。通过后台管理页面进行设置文件夹规则，马上就生效了。
 
错误日志（可选）：
 
复现步骤（可选）：
 1.在后台管理界面，设置一些规则，如下图。访问时正常弹出密码输入框。
 
  
2.直接修改password_config，增删改一些规则，如下图
 
 新录入的规则不生效，访问时直接进入了，未弹出密码框
 
 
3.此时，通过管理后台查看规则，界面的规则没变，跟修改数据库前的一样
 
 
试过更换Chrome，360浏览器、更换电脑登录，后台界面仍如上图所示，未从数据表password_config获取最新规则。
  
您的额外信息（可选）：
  
因为一些业务场景需要，需要自动生成目录及文件、加密，并自动发送邮件给用户访问地址及密码。目前在第三方软件实现自动生成目录及文件、并在password_config表添加规则，但密码未生效，还请帮忙解决，谢谢

**Comment by dreamskr** [comment]
本地数据库，速度非常快的，这点都可以忽略不计了吧？或者是否可以加一个刷新缓存的功能或接口？

**Comment by zhaojun1998** [comment]
你可以直接调用后台登录接口后再调用保存密码接口。访问zfile地址 /doc.html就是接口文档



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月20日(周一) 晚上8:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 文件夹加密不生效问题 (Issue #501)




 
本地数据库，速度非常快的，这点都可以忽略不计了吧？或者是否可以加一个刷新缓存的功能或接口？

**Comment by dreamskr** [comment]
接口文档没这个接口，但试过了在后台管理界面修改密码、保存基本设置、保存存储源信息都不行，进入密码设置，仍然是一样的，缓存未更新

**Comment by zhaojun1998** [comment]
@dreamskr 
1. 如有密码规则 1、规则 2，在 ZFile 中添加的，会写入到数据库，并存储到缓存中。
2. 这时你手动修改数据库增加了规则 3，由于 ZFIle 读取的是缓存，所以在 ZFIle 中还认为是两条数据。
3. 如果这时你去 ZFile 后台保存该规则（这时是还是规则1，规则2），保存的是页面上的数据，也不会读取到你直接修改数据库的数据，且此时会覆盖你直接修改数据库的数据。
4. 想让 ZFile 读取到最新的数据而不是缓存，你只能重启 ZFile，让缓存消失。这时第一次读取到的就是数据库的值了，但仅仅是第一次。后续的操作还是上述的步骤 1 - 3
5. 确实是有这个接口的，如图，先调用登录接口，拿到后台 token 后，再获取或设置存储源的密码规则即可。
![image](https://user-images.githubusercontent.com/35387985/220518284-2ec893fd-1bcd-4844-beaa-04c8d9242b29.png)

**Comment by dreamskr** [comment]
收到，谢谢

**Comment by zhaojun1998** [comment]
@dreamskr 

最新版本在配置文件中增加了配置项 `zfile.dbCache.enable=true`，将值设置为 false 后重启 zfile，将不再使用缓存，而是直接读取数据库
