### ISSUE TITLE
新安装无法打开页面

### ISSUE THREAD

**Issue by maolog** [zfile-dev/zfile#502]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：已搜索，无此问题
- 当前 ZFile 版本：4.1.3
- 是否尝试最新版是否已解决此问题：用的最新版
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：Windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome和EDGE
- 做什么操作提示的错误？：显示空白页
- 期望行为（应该是什么样的结果）：进入系统
- 当前行为（当前是什么样的结果）：空白页
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：访问url:[https://share.maolog.com](https://share.maolog.com)
- 部署方式：Docker-compose和Jdk部署都尝试，同样的问题。

**Comment by zhaojun1998** [comment]
是 cf 的问题，以此进入 cf 设置："速度" -> “优化” -> "Auto Minify" 取消勾选右侧的三个选项。然后在 cf 控制台清楚缓存，再清除你浏览器的缓存，然后再访问，如果还不行，那就过十分钟后重复上述操作。

**Comment by maolog** [comment]
> 是 cf 的问题，以此进入 cf 设置："速度" -> “优化” -> "Auto Minify" 取消勾选右侧的三个选项。然后在 cf 控制台清楚缓存，再清除你浏览器的缓存，然后再访问，如果还不行，那就过十分钟后重复上述操作。

非常感谢作者，确实是CF的设置问题，已解决，此Issue可以关闭了
