### ISSUE TITLE
上传的html不能直接预览，上传的contentType 不对

### ISSUE THREAD

**Issue by suheng1222** [zfile-dev/zfile#506]
<img width="1200" alt="539798c88980eaedc05c61a89cc469c" src="https://user-images.githubusercontent.com/97278817/222376566-d0cc30e9-3819-43f8-809d-841b4c70ec99.png">

**Comment by zhaojun1998** [comment]
@suheng1222 

用其他工具上传，contentType  是什么，预期值是什么，用的其他工具是什么。不能直接预览指的是在 zfile 中，还是在这个火山平台中

**Comment by zhaojun1998** [comment]
暂无反馈，只能先关闭问题了，有反馈再打开
