### ISSUE TITLE
feat: 关于捐赠的一些建议

### ISSUE THREAD

**Issue by fooler64** [zfile-dev/zfile#509]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：
- 是否已尝试使用最新版本，且仍然没有此功能？：
- 功能概述：
- 功能动机：捐赠版过于昂贵（对于我这种学生来说188还是有一点贵了）
- 详细解释（可选）：本人没有足够的预算购买捐赠版，先前开发者对于我的需求解决的十分爽快，希望能有一个打赏链接，挺担心就此不做这个项目了，这样我这种用开源版本的也可以捐一些进行赞助。

**Comment by zhaojun1998** [comment]
不需要，学生就安心用社区版即可，近期内不用担心不维护的。学生用钱多用来学习就行，无需捐赠。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月4日(周六) 晚上7:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] feat: 关于捐赠的一些建议 (Issue #509)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个功能？：
 
是否已尝试使用最新版本，且仍然没有此功能？：
 
功能概述：
 
功能动机：捐赠版过于昂贵（对于我这种学生来说188还是有一点贵了）
 
详细解释（可选）：本人没有足够的预算购买捐赠版，先前开发者对于我的需求解决的十分爽快，希望能有一个打赏链接，挺担心就此不做这个项目了，这样我这种用开源版本的也可以捐一些进行赞助。
