### ISSUE TITLE
u-file的ftp挂载错误

### ISSUE THREAD

**Issue by linanyang** [zfile-dev/zfile#51]
u-file直链云加速的ftp，手机ES文件浏览器挂载正常,zfile却挂载不上。不知道是不是用户名的原因，u-file的用户名有特殊字符 / ,用户名为yayde/uf1121

**Comment by zhaojun1998** [comment]
@linanyang 

u-file 直接使用 upyun，填操作员账号和密码

**Comment by zhaojun1998** [comment]
不过 FTP 功能确实有问题，我会解决的

**Comment by linanyang** [comment]
用又拍云添加，文件目录可以列出来，但是所有文件无法下载。显示错误为404，你要访问的页面或文件不存在。视频也没法播放。

**Comment by zhaojun1998** [comment]
@linanyang  填写加速域名了吗

**Comment by linanyang** [comment]
没有

**Comment by zhaojun1998** [comment]
@linanyang  经测试，u-file 不绑定域名，单独使用 ftp，是会有许多问题的。

**Comment by linanyang** [comment]
好的，谢谢了
