### ISSUE TITLE
feat: 公共用户上传功能

### ISSUE THREAD

**Issue by hapxoby** [zfile-dev/zfile#510]
是否可以支持其他用户或者游客可以上传文件的功能呢

**Comment by zhaojun1998** [comment]
- 目前社区版支持开放文件管理功能给所有人，不区分管理员还是匿名用户
- 目前捐赠版支持控制管理员和匿名用户每个操作的权限（上传、删除、预览、下载）。
- 下个大版本会新增多用户支持
