### ISSUE TITLE
feat: 大文件（text）分段预览（10G的txt大文件无法在线预览）

### ISSUE THREAD

**Issue by shuangt** [zfile-dev/zfile#511]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：无
- 是否已尝试使用最新版本，且仍然没有此功能？：是
- 功能概述：预览上G的text文件，需要完全加载到客户端本地才有可能打开，能否提供流式的分段预览
- 功能动机：
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
我想即使上 G 的文件，本地客户端打开也是很吃力的，更别说限制资源更加严格的浏览器了。这个不会支持。
