### ISSUE TITLE
feat: 查询性能似乎不是很好

### ISSUE THREAD

**Issue by caixintian123** [zfile-dev/zfile#512]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：是
- 是否已尝试使用最新版本，且仍然没有此功能？：是
- 功能概述：1）我在演示站的搜索场景下，查询速度似乎有点慢，在数据量上升之后，当前的这个架构性能可以达到什么样的级别？
2）网盘一般会有分享功能，有些文件可以可以分享给其他用户，并对这个分享文件做一定的权限控制
- 功能动机：
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
zfile 和其他类型的网盘不一样，zfile 不存储文件和文件夹的索引到数据库。而是直接通过存储引擎对应的 API 去获取文件列表，文件信息。

如果是本地存储，就使用操作系统的 API。
如果是云存储，如阿里云 OSS，就调用他的 HTTP API。

本地存储的话，获取的速度还是很快的，单文件夹查询的时间可以低到毫秒甚至更低。
但云存储等的话，发起一条 HTTP 请求，这个损耗就难以预估了，可能 0.1 秒，如果是国外的云存储，你服务器又是国内的，那1 秒都有可能，这是无法避免也是无法改变的。

继续回到搜索的话题上，既然上面描述了 ZFile 不存储所有文件和文件夹信息，那根据关键字搜索内容时，只能去调用 API。先调用根目录获取所有文件和文件夹，然后再依次获取这些文件夹下的子文件和子文件夹，以此类推，直到遍历完成所有文件夹。那你可以计算下，如果一个云存储，里面有 1000 个文件夹，以较快的网络请求，每个 0.1 秒来计算，理想状态，不考虑任何损耗下，查询速度需要 100 秒。
你可能会想，能不能查询一次后缓存起来，这样下次查询就不用调用 API 了，但这样你在存储源直接操作文件的话，ZFile 中的缓存并没有刷新，数据不一致也会很麻烦。

或者严格意义上，ZFile 不能算网盘，只能算文件目录展示。你可以去阿里、腾讯、七牛、亚马逊的对象存储看看，看看有没有全盘搜索功能。

你想你希望要的可能是 cloudreve，他会将你上传的每个文件，创建的每个文件夹都存储到数据库，这样查询不需要去访问存储源 API ，速度是飞快的，但是，这样的话，如果你的存储源本身有数据的话，无法在 cloudreve 中看到，你直接修改存储源中的数据，也无法在 cloudreve 中看到。

关于你说的分享，ZFile 正在做多用户，到时候会在权限上做一些补充，但这个过程会比较长。
