### ISSUE TITLE
feat: 画廊模式预览建议调用压缩后的低分辨率图片

### ISSUE THREAD

**Issue by tim1103** [zfile-dev/zfile#513]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：是
- 是否已尝试使用最新版本，且仍然没有此功能？：是
- 功能概述：画廊模式预览时，调用压缩后的低分辨率图片，加快加载速度
- 功能动机：测试时发现画廊页面如果图片较大加载比较慢
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
这个如果使用服务器压缩的话，需要服务器先下载所有图片，压缩后再返回。整个过程会经过服务器中转，会消耗大量服务器的上行下行带宽，且如果是第三方存储源（非本地存储），那么看到查看图片的速度，就取决于你服务器的带宽了。但是大部分人使用的都是国内 1 - 5 Mbps的带宽，实际的可能会更卡，且服务器的网卡、CPU 会被大量消耗
