### ISSUE TITLE
feat:docker用户希望增加保存配置的功能，每次升级都要重新配置一遍。

### ISSUE THREAD

**Issue by nxliubo** [zfile-dev/zfile#514]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：是
- 是否已尝试使用最新版本，且仍然没有此功能？：是
- 功能概述：docker安装，希望增加保存配置的功能，每次升级都要重新配置一遍。
- 功能动机：升级不便
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
我文档安装教程的 docker 说明中，有相关说明的，且是有特殊标注的。建议您再去看下文档： https://docs.zfile.vip/install/os-docker

```bash {3,4}
docker run -d --name=zfile --restart=always \
    -p 8080:8080 \
    -v /root/zfile/db:/root/.zfile-v4/db \
    -v /root/zfile/logs:/root/.zfile-v4/logs \
    -v /root/zfile/file:/data/file \
    zhaojun1998/zfile
```

第三行和第四行就是为了将容器内的数据目录和日志目录映射到宿主机上，这样即使 docker 容器删除再重建，只要宿主机上的目录不删除，数据就不会丢失。

**Comment by nxliubo** [comment]
> 我文档安装教程的 docker 说明中，有相关说明的，且是有特殊标注的。建议您再去看下文档： https://docs.zfile.vip/install/os-docker
> 
> ```shell
> docker run -d --name=zfile --restart=always \
>     -p 8080:8080 \
>     -v /root/zfile/db:/root/.zfile-v4/db \
>     -v /root/zfile/logs:/root/.zfile-v4/logs \
>     -v /root/zfile/file:/data/file \
>     zhaojun1998/zfile
> ```
> 
> 第三行和第四行就是为了将容器内的数据目录和日志目录映射到宿主机上，这样即使 docker 容器删除再重建，只要宿主机上的目录不删除，数据就不会丢失。

我知道问题在哪里了，原来是内部文件夹改成了这个.zfile-v4，原来没有-v4，从V3升级后，没有注意这个变化。谢谢！
