### ISSUE TITLE
安装启动成功后 创建本地模式储存源失败提示 文件不存在

### ISSUE THREAD

**Issue by Lafatalite** [zfile-dev/zfile#516]
安装成功后启动程序第一次启动失败再次启动成功，进入网页设置管理员账号密码，进入储存源设置 本地源模式  创建失败 提示文件创建失败 
[ZFile 诊断日志 - 2023-03-26 13_12_01.zip](https://github.com/zfile-dev/zfile/files/11070888/ZFile.-.2023-03-26.13_12_01.zip)

**Comment by zhaojun1998** [comment]
是docker启动的么



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月26日(周日) 中午1:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 安装启动成功后 创建本地模式储存源失败提示 文件不存在 (Issue #516)




 
安装成功后启动程序第一次启动失败再次启动成功，进入网页设置管理员账号密码，进入储存源设置 本地源模式  创建失败 提示文件创建失败
 ZFile 诊断日志 - 2023-03-26 13_12_01.zip

**Comment by Lafatalite** [comment]
并不是，是真机运行的 系统是ubuntu 2204

**Comment by zhaojun1998** [comment]
是新建存储源时就报错？请截图 zfile 中存储源如何设置的，还有操作系统文件绝对目录下的文件（确保文件夹存在）

**Comment by Lafatalite** [comment]
![数据源截图](https://user-images.githubusercontent.com/35282465/227767312-7e93ec56-d519-4b93-8729-8c5c22e72027.png)
![文件目录](https://user-i
![error信息](https://user-images.githubusercontent.com/35282465/227767614-f1d6baab-b29c-4e62-990d-c91a53afdcd0.png)
mages.githubusercontent.com/35282465/227767395-c5e591da-6a91-4235-9bac-3c08088654ef.png)

**Comment by Lafatalite** [comment]
![页面截图](https://user-images.githubusercontent.com/35282465/227767704-c87822f9-484c-491b-bbd2-256bd5861da4.png)
![文件目录](https://user-images.githubusercontent.com/35282465/227767707-80f1b3c6-d4a9-4acc-9a98-5848ecaf5c9c.png)
![error信息](https://user-images.githubusercontent.com/35282465/227767710-af58935b-07ad-4c12-8739-02da788238ac.png)

**Comment by zhaojun1998** [comment]
文件目录要写绝对路径。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月26日(周日) 下午5:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 安装启动成功后 创建本地模式储存源失败提示 文件不存在 (Issue #516)

**Comment by Lafatalite** [comment]
可以了 这个相对路径的设置是为docker设计的吗 开始设置的的时候 路径格式错误 页面提示有前缀路径 就没有写全路径

**Comment by zhaojun1998** [comment]
一直都是绝对路径，且这个输入框下方有提示的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月26日(周日) 晚上7:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 安装启动成功后 创建本地模式储存源失败提示 文件不存在 (Issue #516)




 
可以了 这个相对路径的设置是为docker设计的吗 开始设置的的时候 路径格式错误 页面提示有前缀路径 就没有写全路径
