### ISSUE TITLE
feat: zfile如何下载文件夹，目前只能一次下载一个文件

### ISSUE THREAD

**Issue by shbone** [zfile-dev/zfile#519]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：
- 是否已尝试使用最新版本，且仍然没有此功能？：
- 功能概述：
- 功能动机：
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
重复 issue，参考 https://github.com/zfile-dev/zfile/issues/278   https://github.com/zfile-dev/zfile/issues/291
