### ISSUE TITLE
feat: 图片能加一个直接访问选项吗，不下载，应该是返回浏览器的content-type 决定的

### ISSUE THREAD

**Issue by lunasaw** [zfile-dev/zfile#521]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：
- 是否已尝试使用最新版本，且仍然没有此功能？：
- 功能概述：
- 功能动机：
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
在直链后增加参数 `type=preview` 会优先让浏览器自动解析，而不是强制下载 ，注意，仅本地存储、FTP、SFTP 等下载通过 ZFile 的存储源支持这个参数，其他诸如亚马逊 S3、OneDrive 等都是第三方链接，zfile 无法控制其默认行为。

示例：

原链接：`http://127.0.0.1:8080/s/54f8rj`
修改后：`http://127.0.0.1:8080/s/54f8rj?type=preview`

如果原来 url 中已经带了参数，需要将 ? 改为 &，如：


原链接：`http://127.0.0.1:8080/s/54f8rj?param1=value1`
修改后：`http://127.0.0.1:8080/s/54f8rj?param1=value1&type=preview`

**Comment by lunasaw** [comment]
第三方链接可以考虑本地转存吗

**Comment by lunasaw** [comment]
> 在直链后增加参数 `type=preview` 会优先让浏览器自动解析，而不是强制下载 ，注意，仅本地存储、FTP、SFTP 等下载通过 ZFile 的存储源支持这个参数，其他诸如亚马逊 S3、OneDrive 等都是第三方链接，zfile 无法控制其默认行为。
> 
> 
> 
> 示例：
> 
> 
> 
> 原链接：`http://127.0.0.1:8080/s/54f8rj`
> 
> 修改后：`http://127.0.0.1:8080/s/54f8rj?type=preview`
> 
> 
> 
> 如果原来 url 中已经带了参数，需要将 ? 改为 &，如：
> 
> 
> 
> 
> 
> 原链接：`http://127.0.0.1:8080/s/54f8rj?param1=value1`
> 
> 修改后：`http://127.0.0.1:8080/s/54f8rj?param1=value1&type=preview`
> 
> 

第三方链接可以考虑本地转存吗
