### ISSUE TITLE
onedirve是故意写成这样的吗？

### ISSUE THREAD

**Issue by ghost** [zfile-dev/zfile#53]
`README.md` 中有 <https://zfile.jun6.net/onedirve/callback>，我看着有点奇怪，就试着搜`onedirve`，搜到了6处，是故意这么写的吗？

**Comment by zhaojun1998** [comment]
@1una 没明白你什么意思。

**Comment by ghost** [comment]
> 
> 
> @1una 没明白你什么意思。

`onedirve`和`onedrive`是不同的，我想知道这是拼错了还是故意这么写的。

**Comment by lcxw** [comment]
> > @1una 没明白你什么意思。
> 
> `onedirve`和`onedrive`是不同的，我想知道这是拼错了还是故意这么写的。

可能是手误，老哥观察得好仔细啊😂

**Comment by zhaojun1998** [comment]
@1una  是，刚发现，是手误。
