### ISSUE TITLE
无效的或初始化失败的存储源

### ISSUE THREAD

**Issue by Hreint** [zfile-dev/zfile#531]
- 是否已搜索其他 issue，没有人提过这个问题？：是
- 是否已查阅、搜索 [ZFile 文档](https://docs.zfile.vip)，尤其是常见问题页，仍然未解决？：是
- 当前 ZFile 版本：4.1.4
- 是否尝试最新版是否已解决此问题：否
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：Windows 10
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome 
- 做什么操作提示的错误？：在“显示设置”关闭“根目录显示所有存储源”之后，点击后台管理页面左上方的 Zfile 图标返回主页，此时网页左上方“首页”这两个字的左边会多出一个向右的箭头，并且点击“首页”会弹出“无效的或初始化失败的存储”的错误提示，但其实不存在任何问题。
![2023-05-04_170620](https://user-images.githubusercontent.com/64591583/236161111-f78e632a-2bd9-4be3-a8bd-f3d52f8de97f.jpg)

**Comment by zhaojun1998** [comment]
@Hreint 
最新版本已修复
