### ISSUE TITLE
feat: 希望可以添加复制存储源功能

### ISSUE THREAD

**Issue by waitsaber** [zfile-dev/zfile#533]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：是
- 是否已尝试使用最新版本，且仍然没有此功能？：是
- 功能概述：比如我添加了onedriveA并设置了文件过滤、权限等设置，再添加onedriveB的时候可以直接复制OneDriveA的所有设置然后进行api信息的修改，这样可以提升效率。
- 功能动机：因为OneDrive的速度不稳定，各运营商下载的速度不一样有的快有的慢，创建了多个onedrive反代后需要重复的添加存储源然后添加反代域名。
- 详细解释（可选）：可以在存储源界面添加一个“复制”的按钮，点击后自动生成一个新的存储源，新的存储源与被复制的存储源的设置保持一致，且两个存储源都可以独立进行修改而不是以软连接的形式出现。

**Comment by zhaojun1998** [comment]
@waitsaber 

已发布最新版本支持了该功能
