### ISSUE TITLE
IOS safari浏览器 列表无法拖到底部

### ISSUE THREAD

**Issue by noisky** [zfile-dev/zfile#54]
具体如图所示：
不带公告：https://img.ffis.me/images/2020/02/21/22.gif
![不带公告](https://img.ffis.me/images/2020/02/21/22.gif)
带公告：https://img.ffis.me/images/2020/02/21/1.gif
![带公告](https://img.ffis.me/images/2020/02/21/1.gif)

**Comment by zhaojun1998** [comment]
@noisky  更新最新版试试，更换了滚动加载方式。
