### ISSUE TITLE
前端文件夹密码缓存写死问题

### ISSUE THREAD

**Issue by kinshaoyue** [zfile-dev/zfile#548]
1.第一次设置文件夹密码，之后在浏览器中保存。
2.修改文件夹密码之后，发现频繁报文件夹密码错误。修改浏览器保存的密码也没用，f12查看
![image](https://github.com/zfile-dev/zfile/assets/133950736/baab2ffd-2cd5-4586-9c5b-2b29c95fa206)
3.说明密码似乎第一次写入之后，保存到本地前端页面内部了？

**Comment by zhaojun1998** [comment]
是会保存密码到浏览器啊，最新版已经加了是否保存的勾选。自由选择。

**Comment by zhaojun1998** [comment]
改密码了，当然会提示报错了，你再输入成功一次，保存的就是成功的密码了
