### ISSUE TITLE
feat: 添加Swagger功能配置开启或关闭或认证访问  避免暴露Swagger API 

### ISSUE THREAD

**Issue by blsm136** [zfile-dev/zfile#549]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：
- 是否已尝试使用最新版本，且仍然没有此功能？：
- 功能概述：
- 功能动机：
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
zfile 使用的是 [knife4j](https://doc.xiaominfo.com/v2/)，你可以通过以下配置关闭或添加访问密码：

关闭：
```
knife4j.production=true
```

添加访问密码：
```
knife4j.basic.enable=true
knife4j.basic.username=xxx
knife4j.basic.password=yyy
```

详见文档：https://doc.xiaominfo.com/v2/documentation/accesscontrol.html
