### ISSUE TITLE
登录页提示Cannot load from short array because "sun.awt.FontConfiguration.head" is null

### ISSUE THREAD

**Issue by RogerHuOut** [zfile-dev/zfile#550]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：没有
- 是否已查阅、搜索 [ZFile 文档](https://docs.zfile.vip)，尤其是常见问题页，仍然未解决？：是的
- 当前 ZFile 版本：4.1.5
- 是否尝试最新版是否已解决此问题：依旧存在
- 是否尝试重启 ZFile，且问题依旧存在？：依旧存在
- 是否已尝试清空浏览器缓存，且问题依旧存在？：依旧存在
- 操作系统（如 Windows、Mac、iOS、安卓）：windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：chrome
- 做什么操作提示的错误？：访问login页面
- 期望行为（应该是什么样的结果）：
- 当前行为（当前是什么样的结果）：
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
通常是你的 jdk 问题或者操作系统中不包含某些字体库导致的，你服务器是什么操作系统，什么部署方式。

**Comment by zhaojun1998** [comment]
长时间未反馈，关闭 issue，有问题再重新打开
