### ISSUE TITLE
这个搜索逻辑不行啊！

### ISSUE THREAD

**Issue by ghost** [zfile-dev/zfile#553]
![image](https://github.com/zfile-dev/zfile/assets/95120835/d2ccc345-e486-4993-9117-db44f0795855)

直接默认搜全部，回车就搜索。需要指定文件夹，再去指定

**Comment by ghost** [comment]
![image](https://github.com/zfile-dev/zfile/assets/95120835/fe28dab9-2ac4-4b33-87a1-2ba4de27c7b9)


搜索放左边更好，一般都搜文件名，而文件名就在左边。


首页也居中一点。


后台管理放到不起眼的位置。

**Comment by zhaojun1998** [comment]
左边有面包屑啊。放到左边面包屑一动，搜索跟着动也太怪了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月15日(周四) 上午10:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [zfile-dev/zfile] 这个搜索逻辑不行啊！ (Issue #553)




 

 
搜索放左边更好，一般都搜文件名，而文件名就在左边。
 
首页也居中一点。
 
后台管理放到不起眼的位置。

**Comment by ghost** [comment]
> 面包屑

https://down.52pojie.cn/

**Comment by zhaojun1998** [comment]
这属于个人喜好，无法根据你一个人的需求让所有人都这样。你可以自己用自定义css调整位置。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月15日(周四) 上午10:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 这个搜索逻辑不行啊！ (Issue #553)




  
面包屑
  
https://down.52pojie.cn/
