### ISSUE TITLE
生成的直链不能正常下载，但是短链可以

### ISSUE THREAD

**Issue by seagullz4** [zfile-dev/zfile#555]
- 当前 ZFile 版本：最新
- 是否尝试最新版是否已解决此问题：否
- 是否尝试重启 ZFile，且问题依旧存在？：对
- 是否已尝试清空浏览器缓存，且问题依旧存在？：对
- 操作系统（如 Windows、Mac、iOS、安卓）：安卓
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：ch
- 做什么操作提示的错误？：下载文件
- 期望行为（应该是什么样的结果）：直接下载文件成功
- 当前行为（当前是什么样的结果）：弹出一堆乱码
- 网页显示如下  
{"code":500,"msg":"Required URI template variable 'storageKey' for method parameter type String is not present","data":null,"dataCount":null,"traceId":"edd86539-e921-4bcc-bbb7-8fba91e93a1d"}

![Screenshot_20230620_192839_com.lemurbrowser.exts.jpg](https://github.com/zfile-dev/zfile/assets/96653729/2490502e-abcc-44e5-9a38-15b54eb81844)

**Comment by zhaojun1998** [comment]
给个短链和直链的示例链接，域名部分可以隐去。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月20日(周二) 晚上7:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 生成的直链不能正常下载，但是短链可以 (Issue #555)




  
当前 ZFile 版本：最新
 
是否尝试最新版是否已解决此问题：否
 
是否尝试重启 ZFile，且问题依旧存在？：对
 
是否已尝试清空浏览器缓存，且问题依旧存在？：对
 
操作系统（如 Windows、Mac、iOS、安卓）：安卓
 
浏览器（如 Chrome、Firefox、Safari，X 浏览器）：ch
 
做什么操作提示的错误？：下载文件
 
期望行为（应该是什么样的结果）：直接下载文件成功
 
当前行为（当前是什么样的结果）：弹出一堆乱码
 
网页显示如下
 {"code":500,"msg":"Required URI template variable 'storageKey' for method parameter type String is not present","data":null,"dataCount":null,"traceId":"edd86539-e921-4bcc-bbb7-8fba91e93a1d"}

**Comment by zhaojun1998** [comment]
这个已经复现，是修改过直链前缀后，会发生这个，重启 zfile 后就正常了，下个版本会修复

**Comment by abai569ok** [comment]
这个bug   4.1.5版了还没修复
