### ISSUE TITLE
开源版文件夹密码不记住的时候会多次弹出

### ISSUE THREAD

**Issue by Aqr-K** [zfile-dev/zfile#556]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：没有
- 是否已查阅、搜索 [ZFile 文档](https://docs.zfile.vip)，尤其是常见问题页，仍然未解决？：无法解决
- 当前 ZFile 版本：4.1.5
- 是否尝试最新版是否已解决此问题：无法解决
- 是否尝试重启 ZFile，且问题依旧存在？：存在
- 是否已尝试清空浏览器缓存，且问题依旧存在？：和缓存关系不大
- 操作系统（如 Windows、Mac、iOS、安卓）：
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：
- 做什么操作提示的错误？：
- 期望行为（应该是什么样的结果）：
- 当前行为（当前是什么样的结果）：
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：安装的是docker版zfile，前面加了nginx反代，但不管是内网还是公网，用不用反代问题都存在

我在公共电脑上打开zfile时不想保存密码，但是输入文件夹密码不勾选记住的时候，进入二级目录重新返回一级目录会需要重新输入密码
如`/demo`文件夹设置了密码，我进入`/demo`的时候输入密码但不记住的情况下，进入/demo/test1没有问题，但我从`/demo/test1`返回/demo文件夹想进入`/demo/test2`的时候，`/demo`文件夹会重新弹出密码认证
希望能解决二级目录返回一级目录时密码框多次弹出问题

**Comment by zhaojun1998** [comment]
这不是bug啊，既然都不记住密码了。当然重新进入该目录要重新输入密码。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月20日(周二) 晚上11:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 开源版文件夹密码不记住的时候会多次弹出 (Issue #556)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个问题？：没有
 
是否已查阅、搜索 ZFile 文档，尤其是常见问题页，仍然未解决？：无法解决
 
当前 ZFile 版本：4.1.5
 
是否尝试最新版是否已解决此问题：无法解决
 
是否尝试重启 ZFile，且问题依旧存在？：存在
 
是否已尝试清空浏览器缓存，且问题依旧存在？：和缓存关系不大
 
操作系统（如 Windows、Mac、iOS、安卓）：
 
浏览器（如 Chrome、Firefox、Safari，X 浏览器）：
 
做什么操作提示的错误？：
 
期望行为（应该是什么样的结果）：
 
当前行为（当前是什么样的结果）：
 
错误日志（可选）：
 
复现步骤（可选）：
 
您的额外信息（可选）：安装的是docker版zfile，前面加了nginx反代，但不管是内网还是公网，用不用反代问题都存在
  
我在公共电脑上打开zfile时不想保存密码，但是输入文件夹密码不勾选记住的时候，进入二级目录重新返回一级目录会需要重新输入密码
 如/demo文件夹设置了密码，我进入/demo的时候输入密码但不记住的情况下，进入/demo/test1没有问题，但我从/demo/test1返回/demo文件夹想进入/demo/test2的时候，/demo文件夹会重新弹出密码认证
 希望能解决二级目录返回一级目录时密码框多次弹出问题

**Comment by Aqr-K** [comment]
严格上来说，不算退出了这个目录吧，
举个例子，我给根目录设置了密码，然后进入了他的子目录，再怎么说子目录也属于根目录的管辖范围内吧，可是现在是子目录返回根目录就弹出密码框，个人觉得只要一返回就重新输入就有点复杂化了，如果我需要在公共电脑上找个素材，来回切一次就输入一次密码，这不就很浪费效率吗？
能不能变成根目录输入密码后，其下的子目录返回根目录时不会重新弹出密码框，应该可以改成识别ip是否在线，超过多久无反应请求就自动退出密码，这样就不用在返回根目录却换到第二个子目录时也要次次输入密码了

**Comment by Aqr-K** [comment]
密码短还好，手打就行，密码长的就得复制，然后次次粘贴重新输入了

**Comment by zhaojun1998** [comment]
那如果你进入了 /demo/1，人走了，别人直接回退回去 /demo 就能看你加密的文件？这样合理吗。


所有的安全性都是会牺牲方便的，你要用公共电脑真想安全。就应该用无痕模式，或者离开时清空浏览器缓存。这样即使记住密码也被清了。


或者你设计一个即安全又方便的机制，能说服我就可以改。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月21日(周三) 上午7:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 开源版文件夹密码不记住的时候会多次弹出 (Issue #556)




 
严格上来说，不算退出了这个目录吧，
 举个例子，我给根目录设置了密码，然后进入了他的子目录，再怎么说子目录也属于根目录的管辖范围内吧，可是现在是子目录返回根目录就弹出密码框，个人觉得只要一返回就重新输入就有点复杂化了，如果我需要在公共电脑上找个素材，来回切一次就输入一次密码，这不就很浪费效率吗？
 能不能变成根目录输入密码后，其下的子目录返回根目录时不会重新弹出密码框，应该可以改成识别ip是否在线，超过多久无反应请求就自动退出密码，这样就不用在返回根目录却换到第二个子目录时也要次次输入密码了

**Comment by Aqr-K** [comment]
现在我只想到一个解决方法，我只能加多一个目录的层级了，根目录给个二级子目录，然后三级目录再拆分为不同的同级目录，然后我切换不同的子目录是在二级目录里，不用过根目录的多次验证，可这样就相当于多了一个目录层级了，目前版本也没有移动文件夹的功能，又得用ssh进入后台进行层级的移动，很不方便啊

**Comment by Aqr-K** [comment]
我想想，能不能弄个监听，网页处于打开状态的情况下会进行检测，检测用户离开时间，超时后直接打开/demo/1会404或者直接显示超时无法访问，或者有多个密码的目录，可以自动跳回最顶级的需要密码的根目录里重新输入密码啥的，这样应该能保证安全和便捷同时存在吧
很多网页有类似的功能，一定时间没有访问请求，会自动推迟登录状态，能不能做个类似的

**Comment by zhaojun1998** [comment]
我觉得并不合理，也不符合用户直觉，且每个人认为的离开时间也不同。
在离开时间内，也保证不了安全，你的数据等于还是裸露状态。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月21日(周三) 上午7:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 开源版文件夹密码不记住的时候会多次弹出 (Issue #556)




 
我想想，能不能弄个监听，网页处于打开状态的情况下会进行检测，检测用户离开时间，超时后直接打开/demo/1会404或者直接显示超时无法访问，或者有多个密码的目录，可以自动跳回最顶级的需要密码的根目录里重新输入密码啥的，这样应该能保证安全和便捷同时存在吧
 很多网页有类似的功能，一定时间没有访问请求，会自动推迟登录状态，能不能做个类似的

**Comment by Aqr-K** [comment]
可是你目前的密码也不安全啊，我试过了，现在的文件夹加密只在根目录上，如果我知道了二级目录的地址，我直接改网址路径就可以访问，甚至不用进入密码认证的过程，最简单的泄露方法，被人后面瞄到了这个文件夹叫啥，那我这整个文件夹就不安全了，也就说我要是想完全避免泄露，我只能一个一个文件夹设置密码，工作量太大了

**Comment by zhaojun1998** [comment]
有没有可能，密码文件夹的规则支持通配符。你可以自由的控制只加密根目录还是所有子目录，在密码设置页的上方有详细的描述。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月21日(周三) 上午7:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 开源版文件夹密码不记住的时候会多次弹出 (Issue #556)




 
可是你目前的密码也不安全啊，我试过了，现在的文件夹加密只在根目录上，如果我知道了二级目录的地址，我直接改网址路径就可以访问，甚至不用进入密码认证的过程，最简单的泄露方法，被人后面瞄到了这个文件夹叫啥，那我这整个文件夹就不安全了，也就说我要是想完全避免泄露，我只能一个一个文件夹设置密码，工作量太大了

**Comment by Aqr-K** [comment]
我也试过通配符了
现在的问题是只根目录加密的情况下，我只需要输入一次密码就能进入二级目录，但我如果不访问根目录，直接输入子目录地址，照样能进入
这就导致我根目录进行加密的意义不大了，但是如果我对子目录加密，子目录其下的三级目录加密以此类推，这就意味着我用正常方式打开就得输入好几次密码，每次返回上级目录也是
或者试试，能不能做到同ip同User Agen的情况下，在根目录与其下子目录同密码的时候，子目录不会重新跳出密码认证，子目录返回根目录的时候也是。
然后这个登录状态的超时时间就用心跳包的方式，如每多少秒发送一次心跳，如果网页心跳断了，就会彻底退出登录，恢复到需要重新输入密码的状态，这样应该能在维持安全的情况下，也保证了方便性，你觉得可行吗？

**Comment by Aqr-K** [comment]
还有，现在我只是单单从下载的链接里，我就能获取到这个文件所在的真是路径，不管是直链还是短链最后跳转的/pd/后面跟着的肯定是真实路径地址，所以只要我分享过给别人下载，那就已经存在子目录泄漏的可能性，这就导致子目录不是公开的那就必须加密，这就进入一个很奇怪的圈里了，
目录与其下所有目录不加密就存在泄密可能，但是我全部目录加密，在正常使用的时候就会在疯狂打密码，想不打这么多密码就得不加密，不加密就会容易泄露，想不泄露就还得回去加密

**Comment by Aqr-K** [comment]
在我个人看来，不记住密码应该是不让浏览器进行密码的缓存，而不是我这次访问还没结束的时候，每次切换文件夹都跟我要一个密码

**Comment by zhaojun1998** [comment]
@Aqr-K 

你这前后太矛盾了，且很多功能你都没试过，没翻文档或看 zfile 上的说明， 你就说没有这个功能，你这是不负责任且浪费双方时间的

1. 你既然只加密了根目录，子目录自然不受密码保护，这不是必然的吗。
2. 你想保护子目录，但是指向加密二级目录也能通过配置通配符解决啊，* 表示子目录，** 表示所有子目录。甚至你可以写 /demo/video* 之类的，支持这个功能你懒得配置，还想要安全性，这怎么可能啊。
3. ip、ua、心跳这些是把简单问题复杂化，并没有真正解决安全问题，本来你在一个公共电脑上，也只是存储到你使用的浏览器上啊，ua 和 ip 根本不会变。至于心跳，首先是性能问题，其次也不能解决问题。
4. 下载链接泄露路径，这个你可以去后台关闭直链啊，只使用短链就行了。
5. 最开始我就给了你完美的解决方案，使用浏览器专门的无痕模式，或者离开电脑时清除浏览器缓存，这样你既可以享受保存密码的便利性，又可以在离开时，清理密码。

**Comment by Aqr-K** [comment]
你说的这些功能我都在用，我甚至把论坛也看过两边了
我直链开着是因为要用3d功能，你在issued里写着需要打开直链才能使用，
我也知道二级目录三级目录都能用通配符解决加密，我现在就是用/**进行全部子目录加密
可这还是无法解决需要多次输入密码的问题，我现在访问一个文件夹就得复制密码一直确定，每次都要密码很影响效率
还有如果从管理页面点击文档，是打开旧的docs.zhaojun.im网址，不知道是不是我容器还是配置文件是老的配置文件的原因，我一直没管
现在是在想能不能找到一个居中的方法，不影响安全的情况下，更简单的使用ui打开各级文件夹，减少输入密码的次数，太繁琐了   dT-Tb

**Comment by zhaojun1998** [comment]
那你能先回答下，**为什么公共电脑不使用无痕模式或离开时清空浏览器缓存吗**，无痕模式本身就是浏览器专门给你这种场景设计的啊，关闭无痕窗口后自动清理一切记录。

还关于密码问题，我会增加一个选项，支持设置保存密码的期限：
- 30 分钟
- 1 小时
- 1 天
- 关闭所有 zfile 窗口后

**Comment by Aqr-K** [comment]
如果是自己还好，因为无法保证我分享的人能否在使用我搭建的网站的时候会不会做无痕，这就导致了我的数据有泄露出事的风险了

**Comment by zhaojun1998** [comment]
如果别人知道文件夹密码，你永远无法管住，只要对方想泄露，无论多么复杂的防范，你都没办法。

**Comment by Aqr-K** [comment]
你说的对，无法彻底杜绝泄露，
不过咱们讨论点好像有点歪了，变成了泄露与安全上了，现在我纠结的问题点在于，多层级目录的多层级多次输入密码上，
虽然这个多层级能做同样的密码，但照样是要弹出密码框
我的意思是能不能在不影响安全性的情况下，适当性的解决同主目录下不同子目录间的密码框问题，为了安全，全目录密码没问题，但是弹出太多了，我9层目录就弹9次，还没算同级别不同类型的目录呢

**Comment by zhaojun1998** [comment]
我上面不给出解决方案了么，

会增加一个选项，支持设置保存密码的期限：

30 分钟
1 小时
1 天
关闭所有 zfile 窗口后

**Comment by Aqr-K** [comment]
哦哦哦，好的，那就等下个版本上线看看效果先了，打扰了，耽误你时间了
