### ISSUE TITLE
onlyoffice无法正常预览文件，提示"下载失败"

### ISSUE THREAD

**Issue by luoji111** [zfile-dev/zfile#558]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：没有
- 是否已查阅、搜索 [ZFile 文档](https://docs.zfile.vip)，尤其是常见问题页，仍然未解决？：是
- 当前 ZFile 版本：zfile 4.1.4
- 是否尝试最新版是否已解决此问题：是，但无法解决该问题
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：服务器操作系统: Debian GNU/Linux 11 aarch64   客户端操作系统: windows 11 22h2
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：microsoft edge (114.0.1823.51)
- 做什么操作提示的错误？：onlyoffice文档预览
- 期望行为（应该是什么样的结果）：能正常预览office文件
- 当前行为（当前是什么样的结果）：预览office文件 (例如docx) 时提示"下载失败"，无法预览
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：onlyoffice-server是以docker方式部署的，由于我的操作系统是aarch64架构的，我是直接按照onlyoffice的[官方帮助文档](https://helpcenter.onlyoffice.com/installation/docs-community-install-docker-arm64.aspx)部署的

**Comment by zhaojun1998** [comment]
预览的原理是 onlyoffice 服务器下载你 zfile 的文件，请先排查两者之间网络是否通畅，如 zfile 写的本地或局域网地址，onlyoffice 可能无法访问。或者给出你 zfile 地址。

**Comment by zhaojun1998** [comment]
长时间未反馈，关闭 issue，有问题再重新打开

**Comment by CHN-STUDENT** [comment]
话说 onlyOffice能关闭么，内网当个网盘用，不让大家在线预览了，只用下载看 @zhaojun1998

**Comment by zhaojun1998** [comment]
@CHN-STUDENT 

1. 可以在用户管理关闭指定用户的预览权限（包含所有类型）
2. 去下图设置去掉要预览的文件类型
<img width="1431" alt="Image" src="https://github.com/user-attachments/assets/9777c6ed-d873-4d04-8cad-9bd2b9473087" />
