### ISSUE TITLE
能不能更新一个使用宝塔面板java管理器的教程呢？

### ISSUE THREAD

**Issue by mengxiangke** [zfile-dev/zfile#56]
强迫症太厉害，

**Comment by zhaojun1998** [comment]
为什么非要用那个，现在我的文档中，已经描述过，如何通过命令行安装 JDK，及启动，还有通过宝塔反向代理的教程

**Comment by mengxiangke** [comment]
> 什么非要用那个，现在我

我有点强迫症，总想把所有东西，集中在一块。我用宝塔java管理器的设置方法配置zfile不能用，是不是不能用这个java管理器啊。没学过java，容易问zz问题。

**Comment by zhaojun1998** [comment]
他那个管理器安装的是 JDK11，程序不兼容
