### ISSUE TITLE
feat: 能添加Bucket 域名 / CDN 加速域名的下载链接吗？

### ISSUE THREAD

**Issue by leveychen** [zfile-dev/zfile#561]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：已经搜索，没有看到相关功能
- 是否已尝试使用最新版本，且仍然没有此功能？：是的
- 功能概述：在下载分享页面显示基于Bucket 域名 / CDN 加速域名的下载链接
- 功能动机：由于ZFile网盘建立在内网，网盘本身不对外开发，只允许内网访问（云存储是开放式的），但有时候需要把云存储上面的文件分享给其他人，如果能直接复制基于Bucket 域名 / CDN 加速域名的下载链接，这样就能直接分享给小伙伴能在外网直接下载了。
- 详细解释（可选）：
- 如功能动机

**Comment by zhaojun1998** [comment]
不考虑这种情况，需求面很小，别人用不到，你可以自己在内网下载，然后去下载记录复制系统自动跳转到的最终下载链接给别人。
