### ISSUE TITLE
华为手机浏览器下载文件 暂停了再开始就会重新下载

### ISSUE THREAD

**Issue by liorest** [zfile-dev/zfile#562]
华为手机浏览器下载文件 暂停了再开始就会重新开始从零下载

**Comment by zhaojun1998** [comment]
什么存储类型，用pc或其他设备是否正常



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月7日(周五) 晚上11:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 华为手机浏览器下载文件 暂停了再开始就会重新下载 (Issue #562)




 
华为手机浏览器下载文件 暂停了再开始就会重新开始从零下载

**Comment by liorest** [comment]
> 什么存储类型，用pc或其他设备是否正常
> [...](#)
> ---原始邮件--- 发件人： ***@***.***> 发送时间: 2023年7月7日(周五) 晚上11:07 收件人： ***@***.***>; 抄送： ***@***.***>; 主题： [zfile-dev/zfile] 华为手机浏览器下载文件 暂停了再开始就会重新下载 （Issue #562） 华为手机浏览器下载文件 暂停了再开始就会重新开始从零下载 — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您订阅了此线程。消息 ID： ***@***.***>

我测试的是，pc和夸克浏览器正常，就是华为浏览器下载暂停会重新开始。
我之前仿写了一个demo，发现如果加上一个etag响应头，那么华为浏览器是可以正常暂停的。

https://github.com/zfile-dev/zfile/assets/95918383/bb5154ca-bffe-4a3e-8864-f383afd334bb
