### ISSUE TITLE
zfile官网文档无法访问

### ISSUE THREAD

**Issue by sld272** [zfile-dev/zfile#564]
docs.zfile.vip无法访问，显示`网址为https://docs.zfile.vip/install-os/ 的页面可能存在问题，或者已永久移动到新的网址。`，手机、电脑、不同的浏览器、开不开代理都测试过了

**Comment by zhaojun1998** [comment]
我测试了下没问题，用手机流量打开试试呢，可能你网络问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月17日(周一) 凌晨0:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] zfile官网文档无法访问 (Issue #564)




 
docs.zfile.vip无法访问，显示网址为https://docs.zfile.vip/install-os/ 的页面可能存在问题，或者已永久移动到新的网址。，手机、电脑、不同的浏览器、开不开代理都测试过了
