### ISSUE TITLE
feat: 能否添加类似于 OneManager 的那种 复制一个页面下所有 文件直链的功能

### ISSUE THREAD

**Issue by KIPCL** [zfile-dev/zfile#566]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：否
- 是否已尝试使用最新版本，且仍然没有此功能？：是
- 功能概述：导出一个页面下的所有直链
- 功能动机：导出所有直链后可以更方便的下载所有文件 比如 将文件直链写入到一个脚本中批量下载
- 详细解释（可选）：

**Comment by KIPCL** [comment]
打包功能受限于浏览器的单线程限制 这么做可以用多线程工具 如 aria2 等工具进行下载

**Comment by zhaojun1998** [comment]
复制直链可以批量选中文件然后右键生成直链啊

**Comment by KIPCL** [comment]
啊 对不起打扰了 我的问题 没看见
