### ISSUE TITLE
feat: 希望能加个上传一个文件同时存储到不同的平台

### ISSUE THREAD

**Issue by koobai** [zfile-dev/zfile#567]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：否
- 是否已尝试使用最新版本，且仍然没有此功能？：是
- 功能概述：上传一个文件同时存储到不同的平台
- 功能动机：文件多平台备份
- 详细解释（可选）：譬如一个多吉云一个又拍云，我在多吉云里img/路径下上传一张图，同时也会在又拍云/img目录下同步这张图。

**Comment by zhaojun1998** [comment]
不会支持该功能，使用群体少，且功能问题多。
你可以自己改代码，我接受这个功能的代码贡献并合并到主分支。
