### ISSUE TITLE
更新后，拉不到最低部

### ISSUE THREAD

**Issue by smloli** [zfile-dev/zfile#57]

**Comment by smloli** [comment]
![截屏_20200223_073055](https://user-images.githubusercontent.com/55375920/75100881-dae20d80-560e-11ea-8039-8f4d6b7a2492.jpg)

**Comment by zhaojun1998** [comment]
什么浏览器

**Comment by smloli** [comment]
手机版谷歌浏览器，其他手机浏览器也会这样，这个目录底部还有一个2014.12文件夹 预览网站https://iles.fun/#/main/GL%E5%B0%8F%E8%AF%B4/2014

**Comment by scropothree** [comment]
iphone 使用 safari 也是一样，浏览器无法拉到文件列表最下端。

**Comment by zhaojun1998** [comment]
@smloli @scropothree 
更新最新版试试，更换了滚动加载方式。
