### ISSUE TITLE
如何非根目录部署

### ISSUE THREAD

**Issue by 799034552** [zfile-dev/zfile#570]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：是
- 是否已尝试使用最新版本，且仍然没有此功能？：是
- 功能概述：域名根目录已经有其他应用在跑，不想输端口号，用nginx代理一个api后能正常运行，比如说http://ip/zfile
- 功能动机：没有很多子域名
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
不支持，你都用nginx了，可以通过二级域名区分啊。取a.xxx.com是一个网站，b.xxx.com是另一个网站。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月8日(周二) 晚上9:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 如何非根目录部署 (Issue #570)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个功能？：是
 
是否已尝试使用最新版本，且仍然没有此功能？：是
 
功能概述：域名根目录已经有其他应用在跑，不想输端口号，用nginx代理一个api后能正常运行，比如说http://ip/zfile
 
功能动机：没有很多子域名
 
详细解释（可选）：

**Comment by 799034552** [comment]
有时候没有开二级域名dns解析的权限

**Comment by zhaojun1998** [comment]
那无能为力了，确实无法支持非根目录模式。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月8日(周二) 晚上9:08
收件人: ***@***.***&gt;;
抄送: "zhao ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 如何非根目录部署 (Issue #570)




 
有时候没有开二级域名dns解析的权限
