### ISSUE TITLE
关于文件夹密码

### ISSUE THREAD

**Issue by pcbcos** [zfile-dev/zfile#58]
我发现现在的密码设置只对当前目录有效，只要直接输入子目录的路径就可以避开输入密码。希望能提供一个选项，可以控制密码是否对子目录生效，比如识别password.txt里特定的语句判断是否递归设置密码。

**Comment by zhaojun1998** [comment]
会考虑支持，但此功能会进行评估后支持，可能存在性能问题

**Comment by zhaojun1998** [comment]
此问题不会支持，具体原因在  #71  中说明了
