### ISSUE TITLE
使用默认的提供的onlyoffice出现403错误

### ISSUE THREAD

**Issue by mengluo04** [zfile-dev/zfile#581]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：是
- 是否已查阅、搜索 [ZFile 文档](https://docs.zfile.vip)，尤其是常见问题页，仍然未解决？：是，文档说的外网问题经过验证手机可以下载
- 当前 ZFile 版本：4.1.5
- 是否尝试最新版是否已解决此问题：已是最新
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome
- 做什么操作提示的错误？：word，excel预览弹窗内容显示403
- 期望行为（应该是什么样的结果）：正常预览
- 当前行为（当前是什么样的结果）：403
- 错误日志（可选）：
- 复现步骤（可选）：打开任意word或excel
- 您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
手机用流量可访问？&nbsp; 换句话说你zfile的地址是公网可访问地址吗。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月9日(周一) 下午5:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 使用默认的提供的onlyoffice出现403错误 (Issue #581)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个问题？：是
 
是否已查阅、搜索 ZFile 文档，尤其是常见问题页，仍然未解决？：是，文档说的外网问题经过验证手机可以下载
 
当前 ZFile 版本：4.1.5
 
是否尝试最新版是否已解决此问题：已是最新
 
是否尝试重启 ZFile，且问题依旧存在？：是
 
是否已尝试清空浏览器缓存，且问题依旧存在？：是
 
操作系统（如 Windows、Mac、iOS、安卓）：windows
 
浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome
 
做什么操作提示的错误？：word，excel预览弹窗内容显示403
 
期望行为（应该是什么样的结果）：正常预览
 
当前行为（当前是什么样的结果）：403
 
错误日志（可选）：
 
复现步骤（可选）：打开任意word或excel
 
您的额外信息（可选）：

**Comment by mengluo04** [comment]
> 手机用流量可访问？&nbsp; 换句话说你zfile的地址是公网可访问地址吗。
是的，这是文件的直链短链接以及下载截图
http://shuangsheng0513.cn/s/coeeo3，
![4b0e313b918b6078e010262e7b7f6d9](https://github.com/zfile-dev/zfile/assets/32565940/ea011e19-7347-4b8a-96c8-0a02a75013f8)

**Comment by zhaojun1998** [comment]
不清楚你怎么设置的，我访问你发的链接，有时会跳转到一个登录页，而且这还不是 zfile 的登录页，我不清楚你做了什么。如果你用的不是原版 zfile，那么我无法给予你什么帮助，请使用最纯洁最原始的 zfile，排除任何第三方软件的情况下来验证功能再提 bug，不然可能并不是 zfile 的问题，我还要耗费时间去处理。

![image](https://github.com/zfile-dev/zfile/assets/35387985/a38af3c4-85ed-4acd-9e38-d945e6cf49b4)

**Comment by mengluo04** [comment]
> 不清楚你怎么设置的，我访问你发的链接，有时会跳转到一个登录页，而且这还不是 zfile 的登录页，我不清楚你做了什么。如果你用的不是原版 zfile，那么我无法给予你什么帮助，请使用最纯洁最原始的 zfile，排除任何第三方软件的情况下来验证功能再提 bug，不然可能并不是 zfile 的问题，我还要耗费时间去处理。
> 
> ![image](https://user-images.githubusercontent.com/35387985/273567725-a38af3c4-85ed-4acd-9e38-d945e6cf49b4.png)

不好意思，我http和https是两个服务，可能浏览器自动跳转https了，我晚点重新配置一下nginx再提供新的下的链接

**Comment by mengluo04** [comment]
> 不清楚你怎么设置的，我访问你发的链接，有时会跳转到一个登录页，而且这还不是 zfile 的登录页，我不清楚你做了什么。如果你用的不是原版 zfile，那么我无法给予你什么帮助，请使用最纯洁最原始的 zfile，排除任何第三方软件的情况下来验证功能再提 bug，不然可能并不是 zfile 的问题，我还要耗费时间去处理。
> 
> ![image](https://user-images.githubusercontent.com/35387985/273567725-a38af3c4-85ed-4acd-9e38-d945e6cf49b4.png)

已解决，是同一个域名，有的浏览器或者服务会自动将http转换成htpps导致解析错误，更换单独域名后解决,非常感谢

**Comment by zhaojun1998** [comment]
ok，那我关闭问题了
