### ISSUE TITLE
feat:有计划给视频文件添加封面吗 

### ISSUE THREAD

**Issue by hxsen1998** [zfile-dev/zfile#582]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：
- 是否已尝试使用最新版本，且仍然没有此功能？：
- 功能概述：
- 功能动机：
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
怎么添加，封面图片从哪来。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月9日(周一) 晚上11:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] feat:有计划给视频文件添加封面吗  (Issue #582)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个功能？：
 
是否已尝试使用最新版本，且仍然没有此功能？：
 
功能概述：
 
功能动机：
 
详细解释（可选）：

**Comment by Fantasy135** [comment]
> 怎么添加，封面图片从哪来。
自定义方式？

**Comment by zhaojun1998** [comment]
所以你要怎么个自定义啊。根据什么来确定哪个是视频对应的封面。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月11日(周三) 中午11:51
收件人: ***@***.***&gt;;
抄送: "zhao ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] feat:有计划给视频文件添加封面吗  (Issue #582)




  
怎么添加，封面图片从哪来。
 自定义方式？

**Comment by zhaojun1998** [comment]
问题描述不清楚，先关闭了，补充后在开启
