### ISSUE TITLE
反代后下载较大文件会突然中断，重新连接后只能从头开始，无法断点续传

### ISSUE THREAD

**Issue by Aqr-K** [zfile-dev/zfile#583]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：
- 是否已查阅、搜索 [ZFile 文档](https://docs.zfile.vip)，尤其是常见问题页，仍然未解决？：
- 当前 ZFile 版本：4.1.5
- 是否尝试最新版是否已解决此问题：
- 是否尝试重启 ZFile，且问题依旧存在？：
- 是否已尝试清空浏览器缓存，且问题依旧存在？：
- 操作系统（如 Windows、Mac、iOS、安卓）：
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：所有浏览器
- 做什么操作提示的错误？：
- 期望行为（应该是什么样的结果）：
- 当前行为（当前是什么样的结果）：
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：

反代后下载较大文件会突然中断，重新连接后只能从头开始，无法断点续传
使用的是社区免费版，所有浏览器都有这种情况，机子的带宽是50兆上传
我是用Nginx Proxy Manager 进行反代的，也是docker版的，443端口转8443端口
请问一下是不是我反代漏了啥？或者写错了啥吗？
```
    location / {
       proxy_pass http://192.168.100.253:33333;
       proxy_redirect     default;

       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header   X-Real-IP        $remote_addr;
       proxy_set_header   Host             $host:8443;
       proxy_set_header X-Forwarded-Host $host:8443;
       proxy_set_header X-Forwarded-Server $host;
       proxy_set_header X-Forwarded-Proto $scheme;

#禁止缓存
       proxy_buffering off;

#跳过nginx下载缓存
       client_max_body_size 0;
       proxy_max_temp_file_size 0;

#断点续传
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
}
```

**Comment by zhaojun1998** [comment]
1. 不使用反向代理是否正常，如果正常，那就不是 zfile 的问题，而是你反向代理配置问题，这不属于我解决的范畴，你应该去找 nginx。
2. 我记得 nginx 是默认启用 range 头的，你可以只保留以下部分，再验证:
```
location / {

       proxy_pass http://192.168.100.253:33333;

       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header   X-Real-IP        $remote_addr;
       proxy_set_header   Host             $host:8443;
       proxy_set_header X-Forwarded-Host $host:8443;
       proxy_set_header X-Forwarded-Server $host;
       proxy_set_header X-Forwarded-Proto $scheme;
}
```

**Comment by ashelylinluo** [comment]
我现在也遇到这个问题，就是说别人访问我的数据库，下载数据，假设数据是1.9G,下载一半，就断了，说是网络问题，现在只能重新下载。下载小的数据（31.87mb）没有问题，那应该怎么解决。
