### ISSUE TITLE
feat: 建议生成一个预览链接

### ISSUE THREAD

**Issue by Fantasy135** [zfile-dev/zfile#584]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：
- 是否已尝试使用最新版本，且仍然没有此功能？：
- 功能概述：
- 功能动机：
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
请提 issue 时，补充上面的信息，并详细描述需要的功能需求，场景，动机。不然我怎么仅根据标题的几个字猜测你的想法，你不描述清楚我无法进行回复和开发，否则开发出来不符合你预期又是一堆问题。

这个 issue 我先关闭了，你补充好信息再自己重新打开。
