### ISSUE TITLE
手机播放cos里的视频5次重新连接后加载失败

### ISSUE THREAD

**Issue by ChisatoNishikigi73** [zfile-dev/zfile#585]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

手机播放cos里的大体积（>2G）视频5次重新连接后加载失败，电脑则可以正常播放

- 是否已搜索其他 issue，没有人提过这个问题？：是
- 是否已查阅、搜索 [ZFile 文档](https://docs.zfile.vip)，尤其是常见问题页，仍然未解决？：是
- 当前 ZFile 版本：4.1.5
- 是否尝试最新版是否已解决此问题：无法解决
- 是否尝试重启 ZFile，且问题依旧存在？：是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）：IOS
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Safari, Gear, Via
- 做什么操作提示的错误？：加载视频浏览
- 期望行为（应该是什么样的结果）：播放成功
- 当前行为（当前是什么样的结果）：加载失败
- 错误日志（可选）：
- 复现步骤（可选）：手机打开大体积视频
- 您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
那直接去腾讯云自带的 cos 控制台拿到这个 2G+ 的文件的下载链接，放到手机里看看能不能预览呢？

**Comment by ChisatoNishikigi73** [comment]
似乎是因为手机浏览器不支持mkv格式
