### ISSUE TITLE
右键复制的直链，文件名中有特殊符号会无法下载

### ISSUE THREAD

**Issue by noisky** [zfile-dev/zfile#59]
没有特殊符号，正常下载
https://dl.ffis.me/directlink/windows/keyboardtestutility.exe
有特殊符号 无法下载
https://dl.ffis.me/directlink/windows/AAct_v3.8.5_Portable.7z
https://dl.ffis.me/directlink/windows/DirectX Repair V3.9.zip
感觉因为url编码问题，复制的直链，文件名应该进行url编码，未进行编码浏览器识别错误就无法下载了，特别是使用wget进行下载时，不会进行自动转码

**Comment by noisky** [comment]
第二个链接是被世纪互联 恶意检测了。。。
不过url编码 还是有必要的

**Comment by zhaojun1998** [comment]
已更新
