### ISSUE TITLE
feat: 付费下载

### ISSUE THREAD

**Issue by yiranxiamo** [zfile-dev/zfile#590]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个功能？：无人提及
- 是否已尝试使用最新版本，且仍然没有此功能？：无此功能
- 功能概述：付费下载
- 功能动机：原创资源下载需求量较大，希望增加付费下载，1元的价格应该不高。
- 详细解释（可选）：

**Comment by zhaojun1998** [comment]
暂时不会考虑这个功能
