### ISSUE TITLE
feat: 建议将音乐播放器默认图片地址改为HTTPS或保存在前端静态文件中以规避HTTP混用提示不安全

### ISSUE THREAD

**Issue by D3CODING** [zfile-dev/zfile#60]
在线播放音乐，如果音乐没有封面会调用的默认封面地址`http://c.jun6.net/audio.png`，而这个地址是HTTP的，在前端使用HTTPS部署时，谷歌浏览器会提示不安全。在以后更新中谷歌浏览器会禁止HTTPS页面混用HTTP链接图片等。

建议：将链接改为HTTPS或者直接放在在前端静态文件中。

**Comment by lcxw** [comment]
> 在线播放音乐，如果音乐没有封面会调用的默认封面地址`http://c.jun6.net/audio.png`，而这个地址是HTTP的，在前端使用HTTPS部署时，谷歌浏览器会提示不安全。在以后更新中谷歌浏览器会禁止HTTPS页面混用HTTP链接图片等。
> 
> 建议：将链接改为HTTPS或者直接放在在前端静态文件中。

提一个MR呀😂

**Comment by D3CODING** [comment]
因为还没学JAVA和前端，所以找了半天没找到这个图片是在哪里引用的...
![Snipaste_2020-02-24_17-50-59.png](https://i.loli.net/2020/02/24/MeV3TqAIHsJyQ5f.png)

**Comment by D3CODING** [comment]
如果前后端分离部署，直接在`/static/js/app.3d5f33b3.js`里面找到地址更改成https就行了。不知道纯java部署是否也是引用这个文件

**Comment by zhaojun1998** [comment]
已更新
