### ISSUE TITLE
同样是docker部署 cloudreve可以上传150m以上 zfile就卡死 直接不上传了

### ISSUE THREAD

**Issue by lianlianlianlianlianlian** [zfile-dev/zfile#604]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：
- 是否已查阅、搜索 [ZFile 文档](https://docs.zfile.vip)，尤其是常见问题页，仍然未解决？：
- 当前 ZFile 版本：
- 是否尝试最新版是否已解决此问题：
- 是否尝试重启 ZFile，且问题依旧存在？：
- 是否已尝试清空浏览器缓存，且问题依旧存在？：
- 操作系统（如 Windows、Mac、iOS、安卓）：
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：
- 做什么操作提示的错误？：
- 期望行为（应该是什么样的结果）：
- 当前行为（当前是什么样的结果）：
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：

**Comment by lianlianlianlianlianlian** [comment]
> 为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
> 
> * 是否已搜索其他 issue，没有人提过这个问题？：是
> * 是否已查阅、搜索 [ZFile 文档](https://docs.zfile.vip)，尤其是常见问题页，仍然未解决？：是
> * 当前 ZFile 版本：最新
> * 是否尝试最新版是否已解决此问题：是
> * 是否尝试重启 ZFile，且问题依旧存在？：是
> * 是否已尝试清空浏览器缓存，且问题依旧存在？：是
> * 操作系统（如 Windows、Mac、iOS、安卓）：windows mac
> * 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：谷歌 edge
> * 做什么操作提示的错误？：直接暂停上传 卡死
> * 期望行为（应该是什么样的结果）：解决
> * 当前行为（当前是什么样的结果）：小文件可以上传 大文件直接卡死 已经在docker跟宝塔java环境测试了 都一样 改nginx的上传限制突破50m也一样无法解决
> * 错误日志（可选）：
> * 复现步骤（可选）：
> * 您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
请先尝试直接用docker部署时的原始端口访问来测试上传，如果可以正常上传，那就是你反向代理的问题，反之才可以确定是zfile的问题。


还有卡死是在哪卡死，截图？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月20日(周一) 凌晨4:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [zfile-dev/zfile] 同样是docker部署 cloudreve可以上传150m以上 zfile就卡死 直接不上传了 (Issue #604)




  
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个问题？：是
 
是否已查阅、搜索 ZFile 文档，尤其是常见问题页，仍然未解决？：是
 
当前 ZFile 版本：最新
 
是否尝试最新版是否已解决此问题：是
 
是否尝试重启 ZFile，且问题依旧存在？：是
 
是否已尝试清空浏览器缓存，且问题依旧存在？：是
 
操作系统（如 Windows、Mac、iOS、安卓）：windows mac
 
浏览器（如 Chrome、Firefox、Safari，X 浏览器）：谷歌 edge
 
做什么操作提示的错误？：直接暂停上传 卡死
 
期望行为（应该是什么样的结果）：解决
 
当前行为（当前是什么样的结果）：小文件可以上传 大文件直接卡死 已经在docker跟宝塔java环境测试了 都一样 改nginx的上传限制突破50m也一样无法解决
 
错误日志（可选）：
 
复现步骤（可选）：
 
您的额外信息（可选）：

**Comment by zhaojun1998** [comment]
没有更新的回复，我默认已经解决了，如果有问题，请跟进回复再重新打开。
