### ISSUE TITLE
feat: 关于支持其他编码的视频播放问题

### ISSUE THREAD

**Issue by morningwn** [zfile-dev/zfile#607]
可以考虑使用Javacv解码后推流，但是使用的是jni做的应该性能是一个比较大的问题，另外视频的画质会受到影响

**Comment by morningwn** [comment]
前端用js解码应该也是一种，但是具体就不清楚了

**Comment by zhaojun1998** [comment]
不考虑此问题，但如果你要自己开发  PR 的话，我可以考虑接受。
