### ISSUE TITLE
zfile存在严重逻辑漏洞，可通过修改接口返回包，触发debug模式，修改重置管理员密码

### ISSUE THREAD

**Issue by LuckyRiver99** [zfile-dev/zfile#608]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：否
- 是否已查阅、搜索 [ZFile 文档](https://docs.zfile.vip)，尤其是常见问题页，仍然未解决？：否
- 当前 ZFile 版本：4.1.5
- 是否尝试最新版是否已解决此问题：否
- 是否尝试重启 ZFile，且问题依旧存在？：否
- 是否已尝试清空浏览器缓存，且问题依旧存在？：否
- 操作系统（如 Windows、Mac、iOS、安卓）：windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：chrome
- 做什么操作提示的错误？：修改返回包
- 期望行为（应该是什么样的结果）：禁止在返回包修改参数进入debug模式
- 当前行为（当前是什么样的结果）：可通过修改接口返回包，触发debug模式，修改重置管理员密码
- 错误日志（可选）：触发Debug模式
- 复现步骤（可选）：
对/api/site/config/global接口进行请求
```
GET /api/site/config/global HTTP/2
Host: host
Sec-Ch-Ua: "Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
Accept: application/json, text/plain, */*
Axios-Request: true
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://host/local
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
```

![image](https://github.com/zfile-dev/zfile/assets/83155662/fbc801ab-8376-4bef-a7df-a4f7fd64d500)
修改返回包中debugmode参数值又false为true

![image](https://github.com/zfile-dev/zfile/assets/83155662/e9359a23-8122-4817-8aab-c259126a2f49)
触发debug模式，通过点击重置管理员密码功能点可修改重置管理员密码
![image](https://github.com/zfile-dev/zfile/assets/83155662/fbb5c1e2-7d71-42a7-9dbe-a9d4a60e3299)
![image](https://github.com/zfile-dev/zfile/assets/83155662/8483442a-b6c2-4339-b2b2-59ff43468468)

- 您的额外信息（可选）：如果您认可我的漏洞提交，请同意我的cve申请，他可造成严重的危害，谢谢

**Comment by zhaojun1998** [comment]
要不你点个确定试试。后台是有检验的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月28日(周二) 下午5:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] zfile存在严重逻辑漏洞，可通过修改接口返回包，触发debug模式，修改重置管理员密码 (Issue #608)




 
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：
  
是否已搜索其他 issue，没有人提过这个问题？：否
 
是否已查阅、搜索 ZFile 文档，尤其是常见问题页，仍然未解决？：否
 
当前 ZFile 版本：4.1.5
 
是否尝试最新版是否已解决此问题：否
 
是否尝试重启 ZFile，且问题依旧存在？：否
 
是否已尝试清空浏览器缓存，且问题依旧存在？：否
 
操作系统（如 Windows、Mac、iOS、安卓）：windows
 
浏览器（如 Chrome、Firefox、Safari，X 浏览器）：chrome
 
做什么操作提示的错误？：修改返回包
 
期望行为（应该是什么样的结果）：禁止在返回包修改参数进入debug模式
 
当前行为（当前是什么样的结果）：可通过修改接口返回包，触发debug模式，修改重置管理员密码
 
错误日志（可选）：触发Debug模式
 
复现步骤（可选）：
 对/api/site/config/global接口进行请求
  GET /api/site/config/global HTTP/2 Host: host Sec-Ch-Ua: "Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24" Accept: application/json, text/plain, */* Axios-Request: true Sec-Ch-Ua-Mobile: ?0 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Sec-Ch-Ua-Platform: "Windows" Sec-Fetch-Site: same-origin Sec-Fetch-Mode: cors Sec-Fetch-Dest: empty Referer: https://host/local Accept-Encoding: gzip, deflate Accept-Language: zh-CN,zh;q=0.9  
image.png (view on web)
 修改返回包中debugmode参数值又false为true
 
image.png (view on web)
 触发debug模式，通过点击重置管理员密码功能点可修改重置管理员密码
 image.png (view on web)
 image.png (view on web)
  
您的额外信息（可选）：如果您认可我的漏洞提交，请同意我的cve申请，他可造成严重的危害，谢谢
