### ISSUE TITLE
存储环境是minio时 新建文件夹  操作显示成功，但实际没有创建成功！

### ISSUE THREAD

**Issue by jiahengaa** [zfile-dev/zfile#613]
存储环境是minio时 新建文件夹  操作显示成功，但实际没有创建成功！

https://github.com/zfile-dev/zfile/assets/9588909/a49d9aaf-3784-4338-97af-ded40920f10b

**Comment by zhaojun1998** [comment]
请截图 zfile 中 minio 设置，以及 minio 的版本，zfile 的版本。

并尝试使用其他第三方 s3 工具新建文件夹看是否能成功，如果也不能成功，那就不是 ZFile 的问题，请检查 minio 的相关设置（因为之前有人也遇到过和你相同的问题，最后发现是 minio 配置的问题）

**Comment by zhaojun1998** [comment]
长时间无回复，关闭问题了。有进展后再打开。
