### ISSUE TITLE
能不能增加必须登录才能查看存储文件的选项

### ISSUE THREAD

**Issue by 18611429192** [zfile-dev/zfile#615]
## 描述
目前直接输入IP:PORT后就能看到所有我上传的文件，但是我不想让别人看到我的文件
希望能增加一个功能：必须登录才能查看网盘里的文件。

## 额外信息
无

**Comment by zhaojun1998** [comment]
社区版暂不支持该功能，可先使用 nginx 或其他前端程序增加 http basic 校验功能来使用。

**Comment by vvnocode** [comment]
> 社区版暂不支持该功能，可先使用 nginx 或其他前端程序增加 http basic 校验功能来使用。

zfile3接受登陆的合并吗？看图的话zfile3真的不错。

**Comment by zhaojun1998** [comment]
目前不考虑接受
