### ISSUE TITLE
ZFile 开源release server is down

### ISSUE THREAD

**Issue by HavenXia** [zfile-dev/zfile#617]
## 环境信息
- ZFile 版本：`4.1.5`
- 部署方式：`Linux-脚本`
- 操作系统/设备：`Windows`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`

## 复现步骤
目前https://c.jun6.net/ZFILE/zfile-release.war 显示server is down

## 预期结果
预期能打开

## 实际结果
Web server is down with Error code 521

## 额外信息
无

**Comment by zhaojun1998** [comment]
已解决
