### ISSUE TITLE
迁移过后所有存储源均无法访问

### ISSUE THREAD

**Issue by yahcme** [zfile-dev/zfile#619]
## 环境信息
- ZFile 版本：`4.1.5`
- 部署方式：`Linux-脚本`
- 操作系统/设备：`Linux`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`

## 复现步骤
由于机器升级，在另一台机器直接迁移数据库（/root/.zfile-v4/db/zfile）并安装同版本（4.1.5）后，发现已添加的存储源（Onedrive个人版、阿里云OSS）均无法访问，OD个人版更新令牌也无法访问，提示 存储源刷新令牌失败，获取时发生异常。

## 预期结果
应当无问题

## 实际结果
存储源刷新令牌失败，获取时发生异常

## 额外信息
迁移前机器：Ubuntu focal 5.4.0-148-generic openjdk version "1.8.0_362" 后：Debian bookworm 6.1.0-16-amd64 openjdk version "1.8.0_372"

**Comment by zhaojun1998** [comment]
新服务器是国内的？OneDrive 的 API 服务可能在国内服务器上访问被阻断或不稳定。  阿里OSS无法访问请提供报错信息。

**Comment by yahcme** [comment]
新旧机器均位于美国，可以连接至Onedrive的API，无论旧机器是否开机新机器都无法连接存储源

**Comment by zhaojun1998** [comment]
你得贴上错误信息啊，zfile后台也能下载日志。不然我不能凭空猜测你的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月10日(周三) 晚上11:34
收件人: ***@***.***&gt;;
抄送: "zhao ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 迁移过后所有存储源均无法访问 (Issue #619)




 
新旧机器均位于美国，可以连接至Onedrive的API，无论旧机器是否开机新机器都无法连接存储源

**Comment by zhaojun1998** [comment]
就好像你去医院，搬家后说不舒服，只说不舒服，就让医生给开药。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月10日(周三) 晚上11:34
收件人: ***@***.***&gt;;
抄送: "zhao ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 迁移过后所有存储源均无法访问 (Issue #619)




 
新旧机器均位于美国，可以连接至Onedrive的API，无论旧机器是否开机新机器都无法连接存储源

**Comment by zhaojun1998** [comment]
长时间无回复，关闭问题了。有进展后再打开。
