### ISSUE TITLE
阿里云OSS提示权限不足

### ISSUE THREAD

**Issue by TheOrdinaryWow** [zfile-dev/zfile#62]
## 我的环境

操作系统 | Linux
系统版本 | 4.15.0-76-generic
系统架构 | amd64
程序路径 | /root/zfile/WEB-INF/classes
系统启动时间 | 18分29秒
系统总内存 | 1024.00 MB
系统已使用内存 | 863.44 MB
系统空闲内存 | 160.55 MB
JVM 可占用内存 | 239.75 MB
JVM 已占用内存 | 86.05 MB
JVM 空闲内存 | 29.81 MB
JVM 版本 | 1.8.0_242

## 期望行为

阿里云OSS已经配置accesskey，但是无法正常访问。

## 当前行为

<Error>
<script type="text/javascript" class="acInsScirpt">
isExtension=true;console.log('extMode');var AC_xhrCallBack = {};
</script>
<Code>AccessDenied</Code>
<Message>
You have no right to access this object because of bucket acl.
</Message>
<RequestId>**********************</RequestId>
<HostId>****************</HostId>
</Error>

**Comment by zhaojun1998** [comment]
更新最新版 1.9 看看。

**Comment by TheOrdinaryWow** [comment]
> 更新最新版 1.9 看看。

已更新最新版1.9，但是将bucket权限改为私有后仍然无法下载，只有将权限改为公共读后才可正常下载，但是此举存在安全隐患。
使用的是AccessKey，而不是RAM用户或者子用户。

**Comment by zhaojun1998** [comment]
无法下载是指，无论何时都无法下载，还是一段时间后不能正常下载。 且阿里云支持创建只包含部分权限的 AccessKey

**Comment by TheOrdinaryWow** [comment]
> 无法下载是指，无论何时都无法下载，还是一段时间后不能正常下载。 且阿里云支持创建只包含部分权限的 AccessKey

无法下载指的是一直都不能下载。
关于你指的阿里云支持创建只包含部分权限的AccessKey，已参照 [查看链接](https://forum.cloudreve.org/d/328/5) 进行配置相应权限的AccessKey，但是仍然提示权限不足，如图。
![Snipaste_2020-03-01_12-51-27](https://user-images.githubusercontent.com/25114850/75619792-67667000-5bbb-11ea-94f3-9e02158e9237.png)

**Comment by zhaojun1998** [comment]
@nzbcorz  更新 2.2 版本，已解决。

**Comment by yangbohz** [comment]
2.9似乎有出来这个bug了。存储桶设置为私有后提示权限不足，改成公共读就没问题。
