### ISSUE TITLE
zfile在经历宕机后配置的minio中bucket连接信息无法再次使用

### ISSUE THREAD

**Issue by forevernianini** [zfile-dev/zfile#620]
## 环境信息
- ZFile 版本：`4.1.3`
- 部署方式：`Linux-脚本`
- 操作系统/设备：`Windows`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`

## 复现步骤
机房经历停机后，minio服务被迫下线，zfile被迫下线后，重启zfile,重启minio服务后，提示minio服务不可用，需要重新进入数据源界面进行重新保存刷新bucket配置才可以正常使用。

## 预期结果
自动让其恢复数据源功能，而不应该需要二次刷新才可用服务

## 实际结果
需要重新进入数据源界面进行重新保存刷新才可以正常使用

## 额外信息
无

**Comment by zhaojun1998** [comment]
我想你得提供完整的错误信息我才能排查解决，如截图/日志，而不是只是描述一个不可用。

**Comment by zhaojun1998** [comment]
长时间无回复，关闭问题了。有进展后再打开。
