### ISSUE TITLE
OneDrive 国际版令牌获取结果错误

### ISSUE THREAD

**Issue by laoyang3389** [zfile-dev/zfile#621]
## 环境信息
- ZFile 版本：`4.1.5`
- 部署方式：`Docker`
- 操作系统/设备：`Windows`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0`

## 复现步骤
获取访问令牌尝试多次

## 预期结果
正常

## 实际结果
{"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid. Trace ID: 23480d78-4ec0-4232-a852-a68ecced3400 Correlation ID: 4e32b02d-8ab5-4924-9fbb-b8785d241a10 Timestamp: 2024-01-11 14:25:48Z","error_codes":[9002313],"timestamp":"2024-01-11 14:25:48Z","trace_id":"23480d78-4ec0-4232-a852-a68ecced3400","correlation_id":"4e32b02d-8ab5-4924-9fbb-b8785d241a10","error_uri":"https://login.microsoftonline.com/error?code=9002313"}

## 额外信息
无

**Comment by laoyang3389** [comment]
![QQ截图20240111223217](https://github.com/zfile-dev/zfile/assets/125744950/077fced5-32ca-4a59-b6ea-818b0a747be4)

**Comment by zhaojun1998** [comment]
请确定你的 onedrive账号是支持 api 的，比如你是否是正价购买，这种都是有 api 的。
如果你是廉价购买的教育版或者其他的，很可能是没有api的，请咨询购买商家。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月11日(周四) 晚上10:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] OneDrive 国际版令牌获取结果错误 (Issue #621)




 
环境信息
  
ZFile 版本：4.1.5
 
部署方式：Docker
 
操作系统/设备：Windows
 
浏览器/版本号：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
  
复现步骤
 
获取访问令牌尝试多次
 
预期结果
 
正常
 
实际结果
 
{"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid. Trace ID: 23480d78-4ec0-4232-a852-a68ecced3400 Correlation ID: 4e32b02d-8ab5-4924-9fbb-b8785d241a10 Timestamp: 2024-01-11 14:25:48Z","error_codes":[9002313],"timestamp":"2024-01-11 14:25:48Z","trace_id":"23480d78-4ec0-4232-a852-a68ecced3400","correlation_id":"4e32b02d-8ab5-4924-9fbb-b8785d241a10","error_uri":"https://login.microsoftonline.com/error?code=9002313"}
 
额外信息
 
无

**Comment by zhaojun1998** [comment]
长时间无回复，先关闭 issue 了，如仍有问题请继续回复并重新打开问题
