### ISSUE TITLE
创建的文件夹以及文件不显示

### ISSUE THREAD

**Issue by lihetongxue** [zfile-dev/zfile#622]
## 环境信息
- ZFile 版本：`4.1.5`
- 部署方式：`Docker`
- 操作系统/设备：`Windows`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0`

## 复现步骤
我在多个设备和浏览器尝试新建文件夹以及上传文件，然后在我的存储桶当中正常显示了创建的文件夹和文件，我并没有设置隐藏文件夹。

## 预期结果
什么都没有显示

## 实际结果
什么都没有显示

## 额外信息
无

**Comment by zhaojun1998** [comment]
1. 什么存储类型
2. 存储源参数配置请截图，有敏感信息的密钥可打码
3. 你自己在存储源本身创建的文件和文件夹在 ZFile 中能看到么

**Comment by lihetongxue** [comment]
Reply:
1.存储类型为S3
2.
<img width="1024" alt="截屏2024-01-18 00 18 47" src="https://github.com/zfile-dev/zfile/assets/97779346/cf7b76f4-ce84-4050-bb94-828cd789b81d">
3.在存储源创建的文件夹和文件在ZFile不能看到，仍然什么都没有

**Comment by zhaojun1998** [comment]
我猜是你 Endpoint 写错了，我去看了下雨云的文档，应该是写 https://cn-sy1.rains3.com/


https://forum.rainyun.com/t/topic/6437

下图中黄色的框是我标注的

<img width="361" alt="image" src="https://github.com/zfile-dev/zfile/assets/35387985/6a6cf88c-fe96-4eb6-bbcd-65efbd609015">


如果还不行，请先使用其他支持 s3 的工具/软件来填写同样的信息来辅助验证，如果其他的可以，zfile 中不行，那说明才是 zfile 的问题，不然就是你配置问题。

**Comment by lihetongxue** [comment]
我查阅雨云的官方文档，Endpoint确实不需要在https://cn-sy1.rains3.com 后面加上存储桶的名称，但是我在ZFile配置中只有加上存储桶名称才能配置生效，我尝试了换服务器和重建存储桶的操作，结果仍然需要加上存储桶名称的链接才能成功添加存储桶。

随后我在S3 Brower这个软件上成功链接上了我的对象存储，可以看到文件以及新建文件夹等操作,如下图：
<img width="566" alt="屏幕截图 2024-01-18 115500" src="https://github.com/zfile-dev/zfile/assets/97779346/4352ef04-9457-4d5e-a992-6bfd92009219">
值得注意的是，Endpoint的链接为https://cn-sy1.rains3.com， 而不需要带上存储桶的名称，带上名称后我的对象存储不能够链接成功。加上存储桶名称链接为：https://cn-sy1.rains3.com/lihetongxue。

**Comment by zhaojun1998** [comment]
我自费购买了一个 rain s3 测试，得出的结果是 endpoint 无需写存储桶的名称，然后无需勾选 "是否自动配置 CORS 跨域设置"，应该是 rain s3 不限制跨域，也不支持这个 api 导致的。

**Comment by lihetongxue** [comment]
是的，我刚才试着取消勾选，发现一切正常了。

非常感谢，这个问题太麻烦你了，我觉得它比Alist更顺眼，已Star。
