### ISSUE TITLE
未更新的指向性链接

### ISSUE THREAD

**Issue by xiaoyaofengjianshi** [zfile-dev/zfile#630]
## 环境信息
- ZFile 版本：`4.1.5`
- 部署方式：`Linux-宝塔`
- 操作系统/设备：`Linux`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0`

## 复现步骤
admin左上角logo-文档地址：点我查看
点击"点我查看"

## 预期结果
打开文档

## 实际结果
未打开文档，链接错误

## 额外信息
无

**Comment by zhaojun1998** [comment]
已解决
