### ISSUE TITLE
找不到schema history table

### ISSUE THREAD

**Issue by TechGeek24x73** [zfile-dev/zfile#634]
## 环境信息
- ZFile 版本：`4.1.5`
- 部署方式：`源码启动`
- 操作系统/设备：`Windows`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`

## mysql
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234

spring.profiles.active=prod

## 预期结果
1

## 实际结果
1

## 额外信息
Error creating bean with name 'flywayDbInitializer': Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Found non-empty schema(s) `zfile` but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization

**Comment by zhaojun1998** [comment]
不好意思。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月24日(周六) 晚上9:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 找不到schema history table (Issue #634)




 
环境信息
  
ZFile 版本：4.1.5
 
部署方式：源码启动
 
操作系统/设备：Windows
 
浏览器/版本号：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
  
复现步骤
 
mysql
 
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
 spring.datasource.url=jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&amp;serverTimezone=Asia/Shanghai&amp;useSSL=false&amp;allowPublicKeyRetrieval=true
 spring.datasource.username=root
 spring.datasource.password=1234
 
spring.profiles.active=prod
 
预期结果
 
1
 
实际结果
 
1
 
额外信息
 
Error creating bean with name 'flywayDbInitializer': Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Found non-empty schema(s) zfile but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
 at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization

**Comment by zhaojun1998** [comment]
不好意思，不提供开发方面（开发工具源码启动)的任何技术支持。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月24日(周六) 晚上9:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 找不到schema history table (Issue #634)




 
环境信息
  
ZFile 版本：4.1.5
 
部署方式：源码启动
 
操作系统/设备：Windows
 
浏览器/版本号：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
  
复现步骤
 
mysql
 
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
 spring.datasource.url=jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&amp;serverTimezone=Asia/Shanghai&amp;useSSL=false&amp;allowPublicKeyRetrieval=true
 spring.datasource.username=root
 spring.datasource.password=1234
 
spring.profiles.active=prod
 
预期结果
 
1
 
实际结果
 
1
 
额外信息
 
Error creating bean with name 'flywayDbInitializer': Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Found non-empty schema(s) zfile but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
 at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization
