### ISSUE TITLE
希望支持PWA

### ISSUE THREAD

**Issue by xwndo** [zfile-dev/zfile#635]
## 描述
也就是浏览器生成应用，方便手机端使用

## 额外信息
无

**Comment by zhaojun1998** [comment]
欢迎 PR，但我不会主动考虑，你做出来好的话我可以考虑给你挂个地址或教程。


我更喜欢网页的方式，而不是app。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月24日(周六) 晚上9:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 希望支持PWA (Issue #635)




 
描述
 
也就是浏览器生成应用，方便手机端使用
 
额外信息
 
无
