### ISSUE TITLE
建议office文件预览时集成类似于OnlyOffice

### ISSUE THREAD

**Issue by Hang-shao** [zfile-dev/zfile#639]
## 描述
私有化部署时，再单独部署OnlyOffice费时费力。

## 额外信息
无

**Comment by zhaojun1998** [comment]
肯定不会考虑，那会让程序变的很臃肿，我不能因为个别人的需求让所有用户的存储空间买单。
我能提供 OnlyOffice 部署文档已经是能做的最多的事了，想要省事，可以自己写个脚本来实现。

**Comment by Hang-shao** [comment]
好的，感谢回复

在 2024-03-06 15:23:04，"zhao jun" ***@***.***> 写道：


肯定不会考虑，那会让程序变的很臃肿，我不能因为个别人的需求让所有用户的存储空间买单。
我能提供 OnlyOffice 部署文档已经是能做的最多的事了，想要省事，可以自己写个脚本来实现。
