### ISSUE TITLE
视频需要双击才会播放

### ISSUE THREAD

**Issue by jiangjiangflies** [zfile-dev/zfile#64]
你好，
       视频在线播放，有时候单击文件，播放框加载不出来，需要双击才可以播放；而有时候单击就可以了，似乎存在小的bug。
        请求解决，感谢作者！

**Comment by D3CODING** [comment]
这个问题我这边也会出现。
具体表现应该是首次点击视频文件，会只出现一个标题框，如下图
![Snipaste_2020-02-29_00-49-07.png](https://i.loli.net/2020/02/29/PQoi5VxZK83R9Fk.png)
在关闭后再次点击此视频或目录下其他视频即可正常播放。
在1.8版本不会出现，升级为1.9后出现，且火狐和谷歌浏览器均会出现，可能和浏览器缓存有些关系，也可能是更新的那个按需加载的问题。
希望能在下个版本中修复，谢谢。

**Comment by Scolism** [comment]
我也有这个问题，比较奇怪

**Comment by zhaojun1998** [comment]
@jiangjiangflies @lichenzero @CuteLouise  已修复，暂时关闭问题。
