### ISSUE TITLE
双因素认证失效

### ISSUE THREAD

**Issue by ghost** [zfile-dev/zfile#640]
## 环境信息
- ZFile 版本：`4.1.5`
- 部署方式：`Linux-脚本`
- 操作系统/设备：`Linux`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36`

## 复现步骤
在后台管理了启用双因素认证(TOTPauthenticator),在后台绑定和测试绑定都没有问题,但是新开界面尝试使用双因素认证登陆时提示错误,已经重装zfile问题没有解决.

## 预期结果
成功登陆

## 实际结果
提示认证失败

## 额外信息
系统是Debian11,排除双因子认证器的问题

**Comment by zhaojun1998** [comment]
检查服务器时间是否和标准时间同步

**Comment by ghost** [comment]
感谢,已解决,机器重装时间没校正
