### ISSUE TITLE
以Onedrive为例，编辑存储源页填写令牌的相关编辑框都没有加载出来

### ISSUE THREAD

**Issue by mole9630** [zfile-dev/zfile#642]
## 环境信息
- ZFile 版本：`4.1.5`
- 部署方式：`Linux-宝塔`
- 操作系统/设备：`Windows`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0`

## 复现步骤
其中进行了一次服务器迁移，并把数据库转换成了MySQL，今天想更改令牌数据发现没有相关输入框了。

## 预期结果
有填写令牌信息的输入框

## 实际结果
没有填写令牌信息的输入框

## 额外信息
无任何报错反馈

![image](https://github.com/zfile-dev/zfile/assets/32011691/48c99524-64c9-4eed-86b7-a7e6e72536c7)

**Comment by mole9630** [comment]
其他源类型也有同样的问题。
![image](https://github.com/zfile-dev/zfile/assets/32011691/08239a50-af95-4989-9837-fc52e0111803)

**Comment by zhaojun1998** [comment]
那就是你自己迁移的数据有问题，仔细检查每个表的数量和内容是否对得上。迁移前后zfile版本是否一致。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月12日(周二) 晚上10:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [zfile-dev/zfile] 以Onedrive为例，编辑存储源页填写令牌的相关编辑框都没有加载出来 (Issue #642)




 
其他源类型也有同样的问题。
 image.png (view on web)

**Comment by mole9630** [comment]
> 那就是你自己迁移的数据有问题，仔细检查每个表的数量和内容是否对得上。迁移前后zfile版本是否一致。
> [...](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月12日(周二) 晚上10:46 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [zfile-dev/zfile] 以Onedrive为例，编辑存储源页填写令牌的相关编辑框都没有加载出来 (Issue #642) 其他源类型也有同样的问题。 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

是同一版本，只是数据库改成了mysql，可能是数据库迁移时出现的问题。
目前sqllite文件迁移到mysql有没有什么好的方法？

**Comment by mole9630** [comment]
> 那就是你自己迁移的数据有问题，仔细检查每个表的数量和内容是否对得上。迁移前后zfile版本是否一致。
> [...](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月12日(周二) 晚上10:46 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [zfile-dev/zfile] 以Onedrive为例，编辑存储源页填写令牌的相关编辑框都没有加载出来 (Issue #642) 其他源类型也有同样的问题。 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

是同一版本，只是数据库改成了mysql，可能是数据库迁移时出现的问题。
仅是没有相关输入框，网盘还是可以正常读取并在首页正常访问的，添加新存储源时同样也没有相关输入框。
若真是数据库迁移的问题，目前sqllite的db文件迁移到mysql有没有什么好的或快速方法？

**Comment by zhaojun1998** [comment]
1. 你没说你怎么进行数据库迁移的，人工还是工具，工具是什么工具。
2. 你没回答是否已经仔细检查每个表的数量和内容是否对得上
3. 如果你已经进行了前两步仍然不行或不想进行，那可以使用一个空的 MySQL 5.7 及以上的数据库来初始化安装，再重新配置。

**Comment by zhaojun1998** [comment]
暂时没回复，先关闭了，补充信息后再打开
