### ISSUE TITLE
上传大文件时会卡在百分之0

### ISSUE THREAD

**Issue by SmmnaBeta** [zfile-dev/zfile#646]
## 环境信息
- ZFile 版本：`4.1.6 Pro`
- 部署方式：`Linux-脚本`
- 操作系统/设备：`Linux`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0`

## 复现步骤
cdn配置，超过100M的文件进行传输时转到源ip不走cdn，

## 预期结果
正常上传

## 实际结果
卡在0%

## 额外信息
Error: Network Error，无法通过源地址+端口号测试，因为要验证授权。

**Comment by zhaojun1998** [comment]
我想这不是 zfile 要处理的，这是你自己配置问题。

不然我专门为你这种特殊情况开发个规则表达式判断走不同的上传地址？
