### ISSUE TITLE
关于百度统计JS无法检测到的问题

### ISSUE THREAD

**Issue by John-is-playing** [zfile-dev/zfile#649]
## 环境信息
- ZFile 版本：`4.1.5`
- 部署方式：`Linux-脚本`
- 操作系统/设备：`Windows`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0`

## 复现步骤
1.打开后台
2.复制百度统计JS代码
3.复制到后台自定义JS
4.保存修改
5.百度统计端测试

## 预期结果
正常检测到，正常访问

## 实际结果
无法检测到，没有数据

## 额外信息
无

**Comment by zhaojun1998** [comment]
参考http://docs.zfile.vip/custom-js/baidu-tongji


无法检测到那是正常的，你可以查看百度统计问题说明中，可能检测不到的。
但是过一会有数据就行。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月31日(周日) 下午5:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 关于百度统计JS无法检测到的问题 (Issue #649)




 
环境信息
  
ZFile 版本：4.1.5
 
部署方式：Linux-脚本
 
操作系统/设备：Windows
 
浏览器/版本号：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
  
复现步骤
 
1.打开后台
 2.复制百度统计JS代码
 3.复制到后台自定义JS
 4.保存修改
 5.百度统计端测试
 
预期结果
 
正常检测到，正常访问
 
实际结果
 
无法检测到，没有数据
 
额外信息
 
无

**Comment by John-is-playing** [comment]
仍然不行，以下为等待1天后的截图
![image](https://github.com/zfile-dev/zfile/assets/108605883/ab30cec2-c027-40f8-9bbf-f3f7044925aa)

**Comment by zhaojun1998** [comment]
从我个人主页的邮箱发我你 zfile 地址

**Comment by Hearion** [comment]
我也有相同的问题 已经添加很久了 还是检测不到

**Comment by zhaojun1998** [comment]
@Hearion  检测不到，网站的数据统计有数据显示么。

**Comment by Hearion** [comment]
> @Hearion 检测不到，网站数据统计有证据表明什么。

网站数据统计并没有数据
<img width="2583" alt="iShot_2024-05-31_16 34 07" src="https://github.com/zfile-dev/zfile/assets/74294521/742fe62b-8889-4fd1-a6ad-7eddf9a5038a">

**Comment by zhaojun1998** [comment]
@Hearion 

百度统计的原理就是动态加载 hm.baidu.com/hm.js 这个 js，你可以 F12 查看网络请求看看是否加载，请注意如果你或者用户安装了广告拦截之类的插件，这个 js 是会被屏蔽的，比如我通过你刚截图的右上角地址访问你 ZFile 时：

![image](https://github.com/zfile-dev/zfile/assets/35387985/66782eb1-430d-4d26-ac92-ba853f8c1372)

**Comment by Hearion** [comment]
@zhaojun1998 明白了 也找到问题了 是百度的问题 感谢

**Comment by zhaojun1998** [comment]
@Hearion 

具体哪里的问题，是百度提供的 JS 的问题吗，还是广告拦截问题，还是其他的，我好把解决方案放到文档供其他人参考。

**Comment by Hearion** [comment]
@zhaojun1998 百度提供的异步JS文件根本就加载不到 没有任何限制 可能百度那边有问题

**Comment by zhaojun1998** [comment]
确实，我刚直接访问也是返回空白，可能百度的服务异常了。

**Comment by Hearion** [comment]
@zhaojun1998 我已经切换到别的统计方式了 可以正常使用
