### ISSUE TITLE
Docker支持 & 如何去掉HashTag

### ISSUE THREAD

**Issue by xavier-niu** [zfile-dev/zfile#65]
因为我是Docker的重度用户，所以我做了一个基于zfile最新版本的docker镜像，支援自定义PUID和PGID，[Docker Hub](https://hub.docker.com/r/xavierniu/zfile)

另外如何去掉vue路由里的#，我看了一下需要修改router模式为'history', https://stackoverflow.com/questions/34623833/how-to-remove-hashbang-from-url

**Comment by xavier-niu** [comment]
好像GitHub现在GG了，我重新发一遍

因为我是Docker的重度用户，所以做了一个基于zfile最新版本(v1.9)的docker镜像，后续也会随着release更新，支持自定义PUID和PGID，如果有需要可以从docker hub中拉取：https://hub.docker.com/r/xavierniu/zfile

另外请问如何去掉vue路由里的#，我看了一下需要修改router模式为'history', https://stackoverflow.com/questions/34623833/how-to-remove-hashbang-from-url

谢谢

**Comment by lcxw** [comment]
> 好像GitHub现在GG了，我重新发一遍
> 
> 因为我是Docker的重度用户，所以做了一个基于zfile最新版本(v1.9)的docker镜像，后续也会随着release更新，支持自定义PUID和PGID，如果有需要可以从docker hub中拉取：https://hub.docker.com/r/xavierniu/zfile
> 
> 另外请问如何去掉vue路由里的#，我看了一下需要修改router模式为'history', https://stackoverflow.com/questions/34623833/how-to-remove-hashbang-from-url
> 
> 谢谢

可以fork之后自己改一下，刚才github确实是挂了一会。。。

**Comment by xavier-niu** [comment]
> > 好像GitHub现在GG了，我重新发一遍
> > 因为我是Docker的重度用户，所以做了一个基于zfile最新版本(v1.9)的docker镜像，后续也会随着release更新，支持自定义PUID和PGID，如果有需要可以从docker hub中拉取：https://hub.docker.com/r/xavierniu/zfile
> > 另外请问如何去掉vue路由里的#，我看了一下需要修改router模式为'history', https://stackoverflow.com/questions/34623833/how-to-remove-hashbang-from-url
> > 谢谢
> 
> 可以fork之后自己改一下，刚才github确实是挂了一会。。。

但是不能每release一次都改一次 有点麻烦啊。。
