### ISSUE TITLE
提供最新ZFile的Docker镜像 & 如何去掉vue路由的#

### ISSUE THREAD

**Issue by xavier-niu** [zfile-dev/zfile#66]
因为我是Docker的重度用户，所以做了一个基于zfile最新版本(v1.9)的docker镜像，后续也会随着release更新，支持自定义PUID和PGID，如果有需要可以从docker hub中拉取：https://hub.docker.com/r/xavierniu/zfile

另外请问如何去掉vue路由里的#，我看了一下需要修改router模式为'history', https://stackoverflow.com/questions/34623833/how-to-remove-hashbang-from-url

谢谢

**Comment by zhaojun1998** [comment]
下版本将支持路由改为 history 模式。

**Comment by onepve** [comment]
下个版本的history 遥遥无期

**Comment by beigu666** [comment]
> 下一个版本将支持路由更改历史记录模式。

遥遥无期
