### ISSUE TITLE
上传图像并自动生成直链返回，搭配PicGo或自建脚本使用

### ISSUE THREAD

**Issue by Luoshen0618** [zfile-dev/zfile#662]
## 描述
能否提供一个接口，可以实现上传到指定存储库的指定目录，然后生成直链并以json返回；这样借助picgo或者自己写的脚本，可以在Typora中插入图片时，自动同步到存储源，用来做图床更方便。

或者如果不能开发这个接口，我想询问一下：
我想上传到onedrive，我目前使用python的requests库，通过上传接口/api/file/operator/upload/file 仅仅可以获得一个onedrive的地址
我想询问一下如何利用获得的onedrive的地址上传到onedrive呢?

**Comment by zhaojun1998** [comment]
有没有可能，zfile前端页面就是通过接口上传的。你F12找下接口就是了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月30日(周二) 下午5:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 上传图像并自动生成直链返回，搭配PicGo或自建脚本使用 (Issue #662)




 
描述
 
提供一个接口，可以实现上传到指定存储库的指定目录，然后生成直链并以json返回；这样借助picgo或者自己写的脚本，可以在Typora中插入图片时，自动同步到存储源，用来做图床更方便。
 
或者如果不能开发这个接口，我想询问一下：
 我想上传到onedrive，我目前使用python的requexts库，通过上传接口/api/file/operator/upload/file 仅仅可以获得一个onedrive的地址
 我想询问一下如何利用获得的onedrive的地址上传到onedrive呢?

**Comment by Luoshen0618** [comment]
> 有没有可能，zfile前端页面就是通过接口上传的。你F12找下接口就是了。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月30日(周二) 下午5:54 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [zfile-dev/zfile] 上传图像并自动生成直链返回，搭配PicGo或自建脚本使用 (Issue #662) 描述 提供一个接口，可以实现上传到指定存储库的指定目录，然后生成直链并以json返回；这样借助picgo或者自己写的脚本，可以在Typora中插入图片时，自动同步到存储源，用来做图床更方便。 或者如果不能开发这个接口，我想询问一下： 我想上传到onedrive，我目前使用python的requexts库，通过上传接口/api/file/operator/upload/file 仅仅可以获得一个onedrive的地址 我想询问一下如何利用获得的onedrive的地址上传到onedrive呢? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

接口是指这两个吗？但是我在里面并没有看到上传文件信息的参数，用python模拟请求也么有响应。是需要再看源码吗？
![屏幕截图 2024-05-03 011013](https://github.com/zfile-dev/zfile/assets/53894387/dd16eabf-eae3-477b-9e32-f741484641b1)

**Comment by zhaojun1998** [comment]
因为这不是 bug，而是你自己的需求，这个就看你自己能力了，前后端代码都开源的。
