### ISSUE TITLE
基于AbstractS3BaseFileService实现的存储源上传失败

### ISSUE THREAD

**Issue by Daliuq** [zfile-dev/zfile#664]
## 环境信息
- ZFile 版本：`4.1.5`
- 部署方式：`源码启动`
- 操作系统/设备：`Windows`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0`

## 复现步骤
首先我尝试了腾讯云COS，然后尝试了华为云OBS，均是能下载，能访问文件夹，但是就是上传报403，SignatureDoesNotMatch，按理来说其他操作也是要预签名的，其他操作没有问题，就上传有问题

## 预期结果
上传成功

## 实际结果
上传失败

## 额外信息
Windows源码运行，华为云存储源上传报403
<Error>
<script/>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<RequestId>0000018F5393CAFFF8CBFD034A985328</RequestId>
<HostId>Z9v+cC1sRnaWw6x0vi8pxxYA0YVnKxbYHUPAFpnxkX8sLV44u5b02Z+ailn2wCnR</HostId>
<AWSAccessKeyId>DDFUM5GIXQBGZ55ROPPH</AWSAccessKeyId>
<SignatureProvided>4b6102fa12cf3b7ad51dcf101a7f023b19da0aa573624266b95a0c76f201cb91</SignatureProvided>
<StringToSign>AWS4-HMAC-SHA256 20240507T150221Z 20240507/obs/s3/aws4_request d2ff14daa49d16754bb5ee0ac0d342c99a82a2a8115c9701bf506997411d4ad2</StringToSign>
<StringToSignBytes>41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 32 30 32 34 30 35 30 37 54 31 35 30 32 32 31 5a 0a 32 30 32 34 30 35 30 37 2f 6f 62 73 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 64 32 66 66 31 34 64 61 61 34 39 64 31 36 37 35 34 62 62 35 65 65 30 61 63 30 64 33 34 32 63 39 39 61 38 32 61 32 61 38 31 31 35 63 39 37 30 31 62 66 35 30 36 39 39 37 34 31 31 64 34 61 64 32</StringToSignBytes>
<CanonicalRequest>GET /%E7%AC%AC%E5%8D%81%E4%B8%80%E5%91%A8.docx X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=DDFUM5GIXQBGZ55ROPPH%2F20240507%2Fobs%2Fs3%2Faws4_request&amp;X-Amz-Date=20240507T150221Z&amp;X-Amz-Expires=900&amp;X-Amz-SignedHeaders=host host:liuquan.obs.cn-north-4.myhuaweicloud.com host UNSIGNED-PAYLOAD</CanonicalRequest>
<StringToSignBytes>47 45 54 0a 2f 25 45 37 25 41 43 25 41 43 25 45 35 25 38 44 25 38 31 25 45 34 25 42 38 25 38 30 25 45 35 25 39 31 25 41 38 2e 64 6f 63 78 0a 58 2d 41 6d 7a 2d 41 6c 67 6f 72 69 74 68 6d 3d 41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 26 58 2d 41 6d 7a 2d 43 72 65 64 65 6e 74 69 61 6c 3d 44 44 46 55 4d 35 47 49 58 51 42 47 5a 35 35 52 4f 50 50 48 25 32 46 32 30 32 34 30 35 30 37 25 32 46 6f 62 73 25 32 46 73 33 25 32 46 61 77 73 34 5f 72 65 71 75 65 73 74 26 58 2d 41 6d 7a 2d 44 61 74 65 3d 32 30 32 34 30 35 30 37 54 31 35 30 32 32 31 5a 26 58 2d 41 6d 7a 2d 45 78 70 69 72 65 73 3d 39 30 30 26 58 2d 41 6d 7a 2d 53 69 67 6e 65 64 48 65 61 64 65 72 73 3d 68 6f 73 74 0a 68 6f 73 74 3a 6c 69 75 71 75 61 6e 2e 6f 62 73 2e 63 6e 2d 6e 6f 72 74 68 2d 34 2e 6d 79 68 75 61 77 65 69 63 6c 6f 75 64 2e 63 6f 6d 0a 0a 68 6f 73 74 0a 55 4e 53 49 47 4e 45 44 2d 50 41 59 4c 4f 41 44</StringToSignBytes>
</Error>

**Comment by Daliuq** [comment]
或许是使用了前后端分离？

**Comment by zhaojun1998** [comment]
抱歉，因修改的不确定性，对源码运行不提供任何技术支持。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月7日(周二) 晚上11:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 基于AbstractS3BaseFileService实现的存储源上传失败 (Issue #664)




 
环境信息
  
ZFile 版本：4.1.5
 
部署方式：源码启动
 
操作系统/设备：Windows
 
浏览器/版本号：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
  
复现步骤
 
首先我尝试了腾讯云COS，然后尝试了华为云OBS，均是能下载，能访问文件夹，但是就是上传报403，SignatureDoesNotMatch，按理来说其他操作也是要预签名的，其他操作没有问题，就上传有问题
 
预期结果
 
上传成功
 
实际结果
 
上传失败
 
额外信息
 
Windows源码运行，华为云存储源上传报403
 
 <script/&gt;
 SignatureDoesNotMatch
 The request signature we calculated does not match the signature you provided. Check your key and signing method.
 0000018F5393CAFFF8CBFD034A985328
 Z9v+cC1sRnaWw6x0vi8pxxYA0YVnKxbYHUPAFpnxkX8sLV44u5b02Z+ailn2wCnR
 DDFUM5GIXQBGZ55ROPPH
 4b6102fa12cf3b7ad51dcf101a7f023b19da0aa573624266b95a0c76f201cb91
 AWS4-HMAC-SHA256 20240507T150221Z 20240507/obs/s3/aws4_request d2ff14daa49d16754bb5ee0ac0d342c99a82a2a8115c9701bf506997411d4ad2
 41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 32 30 32 34 30 35 30 37 54 31 35 30 32 32 31 5a 0a 32 30 32 34 30 35 30 37 2f 6f 62 73 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 64 32 66 66 31 34 64 61 61 34 39 64 31 36 37 35 34 62 62 35 65 65 30 61 63 30 64 33 34 32 63 39 39 61 38 32 61 32 61 38 31 31 35 63 39 37 30 31 62 66 35 30 36 39 39 37 34 31 31 64 34 61 64 32
 GET /%E7%AC%AC%E5%8D%81%E4%B8%80%E5%91%A8.docx X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=DDFUM5GIXQBGZ55ROPPH%2F20240507%2Fobs%2Fs3%2Faws4_request&amp;X-Amz-Date=20240507T150221Z&amp;X-Amz-Expires=900&amp;X-Amz-SignedHeaders=host host:liuquan.obs.cn-north-4.myhuaweicloud.com host UNSIGNED-PAYLOAD
 47 45 54 0a 2f 25 45 37 25 41 43 25 41 43 25 45 35 25 38 44 25 38 31 25 45 34 25 42 38 25 38 30 25 45 35 25 39 31 25 41 38 2e 64 6f 63 78 0a 58 2d 41 6d 7a 2d 41 6c 67 6f 72 69 74 68 6d 3d 41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 26 58 2d 41 6d 7a 2d 43 72 65 64 65 6e 74 69 61 6c 3d 44 44 46 55 4d 35 47 49 58 51 42 47 5a 35 35 52 4f 50 50 48 25 32 46 32 30 32 34 30 35 30 37 25 32 46 6f 62 73 25 32 46 73 33 25 32 46 61 77 73 34 5f 72 65 71 75 65 73 74 26 58 2d 41 6d 7a 2d 44 61 74 65 3d 32 30 32 34 30 35 30 37 54 31 35 30 32 32 31 5a 26 58 2d 41 6d 7a 2d 45 78 70 69 72 65 73 3d 39 30 30 26 58 2d 41 6d 7a 2d 53 69 67 6e 65 64 48 65 61 64 65 72 73 3d 68 6f 73 74 0a 68 6f 73 74 3a 6c 69 75 71 75 61 6e 2e 6f 62 73 2e 63 6e 2d 6e 6f 72 74 68 2d 34 2e 6d 79 68 75 61 77 65 69 63 6c 6f 75 64 2e 63 6f 6d 0a 0a 68 6f 73 74 0a 55 4e 53 49 47 4e 45 44 2d 50 41 59 4c 4f 41 44

**Comment by Daliuq** [comment]
已解决，服务器端要配置跨域，才能在window下源码运行
