### ISSUE TITLE
feat: 关于安装时存储策略界面的小建议

### ISSUE THREAD

**Issue by D3CODING** [zfile-dev/zfile#67]
### S3储存策略界面问题
在后台设置S3储存时，最后两个选项是直接下拉或者选择的
![Snipaste_2020-02-28_19-54-56.png](https://i.loli.net/2020/02/29/AXsgM3tnY9D4ibQ.png)

但在安装时就选S3，就变成输入框。试了下，前面那个输入域名风格的英文，后面那个应该是写true或者false。
![Snipaste_2020-02-29_00-30-39.png](https://i.loli.net/2020/02/29/QdomhKGV7eDNHZB.png)
这个输入框对第一次使用的用户略微不友好。

因为国内很多对象储存兼容S3协议，再加之S3支持生成私有地址，还是比较有用，希望能够优化下。

### 关于新加入的Ufile策略
一开始以为是Ucloud家的对象储存Ufile，因为一搜索Ufile，前几页都是这个，后来发现是U-file直链云。其实比较希望能够接入Ucloud家的对象储存，因为每个月有20G免费额度，一些小文件是足够了。虽然Ucloud的对象储存也兼容S3，但是试了很久都只能用http不能https，所以直接支持官方SDK就好了。

**Comment by zhaojun1998** [comment]
已发布 2.1 版本，修复了安装时表单的问题，至于 UCLOUD 的对象存储，使用兼容 S3 协议的，不是能填写加速域名吗，你写带 https 的就行了
