### ISSUE TITLE
不兼容S3中针对斜杠[/]和小数点[.]作为文件夹名字

### ISSUE THREAD

**Issue by lcxw** [zfile-dev/zfile#673]
## 环境信息
- ZFile 版本：`3.x`
- 部署方式：`源码启动`
- 操作系统/设备：`Windows`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36`

## 复现步骤
运行源码并配置S3或者minio后，部分文件夹无法显示（文件夹名字就是斜杠，或者理解问根目录），或者文件夹名字是英文小数点

## 预期结果
显示斜杠文件夹，并能进入该文件下，然后列出斜杠文件夹下的数据，主要 斜杠是一个文件夹，而不是根文件夹（及文件路径为空）

## 实际结果
没有显示斜杠文件夹，代码中continue了

## 额外信息
无

**Comment by zhaojun1998** [comment]
你确定你的存储桶中有一个命名为 `/` 还有命名为 `.` 的文件夹？使用其他 S3 连接工具/软件都包含这两个文件夹吗？

我感觉像是你把你目前连接 S3 软件显示出 . 和 / 当成了文件夹，但实际上 . 是一个 UNIX 系统中的隐藏文件用来表示当前目录。

你可以提供一下你使用的软件名，以及你的 S3 具体种类（如阿里），你也可以反馈下使用其他 S3 连接工具/软件显示行为是什么。

**Comment by lcxw** [comment]
明天我截个图过来

**Comment by lcxw** [comment]
![斜杠可以作为文件夹名字，并且下级文件夹名字是斜杠结尾](https://github.com/zfile-dev/zfile/assets/19720270/f28371a5-ccb4-44f3-a078-168573487ce3)
![支持同时列出多个bucket](https://github.com/zfile-dev/zfile/assets/19720270/17446afd-a7e8-4449-8a23-11c0e12e4198)
![bucket列表](https://github.com/zfile-dev/zfile/assets/19720270/fcf4de3d-d109-43b7-a017-176aa996285e)
![斜杠路径下的文件和文件夹](https://github.com/zfile-dev/zfile/assets/19720270/605b6dea-59e9-42e0-9d70-bc9ce2266256)

**Comment by lcxw** [comment]
1. 斜杠可以作为文件夹
2. 斜杠可以作为文件夹名字，并且下级文件夹名字是斜杠结尾
3. 支持同时列出多个bucket

**Comment by lcxw** [comment]
在zfile里面就不会显示斜杠那个文件夹

**Comment by zhaojun1998** [comment]
这是这个软件自己的显示行为，而且这不影响功能使用，我无法为此改变其他 ZFile 用户的使用习惯。

你使用其他 S3 软件看，尤其是网页端的程序（如 `alist`, `cloudreve`），应该都是没有 . 和文件夹后 / 的显示的。

你也没回答我你使用的 S3 是哪家的，如果有官方控制台，如阿里云 OSS， MINIO 都有自带的网页端，你也可以去看看显示行为是什么。

**Comment by lcxw** [comment]
好的，这个软件是S3 browser，服务端是minio，如果不打算改也没事，我自己fork一个重新打个包就行，再次感谢作者提供的开源软件，对我帮助非常大。

**Comment by lcxw** [comment]
另外再咨询一个事，是否有计划在同一个配置里面支持列出多个bucket，而不是每个bucket都要单独重新配置一遍。

**Comment by zhaojun1998** [comment]
没计划，但是现在有复制功能啊。后台存储源下拉菜单中有。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月23日(周四) 中午1:10
收件人: ***@***.***&gt;;
抄送: "zhao ***@***.******@***.***&gt;;
主题: Re: [zfile-dev/zfile] 不兼容S3中针对斜杠[/]和小数点[.]作为文件夹名字 (Issue #673)




 
另外再咨询一个事，是否有计划在同一个配置里面支持列出多个bucket，而不是每个bucket都要单独重新配置一遍。
