### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by xuze1993** [zfile-dev/zfile#68]
对象存储访问的时候总是报错，还有下载的时候不支持中文名。这个是功能上的原因吗

**Comment by zhaojun1998** [comment]
请提供更详细的信息，哪家的对象存储，公有策略还是私有，举例文件名

**Comment by xuze1993** [comment]
就是我试阿里oss和又拍云的时候列目录都能看到，但是访问文件会报错“系统异常，请联系管理员”，好像是私有策略

**Comment by zhaojun1998** [comment]
已发布 2.1 版本，修复了此问题
