### ISSUE TITLE
捐赠版视频性能劣化

### ISSUE THREAD

**Issue by zcbm1341** [zfile-dev/zfile#684]
## 环境信息
- ZFile 版本：`4.1.6 Pro`
- 部署方式：`Linux-脚本`
- 操作系统/设备：`Linux`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`

## 复现步骤
案例1：
关闭多线程下载功能，使用网页播放特定视频，拖动进度条
案例2：
关闭多线程下载功能，使用potplayer特定视频，拖动进度条
案例3：
开启多线程下载功能，使用网页播放特定视频，拖动进度条
案例4：
开启多线程下载功能，使用potplayer特定视频，拖动进度条

## 预期结果
以下为zfile 4.1.5的表现
案例1、3：
可以立即播放，并且拖动进度条也没有明显的缓冲时间
案例2、4：
可以立即播放，并且拖动进度条也没有明显的缓冲时间

## 实际结果
案例1：
可以立即播放，但无法拖动进度条
案例2：
可以立即播放，拖动进度条会导致软件卡死
案例3：
需要等待很长一段时间才能播放，拖动进度条后也有较长的缓冲时间
案例4：
需要等待很长一段时间才能播放，拖动进度条会导致软件卡死

## 额外信息
zfile 4.1.6 Pro在网页版加载视频或potplayer播放视频时cpu占用率非常高（可以到100%），zfile 4.1.5则维持在很低的水平（10%不到）。
两个版本均使用相同的本地存储源
===捐赠版配置===
zfile版本：4.1.6Pro
软件架构：arm64
操作系统：Ubuntu 24.04 LTS
CPU：RK3568
内存：4GB
===开源版配置===
zfile版本：4.1.5
操作系统：Ubuntu 24.04 LTS
CPU：RK3568
内存：4GB
JRE：openjdk 21.0.3

网页播放，4.1.5
![image-20240715105511400](https://github.com/user-attachments/assets/90f6e38b-5897-40f0-bbe1-15d9dd4e1364)
网页播放，4.1.6 Pro
![image-20240715110343747](https://github.com/user-attachments/assets/f83345c0-92d1-4a74-a1a0-aa3667d87a4b)
potplayer播放，4.1.5
![image-20240715111453293](https://github.com/user-attachments/assets/b0aa6b07-7672-4e22-939e-c3143ad2f812)
potplayer播放，4.1.6 Pro
![image-20240715111150878](https://github.com/user-attachments/assets/994e4731-fd91-4156-ab65-2826b61c94c3)

**Comment by zhaojun1998** [comment]
已确认是 JDK 版本问题，下次更新捐赠版会支持更高版本的 JDK
