### ISSUE TITLE
腾讯云COS权限不足

### ISSUE THREAD

**Issue by ghost** [zfile-dev/zfile#69]
**问题 :** 腾讯云COS提示权限不足
- 已经添加了子用户,并授予了权限
- 子用户和根用户都不行
- 文件权限都是继承自Bucket
- 跨域访问也设置好了

**环境信息 :**
zfile : 最新的2.0版
Ubuntu 18.04
阿里云ECS
**PS :**
貌似阿里云存在一样的问题

**Comment by zhaojun1998** [comment]
已发布 2.1 版本，修复了此问题
