### ISSUE TITLE
本地存储可以映射多个盘吗（docker）

### ISSUE THREAD

**Issue by maomaoyan** [zfile-dev/zfile#690]
## 环境信息
- ZFile 版本：`4.1.5`
- 部署方式：`Docker`
- 操作系统/设备：`其他(在附加信息中填写)`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36`

## 复现步骤
ImmortalWrt openwrt系统里docker安装zfile成功运行
部署的时候-v /root/zfile/file:/data/file \ 这行看起来只能映射一个地址。
但是我软路由像有两个分区不同盘，我想在加一个地址。不然zfile后台管理的文件路径，只能填一个/data/file。

## 预期结果
本地存储可以挂载多个路径

## 实际结果
本地存储只能挂载一个路径

## 额外信息
请问下我应该怎么设置才能解决此问题

**Comment by zhaojun1998** [comment]
你部署时写多个-v不就是了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月5日(周一) 下午5:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 本地存储可以映射多个盘吗（docker） (Issue #690)




 
环境信息
  
ZFile 版本：4.1.5
 
部署方式：Docker
 
操作系统/设备：其他(在附加信息中填写)
 
浏览器/版本号：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
  
复现步骤
 
ImmortalWrt openwrt系统里docker安装zfile成功运行
 部署的时候-v /root/zfile/file:/data/file \ 这行看起来只能映射一个地址。
 但是我软路由像有两个分区不同盘，我想在加一个地址。不然zfile后台管理的文件路径，只能填一个/data/file。
 
预期结果
 
本地存储可以挂载多个路径
 
实际结果
 
本地存储只能挂载一个路径
 
额外信息
 
请问下我应该怎么设置才能解决此问题
