### ISSUE TITLE
文件夹后的大小不正确

### ISSUE THREAD

**Issue by vincexjl** [zfile-dev/zfile#697]
## 描述
文件夹后显示的大小似乎不是文件夹的大小信息，请问是什么信息，并且能否实现显示为该文件夹实际占用大小空间信息

## 额外信息
无

**Comment by zhaojun1998** [comment]
如果显示-或4096是正常的，因为存储源没有接口直接提供文件夹大小，除非递归所有子文件统计，但是那样非常占用资源，比如你右键c盘属性，看看多久能统计出占用大小。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月11日(周三) 下午5:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 文件夹后的大小不正确 (Issue #697)




 
描述
 
文件夹后显示的大小似乎不是文件夹的大小信息，请问是什么信息，并且能否实现显示为该文件夹实际占用大小空间信息
 
额外信息
 
无
