### ISSUE TITLE
能否以环境变量的方式配置mysql数据库

### ISSUE THREAD

**Issue by candies404** [zfile-dev/zfile#698]
## 描述
能否以环境变量的方式配置mysql数据库

## 额外信息
无

**Comment by zhaojun1998** [comment]
1.为啥不用配置文件，
2.什么场景要用环境变量来配置
3.比如怎么配置 win还是linux还是docker



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月12日(周四) 凌晨1:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zfile-dev/zfile] 能否以环境变量的方式配置mysql数据库 (Issue #698)




 
描述
 
能否以环境变量的方式配置mysql数据库
 
额外信息
 
无

**Comment by candies404** [comment]
配置文件的方式比较麻烦，我用的是docker习惯了 -e xxx=xxx



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhao ***@***.***&gt;; 
发送时间: 2024年9月12日(星期四) 上午7:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zfile-dev/zfile] 能否以环境变量的方式配置mysql数据库 (Issue #698)














 1.为啥不用配置文件， 
 2.什么场景要用环境变量来配置 
 3.比如怎么配置 win还是linux还是docker 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年9月12日(周四) 凌晨1:20 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [zfile-dev/zfile] 能否以环境变量的方式配置mysql数据库 (Issue #698) 
 
 
 
 
   
 描述 
   
 能否以环境变量的方式配置mysql数据库 
   
 额外信息 
   
 无

**Comment by zhaojun1998** [comment]
还真是支持的，所有选项大写，`.` 和 `-` 变成 `_` 即可，如：

```
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
```

可这样通过环境变量配置：

```
-e SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
-e SPRING_DATASOURCE_URL='jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true'
-e SPRING_DATASOURCE_USERNAME=root
-e SPRING_DATASOURCE_PASSWORD=password
```

> 注意：有特殊字符的需要转义或加引号，如上面的 `SPRING_DATASOURCE_URL`。还有通过 docker 指定环境变量后，根据 docker 的特性，如需修改需重建容器

**Comment by candies404** [comment]
可以了，感谢您的回复
