### ISSUE TITLE
点击刷新缓存 会提示错误, 看network那边的日志是 

### ISSUE THREAD

**Issue by shoaly** [zfile-dev/zfile#70]
## 错误日志
从console那边看到 是找不到这个接口
chunk-vendors.b5ddaa46.js:40 POST ...../admin/cache/refresh 404

**Comment by zhaojun1998** [comment]
@shoaly  已发布 2.1 版本，修复了此问题

**Comment by shoaly** [comment]
真棒~~  之前的版本也很好用 已经用上了, 老婆网课可以让学生下载课件

**Comment by shoaly** [comment]
我从github得release里面下载得2.2.war 解压缩之后 还是会复现无法刷新单个目录缓存得bug
*---------------------------------------------------------------------------------*
