### ISSUE TITLE
使用反代内网穿透后，访问为宝塔的默认站点，不穿透是正常的，穿透其他页面没有这个问题

### ISSUE THREAD

**Issue by blacowboy** [zfile-dev/zfile#700]
## 环境信息
- ZFile 版本：`4.1.5`
- 涉及存储源：`不涉及`
- 部署方式：`Linux-宝塔`
- 操作系统/设备：`Windows`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0`

## 复现步骤
反代+穿透后访问为宝塔默认站点p6oy.top，改HOSTS为本地后访问为zfile页面

## 预期结果
file.p6oy.top为zfile页面

## 实际结果
file.p6oy.top为p6oy.top页面

## 额外信息
无

**Comment by zhaojun1998** [comment]
我想这是你配置问题，zfile 不会限制这个，也没有做什么跳转。
你可以将 zfile 停止掉，在同端口运行一个其他 web 程序来验证，如果仍然是同样的问题，那就检查你宝塔反代或穿透的配置吧。

**Comment by zhaojun1998** [comment]
长时间未回复，先关闭了
