### ISSUE TITLE
视频无法播放

### ISSUE THREAD

**Issue by 1115501230** [zfile-dev/zfile#702]
## 环境信息
- ZFile 版本：`4.1.6 Pro`
- 涉及存储源：`FTP`
- 部署方式：`Linux-宝塔`
- 操作系统/设备：`Linux`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/82.0.4068.4 Safari/537.36`

## 复现步骤
1.点击视频后，无法实现在线播放，但是点击直接下载，会跳转在线播放，说明视频地址无问题，应该是内置播放器问题
2.设置基路径后，视频地址忽略了基路径的文件目录，导致无法下载和播放问题

## 预期结果
点击视频在线播放

## 实际结果
在线播放失败

## 额外信息
错误出现在我在ftp储存中点击播放视频导致:
Access to video at 'http://b21029.03184.com:9040/L_20240923210555kmpsbq/video_share/%E6%88%91%E5%B7%AE%E7%82%B9%E5%B0%B1%E4%BF%A1%E4%BA%86/%E5%A4%A7%E5%8A%9B%E9%87%91%E5%88%9A1-001-laoyu.12580.wang-%E5%B1%8C%E7%B5%B2%E4%BA%BA%E7%94%9F.mp4?signature=fccbf18dcc5a56380d19bb803a63e50dab57465a1984da40e2a748bc2a14990869d2769a85eec86580f85f324d76e9848739fc103a9c1aa2053a52aea24612b30324299fc2e7b5fc3887fd9c6a7424fc94ee80244ae215e3a7e515cbaa943da7bb91802ec4b0f1ea2c1a5e7f11345e7d' from origin 'http://yun.12580.wang' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
b21029.03184.com:9040/L_20240923210555kmpsbq/video_share/%E6%88%91%E5%B7%AE%E7%82%B9%E5%B0%B1%E4%BF%A1%E4%BA%86/%E5%A4%A7%E5%8A%9B%E9%87%91%E5%88%9A1-001-laoyu.12580.wang-%E5%B1%8C%E7%B5%B2%E4%BA%BA%E7%94%9F.mp4?signature=fccbf18dcc5a56380d19bb803a63e50dab57465a1984da40e2a748bc2a14990869d2769a85eec86580f85f324d76e9848739fc103a9c1aa2053a52aea24612b30324299fc2e7b5fc3887fd9c6a7424fc94ee80244ae215e3a7e515cbaa943da7bb91802ec4b0f1ea2c1a5e7f11345e7d:1 GET http://b21029.03184.com:9040/L_20240923210555kmpsbq/video_share/%E6%88%91%E5%B7%AE%E7%82%B9%E5%B0%B1%E4%BF%A1%E4%BA%86/%E5%A4%A7%E5%8A%9B%E9%87%91%E5%88%9A1-001-laoyu.12580.wang-%E5%B1%8C%E7%B5%B2%E4%BA%BA%E7%94%9F.mp4?signature=fccbf18dcc5a56380d19bb803a63e50dab57465a1984da40e2a748bc2a14990869d2769a85eec86580f85f324d76e9848739fc103a9c1aa2053a52aea24612b30324299fc2e7b5fc3887fd9c6a7424fc94ee80244ae215e3a7e515cbaa943da7bb91802ec4b0f1ea2c1a5e7f11345e7d net::ERR_FAILED
AI解释:这个错误是由跨源资源共享(CORS)策略引起的。CORS是一种安全机制,用于限制网页从不同源加载资源。在这种情况下,视频资源的服务器没有正确配置CORS头,导致浏览器阻止了访问。

**Comment by zhaojun1998** [comment]
显然 AI 已经告诉了你答案，你填写加速域名了把，你这个加速域名没支持跨域访问，试试不填写加速域名播放。

关于问题 2 我复现后会解决

**Comment by 1115501230** [comment]
已经收到您发送的材料，如果未备注清楚的文件，将不会被使用！若未备注清楚请备注好发过来。感谢您的阅读。

**Comment by zhaojun1998** [comment]
长时间未回复，关闭问题，有需要再打开
