### ISSUE TITLE
本地存储不能使用文件路径

### ISSUE THREAD

**Issue by youngledo** [zfile-dev/zfile#703]
## 环境信息
- ZFile 版本：`4.1.5`
- 涉及存储源：`本地存储`
- 部署方式：`其他(在附加信息中填写)`
- 操作系统/设备：`Linux`
- 浏览器/版本号：`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0`

## 复现步骤
1. 使用[1Panel](https://1panel.cn/)（类似宝塔）在应用商店安装的ZFile，并挂载了目录（/opt/zfile/data/mnt），部署成功。
  <img width="588" alt="image" src="https://github.com/user-attachments/assets/c2643dee-dbe6-4ba4-9a56-9f9ad2e0596d">

2. 使用本地存储，设置文件路径，提示文件路径“/opt/zfile/data/mnt”不存在。

## 预期结果
正常创建本地存储。

## 实际结果
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/9990ae1e-0ee4-405d-b69a-2446b7b69893">

## 额外信息
无

**Comment by zhaojun1998** [comment]
修改 docker 配置是需要删除容器重建才生效哦（docker 本身限制），而且你可以先挂载 / 去前台查看实际的文件目录情况。

**Comment by youngledo** [comment]
> 修改 docker 配置是需要删除容器重建才生效哦（docker 本身限制），而且你可以先挂载 / 去前台查看实际的文件目录情况。

1Panel上修改的，有重建。但是否是删除再重建这个不好说，你也可以试下。我暂时放弃本地存储了。
