### ISSUE TITLE
PDF打开内容乱码

### ISSUE THREAD

**Issue by panther125** [zfile-dev/zfile#705]
## 环境信息
- ZFile 版本：`4.1.5`
- 涉及存储源：`本地存储`
- 部署方式：`Linux-脚本`
- 操作系统/设备：`Linux`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36`

## 复现步骤
上传PDF文件，在线预览发生乱码

## 预期结果
显示正常内容

## 实际结果
乱码

## 额外信息
无

**Comment by zhaojun1998** [comment]
1. 请提供截图，怎么个乱码。
2. 将 pdf 拖到浏览器空白标签页看看用浏览器自带预览是否正常。

**Comment by panther125** [comment]
![Uploading image.png…]()

**Comment by panther125** [comment]
![](https://img.picui.cn/free/2024/11/03/6727934e314db.png)
浏览器是不乱码的
项目使用源代码部署方式部署

**Comment by zhaojun1998** [comment]
> 
> ![](https://img.picui.cn/free/2024/11/03/6727934e314db.png)
> 浏览器是不乱码的
> 项目使用源代码部署方式部署

看起来你是自己在显示设置-文本文件后缀手动增加过pdf后缀，应该去掉。
