### ISSUE TITLE
密码设置bug

### ISSUE THREAD

**Issue by jiangjiangflies** [zfile-dev/zfile#71]
您好，
   对根目录文件夹设置密码，用户访问 http://www.example.com/#/main/ 需要输入密码；
   但是直接访问该文件夹下面的所有子目录，就可以跳过密码验证直接访问。比如访问 http://www.example.com/#/main/A/ 就不需要输密码。这样一来，设置的密码就相当于是无效的。

  我想设置一个全局密码，类似Ngnix目录列表的密码设置。用户访问网站http://www.example.com/ 
 就需要密码，同时，不可以跳过密码验证，直接访问子目录，如 http://www.example.com/A/
  
  大佬有解决办法吗？

**Comment by zhaojun1998** [comment]
不会支持此功能的。
首先，如果他根目录都进不去，那么他怎么知道里面有什么文件夹。
其次，这样支持的话，会有严重的性能问题，如请求文件夹  xxx.com/#/main/1/2/3/4/5/6/7/8/9/10   ，那么性能，就会比以前慢 10 倍，因为要获取他所有父文件夹中的内容。

**Comment by jiangjiangflies** [comment]
> 不会支持此功能的。
> 首先，如果他根目录都进不去，那么他怎么知道里面有什么文件夹。
> 其次，这样支持的话，会有严重的性能问题，如请求文件夹 xxx.com/#/main/1/2/3/4/5/6/7/8/9/10 ，那么性能，就会比以前慢 10 倍，因为要获取他所有父文件夹中的内容。

是这样的，根目录的密码我会定期更改。他进去一次就知道所有的子文件夹了，以后我在怎么修改根目录密码也没用了。
不过目前我已经用Nginx反代功能实现我的目的啦。辛苦了！

**Comment by jiangjiangflies** [comment]
> 不会支持此功能的。
> 首先，如果他根目录都进不去，那么他怎么知道里面有什么文件夹。
> 其次，这样支持的话，会有严重的性能问题，如请求文件夹 xxx.com/#/main/1/2/3/4/5/6/7/8/9/10 ，那么性能，就会比以前慢 10 倍，因为要获取他所有父文件夹中的内容。

是这样的，根目录的密码我会定期更改。他进去一次就知道所有的子文件夹了，以后我在怎么修改根目录密码也没用了。
不过目前我已经用Nginx反代功能实现我的目的啦。辛苦了！

**Comment by smloli** [comment]
可以分享一下教程吗
