### ISSUE TITLE
IDEA编译出现错误

### ISSUE THREAD

**Issue by Steelzy** [zfile-dev/zfile#75]
您好，编译的时候提示bean未找到，是怎么回事呢？还麻烦请教您一下,谢谢！
![image](https://user-images.githubusercontent.com/31895011/76416449-15e98c80-63d6-11ea-9f5f-21efbe72d89d.png)

**Comment by lcxw** [comment]
你的数据库配置好没啊

**Comment by Steelzy** [comment]
> 你的数据库配置好没啊

哦，不好意思，忘了数据库还没配置。谢谢

**Comment by Steelzy** [comment]
> 你的数据库配置好没啊

不好意思，再次打扰，我配置好了数据库，还是这个错误？

**Comment by zhaojun1998** [comment]
拉取代码后你都改了什么东西

**Comment by Steelzy** [comment]
> 拉取代码后你都改了什么东西

就把数据源改为了mysql，其他什么都没有修改

**Comment by zhaojun1998** [comment]
如果不改数据库源，可以启动么

**Comment by Steelzy** [comment]
> 如果不改数据库源，可以启动么

试过了，拉下来第一次运行（什么都没改）就是这个错误

**Comment by zhaojun1998** [comment]
删除用户目录下 `.zfile` 文件夹试试

**Comment by Steelzy** [comment]
> 删除用户目录下 `.zfile` 文件夹试试

好的，谢谢

**Comment by Steelzy** [comment]
> 删除用户目录下 `.zfile` 文件夹试试

您好 ，错误消失了，127.0.0.1 8080端口能够正常访问了，想问下这个是为什么呢？删除.zfile文件夹，就能解决这个问题？

**Comment by Steelzy** [comment]
> 删除用户目录下 `.zfile` 文件夹试试

非常感谢 您的帮助！
