### ISSUE TITLE
请问main和admin/login是否可以运行在不同的端口

### ISSUE THREAD

**Issue by slinar** [zfile-dev/zfile#76]
如题, 比如main在80运行, admin管理界面在8081运行, 方便防火墙做策略, 这样只有指定IP可以访问管理界面

**Comment by oldzhg** [comment]
同问 可不可以自定义端口 8080上有服务

**Comment by zhaojun1998** [comment]
@slinar 不支持运行在不同端口

**Comment by zhaojun1998** [comment]
@oldzhg  支持自定义端口，文档中有写
