### ISSUE TITLE
feat: 隐藏文件夹功能

### ISSUE THREAD

**Issue by yangbohz** [zfile-dev/zfile#77]
## 概述

类似文件夹密码保护那样，增加一个文件夹隐藏的功能

## 动机

不需要用户权限管理，但是有些文件不希望所有人看到，前台显示密码保护可能会有好奇宝宝不断地尝试密码

## 详细解释

在文件夹下放置一个hidden文件，则此文件夹再前台不显示，只能通过输入url的方式打开。可以和密码访问结合比如即隐藏又加密或者仅隐藏。可以将目前的密码文件稍微修改一下，比如放置一个access文件，如下
···
password:thisispw
hidden:true

**Comment by abiglee** [comment]
感觉很鸡肋的功能啊

**Comment by yangbohz** [comment]
> 感觉很鸡肋的功能啊

功能总没有嫌多的嘛╮(╯▽╰)╭

**Comment by lcxw** [comment]
> > 感觉很鸡肋的功能啊
> 
> 功能总没有嫌多的嘛╮(╯▽╰)╭

fork？

**Comment by zhaojun1998** [comment]
@vensterlz @abiglee @lcxw   已在 2.8 版本增加此功能。
