### ISSUE TITLE
feat: 关于文件夹加密优化

### ISSUE THREAD

**Issue by jiangjiangflies** [zfile-dev/zfile#79]
作者，您好，
首先非常感谢开发zfile。关于文件夹密码，想提一个小建议。
目前给文件夹A加密码，用户可以绕过A文件夹，直接访问其子文件夹。这个漏洞还是比较严重的。理想的效果是，给文件夹A加密码，如果用户直接访问其子文件夹a，那么会要求其输入A文件夹的密码。并且，输入密码后，短时间内无需再次输入。
另外一个项目：[OLAINDEX](https://github.com/WangNingkai/OLAINDEX) 的文件夹加密效果就是这样的。强烈建议作者参考借鉴~
感谢！

**Comment by zhaojun1998** [comment]
这个问题，你之前提过的，确实会有性能问题的。

既然这样的话，我还是支持一下，将其改为配置，当然，此功能的前提，是开启缓存的情况下，不开启缓存的话，递归父文件夹的效率绝对是无法接受的。

**Comment by jiangjiangflies** [comment]
对的，我之前提过这个问题。后来发现OLAINDEX有这个功能，感觉挺好用，所以再次向您提出来。您的Zfile更简洁，我也在用。
改为配置吧，而且不需要再手动加一个密码文件了，更便捷一些！太感谢了！

**Comment by capric98** [comment]
> 对的，我之前提过这个问题。后来发现OLAINDEX有这个功能，感觉挺好用，所以再次向您提出来。您的Zfile更简洁，我也在用。
> 改为配置吧，而且不需要再手动加一个密码文件了，更便捷一些！太感谢了！

我有个建议，对于某个文件夹，若其无`password.txt`但其父文件夹有密码的话，要求提供父文件夹的密码，至多只向上递归一层；如果想要绕过密码的话，需要猜出两层目录结构，可能性大大降低，如果想要更高的安全系数，应该建议用户给每个文件夹做好加密
