### ISSUE TITLE
feat: 请求/api/config时带上password参数

### ISSUE THREAD

**Issue by capric98** [zfile-dev/zfile#83]
## 概述
前端在请求`/api/config?path=xxx`时，若该文件夹为加密文件夹，需和`/api/list?path=xxx&password=xxx`一样，同时带上`password`参数。

## 动机
请求`/api/config`的返回中可能含有readme信息，如果加密文件夹内的readme信息含有该文件夹内子文件夹的目录结构或者其他信息，通过该api便能够获取加密文件夹的部分信息，可能会造成安全问题，因此建议对`/api/config`的请求同样加上password信息

## 详细解释
假设有如下目录结构：
```
| - root
|      | - example
|            | - password.txt
|            | - readme.md
|            | - A
|            |     | - something
|            | - B
|                  | - something
```
用户Alice为了某些原因，在readme中标出了目录下的子结构（例如：该目录是XXX用途，A中为XXX，B中为XXX），当Bob请求`/api/config?path=/example`时，其中`readme`部分将上述内容返回，这样Bob将可以在不知道password.txt中密码的情况下，通过`/api/list?path=/example/A`获取文件夹A中的内容，这可能会造成一些安全上的担忧。
若`/api/config`与`/api/list`一样对加密文件夹要求提供密码，否则将返回`code=-2`，可以避免这种情况发生

**Comment by zhaojun1998** [comment]
已解决
