### ISSUE TITLE
feat: 感谢大佬的程序,菜鸟简单做了个docker先将就用着,等着官方版.

### ISSUE THREAD

**Issue by stilleshan** [zfile-dev/zfile#86]
差不多1-2个月前看楼主在V站发的开源贴,就收藏了...一直到现在才装...

作为docker党,简单将就做了个粗糙的先用着...等着官方版..

https://hub.docker.com/r/stilleshan/zfile

**Comment by zhaojun1998** [comment]
感谢，我现学了下，改动发了个官方版，先用着：

https://hub.docker.com/r/zhaojun1998/zfile

**Comment by lee29** [comment]
> 感谢，我现学了下，改动发了个官方版，先用着：
> 
> https://hub.docker.com/r/zhaojun1998/zfile

大佬，可以支持一下群晖的docker么

**Comment by stilleshan** [comment]
> > 感谢，我现学了下，改动发了个官方版，先用着：
> > https://hub.docker.com/r/zhaojun1998/zfile
> 
> 大佬，可以支持一下群晖的docker么

理论上我的docker和大佬出的官方版基本一样吧,都可以,按照下面操作

[群晖NAS高级服务 - docker 部署 zfile 在线文件目录](https://www.ioiox.com/archives/93.html)

**Comment by zhaojun1998** [comment]
一样的，都可以用

**Comment by lee29** [comment]
> > > 感谢，我现学了下，改动发了个官方版，先用着：
> > > https://hub.docker.com/r/zhaojun1998/zfile
> > 
> > 
> > 大佬，可以支持一下群晖的docker么
> 
> 理论上我的docker和大佬出的官方版基本一样吧,都可以,按照下面操作
> 
> [群晖NAS高级服务 - docker 部署 zfile 在线文件目录](https://www.ioiox.com/archives/93.html)


apm home: 
OPTS param:
Starting the zfile-2.2 ...OK!
PID: 34

大佬，日志显示这个，然后网页端也上不去。。。。

**Comment by lee29** [comment]
> > > > 感谢，我现学了下，改动发了个官方版，先用着：
> > > > https://hub.docker.com/r/zhaojun1998/zfile
> > > 
> > > 
> > > 大佬，可以支持一下群晖的docker么
> > 
> > 
> > 理论上我的docker和大佬出的官方版基本一样吧,都可以,按照下面操作
> > [群晖NAS高级服务 - docker 部署 zfile 在线文件目录](https://www.ioiox.com/archives/93.html)
> 
> apm home:
> OPTS param:
> Starting the zfile-2.2 ...OK!
> PID: 34
> 
> 大佬，日志显示这个，然后网页端也上不去。。。。

搞定了，原来第一次配置的时候是不能指定data的。。。

**Comment by lee29** [comment]
> > > > > 感谢，我现学了下，改动发了个官方版，先用着：
> > > > > https://hub.docker.com/r/zhaojun1998/zfile
> > > > 
> > > > 
> > > > 大佬，可以支持一下群晖的docker么
> > > 
> > > 
> > > 理论上我的docker和大佬出的官方版基本一样吧,都可以,按照下面操作
> > > [群晖NAS高级服务 - docker 部署 zfile 在线文件目录](https://www.ioiox.com/archives/93.html)
> > 
> > 
> > apm home:
> > OPTS param:
> > Starting the zfile-2.2 ...OK!
> > PID: 34
> > 大佬，日志显示这个，然后网页端也上不去。。。。
> 
> 搞定了，原来第一次配置的时候是不能指定data的。。。



> 一样的，都可以用

大佬，有个问题是怎么装载多个目录？

**Comment by zhaojun1998** [comment]
@lee29 新版本已支持同时挂载多个存储策略。且也有了 docker 镜像，故此问题关闭了
