### ISSUE TITLE
install 页面站点地址输入框前端校验规则有问题，比如局域网主机填写 http://cdh231:666 就会报错

### ISSUE THREAD

**Issue by geekyouth** [zfile-dev/zfile#88]
## 我的环境

操作系统  Linux
系统版本 3.10.0-1062.el7.x86_64
系统架构 amd64
程序路径 /opt/module/zfile-2.2/WEB-INF/classes
系统启动时间 36分36秒
系统总内存 3.87 GB
系统已使用内存 3.65 GB
系统空闲内存 228.89 MB
JVM 可占用内存 6.07 GB
JVM 已占用内存 880.00 MB
JVM 空闲内存 571.40 MB
JVM 版本 1.8.0_144

![image](https://user-images.githubusercontent.com/12899262/77647251-0acf5880-6fa1-11ea-960d-de215b491741.png)

## 错误日志

日志未记录到此错误
![image](https://user-images.githubusercontent.com/12899262/77647452-67cb0e80-6fa1-11ea-80eb-0a1b0993dce4.png)

## 期望行为
http://cdh231:666 这个地址应该是合规的呀。localhost 就不会报错。

![image](https://user-images.githubusercontent.com/12899262/77647472-70234980-6fa1-11ea-9efc-4c81911ed49f.png)

## 当前行为

版本号： https://github.com/zhaojun1998/zfile/releases/download/2.2/zfile-2.2.war

不过现在曲线救国绕过这个问题了，我填写了完整的局域网ip + 端口 【 http://192.168.8.231:666 】 就可以通过了。

**Comment by fcwys** [comment]
通常情况使用域名，一般形式为xxx.xxx这种，而localhost是一个很特殊的主机名，虽然理论上可行，但不建议这样用，哪怕是局域网也尽量使用域名或ip方式访问比较好

**Comment by zhaojun1998** [comment]
cdh231 这是本地 host 映射吧，如果是 cdh231.xxx 应该就不会有问题了，这是 ele ui 的通用 url 校验。
