### ISSUE TITLE
直链 doesn't work

### ISSUE THREAD

**Issue by pcbcos** [zfile-dev/zfile#89]
## 我的环境

操作系统 | Linux
-- | --
系统版本 | 5.5.7-1.el7.elrepo.x86_64
系统架构 | amd64
程序路径 | /root/zfile/WEB-INF/classes
系统启动时间 | 24分46秒
系统总内存 | 512.00 MB
系统已使用内存 | NaN undefined
系统空闲内存 | 961.99 MB
JVM 可占用内存 | 481.44 MB
JVM 已占用内存 | 80.27 MB
JVM 空闲内存 | 31.53 MB
JVM 版本 | 1.8.0_242

[zfile-2020-04-07-0.log](https://github.com/zhaojun1998/zfile/files/4445779/zfile-2020-04-07-0.log)

## 期望行为
idm能使进行下载

## 当前行为
![QQ截图20200408001647](https://user-images.githubusercontent.com/29155762/78693781-51706b80-792e-11ea-86f4-786ed4a5ab81.png)
直接点击下载是正常的，将直链使用迅雷、aria2下载正常
其他人也有这样的问题

**Comment by zhaojun1998** [comment]
@pcbcos 已更新 2.4 版本，请更新新版本后再次
