### ISSUE TITLE
［功能建议］是否可以支持文件链接分享

### ISSUE THREAD

**Issue by guqing** [zfile-dev/zfile#9]
有没有新增类似百度云那样，使用分享链接，分享文件的功能的打算呢，如此 网盘里的文件分享起来更方便

**Comment by zhaojun1998** [comment]
@guqing  定位不一样，那适用于多用户，本项目不会向那个方向开发的。

**Comment by guqing** [comment]
好的😃

**Comment by guqing** [comment]
> @guqing 定位不一样，那适用于多用户，本项目不会向那个方向开发的。

好的😃
