### ISSUE TITLE
只有ipv6的服务器是不是没法使用啊

### ISSUE THREAD

**Issue by Humetea** [zfile-dev/zfile#90]
大佬，那个监听端口8080是仅监听ipv4的吗

**Comment by Humetea** [comment]
知道原因了，应该是默认监听的是ipv4端口，可以用nginx反向代理一下，指到本地ipv4监听端口就可以。
可以在nginx中配置如下
server {
    listen 80;                       
    listen [::]:80;                    
    server_name host;      ##host改为浏览器访问的域名
    location / {
        proxy_pass http://localhost:8080;  ##修改为zfile监听的端口
    }
}

**Comment by Humetea** [comment]
nginx反代还是存在一个问题，安装的时候总是会显示异常，即使我的vps设置了dns64，也许与API有关系

**Comment by zhaojun1998** [comment]
@Humetea 暂无条件来测试 ipv6

**Comment by zhaojun1998** [comment]
先使用 ipv4 吧

**Comment by onepve** [comment]
> @Humetea 暂无条件来测试 ipv6

https://www.shopee6.com/cross-border-jianzhan-jingyan/euserv-order-v2ray-bt.html
https://wangdalao.com/2913.html
来玩呀大佬
