### ISSUE TITLE
feat: 首先感谢大佬，其次请问是否支持arm64架构？

### ISSUE THREAD

**Issue by adll123** [zfile-dev/zfile#93]
在dockerhub里查看tag，貌似没有arm64，求问是否支持？
如支持是否后续会出arm64的docker包？再次感谢

**Comment by lcxw** [comment]
可以自己构建的，程序上是支持的，你是想跑在树莓派上吗

**Comment by adll123** [comment]
> 可以自己构建的，程序上是支持的，你是想跑在树莓派上吗

差不多，是打算放在盒子里挂着OneDrive跑，小白自己不会构建（囧

**Comment by zhaojun1998** [comment]
@adrianliulee 
取决于所属架构是否支持安装 Java，理论上支持所有架构的。

**Comment by adll123** [comment]
> @adrianliulee
> 取决于所属架构是否支持安装 Java，理论上支持所有架构的。

好的，多谢大佬
