### ISSUE TITLE
docker 部署2.3 password.txt 错误?

### ISSUE THREAD

**Issue by stilleshan** [zfile-dev/zfile#95]
## 密码问题
官方docker貌似还没更新,我自己根据dockerfile build了以下,支持了2.3
但是发现在创建 password.txt 后,前台输入密码都是错误的.我看演示站点是2.3版本密码没问题,可能和docker运行有关?

## docker挂载
在就是新版貌似挂载数据库要在docker run里多加一个,类似以下?
```
    -v /root/zfile/conf:/root/.zfile \
    -v /root/zfile/db:/root/.zfile-new/db \
    -v /root/zfile/data:/root/zfile/data \
```

**Comment by stilleshan** [comment]
密码问题,本地存储和onedrive都测试过..不行.

**Comment by zhaojun1998** [comment]
@stilleshan 在 Linux 下使用 `vi/vim` 编辑会自动加一个换行符，这个要注意下。看看你是不是这个导致的。
