### ISSUE TITLE
系统异常, 请联系管理员

### ISSUE THREAD

**Issue by 5536086** [zfile-dev/zfile#96]
添加多盘之后，只有第一个盘能正常访问，后面的全部提示“系统异常，请联系管理员”。截图如下：
![QQ截图20200419215120](https://user-images.githubusercontent.com/20472307/79689536-1b18e180-8288-11ea-9433-d056135ffe98.jpg)

**Comment by zhaojun1998** [comment]
是同时添加多个 OneDrive 吧，已在 2.4 版本修复

**Comment by mi229ller** [comment]
2.4版本，依然存在 系统异常，请联系管理员 的问题。

**Comment by mi229ller** [comment]
建议把如果文件夹名和文件名是中文，只有文件名直链时转换为16进制，文件夹名依然是汉字，建议全部变成16进制。  https://zfile.jun6.net/directlink/1/视频/%E5%B8%A6%E5%AD%97%E5%B9%95%E7%9A%84%E8%A7%86%E9%A2%91.mp4
