### ISSUE TITLE
[问题]腾讯云cos

### ISSUE THREAD

**Issue by ravizhan** [zfile-dev/zfile#98]
请问zfile支持**腾讯云cos签名**或者**加速域名的cdn鉴权**吗
还有在修改已存在的驱动器时会报错
![Snipaste_2020-04-20_20-38-12](https://user-images.githubusercontent.com/37010563/79752581-25e67b80-8347-11ea-8c67-08b5ac0a5af5.png)

**Comment by ravizhan** [comment]
附错误日志
[zfile.log](https://github.com/zhaojun1998/zfile/files/4503613/zfile.log)

**Comment by zhaojun1998** [comment]
@ravizhan 此问题已在 2.4 版本修复
